In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.0.3

In [2]:
import os

data_path = "../data/Raw_Datasets"

files = os.listdir(data_path)

print("Number of CSV files:", len(files))
print("\nFiles:")
for file in files:
    print(file)

Number of CSV files: 18

Files:
allergies.csv
careplans.csv
claims.csv
claims_transactions.csv
conditions.csv
devices.csv
encounters.csv
imaging_studies.csv
immunizations.csv
medications.csv
observations.csv
organizations.csv
patients.csv
payers.csv
payer_transitions.csv
procedures.csv
providers.csv
supplies.csv

In [3]:
import pandas as pd
import os

data_path = "../data/Raw_Datasets"

dataset_info = []

for file in os.listdir(data_path):
    if file.endswith(".csv"):
        file_path = os.path.join(data_path, file)
        df = pd.read_csv(file_path)
        
        dataset_info.append({
            "File": file,
            "Rows": df.shape[0],
            "Columns": df.shape[1]
        })

dataset_info = pd.DataFrame(dataset_info)

dataset_info

                       File    Rows  Columns
0             allergies.csv     794       15
1             careplans.csv    3931        9
2                claims.csv  117889       31
3   claims_transactions.csv  711238       33
4            conditions.csv   38094        6
5               devices.csv      89        7
6            encounters.csv   61459       15
7       imaging_studies.csv  151637       13
8         immunizations.csv   17009        6
9           medications.csv   56430       13
10         observations.csv  531144        9
11        organizations.csv    1127       11
12             patients.csv    1163       25
13               payers.csv      10       21
14    payer_transitions.csv   53101        8
15           procedures.csv   83823        9
16            providers.csv    5056       12
17             supplies.csv    1573        6

In [4]:
encounters = pd.read_csv("../data/Raw_Datasets/encounters.csv")

print("Shape:", encounters.shape)
print("\nColumns:")
print(encounters.columns.tolist())

Shape: (61459, 15)

Columns:
['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PROVIDER', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION']

In [5]:
encounters["ENCOUNTERCLASS"].value_counts()

ENCOUNTERCLASS
wellness      24038
ambulatory    20124
outpatient    10837
urgentcare     2564
emergency      2168
inpatient      1728
Name: count, dtype: int64

In [6]:
print(encounters[["START", "STOP"]].head(10))

                  START                  STOP
0  2019-02-17T05:07:38Z  2019-02-17T05:22:38Z
1  2019-03-24T05:07:38Z  2019-03-24T05:22:38Z
2  2019-05-26T05:07:38Z  2019-05-26T05:22:38Z
3  2019-07-28T05:07:38Z  2019-07-28T05:22:38Z
4  2019-10-27T05:07:38Z  2019-10-27T05:22:38Z
5  2020-01-26T05:07:38Z  2020-01-26T05:22:38Z
6  2020-02-05T06:07:38Z  2020-02-05T06:22:38Z
7  2020-02-17T10:07:38Z  2020-02-17T10:40:32Z
8  2020-04-26T05:07:38Z  2020-04-26T05:22:38Z
9  2020-07-26T05:07:38Z  2020-07-26T05:22:38Z

In [7]:
inpatient = encounters[encounters["ENCOUNTERCLASS"] == "inpatient"]

print("Number of inpatient encounters:", len(inpatient))
print("\nFirst 10 inpatient START and STOP times:")
print(inpatient[["START", "STOP"]].head(10))

Number of inpatient encounters: 1728

First 10 inpatient START and STOP times:
                     START                  STOP
358   2020-02-22T01:17:19Z  2020-02-23T01:17:19Z
389   2006-02-18T21:56:43Z  2006-02-19T21:56:43Z
606   2021-02-08T17:17:44Z  2021-02-20T17:37:23Z
628   2021-02-20T17:37:23Z  2021-02-24T17:37:23Z
634   2021-02-24T17:37:23Z  2021-02-26T17:37:23Z
1205  2021-05-28T05:53:58Z  2021-05-29T05:53:58Z
1294  2013-03-30T06:57:17Z  2013-05-26T06:57:17Z
1296  2013-04-11T19:19:25Z  2013-04-12T19:19:25Z
1297  2013-05-02T05:07:06Z  2013-05-03T05:07:06Z
1304  2013-05-24T20:29:47Z  2013-05-25T20:29:47Z

In [8]:
print("Missing START:", encounters["START"].isna().sum())
print("Missing STOP:", encounters["STOP"].isna().sum())

Missing START: 0
Missing STOP: 0

In [9]:
start = pd.to_datetime(encounters["START"])
stop = pd.to_datetime(encounters["STOP"])

invalid_duration = (stop < start).sum()

print("Records where STOP is before START:", invalid_duration)

Records where STOP is before START: 0

In [10]:
print("Duplicate encounter IDs:", encounters["Id"].duplicated().sum())

Duplicate encounter IDs: 0

In [11]:
print(encounters[["BASE_ENCOUNTER_COST", "TOTAL_CLAIM_COST", "PAYER_COVERAGE"]].describe())

       BASE_ENCOUNTER_COST  TOTAL_CLAIM_COST  PAYER_COVERAGE
count         61459.000000      61459.000000    61459.000000
mean            113.262767       4149.657952     1033.709602
std              23.847374      10919.677889     4902.646135
min              77.490000          0.000000        0.000000
25%              77.490000        129.160000        0.000000
50%             129.160000        786.330000        0.000000
75%             129.160000       1625.890000       29.990000
max             129.160000     873646.190000   227851.810000

In [12]:
print("Total claim cost = 0:", (encounters["TOTAL_CLAIM_COST"] == 0).sum())
print("Total claim cost > 0:", (encounters["TOTAL_CLAIM_COST"] > 0).sum())

Total claim cost = 0: 229
Total claim cost > 0: 61230

In [13]:
coverage_greater_than_cost = (
    encounters["PAYER_COVERAGE"] > encounters["TOTAL_CLAIM_COST"]
).sum()

print("Payer coverage greater than total claim cost:", coverage_greater_than_cost)

Payer coverage greater than total claim cost: 0

In [14]:
print(
    encounters[
        ["BASE_ENCOUNTER_COST", "TOTAL_CLAIM_COST", "PAYER_COVERAGE"]
    ].isna().sum()
)

BASE_ENCOUNTER_COST    0
TOTAL_CLAIM_COST       0
PAYER_COVERAGE         0
dtype: int64

In [16]:
print("Missing PATIENT:", encounters["PATIENT"].isna().sum())
print("Unique encounter IDs:", encounters["Id"].nunique())
print("Total encounter rows:", len(encounters))

Missing PATIENT: 0
Unique encounter IDs: 61459
Total encounter rows: 61459

In [17]:
patients = pd.read_csv("../data/Raw_Datasets/patients.csv")

print("Shape:", patients.shape)
print("\nColumns:")
print(patients.columns.tolist())

Shape: (1163, 25)

Columns:
['Id', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT', 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE']

In [18]:
print("Duplicate patient IDs:", patients["Id"].duplicated().sum())
print("Missing patient IDs:", patients["Id"].isna().sum())

Duplicate patient IDs: 0
Missing patient IDs: 0

In [19]:
print("Missing BIRTHDATE:", patients["BIRTHDATE"].isna().sum())

Missing BIRTHDATE: 0

In [20]:
print("Patients with DEATHDATE:", patients["DEATHDATE"].notna().sum())
print("Patients without DEATHDATE:", patients["DEATHDATE"].isna().sum())

Patients with DEATHDATE: 163
Patients without DEATHDATE: 1000

In [21]:
print(patients["GENDER"].value_counts(dropna=False))

GENDER
F    616
M    547
Name: count, dtype: int64

In [22]:
print(patients["MARITAL"].value_counts(dropna=False))

MARITAL
M      625
NaN    384
S      154
Name: count, dtype: int64

In [23]:
print(patients["RACE"].value_counts(dropna=False))

RACE
white       963
black        96
asian        73
hawaiian     18
other        11
native        2
Name: count, dtype: int64

In [24]:
print(patients["ETHNICITY"].value_counts(dropna=False))

ETHNICITY
nonhispanic    1058
hispanic        105
Name: count, dtype: int64

In [25]:
print(patients["HEALTHCARE_EXPENSES"].describe())

count    1.163000e+03
mean     1.256248e+06
std      1.148747e+06
min      8.259920e+02
25%      4.426256e+05
50%      1.142154e+06
75%      1.900910e+06
max      2.311655e+07
Name: HEALTHCARE_EXPENSES, dtype: float64

In [26]:
print("Missing HEALTHCARE_EXPENSES:", patients["HEALTHCARE_EXPENSES"].isna().sum())

Missing HEALTHCARE_EXPENSES: 0

In [27]:
print(patients["HEALTHCARE_COVERAGE"].describe())

count    1.163000e+03
mean     1.717684e+05
std      4.885749e+05
min      0.000000e+00
25%      1.293600e+03
50%      1.747219e+04
75%      2.051068e+05
max      1.356228e+07
Name: HEALTHCARE_COVERAGE, dtype: float64

In [28]:
claims = pd.read_csv("../data/Raw_Datasets/claims.csv")

print("Shape:", claims.shape)
print("\nColumns:")
print(claims.columns.tolist())

Shape: (117889, 31)

Columns:
['Id', 'PATIENTID', 'PROVIDERID', 'PRIMARYPATIENTINSURANCEID', 'SECONDARYPATIENTINSURANCEID', 'DEPARTMENTID', 'PATIENTDEPARTMENTID', 'DIAGNOSIS1', 'DIAGNOSIS2', 'DIAGNOSIS3', 'DIAGNOSIS4', 'DIAGNOSIS5', 'DIAGNOSIS6', 'DIAGNOSIS7', 'DIAGNOSIS8', 'REFERRINGPROVIDERID', 'APPOINTMENTID', 'CURRENTILLNESSDATE', 'SERVICEDATE', 'SUPERVISINGPROVIDERID', 'STATUS1', 'STATUS2', 'STATUSP', 'OUTSTANDING1', 'OUTSTANDING2', 'OUTSTANDINGP', 'LASTBILLEDDATE1', 'LASTBILLEDDATE2', 'LASTBILLEDDATEP', 'HEALTHCARECLAIMTYPEID1', 'HEALTHCARECLAIMTYPEID2']

In [29]:
Columns:
['Id', 'PATIENTID', 'PROVIDERID', 'PRIMARYPATIENTINSURANCEID', 'SECONDARYPATIENTINSURANCEID', 'DEPARTMENTID', 'PATIENTDEPARTMENTID', 'DIAGNOSIS1', 'DIAGNOSIS2', 'DIAGNOSIS3', 'DIAGNOSIS4', 'DIAGNOSIS5', 'DIAGNOSIS6', 'DIAGNOSIS7', 'DIAGNOSIS8', 'REFERRINGPROVIDERID', 'APPOINTMENTID', 'CURRENTILLNESSDATE', 'SERVICEDATE', 'SUPERVISINGPROVIDERID', 'STATUS1', 'STATUS2', 'STATUSP', 'OUTSTANDING1', 'OUTSTANDING2', 'OUTSTANDINGP', 'LASTBILLEDDATE1', 'LASTBILLEDDATE2', 'LASTBILLEDDATEP', 'HEALTHCARECLAIMTYPEID1', 'HEALTHCARECLAIMTYPEID2']

SyntaxError: invalid syntax (1068357153.py, line 1)

In [30]:
conditions = pd.read_csv("../data/Raw_Datasets/conditions.csv")

print("Shape:", conditions.shape)
print("\nColumns:")
print(conditions.columns.tolist())

Shape: (38094, 6)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION']

In [31]:
procedures = pd.read_csv("../data/Raw_Datasets/procedures.csv")

print("Shape:", procedures.shape)
print("\nColumns:")
print(procedures.columns.tolist())

Shape: (83823, 9)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION']

In [32]:
organizations = pd.read_csv("../data/Raw_Datasets/organizations.csv")

print("Shape:", organizations.shape)
print("\nColumns:")
print(organizations.columns.tolist())

Shape: (1127, 11)

Columns:
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON', 'PHONE', 'REVENUE', 'UTILIZATION']

In [33]:
import pandas as pd

data_path = "../data/Raw_Datasets"

files_to_inspect = [
    "providers.csv",
    "payers.csv",
    "medications.csv",
    "careplans.csv",
    "observations.csv",
    "imaging_studies.csv",
    "immunizations.csv",
    "allergies.csv",
    "devices.csv",
    "supplies.csv",
    "payer_transitions.csv",
    "claims_transactions.csv"
]

for file in files_to_inspect:
    df = pd.read_csv(f"{data_path}/{file}")
    
    print("\n" + "="*70)
    print(file)
    print("Shape:", df.shape)
    print("Columns:")
    print(df.columns.tolist())

======================================================================
providers.csv
Shape: (5056, 12)
Columns:
['Id', 'ORGANIZATION', 'NAME', 'GENDER', 'SPECIALITY', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON', 'UTILIZATION']

======================================================================
payers.csv
Shape: (10, 21)
Columns:
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE_HEADQUARTERED', 'ZIP', 'PHONE', 'AMOUNT_COVERED', 'AMOUNT_UNCOVERED', 'REVENUE', 'COVERED_ENCOUNTERS', 'UNCOVERED_ENCOUNTERS', 'COVERED_MEDICATIONS', 'UNCOVERED_MEDICATIONS', 'COVERED_PROCEDURES', 'UNCOVERED_PROCEDURES', 'COVERED_IMMUNIZATIONS', 'UNCOVERED_IMMUNIZATIONS', 'UNIQUE_CUSTOMERS', 'QOLS_AVG', 'MEMBER_MONTHS']

======================================================================
medications.csv
Shape: (56430, 13)
Columns:
['START', 'STOP', 'PATIENT', 'PAYER', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'PAYER_COVERAGE', 'DISPENSES', 'TOTALCOST', 'REASONCODE', 'REASONDESCRIPTION']

======================================================================
careplans.csv
Shape: (3931, 9)
Columns:
['Id', 'START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'REASONCODE', 'REASONDESCRIPTION']

======================================================================
observations.csv
Shape: (531144, 9)
Columns:
['DATE', 'PATIENT', 'ENCOUNTER', 'CATEGORY', 'CODE', 'DESCRIPTION', 'VALUE', 'UNITS', 'TYPE']

======================================================================
imaging_studies.csv
Shape: (151637, 13)
Columns:
['Id', 'DATE', 'PATIENT', 'ENCOUNTER', 'SERIES_UID', 'BODYSITE_CODE', 'BODYSITE_DESCRIPTION', 'MODALITY_CODE', 'MODALITY_DESCRIPTION', 'INSTANCE_UID', 'SOP_CODE', 'SOP_DESCRIPTION', 'PROCEDURE_CODE']

======================================================================
immunizations.csv
Shape: (17009, 6)
Columns:
['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST']

======================================================================
allergies.csv
Shape: (794, 15)
Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'SYSTEM', 'DESCRIPTION', 'TYPE', 'CATEGORY', 'REACTION1', 'DESCRIPTION1', 'SEVERITY1', 'REACTION2', 'DESCRIPTION2', 'SEVERITY2']

======================================================================
devices.csv
Shape: (89, 7)
Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'UDI']

======================================================================
supplies.csv
Shape: (1573, 6)
Columns:
['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'QUANTITY']

======================================================================
payer_transitions.csv
Shape: (53101, 8)
Columns:
['PATIENT', 'MEMBERID', 'START_YEAR', 'END_YEAR', 'PAYER', 'SECONDARY_PAYER', 'OWNERSHIP', 'OWNERNAME']

======================================================================
claims_transactions.csv
Shape: (711238, 33)
Columns:
['ID', 'CLAIMID', 'CHARGEID', 'PATIENTID', 'TYPE', 'AMOUNT', 'METHOD', 'FROMDATE', 'TODATE', 'PLACEOFSERVICE', 'PROCEDURECODE', 'MODIFIER1', 'MODIFIER2', 'DIAGNOSISREF1', 'DIAGNOSISREF2', 'DIAGNOSISREF3', 'DIAGNOSISREF4', 'UNITS', 'DEPARTMENTID', 'NOTES', 'UNITAMOUNT', 'TRANSFEROUTID', 'TRANSFERTYPE', 'PAYMENTS', 'ADJUSTMENTS', 'TRANSFERS', 'OUTSTANDING', 'APPOINTMENTID', 'LINENOTE', 'PATIENTINSURANCEID', 'FEESCHEDULEID', 'PROVIDERID', 'SUPERVISINGPROVIDERID']

In [1]:
# Phase 2 - Data Cleaning & Validation
# Step 2.2 - Load core datasets

import pandas as pd

patients = pd.read_csv("../data/Raw_Datasets/patients.csv")
encounters = pd.read_csv("../data/Raw_Datasets/encounters.csv")
providers = pd.read_csv("../data/Raw_Datasets/providers.csv")
organizations = pd.read_csv("../data/Raw_Datasets/organizations.csv")
payers = pd.read_csv("../data/Raw_Datasets/payers.csv")
conditions = pd.read_csv("../data/Raw_Datasets/conditions.csv")
procedures = pd.read_csv("../data/Raw_Datasets/procedures.csv")

print("Core datasets loaded successfully.")

Core datasets loaded successfully.

In [2]:
# Check: Do all encounter patient IDs exist in patients table?

patient_ids_in_patients = set(patients["Id"])
patient_ids_in_encounters = set(encounters["PATIENT"])

missing_patient_ids = patient_ids_in_encounters - patient_ids_in_patients

print("Unique patient IDs in encounters:", len(patient_ids_in_encounters))
print("Patient IDs in patients table:", len(patient_ids_in_patients))
print("Patient IDs in encounters not found in patients:", len(missing_patient_ids))

Unique patient IDs in encounters: 1163
Patient IDs in patients table: 1163
Patient IDs in encounters not found in patients: 0

In [3]:
# Check: Do all encounter provider IDs exist in providers table?

provider_ids_in_providers = set(providers["Id"])
provider_ids_in_encounters = set(encounters["PROVIDER"])

missing_provider_ids = provider_ids_in_encounters - provider_ids_in_providers

print("Unique provider IDs in encounters:", len(provider_ids_in_encounters))
print("Provider IDs in providers table:", len(provider_ids_in_providers))
print("Provider IDs in encounters not found in providers:", len(missing_provider_ids))

Unique provider IDs in encounters: 1123
Provider IDs in providers table: 5056
Provider IDs in encounters not found in providers: 0

In [4]:
# Check: Do all encounter organization IDs exist in organizations table?

organization_ids_in_organizations = set(organizations["Id"])
organization_ids_in_encounters = set(encounters["ORGANIZATION"])

missing_organization_ids = (
    organization_ids_in_encounters - organization_ids_in_organizations
)

print("Unique organization IDs in encounters:", len(organization_ids_in_encounters))
print("Organization IDs in organizations table:", len(organization_ids_in_organizations))
print(
    "Organization IDs in encounters not found in organizations:",
    len(missing_organization_ids)
)

Unique organization IDs in encounters: 1122
Organization IDs in organizations table: 1127
Organization IDs in encounters not found in organizations: 0

In [5]:
# Check: Do all encounter payer IDs exist in payers table?

payer_ids_in_payers = set(payers["Id"])
payer_ids_in_encounters = set(encounters["PAYER"])

missing_payer_ids = payer_ids_in_encounters - payer_ids_in_payers

print("Unique payer IDs in encounters:", len(payer_ids_in_encounters))
print("Payer IDs in payers table:", len(payer_ids_in_payers))
print("Payer IDs in encounters not found in payers:", len(missing_payer_ids))

Unique payer IDs in encounters: 10
Payer IDs in payers table: 10
Payer IDs in encounters not found in payers: 0

In [6]:
# Check: Do all condition encounter IDs exist in encounters table?

encounter_ids_in_encounters = set(encounters["Id"])
encounter_ids_in_conditions = set(conditions["ENCOUNTER"])

missing_condition_encounters = (
    encounter_ids_in_conditions - encounter_ids_in_encounters
)

print("Unique encounter IDs in conditions:", len(encounter_ids_in_conditions))
print("Encounter IDs in encounters table:", len(encounter_ids_in_encounters))
print(
    "Condition encounter IDs not found in encounters:",
    len(missing_condition_encounters)
)

Unique encounter IDs in conditions: 26904
Encounter IDs in encounters table: 61459
Condition encounter IDs not found in encounters: 0

In [7]:
# Check: Do all procedure encounter IDs exist in encounters table?

encounter_ids_in_procedures = set(procedures["ENCOUNTER"])

missing_procedure_encounters = (
    encounter_ids_in_procedures - encounter_ids_in_encounters
)

print("Unique encounter IDs in procedures:", len(encounter_ids_in_procedures))
print("Encounter IDs in encounters table:", len(encounter_ids_in_encounters))
print(
    "Procedure encounter IDs not found in encounters:",
    len(missing_procedure_encounters)
)

Unique encounter IDs in procedures: 25854
Encounter IDs in encounters table: 61459
Procedure encounter IDs not found in encounters: 0

In [8]:
# Step 2.3 - Missing value check for encounters

missing_values = encounters.isna().sum()

missing_values = missing_values[missing_values > 0]

print("Columns with missing values:")
print(missing_values)

Columns with missing values:
REASONCODE           45502
REASONDESCRIPTION    45502
dtype: int64

In [9]:
# Check missing values in patients table

missing_patient_values = patients.isna().sum()

missing_patient_values = missing_patient_values[missing_patient_values > 0]

print("Columns with missing values:")
print(missing_patient_values)

Columns with missing values:
DEATHDATE    1000
DRIVERS       215
PASSPORT      276
PREFIX        245
SUFFIX       1147
MAIDEN        832
MARITAL       384
ZIP           545
dtype: int64

In [10]:
# Check missing values in conditions table

missing_condition_values = conditions.isna().sum()

missing_condition_values = missing_condition_values[
    missing_condition_values > 0
]

print("Columns with missing values:")
print(missing_condition_values)

Columns with missing values:
STOP    8169
dtype: int64

In [11]:
# Check missing values in procedures table

missing_procedure_values = procedures.isna().sum()

missing_procedure_values = missing_procedure_values[
    missing_procedure_values > 0
]

print("Columns with missing values:")
print(missing_procedure_values)

Columns with missing values:
REASONCODE           63226
REASONDESCRIPTION    63226
dtype: int64

In [12]:
# Check missing values in providers table

missing_provider_values = providers.isna().sum()

missing_provider_values = missing_provider_values[
    missing_provider_values > 0
]

print("Columns with missing values:")
print(missing_provider_values)

Columns with missing values:
Series([], dtype: int64)

In [13]:
# Check missing values in organizations table

missing_organization_values = organizations.isna().sum()

missing_organization_values = missing_organization_values[
    missing_organization_values > 0
]

print("Columns with missing values:")
print(missing_organization_values)

Columns with missing values:
PHONE    153
dtype: int64

In [15]:
# Check missing values in payers table

missing_payer_values = payers.isna().sum()

missing_payer_values = missing_payer_values[
    missing_payer_values > 0
]

print("Columns with missing values:")
print(missing_payer_values)

Columns with missing values:
ADDRESS                1
CITY                   1
STATE_HEADQUARTERED    1
ZIP                    1
PHONE                  1
dtype: int64

In [16]:
# Step 2.4 - Check duplicate encounter records

print("Duplicate encounter IDs:", encounters["Id"].duplicated().sum())
print("Duplicate rows:", encounters.duplicated().sum())

Duplicate encounter IDs: 0
Duplicate rows: 0

In [17]:
# Step 2.4 - Duplicate ID checks for core tables

duplicate_checks = {
    "Patients": patients["Id"].duplicated().sum(),
    "Providers": providers["Id"].duplicated().sum(),
    "Organizations": organizations["Id"].duplicated().sum(),
    "Payers": payers["Id"].duplicated().sum(),
}

for table, count in duplicate_checks.items():
    print(f"{table}: {count} duplicate IDs")

Patients: 0 duplicate IDs
Providers: 0 duplicate IDs
Organizations: 0 duplicate IDs
Payers: 0 duplicate IDs

In [18]:
# Step 2.5 - Check data types in encounters

print(encounters.dtypes)

Id                         str
START                      str
STOP                       str
PATIENT                    str
ORGANIZATION               str
PROVIDER                   str
PAYER                      str
ENCOUNTERCLASS             str
CODE                     int64
DESCRIPTION                str
BASE_ENCOUNTER_COST    float64
TOTAL_CLAIM_COST       float64
PAYER_COVERAGE         float64
REASONCODE             float64
REASONDESCRIPTION          str
dtype: object

In [19]:
print(encounters[["START", "STOP"]].head())

                  START                  STOP
0  2019-02-17T05:07:38Z  2019-02-17T05:22:38Z
1  2019-03-24T05:07:38Z  2019-03-24T05:22:38Z
2  2019-05-26T05:07:38Z  2019-05-26T05:22:38Z
3  2019-07-28T05:07:38Z  2019-07-28T05:22:38Z
4  2019-10-27T05:07:38Z  2019-10-27T05:22:38Z

In [20]:
# Convert START and STOP to datetime

encounters["START"] = pd.to_datetime(encounters["START"], utc=True)
encounters["STOP"] = pd.to_datetime(encounters["STOP"], utc=True)

print(encounters[["START", "STOP"]].dtypes)

START    datetime64[us, UTC]
STOP     datetime64[us, UTC]
dtype: object

In [21]:
# Check for missing and invalid encounter dates

print("Missing START:", encounters["START"].isna().sum())
print("Missing STOP:", encounters["STOP"].isna().sum())

print(
    "STOP before START:",
    (encounters["STOP"] < encounters["START"]).sum()
)

Missing START: 0
Missing STOP: 0
STOP before START: 0

In [22]:
# Step 2.6 - Calculate encounter duration

encounters["ENCOUNTER_DURATION_HOURS"] = (
    encounters["STOP"] - encounters["START"]
).dt.total_seconds() / 3600

print(encounters["ENCOUNTER_DURATION_HOURS"].describe())

count     61459.000000
mean          6.669627
std         704.788610
min           0.250000
25%           0.250000
50%           0.250000
75%           0.250000
max      125664.000000
Name: ENCOUNTER_DURATION_HOURS, dtype: float64

In [23]:
# Find encounters with unusually long durations

long_encounters = encounters[
    encounters["ENCOUNTER_DURATION_HOURS"] > 24 * 30
][[
    "Id",
    "PATIENT",
    "START",
    "STOP",
    "ENCOUNTERCLASS",
    "DESCRIPTION",
    "ENCOUNTER_DURATION_HOURS"
]]

print("Encounters longer than 30 days:", len(long_encounters))

long_encounters.head(10)

Encounters longer than 30 days: 22

,Id,PATIENT,START,STOP,ENCOUNTERCLASS,DESCRIPTION,ENCOUNTER_DURATION_HOURS
1294,478bcf5b-a931-08b5-e78a-011520327b92,8bf6aa92-645f-3c82-ddcd-5851496a6aa8,2013-03-30 06:57:17+00:00,2013-05-26 06:57:17+00:00,inpatient,Periodic reevaluation and management of health...,1368.000000
2810,eda32d58-7877-e333-3e16-9badc52b681e,e15d5c46-48a2-2364-2b4f-529ecbe0c956,2005-02-07 18:52:09+00:00,2005-03-20 07:52:09+00:00,emergency,Encounter for problem,973.000000
2851,c57829e7-c059-9522-9830-fcd6cd4528e0,97899f1d-9c3b-2b90-17b8-400c11ab8f0f,2014-02-05 02:27:51+00:00,2014-11-10 02:27:51+00:00,outpatient,Encounter for problem (procedure),6672.000000
3832,8ce35743-c820-6dc0-e985-6607d2e3af54,0fc183b2-8b93-ec17-d2fc-e703b373c9d7,2014-02-05 16:27:03+00:00,2014-08-04 16:27:03+00:00,outpatient,Encounter for problem (procedure),4320.000000
7587,65cd67cf-aace-94d1-1812-e5b8f154f61c,4e64cd82-c0b5-2005-2690-240374ca045c,1994-10-05 17:24:34+00:00,1994-11-08 16:54:34+00:00,emergency,Encounter for problem,815.500000
8604,dae6855e-d041-9286-a982-f0aff56658cc,396babc6-6b4f-e29b-40f7-ea119ee57ac4,2014-02-02 13:01:36+00:00,2014-03-14 13:01:36+00:00,outpatient,Encounter for problem (procedure),960.000000
16013,1947d11c-65fb-8b71-f0b0-d135055c7fca,eb7cffc3-28d2-e8b0-72bc-8e86860ed313,2013-05-21 19:55:48+00:00,2014-04-21 17:11:36+00:00,inpatient,Periodic reevaluation and management of health...,8037.263333
19374,13666c38-25d5-e036-bfbe-0673382291f4,9cbf47d8-b59a-ef34-c330-77accc084c17,1997-11-25 15:07:05+00:00,1998-07-19 15:07:05+00:00,inpatient,Encounter for symptom (procedure),5664.000000
20750,8a8af635-42a4-b23a-79e9-c125c6a1e1a1,418c6a4c-1615-cba9-80b3-ac2901f4c07f,2014-02-05 10:49:12+00:00,2014-12-08 10:49:12+00:00,outpatient,Encounter for problem (procedure),7344.000000
32786,93dde3b7-d59a-76be-1054-97f918253d78,e259daec-8b59-74a7-a92c-e4451146d6fc,2014-02-05 22:51:23+00:00,2014-04-21 22:51:23+00:00,outpatient,Encounter for problem (procedure),1800.000000

In [24]:
# Check long-duration encounters by encounter type

long_duration_summary = (
    encounters[encounters["ENCOUNTER_DURATION_HOURS"] > 24 * 30]
    .groupby("ENCOUNTERCLASS")
    .size()
    .sort_values(ascending=False)
)

print(long_duration_summary)

ENCOUNTERCLASS
outpatient    14
inpatient      5
emergency      2
ambulatory     1
dtype: int64

In [25]:
# Step 2.7.1 - Patients structure and data types

print("Shape:", patients.shape)
print("\nData types:")
print(patients.dtypes)

Shape: (1163, 25)

Data types:
Id                         str
BIRTHDATE                  str
DEATHDATE                  str
SSN                        str
DRIVERS                    str
PASSPORT                   str
PREFIX                     str
FIRST                      str
LAST                       str
SUFFIX                     str
MAIDEN                     str
MARITAL                    str
RACE                       str
ETHNICITY                  str
GENDER                     str
BIRTHPLACE                 str
ADDRESS                    str
CITY                       str
STATE                      str
COUNTY                     str
ZIP                    float64
LAT                    float64
LON                    float64
HEALTHCARE_EXPENSES    float64
HEALTHCARE_COVERAGE    float64
dtype: object

In [26]:
# Step 2.7.2 - Missing values

patient_missing = patients.isna().sum()

print("Columns with missing values:")
print(patient_missing[patient_missing > 0])

Columns with missing values:
DEATHDATE    1000
DRIVERS       215
PASSPORT      276
PREFIX        245
SUFFIX       1147
MAIDEN        832
MARITAL       384
ZIP           545
dtype: int64

In [27]:
# Step 2.7.3 - Duplicate checks

print("Duplicate patient IDs:", patients["Id"].duplicated().sum())
print("Duplicate complete rows:", patients.duplicated().sum())

Duplicate patient IDs: 0
Duplicate complete rows: 0

In [28]:
# Step 2.7.4 - Patient ID validation

print("Missing patient IDs:", patients["Id"].isna().sum())
print("Unique patient IDs:", patients["Id"].nunique())
print("Total patient records:", len(patients))

Missing patient IDs: 0
Unique patient IDs: 1163
Total patient records: 1163

In [29]:
# Step 2.7.5 - Inspect patient date columns

print(patients[["BIRTHDATE", "DEATHDATE"]].head(10))
print()
print(patients[["BIRTHDATE", "DEATHDATE"]].dtypes)

    BIRTHDATE DEATHDATE
0  2019-02-17       NaN
1  2005-07-04       NaN
2  1998-05-11       NaN
3  2003-01-28       NaN
4  1993-12-23       NaN
5  2020-12-04       NaN
6  1990-12-15       NaN
7  1985-06-05       NaN
8  1979-12-17       NaN
9  2006-07-11       NaN

BIRTHDATE    str
DEATHDATE    str
dtype: object

In [30]:
# Step 2.7.6 - Convert patient dates

patients["BIRTHDATE"] = pd.to_datetime(
    patients["BIRTHDATE"],
    errors="coerce"
)

patients["DEATHDATE"] = pd.to_datetime(
    patients["DEATHDATE"],
    errors="coerce"
)

print(patients[["BIRTHDATE", "DEATHDATE"]].dtypes)

BIRTHDATE    datetime64[us]
DEATHDATE    datetime64[us]
dtype: object

In [31]:
# Step 2.7.7 - Birthdate validation

print("Missing birthdates:", patients["BIRTHDATE"].isna().sum())

print(
    "Future birthdates:",
    (patients["BIRTHDATE"] > pd.Timestamp.today()).sum()
)

print(
    "Birthdate after deathdate:",
    (
        patients["DEATHDATE"].notna()
        & (patients["BIRTHDATE"] > patients["DEATHDATE"])
    ).sum()
)

Missing birthdates: 0
Future birthdates: 0
Birthdate after deathdate: 0

In [32]:
# Step 2.7.8 - Categorical value checks

print("Gender values:")
print(patients["GENDER"].value_counts(dropna=False))

print("\nRace values:")
print(patients["RACE"].value_counts(dropna=False))

print("\nEthnicity values:")
print(patients["ETHNICITY"].value_counts(dropna=False))

print("\nMarital status values:")
print(patients["MARITAL"].value_counts(dropna=False))

Gender values:
GENDER
F    616
M    547
Name: count, dtype: int64

Race values:
RACE
white       963
black        96
asian        73
hawaiian     18
other        11
native        2
Name: count, dtype: int64

Ethnicity values:
ETHNICITY
nonhispanic    1058
hispanic        105
Name: count, dtype: int64

Marital status values:
MARITAL
M      625
NaN    384
S      154
Name: count, dtype: int64

In [33]:
# Step 2.7.9 - Healthcare financial fields

print("HEALTHCARE_EXPENSES:")
print(patients["HEALTHCARE_EXPENSES"].describe())

print("\nHEALTHCARE_COVERAGE:")
print(patients["HEALTHCARE_COVERAGE"].describe())

HEALTHCARE_EXPENSES:
count    1.163000e+03
mean     1.256248e+06
std      1.148747e+06
min      8.259920e+02
25%      4.426256e+05
50%      1.142154e+06
75%      1.900910e+06
max      2.311655e+07
Name: HEALTHCARE_EXPENSES, dtype: float64

HEALTHCARE_COVERAGE:
count    1.163000e+03
mean     1.717684e+05
std      4.885749e+05
min      0.000000e+00
25%      1.293600e+03
50%      1.747219e+04
75%      2.051068e+05
max      1.356228e+07
Name: HEALTHCARE_COVERAGE, dtype: float64

In [34]:
# Step 2.7.10 - Check negative healthcare financial values

print(
    "Negative healthcare expenses:",
    (patients["HEALTHCARE_EXPENSES"] < 0).sum()
)

print(
    "Negative healthcare coverage:",
    (patients["HEALTHCARE_COVERAGE"] < 0).sum()
)

Negative healthcare expenses: 0
Negative healthcare coverage: 0

In [35]:
# Step 2.7.11 - Geographic field validation

print("Missing CITY:", patients["CITY"].isna().sum())
print("Missing STATE:", patients["STATE"].isna().sum())
print("Missing COUNTY:", patients["COUNTY"].isna().sum())
print("Missing LAT:", patients["LAT"].isna().sum())
print("Missing LON:", patients["LON"].isna().sum())

print("\nLatitude range:")
print(patients["LAT"].min(), "to", patients["LAT"].max())

print("\nLongitude range:")
print(patients["LON"].min(), "to", patients["LON"].max())

Missing CITY: 0
Missing STATE: 0
Missing COUNTY: 0
Missing LAT: 0
Missing LON: 0

Latitude range:
41.299941849839286 to 42.888532327017366

Longitude range:
-73.44516489242905 to -69.97883129100411

In [36]:
# Step 2.7.12 - Patient-to-encounter relationship

encounter_patient_ids = set(encounters["PATIENT"].unique())
patient_ids = set(patients["Id"].unique())

unmatched_patient_references = encounter_patient_ids - patient_ids

print(
    "Patient IDs referenced in encounters but missing from patients:",
    len(unmatched_patient_references)
)

Patient IDs referenced in encounters but missing from patients: 0

In [37]:
# Step 2.8.1 - Providers structure and data types

print("Shape:", providers.shape)
print("\nData types:")
print(providers.dtypes)

Shape: (5056, 12)

Data types:
Id                  str
ORGANIZATION        str
NAME                str
GENDER              str
SPECIALITY          str
ADDRESS             str
CITY                str
STATE               str
ZIP                 str
LAT             float64
LON             float64
UTILIZATION       int64
dtype: object

In [39]:
# Step 2.8.2 - Missing values

provider_missing = providers.isna().sum()

print("Columns with missing values:")
print(provider_missing[provider_missing > 0])

Columns with missing values:
Series([], dtype: int64)

In [40]:
# Step 2.8.3 - Duplicate checks

print("Duplicate provider IDs:", providers["Id"].duplicated().sum())
print("Duplicate complete rows:", providers.duplicated().sum())

Duplicate provider IDs: 0
Duplicate complete rows: 0

In [41]:
# Step 2.8.4 - Provider ID validation

print("Missing provider IDs:", providers["Id"].isna().sum())
print("Unique provider IDs:", providers["Id"].nunique())
print("Total provider records:", len(providers))

Missing provider IDs: 0
Unique provider IDs: 5056
Total provider records: 5056

In [42]:
# Step 2.8.5 - Provider categorical values

print("Gender values:")
print(providers["GENDER"].value_counts(dropna=False))

print("\nSpeciality values:")
print(providers["SPECIALITY"].value_counts(dropna=False))

Gender values:
GENDER
F    2609
M    2447
Name: count, dtype: int64

Speciality values:
SPECIALITY
GENERAL PRACTICE                   1128
PHYSICIAN ASSISTANT                 542
NURSE PRACTITIONER                  387
CLINICAL SOCIAL WORKER              376
PHYSICAL THERAPY                    344
                                   ...
SPORTS MEDICINE                       1
RADIATION ONCOLOGY                    1
INTERVENTIONAL RADIOLOGY              1
HAND SURGERY                          1
COLORECTAL SURGERY (PROCTOLOGY)       1
Name: count, Length: 63, dtype: int64

In [43]:
# Step 2.8.6 - Provider to organization relationship

provider_org_ids = set(providers["ORGANIZATION"].dropna().unique())
organization_ids = set(organizations["Id"].unique())

unmatched_provider_organizations = provider_org_ids - organization_ids

print(
    "Provider organization IDs missing from organizations:",
    len(unmatched_provider_organizations)
)

Provider organization IDs missing from organizations: 0

In [44]:
# Step 2.8.7 - Provider to encounter relationship

encounter_provider_ids = set(encounters["PROVIDER"].dropna().unique())
provider_ids = set(providers["Id"].unique())

unmatched_encounter_providers = encounter_provider_ids - provider_ids

print(
    "Provider IDs referenced in encounters but missing from providers:",
    len(unmatched_encounter_providers)
)

Provider IDs referenced in encounters but missing from providers: 0

In [45]:
# Step 2.8.8 - Provider geographic validation

print("Missing CITY:", providers["CITY"].isna().sum())
print("Missing STATE:", providers["STATE"].isna().sum())
print("Missing ZIP:", providers["ZIP"].isna().sum())
print("Missing LAT:", providers["LAT"].isna().sum())
print("Missing LON:", providers["LON"].isna().sum())

print("\nLatitude range:")
print(providers["LAT"].min(), "to", providers["LAT"].max())

print("\nLongitude range:")
print(providers["LON"].min(), "to", providers["LON"].max())

Missing CITY: 0
Missing STATE: 0
Missing ZIP: 0
Missing LAT: 0
Missing LON: 0

Latitude range:
41.293416 to 42.851284

Longitude range:
-73.361473 to -69.969034

In [46]:
# Step 2.8.9 - Provider utilization validation

print(providers["UTILIZATION"].describe())

print(
    "\nNegative utilization values:",
    (providers["UTILIZATION"] < 0).sum()
)

count    5056.000000
mean       28.670095
std       187.393116
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max      3954.000000
Name: UTILIZATION, dtype: float64

Negative utilization values: 0

In [48]:
# Step 2.8.10 - Provider summary

print("Total providers:", len(providers))
print("Unique providers:", providers["Id"].nunique())
print("Unique specialties:", providers["SPECIALITY"].nunique())
print("Unique organizations:", providers["ORGANIZATION"].nunique())

Total providers: 5056
Unique providers: 5056
Unique specialties: 63
Unique organizations: 1127

In [49]:
# Step 2.9.1 - Organizations structure and data types

print("Shape:", organizations.shape)

print("\nData types:")
print(organizations.dtypes)

Shape: (1127, 11)

Data types:
Id                 str
NAME               str
ADDRESS            str
CITY               str
STATE              str
ZIP                str
LAT            float64
LON            float64
PHONE              str
REVENUE        float64
UTILIZATION      int64
dtype: object

In [50]:
# Step 2.9.2 - Missing values

organization_missing = organizations.isna().sum()

print("Columns with missing values:")
print(organization_missing[organization_missing > 0])

Columns with missing values:
PHONE    153
dtype: int64

In [51]:
# Step 2.9.3 - Duplicate checks

print("Duplicate organization IDs:", organizations["Id"].duplicated().sum())
print("Duplicate complete rows:", organizations.duplicated().sum())

Duplicate organization IDs: 0
Duplicate complete rows: 0

In [52]:
# Step 2.9.4 - Organization ID validation

print("Missing organization IDs:", organizations["Id"].isna().sum())
print("Unique organization IDs:", organizations["Id"].nunique())
print("Total organization records:", len(organizations))

Missing organization IDs: 0
Unique organization IDs: 1127
Total organization records: 1127

In [53]:
# Step 2.9.5 - Organization to provider relationship

provider_org_ids = set(providers["ORGANIZATION"].dropna().unique())
organization_ids = set(organizations["Id"].unique())

unmatched_provider_organizations = provider_org_ids - organization_ids

print(
    "Organizations referenced by providers but missing from organizations:",
    len(unmatched_provider_organizations)
)

Organizations referenced by providers but missing from organizations: 0

In [54]:
# Step 2.9.6 - Organization to encounter relationship

encounter_org_ids = set(encounters["ORGANIZATION"].dropna().unique())
organization_ids = set(organizations["Id"].unique())

unmatched_encounter_organizations = encounter_org_ids - organization_ids

print(
    "Organizations referenced in encounters but missing from organizations:",
    len(unmatched_encounter_organizations)
)

Organizations referenced in encounters but missing from organizations: 0

In [55]:
# Step 2.9.7 - Organization geographic validation

print("Missing CITY:", organizations["CITY"].isna().sum())
print("Missing STATE:", organizations["STATE"].isna().sum())
print("Missing ZIP:", organizations["ZIP"].isna().sum())
print("Missing LAT:", organizations["LAT"].isna().sum())
print("Missing LON:", organizations["LON"].isna().sum())

print("\nLatitude range:")
print(organizations["LAT"].min(), "to", organizations["LAT"].max())

print("\nLongitude range:")
print(organizations["LON"].min(), "to", organizations["LON"].max())

Missing CITY: 0
Missing STATE: 0
Missing ZIP: 0
Missing LAT: 0
Missing LON: 0

Latitude range:
41.293416 to 42.851284

Longitude range:
-73.361473 to -69.969034

In [56]:
# Step 2.9.8 - Organization financial and utilization validation

print("REVENUE:")
print(organizations["REVENUE"].describe())

print("\nUTILIZATION:")
print(organizations["UTILIZATION"].describe())

print(
    "\nNegative revenue:",
    (organizations["REVENUE"] < 0).sum()
)

print(
    "Negative utilization:",
    (organizations["UTILIZATION"] < 0).sum()
)

REVENUE:
count    1127.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: REVENUE, dtype: float64

UTILIZATION:
count    1127.000000
mean      128.621118
std       380.502441
min         2.000000
25%        28.000000
50%        42.000000
75%        69.000000
max      3954.000000
Name: UTILIZATION, dtype: float64

Negative revenue: 0
Negative utilization: 0

In [57]:
# Step 2.9.9 - Organization name validation

print("Missing organization names:", organizations["NAME"].isna().sum())
print("Unique organization names:", organizations["NAME"].nunique())

Missing organization names: 0
Unique organization names: 984

In [58]:
# Step 2.9.10 - Organization summary

print("Total organizations:", len(organizations))
print("Unique organizations:", organizations["Id"].nunique())
print("Organizations used by providers:", providers["ORGANIZATION"].nunique())
print("Organizations used by encounters:", encounters["ORGANIZATION"].nunique())

Total organizations: 1127
Unique organizations: 1127
Organizations used by providers: 1127
Organizations used by encounters: 1122

In [59]:
# Step 2.10.1 - Payers structure and data types

print("Shape:", payers.shape)

print("\nData types:")
print(payers.dtypes)

Shape: (10, 21)

Data types:
Id                             str
NAME                           str
ADDRESS                        str
CITY                           str
STATE_HEADQUARTERED            str
ZIP                        float64
PHONE                          str
AMOUNT_COVERED             float64
AMOUNT_UNCOVERED           float64
REVENUE                    float64
COVERED_ENCOUNTERS           int64
UNCOVERED_ENCOUNTERS         int64
COVERED_MEDICATIONS          int64
UNCOVERED_MEDICATIONS        int64
COVERED_PROCEDURES           int64
UNCOVERED_PROCEDURES         int64
COVERED_IMMUNIZATIONS        int64
UNCOVERED_IMMUNIZATIONS      int64
UNIQUE_CUSTOMERS             int64
QOLS_AVG                   float64
MEMBER_MONTHS                int64
dtype: object

In [60]:
# Step 2.10.2 - Missing values

payer_missing = payers.isna().sum()

print("Columns with missing values:")
print(payer_missing[payer_missing > 0])

Columns with missing values:
ADDRESS                1
CITY                   1
STATE_HEADQUARTERED    1
ZIP                    1
PHONE                  1
dtype: int64

In [61]:
# Step 2.10.3 - Duplicate checks

print("Duplicate payer IDs:", payers["Id"].duplicated().sum())
print("Duplicate complete rows:", payers.duplicated().sum())

Duplicate payer IDs: 0
Duplicate complete rows: 0

In [62]:
# Step 2.10.4 - Payer ID validation

print("Missing payer IDs:", payers["Id"].isna().sum())
print("Unique payer IDs:", payers["Id"].nunique())
print("Total payer records:", len(payers))

Missing payer IDs: 0
Unique payer IDs: 10
Total payer records: 10

In [63]:
# Step 2.10.5 - Payer to encounter relationship

encounter_payer_ids = set(encounters["PAYER"].dropna().unique())
payer_ids = set(payers["Id"].unique())

unmatched_encounter_payers = encounter_payer_ids - payer_ids

print(
    "Payer IDs referenced in encounters but missing from payers:",
    len(unmatched_encounter_payers)
)

Payer IDs referenced in encounters but missing from payers: 0

In [66]:
# Step 2.10.6 - Payer categorical information

print("Payer names:")
print(payers["NAME"].value_counts(dropna=False))

print("\nOwnership:")
print(payers["OWNERSHIP"].value_counts(dropna=False))

Payer names:
NAME
Dual Eligible             1
Medicare                  1
Medicaid                  1
Humana                    1
Blue Cross Blue Shield    1
UnitedHealthcare          1
Aetna                     1
Cigna Health              1
Anthem                    1
NO_INSURANCE              1
Name: count, dtype: int64

Ownership:

KeyError: 'OWNERSHIP'

In [67]:
# Step 2.10.7 - Payer financial fields

financial_columns = [
    "REVENUE",
    "COVERED_ENCOUNTERS",
    "UNCOVERED_ENCOUNTERS",
    "COVERED_MEDICATIONS",
    "UNCOVERED_MEDICATIONS",
    "COVERED_PROCEDURES",
    "UNCOVERED_PROCEDURES",
    "COVERED_IMMUNIZATIONS",
    "UNCOVERED_IMMUNIZATIONS",
    "COVERED_DRUGS",
    "UNCOVERED_DRUGS",
    "COVERED_CAREPLANS",
    "UNCOVERED_CAREPLANS"
]

for column in financial_columns:
    if column in payers.columns:
        print(f"\n{column}:")
        print(payers[column].describe())

REVENUE:
count    1.000000e+01
mean     9.015734e+07
std      7.315884e+07
min      0.000000e+00
25%      9.171688e+06
50%      1.342622e+08
75%      1.499554e+08
max      1.598388e+08
Name: REVENUE, dtype: float64

COVERED_ENCOUNTERS:
count       10.000000
mean      9391.600000
std       5435.184535
min          0.000000
25%       7125.250000
50%      10992.500000
75%      11483.750000
max      17058.000000
Name: COVERED_ENCOUNTERS, dtype: float64

UNCOVERED_ENCOUNTERS:
count       10.000000
mean      5080.400000
std      10799.885835
min          0.000000
25%          0.000000
50%       2061.500000
75%       2172.250000
max      35195.000000
Name: UNCOVERED_ENCOUNTERS, dtype: float64

COVERED_MEDICATIONS:
count       10.000000
mean      2217.700000
std       3631.653956
min          0.000000
25%          0.000000
50%          0.000000
75%       3649.750000
max      10455.000000
Name: COVERED_MEDICATIONS, dtype: float64

UNCOVERED_MEDICATIONS:
count       10.000000
mean      4283.700000
std       4414.731149
min          0.000000
25%          0.000000
50%       5609.500000
75%       5948.500000
max      13776.000000
Name: UNCOVERED_MEDICATIONS, dtype: float64

COVERED_PROCEDURES:
count       10.000000
mean      5565.900000
std      10823.704618
min          0.000000
25%          0.000000
50%          0.000000
75%       5355.500000
max      32913.000000
Name: COVERED_PROCEDURES, dtype: float64

UNCOVERED_PROCEDURES:
count       10.00000
mean     12064.30000
std      16045.16132
min          0.00000
25%          0.00000
50%      13016.00000
75%      13676.00000
max      53599.00000
Name: UNCOVERED_PROCEDURES, dtype: float64

COVERED_IMMUNIZATIONS:
count      10.000000
mean     1645.300000
std      2800.596922
min         0.000000
25%         0.000000
50%         0.000000
75%      2362.750000
max      7612.000000
Name: COVERED_IMMUNIZATIONS, dtype: float64

UNCOVERED_IMMUNIZATIONS:
count      10.000000
mean     4400.400000
std      3801.406178
min         0.000000
25%         0.000000
50%      6892.000000
75%      7366.500000
max      7844.000000
Name: UNCOVERED_IMMUNIZATIONS, dtype: float64

In [68]:
# Step 2.10.8 - Payer coverage and quality fields

coverage_columns = [
    "QOLS_AVG",
    "MEMBER_MONTHS"
]

for column in coverage_columns:
    if column in payers.columns:
        print(f"\n{column}:")
        print(payers[column].describe())

QOLS_AVG:
count    10.000000
mean      0.904887
std       0.372492
min       0.537055
25%       0.818868
50%       0.824410
75%       0.840917
max       1.931809
Name: QOLS_AVG, dtype: float64

MEMBER_MONTHS:
count       10.000000
mean     57008.400000
std      27568.800946
min       3060.000000
25%      37575.000000
50%      73920.000000
75%      76200.000000
max      78384.000000
Name: MEMBER_MONTHS, dtype: float64

In [69]:
# Step 2.10.9 - Check for negative numeric values

numeric_columns = payers.select_dtypes(include="number").columns

for column in numeric_columns:
    negative_count = (payers[column] < 0).sum()
    print(f"{column}: {negative_count} negative values")

ZIP: 0 negative values
AMOUNT_COVERED: 0 negative values
AMOUNT_UNCOVERED: 0 negative values
REVENUE: 0 negative values
COVERED_ENCOUNTERS: 0 negative values
UNCOVERED_ENCOUNTERS: 0 negative values
COVERED_MEDICATIONS: 0 negative values
UNCOVERED_MEDICATIONS: 0 negative values
COVERED_PROCEDURES: 0 negative values
UNCOVERED_PROCEDURES: 0 negative values
COVERED_IMMUNIZATIONS: 0 negative values
UNCOVERED_IMMUNIZATIONS: 0 negative values
UNIQUE_CUSTOMERS: 0 negative values
QOLS_AVG: 0 negative values
MEMBER_MONTHS: 0 negative values

In [70]:
# Step 2.10.10 - Payer geographic validation

geographic_columns = [
    "CITY",
    "STATE_HEADQUARTERED",
    "ZIP"
]

for column in geographic_columns:
    if column in payers.columns:
        print(f"Missing {column}:", payers[column].isna().sum())

Missing CITY: 1
Missing STATE_HEADQUARTERED: 1
Missing ZIP: 1

In [71]:
# Step 2.10.11 - Final payer summary

print("Total payers:", len(payers))
print("Unique payer IDs:", payers["Id"].nunique())
print("Unique payer names:", payers["NAME"].nunique())
print("Payers used in encounters:", encounters["PAYER"].nunique())

Total payers: 10
Unique payer IDs: 10
Unique payer names: 10
Payers used in encounters: 10

In [72]:
# ============================================
# CONDITIONS DATASET - BASIC STRUCTURE
# ============================================

conditions = pd.read_csv("../data/Raw_Datasets/conditions.csv")

print("Shape:", conditions.shape)
print("\nColumns:")
print(conditions.columns.tolist())

print("\nData Types:")
print(conditions.dtypes)

Shape: (38094, 6)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION']

Data Types:
START            str
STOP             str
PATIENT          str
ENCOUNTER        str
CODE           int64
DESCRIPTION      str
dtype: object

In [73]:
# ============================================
# MISSING VALUE CHECK
# ============================================

missing_conditions = conditions.isnull().sum()

print("Missing values in each column:")
print(missing_conditions)

print("\nColumns with missing values:")
print(missing_conditions[missing_conditions > 0])

Missing values in each column:
START             0
STOP           8169
PATIENT           0
ENCOUNTER         0
CODE              0
DESCRIPTION       0
dtype: int64

Columns with missing values:
STOP    8169
dtype: int64

In [74]:
# ============================================
# DUPLICATE CHECK
# ============================================

duplicate_rows = conditions.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)

print("Total rows:", len(conditions))
print("Unique complete rows:", conditions.drop_duplicates().shape[0])

Duplicate complete rows: 0
Total rows: 38094
Unique complete rows: 38094

In [75]:
# ============================================
# PATIENT REFERENCE VALIDATION
# ============================================

condition_patient_ids = set(conditions["PATIENT"].dropna())
patient_ids = set(patients["Id"].dropna())

missing_patient_refs = condition_patient_ids - patient_ids

print("Unique patients in conditions:", len(condition_patient_ids))
print("Unique patients in patients table:", len(patient_ids))
print("Patient references missing from patients table:", len(missing_patient_refs))

if len(missing_patient_refs) == 0:
    print("✓ All condition patient references are valid.")
else:
    print("⚠ Some patient references are missing.")

Unique patients in conditions: 1147
Unique patients in patients table: 1163
Patient references missing from patients table: 0
✓ All condition patient references are valid.

In [76]:
# ============================================
# ENCOUNTER REFERENCE VALIDATION
# ============================================

condition_encounter_ids = set(conditions["ENCOUNTER"].dropna())
encounter_ids = set(encounters["Id"].dropna())

missing_encounter_refs = condition_encounter_ids - encounter_ids

print("Unique encounters in conditions:", len(condition_encounter_ids))
print("Unique encounters in encounters table:", len(encounter_ids))
print("Encounter references missing from encounters table:", len(missing_encounter_refs))

if len(missing_encounter_refs) == 0:
    print("✓ All condition encounter references are valid.")
else:
    print("⚠ Some encounter references are missing.")

Unique encounters in conditions: 26904
Unique encounters in encounters table: 61459
Encounter references missing from encounters table: 0
✓ All condition encounter references are valid.

In [78]:
# ============================================
# DATE VALIDATION
# ============================================

conditions["START"] = pd.to_datetime(
    conditions["START"],
    errors="coerce"
)

conditions["STOP"] = pd.to_datetime(
    conditions["STOP"],
    errors="coerce"
)

print("START datatype:", conditions["START"].dtype)
print("STOP datatype:", conditions["STOP"].dtype)

print("\nMissing START:", conditions["START"].isna().sum())
print("Missing STOP:", conditions["STOP"].isna().sum())

START datatype: datetime64[us]
STOP datatype: datetime64[us]

Missing START: 0
Missing STOP: 8169

In [79]:
# ============================================
# CONDITION DATE LOGIC CHECK
# ============================================

invalid_condition_dates = (
    conditions["STOP"].notna() &
    conditions["START"].notna() &
    (conditions["STOP"] < conditions["START"])
).sum()

print("Records where STOP is before START:", invalid_condition_dates)

if invalid_condition_dates == 0:
    print("✓ No invalid condition date sequences found.")
else:
    print("⚠ Invalid condition date sequences found.")

Records where STOP is before START: 0
✓ No invalid condition date sequences found.

In [80]:
# ============================================
# CONDITION / DIAGNOSIS INFORMATION
# ============================================

print("Unique condition codes:", conditions["CODE"].nunique())
print("Unique condition descriptions:", conditions["DESCRIPTION"].nunique())

print("\nMissing condition codes:", conditions["CODE"].isna().sum())
print("Missing condition descriptions:", conditions["DESCRIPTION"].isna().sum())

print("\nTop 20 condition descriptions:")
print(
    conditions["DESCRIPTION"]
    .value_counts()
    .head(20)
)

Unique condition codes: 202
Unique condition descriptions: 204

Missing condition codes: 0
Missing condition descriptions: 0

Top 20 condition descriptions:
DESCRIPTION
Full-time employment (finding)                               13805
Stress (finding)                                              5137
Part-time employment (finding)                                2426
Social isolation (finding)                                    1243
Viral sinusitis (disorder)                                    1233
Limited social contact (finding)                              1200
Not in labor force (finding)                                  1077
Victim of intimate partner abuse (finding)                     819
Acute viral pharyngitis (disorder)                             678
Acute bronchitis (disorder)                                    571
Reports of violence in the environment (finding)               565
Normal pregnancy                                               527
Received higher education (finding)                            523
Body mass index 30+ - obesity (finding)                        463
Risk activity involvement (finding)                            392
Prediabetes                                                    341
Anemia (disorder)                                              324
Hypertension                                                   292
Received certificate of high school equivalency (finding)      265
Chronic sinusitis (disorder)                                   219
Name: count, dtype: int64

In [81]:
# ============================================
# CONDITIONS PER ENCOUNTER
# ============================================

conditions_per_encounter = (
    conditions.groupby("ENCOUNTER")
    .size()
)

print("Average conditions per encounter:",
      conditions_per_encounter.mean())

print("Median conditions per encounter:",
      conditions_per_encounter.median())

print("Maximum conditions for one encounter:",
      conditions_per_encounter.max())

print("\nConditions per encounter summary:")
print(conditions_per_encounter.describe())

Average conditions per encounter: 1.4159232827832293
Median conditions per encounter: 1.0
Maximum conditions for one encounter: 13

Conditions per encounter summary:
count    26904.000000
mean         1.415923
std          0.753878
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         13.000000
dtype: float64

In [83]:
# ============================================
# CONDITIONS DATASET - FINAL SUMMARY
# ============================================

print("============================================")
print("CONDITIONS DATASET VALIDATION SUMMARY")
print("============================================")

print("Total rows:", len(conditions))
print("Total columns:", conditions.shape[1])

print("\nMissing values:")
print(conditions.isnull().sum()[conditions.isnull().sum() > 0])

print("\nDuplicate complete rows:", conditions.duplicated().sum())

print("\nUnique patients:", conditions["PATIENT"].nunique())
print("Unique encounters:", conditions["ENCOUNTER"].nunique())
print("Unique condition codes:", conditions["CODE"].nunique())
print("Unique descriptions:", conditions["DESCRIPTION"].nunique())

print("\nInvalid STOP < START records:",
      (
          conditions["STOP"].notna() &
          conditions["START"].notna() &
          (conditions["STOP"] < conditions["START"])
      ).sum())

print("\nConditions dataset validation completed.")

============================================
CONDITIONS DATASET VALIDATION SUMMARY
============================================
Total rows: 38094
Total columns: 6

Missing values:
STOP    8169
dtype: int64

Duplicate complete rows: 0

Unique patients: 1147
Unique encounters: 26904
Unique condition codes: 202
Unique descriptions: 204

Invalid STOP < START records: 0

Conditions dataset validation completed.

In [85]:
# ============================================
# PROCEDURES DATASET - BASIC STRUCTURE
# ============================================

procedures = pd.read_csv("../data/Raw_Datasets/procedures.csv")

print("Shape:", procedures.shape)

print("\nColumns:")
print(procedures.columns.tolist())

print("\nData Types:")
print(procedures.dtypes)

Shape: (83823, 9)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION']

Data Types:
START                    str
STOP                     str
PATIENT                  str
ENCOUNTER                str
CODE                   int64
DESCRIPTION              str
BASE_COST            float64
REASONCODE           float64
REASONDESCRIPTION        str
dtype: object

In [86]:
# ============================================
# MISSING VALUE CHECK
# ============================================

missing_procedures = procedures.isnull().sum()

print("Missing values in each column:")
print(missing_procedures)

print("\nColumns with missing values:")
print(missing_procedures[missing_procedures > 0])

Missing values in each column:
START                    0
STOP                     0
PATIENT                  0
ENCOUNTER                0
CODE                     0
DESCRIPTION              0
BASE_COST                0
REASONCODE           63226
REASONDESCRIPTION    63226
dtype: int64

Columns with missing values:
REASONCODE           63226
REASONDESCRIPTION    63226
dtype: int64

In [87]:
# ============================================
# DUPLICATE CHECK
# ============================================

duplicate_rows = procedures.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)
print("Total rows:", len(procedures))
print("Unique complete rows:", procedures.drop_duplicates().shape[0])

Duplicate complete rows: 0
Total rows: 83823
Unique complete rows: 83823

In [88]:
# ============================================
# PATIENT REFERENCE VALIDATION
# ============================================

procedure_patient_ids = set(procedures["PATIENT"].dropna())
patient_ids = set(patients["Id"].dropna())

missing_patient_refs = procedure_patient_ids - patient_ids

print("Unique patients in procedures:", len(procedure_patient_ids))
print("Unique patients in patients table:", len(patient_ids))
print("Patient references missing from patients table:",
      len(missing_patient_refs))

if len(missing_patient_refs) == 0:
    print("✓ All procedure patient references are valid.")
else:
    print("⚠ Some patient references are missing.")

Unique patients in procedures: 1162
Unique patients in patients table: 1163
Patient references missing from patients table: 0
✓ All procedure patient references are valid.

In [89]:
# ============================================
# ENCOUNTER REFERENCE VALIDATION
# ============================================

procedure_encounter_ids = set(procedures["ENCOUNTER"].dropna())
encounter_ids = set(encounters["Id"].dropna())

missing_encounter_refs = procedure_encounter_ids - encounter_ids

print("Unique encounters in procedures:",
      len(procedure_encounter_ids))

print("Unique encounters in encounters table:",
      len(encounter_ids))

print("Encounter references missing from encounters table:",
      len(missing_encounter_refs))

if len(missing_encounter_refs) == 0:
    print("✓ All procedure encounter references are valid.")
else:
    print("⚠ Some encounter references are missing.")

Unique encounters in procedures: 25854
Unique encounters in encounters table: 61459
Encounter references missing from encounters table: 0
✓ All procedure encounter references are valid.

In [90]:
# ============================================
# DATE VALIDATION
# ============================================

procedures["START"] = pd.to_datetime(
    procedures["START"],
    errors="coerce"
)

procedures["STOP"] = pd.to_datetime(
    procedures["STOP"],
    errors="coerce"
)

print("START datatype:", procedures["START"].dtype)
print("STOP datatype:", procedures["STOP"].dtype)

print("\nMissing START:", procedures["START"].isna().sum())
print("Missing STOP:", procedures["STOP"].isna().sum())

START datatype: datetime64[us, UTC]
STOP datatype: datetime64[us, UTC]

Missing START: 0
Missing STOP: 0

In [91]:
# ============================================
# PROCEDURE DATE LOGIC CHECK
# ============================================

invalid_procedure_dates = (
    procedures["STOP"].notna() &
    procedures["START"].notna() &
    (procedures["STOP"] < procedures["START"])
).sum()

print("Records where STOP is before START:",
      invalid_procedure_dates)

if invalid_procedure_dates == 0:
    print("✓ No invalid procedure date sequences found.")
else:
    print("⚠ Invalid procedure date sequences found.")

Records where STOP is before START: 0
✓ No invalid procedure date sequences found.

In [92]:
# ============================================
# PROCEDURE INFORMATION
# ============================================

print("Unique procedure codes:",
      procedures["CODE"].nunique())

print("Unique procedure descriptions:",
      procedures["DESCRIPTION"].nunique())

print("\nMissing procedure codes:",
      procedures["CODE"].isna().sum())

print("Missing procedure descriptions:",
      procedures["DESCRIPTION"].isna().sum())

print("\nTop 20 procedure descriptions:")

print(
    procedures["DESCRIPTION"]
    .value_counts()
    .head(20)
)

Unique procedure codes: 170
Unique procedure descriptions: 178

Missing procedure codes: 0
Missing procedure descriptions: 0

Top 20 procedure descriptions:
DESCRIPTION
Assessment of health and social care needs (procedure)                                     8901
Depression screening (procedure)                                                           7727
Depression screening using Patient Health Questionnaire Two-Item score (procedure)         6940
Assessment of substance use (procedure)                                                    6199
Medication Reconciliation (procedure)                                                      6032
Assessment of anxiety (procedure)                                                          4954
Assessment using Alcohol Use Disorders Identification Test - Consumption (procedure)       2765
Screening for drug abuse (procedure)                                                       2748
Evaluation of uterine fundal height                                                        2717
Auscultation of the fetal heart                                                            2717
Screening for domestic abuse (procedure)                                                   2680
Subcutaneous immunotherapy                                                                 1929
Assessment using Morse Fall Scale (procedure)                                              1844
Intramuscular injection                                                                    1450
Depression screening using Patient Health Questionnaire Nine Item score (procedure)        1224
Renal dialysis (procedure)                                                                 1079
Electrical cardioversion                                                                    964
Movement therapy (regime/therapy)                                                           910
Combined chemotherapy and radiation therapy (procedure)                                     690
Assessment using Car  Relax  Alone  Forget  Friends  Trouble Screening Test (procedure)     686
Name: count, dtype: int64

In [93]:
# ============================================
# PROCEDURE REASON INFORMATION
# ============================================

print("Missing REASONCODE:",
      procedures["REASONCODE"].isna().sum())

print("Missing REASONDESCRIPTION:",
      procedures["REASONDESCRIPTION"].isna().sum())

print("\nUnique REASONCODE values:",
      procedures["REASONCODE"].nunique())

print("Unique REASONDESCRIPTION values:",
      procedures["REASONDESCRIPTION"].nunique())

Missing REASONCODE: 63226
Missing REASONDESCRIPTION: 63226

Unique REASONCODE values: 48
Unique REASONDESCRIPTION values: 48

In [94]:
# ============================================
# PROCEDURES PER ENCOUNTER
# ============================================

procedures_per_encounter = (
    procedures.groupby("ENCOUNTER")
    .size()
)

print("Average procedures per encounter:",
      procedures_per_encounter.mean())

print("Median procedures per encounter:",
      procedures_per_encounter.median())

print("Maximum procedures for one encounter:",
      procedures_per_encounter.max())

print("\nProcedures per encounter summary:")

print(procedures_per_encounter.describe())

Average procedures per encounter: 3.2421675562775585
Median procedures per encounter: 2.0
Maximum procedures for one encounter: 27

Procedures per encounter summary:
count    25854.000000
mean         3.242168
std          2.986637
min          1.000000
25%          1.000000
50%          2.000000
75%          5.000000
max         27.000000
dtype: float64

In [95]:
# ============================================
# PROCEDURES DATASET - FINAL SUMMARY
# ============================================

print("============================================")
print("PROCEDURES DATASET VALIDATION SUMMARY")
print("============================================")

print("Total rows:", len(procedures))
print("Total columns:", procedures.shape[1])

print("\nMissing values:")
print(
    procedures.isnull().sum()[
        procedures.isnull().sum() > 0
    ]
)

print("\nDuplicate complete rows:",
      procedures.duplicated().sum())

print("\nUnique patients:",
      procedures["PATIENT"].nunique())

print("Unique encounters:",
      procedures["ENCOUNTER"].nunique())

print("Unique procedure codes:",
      procedures["CODE"].nunique())

print("Unique descriptions:",
      procedures["DESCRIPTION"].nunique())

print("\nInvalid STOP < START records:",
      (
          procedures["STOP"].notna() &
          procedures["START"].notna() &
          (procedures["STOP"] < procedures["START"])
      ).sum())

print("\nProcedures dataset validation completed.")

============================================
PROCEDURES DATASET VALIDATION SUMMARY
============================================
Total rows: 83823
Total columns: 9

Missing values:
REASONCODE           63226
REASONDESCRIPTION    63226
dtype: int64

Duplicate complete rows: 0

Unique patients: 1162
Unique encounters: 25854
Unique procedure codes: 170
Unique descriptions: 178

Invalid STOP < START records: 0

Procedures dataset validation completed.

In [96]:
# ============================================
# CLAIMS DATASET - BASIC STRUCTURE
# ============================================

claims = pd.read_csv("../data/Raw_Datasets/claims.csv")

print("Shape:", claims.shape)

print("\nColumns:")
print(claims.columns.tolist())

print("\nData Types:")
print(claims.dtypes)

Shape: (117889, 31)

Columns:
['Id', 'PATIENTID', 'PROVIDERID', 'PRIMARYPATIENTINSURANCEID', 'SECONDARYPATIENTINSURANCEID', 'DEPARTMENTID', 'PATIENTDEPARTMENTID', 'DIAGNOSIS1', 'DIAGNOSIS2', 'DIAGNOSIS3', 'DIAGNOSIS4', 'DIAGNOSIS5', 'DIAGNOSIS6', 'DIAGNOSIS7', 'DIAGNOSIS8', 'REFERRINGPROVIDERID', 'APPOINTMENTID', 'CURRENTILLNESSDATE', 'SERVICEDATE', 'SUPERVISINGPROVIDERID', 'STATUS1', 'STATUS2', 'STATUSP', 'OUTSTANDING1', 'OUTSTANDING2', 'OUTSTANDINGP', 'LASTBILLEDDATE1', 'LASTBILLEDDATE2', 'LASTBILLEDDATEP', 'HEALTHCARECLAIMTYPEID1', 'HEALTHCARECLAIMTYPEID2']

Data Types:
Id                                 str
PATIENTID                          str
PROVIDERID                         str
PRIMARYPATIENTINSURANCEID          str
SECONDARYPATIENTINSURANCEID        str
DEPARTMENTID                     int64
PATIENTDEPARTMENTID              int64
DIAGNOSIS1                       int64
DIAGNOSIS2                     float64
DIAGNOSIS3                     float64
DIAGNOSIS4                     float64
DIAGNOSIS5                     float64
DIAGNOSIS6                     float64
DIAGNOSIS7                     float64
DIAGNOSIS8                     float64
REFERRINGPROVIDERID            float64
APPOINTMENTID                      str
CURRENTILLNESSDATE                 str
SERVICEDATE                        str
SUPERVISINGPROVIDERID              str
STATUS1                            str
STATUS2                            str
STATUSP                            str
OUTSTANDING1                   float64
OUTSTANDING2                   float64
OUTSTANDINGP                   float64
LASTBILLEDDATE1                    str
LASTBILLEDDATE2                    str
LASTBILLEDDATEP                    str
HEALTHCARECLAIMTYPEID1           int64
HEALTHCARECLAIMTYPEID2           int64
dtype: object

In [97]:
# ============================================
# MISSING VALUE CHECK
# ============================================

missing_claims = claims.isnull().sum()

print("Missing values in each column:")
print(missing_claims)

print("\nColumns with missing values:")
print(missing_claims[missing_claims > 0])

Missing values in each column:
Id                                  0
PATIENTID                           0
PROVIDERID                          0
PRIMARYPATIENTINSURANCEID           0
SECONDARYPATIENTINSURANCEID         0
DEPARTMENTID                        0
PATIENTDEPARTMENTID                 0
DIAGNOSIS1                          0
DIAGNOSIS2                      89378
DIAGNOSIS3                     111855
DIAGNOSIS4                     116212
DIAGNOSIS5                     117411
DIAGNOSIS6                     117757
DIAGNOSIS7                     117822
DIAGNOSIS8                     117859
REFERRINGPROVIDERID            117889
APPOINTMENTID                       0
CURRENTILLNESSDATE                  0
SERVICEDATE                         0
SUPERVISINGPROVIDERID               0
STATUS1                             0
STATUS2                        103727
STATUSP                             0
OUTSTANDING1                        0
OUTSTANDING2                   103727
OUTSTANDINGP                        0
LASTBILLEDDATE1                     0
LASTBILLEDDATE2                103727
LASTBILLEDDATEP                     0
HEALTHCARECLAIMTYPEID1              0
HEALTHCARECLAIMTYPEID2              0
dtype: int64

Columns with missing values:
DIAGNOSIS2              89378
DIAGNOSIS3             111855
DIAGNOSIS4             116212
DIAGNOSIS5             117411
DIAGNOSIS6             117757
DIAGNOSIS7             117822
DIAGNOSIS8             117859
REFERRINGPROVIDERID    117889
STATUS2                103727
OUTSTANDING2           103727
LASTBILLEDDATE2        103727
dtype: int64

In [98]:
# ============================================
# DUPLICATE CHECK
# ============================================

duplicate_claim_ids = claims["Id"].duplicated().sum()
duplicate_complete_rows = claims.duplicated().sum()

print("Duplicate claim IDs:", duplicate_claim_ids)
print("Duplicate complete rows:", duplicate_complete_rows)

print("Total claim records:", len(claims))
print("Unique claim IDs:", claims["Id"].nunique())

Duplicate claim IDs: 0
Duplicate complete rows: 0
Total claim records: 117889
Unique claim IDs: 117889

In [105]:
# ============================================
# PAYER REFERENCE VALIDATION
# ============================================

claim_payer_ids = set(claims["PAYER"].dropna())
payer_ids = set(payers["Id"].dropna())

missing_payer_refs = claim_payer_ids - payer_ids

print("Unique payers in claims:", len(claim_payer_ids))
print("Unique payers in payers table:", len(payer_ids))
print("Payer references missing from payers table:",
      len(missing_payer_refs))

if len(missing_payer_refs) == 0:
    print("✓ All claim payer references are valid.")
else:
    print("⚠ Some payer references are missing.")

KeyError: 'PAYER'

In [106]:
# ============================================
# CLAIMS - PROVIDER REFERENCE VALIDATION
# ============================================

claim_provider_ids = set(claims["PROVIDERID"].dropna())
provider_ids = set(providers["Id"].dropna())

missing_provider_refs = claim_provider_ids - provider_ids

print("Unique providers in claims:", len(claim_provider_ids))
print("Unique providers in providers table:", len(provider_ids))
print("Provider references missing from providers table:",
      len(missing_provider_refs))

if len(missing_provider_refs) == 0:
    print("✓ All claim provider references are valid.")
else:
    print("⚠ Some provider references are missing.")

Unique providers in claims: 1123
Unique providers in providers table: 5056
Provider references missing from providers table: 0
✓ All claim provider references are valid.

In [107]:
# ============================================
# CLAIMS - PRIMARY INSURANCE VALIDATION
# ============================================

payer_ids = set(payers["Id"].dropna())

primary_insurance_ids = set(
    claims["PRIMARYPATIENTINSURANCEID"].dropna()
)

missing_primary_insurance = (
    primary_insurance_ids - payer_ids
)

print("Unique primary insurance IDs:",
      len(primary_insurance_ids))

print("Unique payer IDs:",
      len(payer_ids))

print("Primary insurance references missing from payers:",
      len(missing_primary_insurance))

if len(missing_primary_insurance) == 0:
    print("✓ All primary insurance references are valid.")
else:
    print("⚠ Some primary insurance references are missing.")

Unique primary insurance IDs: 11
Unique payer IDs: 10
Primary insurance references missing from payers: 1
⚠ Some primary insurance references are missing.

In [108]:
# ============================================
# CLAIMS - SECONDARY INSURANCE VALIDATION
# ============================================

secondary_insurance_ids = set(
    claims["SECONDARYPATIENTINSURANCEID"].dropna()
)

missing_secondary_insurance = (
    secondary_insurance_ids - payer_ids
)

print("Unique secondary insurance IDs:",
      len(secondary_insurance_ids))

print("Secondary insurance references missing from payers:",
      len(missing_secondary_insurance))

if len(missing_secondary_insurance) == 0:
    print("✓ All secondary insurance references are valid.")
else:
    print("⚠ Some secondary insurance references are missing.")

Unique secondary insurance IDs: 8
Secondary insurance references missing from payers: 1
⚠ Some secondary insurance references are missing.

In [109]:
# ============================================
# CLAIMS - DATE VALIDATION
# ============================================

date_columns = [
    "CURRENTILLNESSDATE",
    "SERVICEDATE",
    "LASTBILLEDDATE1",
    "LASTBILLEDDATE2",
    "LASTBILLEDDATEP"
]

for column in date_columns:
    claims[column] = pd.to_datetime(
        claims[column],
        errors="coerce"
    )

print("Date column validation:\n")

for column in date_columns:
    print(
        column,
        "->",
        claims[column].dtype,
        "| Missing:",
        claims[column].isna().sum()
    )

Date column validation:

CURRENTILLNESSDATE -> datetime64[us, UTC] | Missing: 0
SERVICEDATE -> datetime64[us, UTC] | Missing: 0
LASTBILLEDDATE1 -> datetime64[us, UTC] | Missing: 0
LASTBILLEDDATE2 -> datetime64[us, UTC] | Missing: 103727
LASTBILLEDDATEP -> datetime64[us, UTC] | Missing: 0

In [110]:
# ============================================
# CLAIMS - DATE LOGIC CHECK
# ============================================

print("============================================")
print("CLAIMS DATE LOGIC CHECK")
print("============================================")

invalid_illness_service = (
    claims["CURRENTILLNESSDATE"] >
    claims["SERVICEDATE"]
).sum()

print(
    "CURRENTILLNESSDATE after SERVICEDATE:",
    invalid_illness_service
)

for column in [
    "LASTBILLEDDATE1",
    "LASTBILLEDDATE2",
    "LASTBILLEDDATEP"
]:

    invalid_dates = (
        claims[column].notna() &
        (claims[column] < claims["SERVICEDATE"])
    ).sum()

    print(
        column,
        "before SERVICEDATE:",
        invalid_dates
    )

============================================
CLAIMS DATE LOGIC CHECK
============================================
CURRENTILLNESSDATE after SERVICEDATE: 0
LASTBILLEDDATE1 before SERVICEDATE: 0
LASTBILLEDDATE2 before SERVICEDATE: 0
LASTBILLEDDATEP before SERVICEDATE: 0

In [111]:
# ============================================
# CLAIMS - FINANCIAL COLUMN ANALYSIS
# ============================================

financial_columns = [
    "OUTSTANDING1",
    "OUTSTANDING2",
    "OUTSTANDINGP"
]

print("Financial columns:")
print(financial_columns)

print("\nFinancial summary:")

print(
    claims[financial_columns]
    .describe()
    .T
)

Financial columns:
['OUTSTANDING1', 'OUTSTANDING2', 'OUTSTANDINGP']

Financial summary:
                 count  mean  std  min  25%  50%  75%  max
OUTSTANDING1  117889.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
OUTSTANDING2   14162.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
OUTSTANDINGP  117889.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [112]:
# ============================================
# CLAIMS - NEGATIVE FINANCIAL VALUES
# ============================================

for column in financial_columns:

    negative_count = (
        claims[column] < 0
    ).sum()

    print(
        column,
        "-> negative values:",
        negative_count
    )

OUTSTANDING1 -> negative values: 0
OUTSTANDING2 -> negative values: 0
OUTSTANDINGP -> negative values: 0

In [113]:
# ============================================
# CLAIMS - ZERO FINANCIAL VALUES
# ============================================

for column in financial_columns:

    zero_count = (
        claims[column] == 0
    ).sum()

    print(
        column,
        "-> zero values:",
        zero_count
    )

OUTSTANDING1 -> zero values: 117889
OUTSTANDING2 -> zero values: 14162
OUTSTANDINGP -> zero values: 117889

In [114]:
# ============================================
# CLAIMS - STATUS ANALYSIS
# ============================================

for column in [
    "STATUS1",
    "STATUS2",
    "STATUSP"
]:

    print("\n================================")
    print(column)
    print("================================")

    print(
        claims[column]
        .value_counts(dropna=False)
    )

================================
STATUS1
================================
STATUS1
CLOSED    117732
BILLED       157
Name: count, dtype: int64

================================
STATUS2
================================
STATUS2
NaN       103727
CLOSED     14118
BILLED        44
Name: count, dtype: int64

================================
STATUSP
================================
STATUSP
CLOSED    117732
BILLED       157
Name: count, dtype: int64

In [115]:
# ============================================
# CLAIMS - DIAGNOSIS INFORMATION
# ============================================

diagnosis_columns = [
    "DIAGNOSIS1",
    "DIAGNOSIS2",
    "DIAGNOSIS3",
    "DIAGNOSIS4",
    "DIAGNOSIS5",
    "DIAGNOSIS6",
    "DIAGNOSIS7",
    "DIAGNOSIS8"
]

print("============================================")
print("DIAGNOSIS INFORMATION")
print("============================================")

for column in diagnosis_columns:

    print(
        column,
        "-> Populated:",
        claims[column].notna().sum(),
        "| Missing:",
        claims[column].isna().sum(),
        "| Unique:",
        claims[column].nunique()
    )

============================================
DIAGNOSIS INFORMATION
============================================
DIAGNOSIS1 -> Populated: 117889 | Missing: 0 | Unique: 176
DIAGNOSIS2 -> Populated: 28511 | Missing: 89378 | Unique: 127
DIAGNOSIS3 -> Populated: 6034 | Missing: 111855 | Unique: 64
DIAGNOSIS4 -> Populated: 1677 | Missing: 116212 | Unique: 46
DIAGNOSIS5 -> Populated: 478 | Missing: 117411 | Unique: 44
DIAGNOSIS6 -> Populated: 132 | Missing: 117757 | Unique: 24
DIAGNOSIS7 -> Populated: 67 | Missing: 117822 | Unique: 16
DIAGNOSIS8 -> Populated: 30 | Missing: 117859 | Unique: 9

In [116]:
# ============================================
# CLAIMS - HEALTHCARE CLAIM TYPES
# ============================================

for column in [
    "HEALTHCARECLAIMTYPEID1",
    "HEALTHCARECLAIMTYPEID2"
]:

    print("\n================================")
    print(column)
    print("================================")

    print(
        claims[column]
        .value_counts(dropna=False)
    )

================================
HEALTHCARECLAIMTYPEID1
================================
HEALTHCARECLAIMTYPEID1
2    69039
1    48850
Name: count, dtype: int64

================================
HEALTHCARECLAIMTYPEID2
================================
HEALTHCARECLAIMTYPEID2
0    103727
2     10186
1      3976
Name: count, dtype: int64

In [117]:
# ============================================
# CLAIMS - DEPARTMENT INFORMATION
# ============================================

print("Unique DEPARTMENTID:",
      claims["DEPARTMENTID"].nunique())

print("Unique PATIENTDEPARTMENTID:",
      claims["PATIENTDEPARTMENTID"].nunique())

print("\nTop DEPARTMENTID values:")

print(
    claims["DEPARTMENTID"]
    .value_counts()
    .head(20)
)

print("\nTop PATIENTDEPARTMENTID values:")

print(
    claims["PATIENTDEPARTMENTID"]
    .value_counts()
    .head(20)
)

Unique DEPARTMENTID: 7
Unique PATIENTDEPARTMENTID: 7

Top DEPARTMENTID values:
DEPARTMENTID
20    47558
1     28480
2     26379
10     6207
3      3403
4      3286
5      2576
Name: count, dtype: int64

Top PATIENTDEPARTMENTID values:
PATIENTDEPARTMENTID
20    47558
1     28480
2     26379
10     6207
3      3403
4      3286
5      2576
Name: count, dtype: int64

In [118]:
# ============================================
# CLAIMS - FINAL VALIDATION SUMMARY
# ============================================

print("============================================")
print("CLAIMS DATASET VALIDATION SUMMARY")
print("============================================")

print("Total rows:", len(claims))
print("Total columns:", claims.shape[1])

print("\nDuplicate claim IDs:",
      claims["Id"].duplicated().sum())

print("Duplicate complete rows:",
      claims.duplicated().sum())

print("\nUnique patients:",
      claims["PATIENTID"].nunique())

print("Unique providers:",
      claims["PROVIDERID"].nunique())

print("Unique primary insurance IDs:",
      claims["PRIMARYPATIENTINSURANCEID"].nunique())

print("Unique secondary insurance IDs:",
      claims["SECONDARYPATIENTINSURANCEID"].nunique())

print("\nMissing values:")

missing_summary = claims.isnull().sum()

print(
    missing_summary[
        missing_summary > 0
    ]
)

print("\nClaims validation completed.")

============================================
CLAIMS DATASET VALIDATION SUMMARY
============================================
Total rows: 117889
Total columns: 31

Duplicate claim IDs: 0
Duplicate complete rows: 0

Unique patients: 1163
Unique providers: 1123
Unique primary insurance IDs: 11
Unique secondary insurance IDs: 8

Missing values:
DIAGNOSIS2              89378
DIAGNOSIS3             111855
DIAGNOSIS4             116212
DIAGNOSIS5             117411
DIAGNOSIS6             117757
DIAGNOSIS7             117822
DIAGNOSIS8             117859
REFERRINGPROVIDERID    117889
STATUS2                103727
OUTSTANDING2           103727
LASTBILLEDDATE2        103727
dtype: int64

Claims validation completed.

In [1]:
# ============================================================
# REMAINING DATASETS - COMPLETE VALIDATION
# Healthcare Cost Optimization Analytics
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. DATA PATH
# ------------------------------------------------------------

DATA_PATH = Path("../data/Raw_Datasets")

datasets_to_validate = [
    "claims_transactions.csv",
    "medications.csv",
    "observations.csv",
    "careplans.csv",
    "imaging_studies.csv",
    "allergies.csv",
    "immunizations.csv",
    "payer_transitions.csv"
]

# ------------------------------------------------------------
# 2. LOAD ALL DATASETS
# ------------------------------------------------------------

data = {}

for file_name in datasets_to_validate:
    file_path = DATA_PATH / file_name

    df = pd.read_csv(file_path)
    data[file_name] = df

    print("=" * 80)
    print(f"{file_name}")
    print("=" * 80)
    print(f"Rows    : {df.shape[0]:,}")
    print(f"Columns : {df.shape[1]}")
    print()
    print("Columns:")
    print(df.columns.tolist())
    print()
    print("Data types:")
    print(df.dtypes)
    print()


# ============================================================
# 3. GENERAL STRUCTURAL VALIDATION
# ============================================================

for file_name, df in data.items():

    print("\n" + "=" * 80)
    print(f"STRUCTURAL VALIDATION - {file_name}")
    print("=" * 80)

    print(f"Total rows: {len(df):,}")
    print(f"Total columns: {len(df.columns)}")

    # --------------------------------------------------------
    # Duplicate rows
    # --------------------------------------------------------

    duplicate_rows = df.duplicated().sum()

    print(f"Duplicate complete rows: {duplicate_rows:,}")

    # --------------------------------------------------------
    # ID validation
    # --------------------------------------------------------

    if "Id" in df.columns:

        duplicate_ids = df["Id"].duplicated().sum()
        missing_ids = df["Id"].isna().sum()
        unique_ids = df["Id"].nunique(dropna=True)

        print(f"Unique IDs: {unique_ids:,}")
        print(f"Duplicate IDs: {duplicate_ids:,}")
        print(f"Missing IDs: {missing_ids:,}")

    # --------------------------------------------------------
    # Missing values
    # --------------------------------------------------------

    missing = df.isna().sum()
    missing = missing[missing > 0].sort_values(ascending=False)

    print("\nMissing values:")

    if len(missing) == 0:
        print("No missing values.")
    else:
        print(missing)

    # --------------------------------------------------------
    # Numeric columns
    # --------------------------------------------------------

    numeric_cols = df.select_dtypes(include=np.number).columns.tolist()

    if numeric_cols:

        print("\nNumeric columns:")

        for col in numeric_cols:

            negative_count = (df[col] < 0).sum()
            zero_count = (df[col] == 0).sum()

            print(
                f"{col} -> "
                f"negative: {negative_count:,} | "
                f"zero: {zero_count:,}"
            )


# ============================================================
# 4. PATIENT REFERENCE VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("PATIENT REFERENCE VALIDATION")
print("=" * 80)

patients = data.get("patients.csv")

# patients.csv was already loaded earlier in the notebook.
# If it is not currently available, load it safely.

if patients is None:
    patients = pd.read_csv(DATA_PATH / "patients.csv")

patient_ids = set(patients["Id"].dropna())

for file_name, df in data.items():

    patient_columns = [
        col for col in df.columns
        if col.upper() in [
            "PATIENT",
            "PATIENTID",
            "PATIENT_ID"
        ]
    ]

    for col in patient_columns:

        source_ids = set(df[col].dropna())

        missing_refs = source_ids - patient_ids

        print(f"\n{file_name} -> {col}")
        print(f"Unique patient references: {len(source_ids):,}")
        print(f"Missing patient references: {len(missing_refs):,}")

        if len(missing_refs) == 0:
            print("✓ All patient references are valid.")
        else:
            print("⚠ Some patient references are not present in patients.csv.")


# ============================================================
# 5. PROVIDER REFERENCE VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("PROVIDER REFERENCE VALIDATION")
print("=" * 80)

providers = data.get("providers.csv")

if providers is None:
    providers = pd.read_csv(DATA_PATH / "providers.csv")

provider_ids = set(providers["Id"].dropna())

for file_name, df in data.items():

    provider_columns = [
        col for col in df.columns
        if "PROVIDER" in col.upper()
    ]

    for col in provider_columns:

        source_ids = set(df[col].dropna())

        missing_refs = source_ids - provider_ids

        print(f"\n{file_name} -> {col}")
        print(f"Unique provider references: {len(source_ids):,}")
        print(f"Missing provider references: {len(missing_refs):,}")

        if len(missing_refs) == 0:
            print("✓ All provider references are valid.")
        else:
            print("⚠ Some provider references are not present in providers.csv.")


# ============================================================
# 6. ENCOUNTER REFERENCE VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("ENCOUNTER REFERENCE VALIDATION")
print("=" * 80)

encounters = data.get("encounters.csv")

if encounters is None:
    encounters = pd.read_csv(DATA_PATH / "encounters.csv")

encounter_ids = set(encounters["Id"].dropna())

for file_name, df in data.items():

    encounter_columns = [
        col for col in df.columns
        if col.upper() in [
            "ENCOUNTER",
            "ENCOUNTERID",
            "ENCOUNTER_ID"
        ]
    ]

    for col in encounter_columns:

        source_ids = set(df[col].dropna())

        missing_refs = source_ids - encounter_ids

        print(f"\n{file_name} -> {col}")
        print(f"Unique encounter references: {len(source_ids):,}")
        print(f"Missing encounter references: {len(missing_refs):,}")

        if len(missing_refs) == 0:
            print("✓ All encounter references are valid.")
        else:
            print("⚠ Some encounter references are not present in encounters.csv.")


# ============================================================
# 7. PAYER REFERENCE VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("PAYER REFERENCE VALIDATION")
print("=" * 80)

payers = data.get("payers.csv")

if payers is None:
    payers = pd.read_csv(DATA_PATH / "payers.csv")

payer_ids = set(payers["Id"].dropna())

for file_name, df in data.items():

    payer_columns = [
        col for col in df.columns
        if "PAYER" in col.upper()
    ]

    for col in payer_columns:

        source_ids = set(df[col].dropna())

        missing_refs = source_ids - payer_ids

        print(f"\n{file_name} -> {col}")
        print(f"Unique payer references: {len(source_ids):,}")
        print(f"Missing payer references: {len(missing_refs):,}")

        if len(missing_refs) == 0:
            print("✓ All payer references are valid.")
        else:
            print("⚠ Some payer references are not present in payers.csv.")


# ============================================================
# 8. DATE COLUMN VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("DATE COLUMN VALIDATION")
print("=" * 80)

for file_name, df in data.items():

    print(f"\n--- {file_name} ---")

    date_columns = []

    for col in df.columns:

        col_upper = col.upper()

        # Identify likely date columns
        if any(keyword in col_upper for keyword in [
            "DATE",
            "START",
            "STOP",
            "TIME"
        ]):

            date_columns.append(col)

    if not date_columns:
        print("No obvious date columns detected.")
        continue

    for col in date_columns:

        converted = pd.to_datetime(
            df[col],
            errors="coerce",
            utc=True
        )

        invalid = (
            df[col].notna() &
            converted.isna()
        ).sum()

        missing = converted.isna().sum()

        print(
            f"{col} -> "
            f"Invalid values: {invalid:,} | "
            f"Missing after conversion: {missing:,}"
        )


# ============================================================
# 9. NEGATIVE NUMERIC VALUE CHECK
# ============================================================

print("\n" + "=" * 80)
print("NEGATIVE VALUE CHECK")
print("=" * 80)

for file_name, df in data.items():

    numeric_cols = df.select_dtypes(include=np.number).columns.tolist()

    if not numeric_cols:
        continue

    print(f"\n--- {file_name} ---")

    found_negative = False

    for col in numeric_cols:

        negative_count = (df[col] < 0).sum()

        if negative_count > 0:

            found_negative = True

            print(
                f"{col} -> "
                f"Negative values: {negative_count:,}"
            )

    if not found_negative:
        print("No negative numeric values found.")


# ============================================================
# 10. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("REMAINING DATASETS VALIDATION SUMMARY")
print("=" * 80)

summary_rows = []

for file_name, df in data.items():

    summary_rows.append({
        "Dataset": file_name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Duplicate Rows": df.duplicated().sum(),
        "Missing Cells": int(df.isna().sum().sum())
    })

validation_summary = pd.DataFrame(summary_rows)

print(validation_summary.to_string(index=False))

print("\n" + "=" * 80)
print("ALL REMAINING DATASET VALIDATIONS COMPLETED")
print("=" * 80)

================================================================================
claims_transactions.csv
================================================================================
Rows    : 711,238
Columns : 33

Columns:
['ID', 'CLAIMID', 'CHARGEID', 'PATIENTID', 'TYPE', 'AMOUNT', 'METHOD', 'FROMDATE', 'TODATE', 'PLACEOFSERVICE', 'PROCEDURECODE', 'MODIFIER1', 'MODIFIER2', 'DIAGNOSISREF1', 'DIAGNOSISREF2', 'DIAGNOSISREF3', 'DIAGNOSISREF4', 'UNITS', 'DEPARTMENTID', 'NOTES', 'UNITAMOUNT', 'TRANSFEROUTID', 'TRANSFERTYPE', 'PAYMENTS', 'ADJUSTMENTS', 'TRANSFERS', 'OUTSTANDING', 'APPOINTMENTID', 'LINENOTE', 'PATIENTINSURANCEID', 'FEESCHEDULEID', 'PROVIDERID', 'SUPERVISINGPROVIDERID']

Data types:
ID                           str
CLAIMID                      str
CHARGEID                   int64
PATIENTID                    str
TYPE                         str
AMOUNT                   float64
METHOD                       str
FROMDATE                     str
TODATE                       str
PLACEOFSERVICE               str
PROCEDURECODE              int64
MODIFIER1                float64
MODIFIER2                float64
DIAGNOSISREF1              int64
DIAGNOSISREF2            float64
DIAGNOSISREF3            float64
DIAGNOSISREF4            float64
UNITS                      int64
DEPARTMENTID               int64
NOTES                        str
UNITAMOUNT               float64
TRANSFEROUTID            float64
TRANSFERTYPE                 str
PAYMENTS                 float64
ADJUSTMENTS              float64
TRANSFERS                float64
OUTSTANDING              float64
APPOINTMENTID                str
LINENOTE                 float64
PATIENTINSURANCEID           str
FEESCHEDULEID              int64
PROVIDERID                   str
SUPERVISINGPROVIDERID        str
dtype: object

================================================================================
medications.csv
================================================================================
Rows    : 56,430
Columns : 13

Columns:
['START', 'STOP', 'PATIENT', 'PAYER', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'PAYER_COVERAGE', 'DISPENSES', 'TOTALCOST', 'REASONCODE', 'REASONDESCRIPTION']

Data types:
START                    str
STOP                     str
PATIENT                  str
PAYER                    str
ENCOUNTER                str
CODE                   int64
DESCRIPTION              str
BASE_COST            float64
PAYER_COVERAGE       float64
DISPENSES              int64
TOTALCOST            float64
REASONCODE           float64
REASONDESCRIPTION        str
dtype: object

================================================================================
observations.csv
================================================================================
Rows    : 531,144
Columns : 9

Columns:
['DATE', 'PATIENT', 'ENCOUNTER', 'CATEGORY', 'CODE', 'DESCRIPTION', 'VALUE', 'UNITS', 'TYPE']

Data types:
DATE           str
PATIENT        str
ENCOUNTER      str
CATEGORY       str
CODE           str
DESCRIPTION    str
VALUE          str
UNITS          str
TYPE           str
dtype: object

================================================================================
careplans.csv
================================================================================
Rows    : 3,931
Columns : 9

Columns:
['Id', 'START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'REASONCODE', 'REASONDESCRIPTION']

Data types:
Id                       str
START                    str
STOP                     str
PATIENT                  str
ENCOUNTER                str
CODE                   int64
DESCRIPTION              str
REASONCODE           float64
REASONDESCRIPTION        str
dtype: object

================================================================================
imaging_studies.csv
================================================================================
Rows    : 151,637
Columns : 13

Columns:
['Id', 'DATE', 'PATIENT', 'ENCOUNTER', 'SERIES_UID', 'BODYSITE_CODE', 'BODYSITE_DESCRIPTION', 'MODALITY_CODE', 'MODALITY_DESCRIPTION', 'INSTANCE_UID', 'SOP_CODE', 'SOP_DESCRIPTION', 'PROCEDURE_CODE']

Data types:
Id                        str
DATE                      str
PATIENT                   str
ENCOUNTER                 str
SERIES_UID                str
BODYSITE_CODE           int64
BODYSITE_DESCRIPTION      str
MODALITY_CODE             str
MODALITY_DESCRIPTION      str
INSTANCE_UID              str
SOP_CODE                  str
SOP_DESCRIPTION           str
PROCEDURE_CODE          int64
dtype: object

================================================================================
allergies.csv
================================================================================
Rows    : 794
Columns : 15

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'SYSTEM', 'DESCRIPTION', 'TYPE', 'CATEGORY', 'REACTION1', 'DESCRIPTION1', 'SEVERITY1', 'REACTION2', 'DESCRIPTION2', 'SEVERITY2']

Data types:
START               str
STOP            float64
PATIENT             str
ENCOUNTER           str
CODE              int64
SYSTEM              str
DESCRIPTION         str
TYPE                str
CATEGORY            str
REACTION1       float64
DESCRIPTION1        str
SEVERITY1           str
REACTION2       float64
DESCRIPTION2        str
SEVERITY2           str
dtype: object

================================================================================
immunizations.csv
================================================================================
Rows    : 17,009
Columns : 6

Columns:
['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST']

Data types:
DATE               str
PATIENT            str
ENCOUNTER          str
CODE             int64
DESCRIPTION        str
BASE_COST      float64
dtype: object

================================================================================
payer_transitions.csv
================================================================================
Rows    : 53,101
Columns : 8

Columns:
['PATIENT', 'MEMBERID', 'START_YEAR', 'END_YEAR', 'PAYER', 'SECONDARY_PAYER', 'OWNERSHIP', 'OWNERNAME']

Data types:
PATIENT            str
MEMBERID           str
START_YEAR         str
END_YEAR           str
PAYER              str
SECONDARY_PAYER    str
OWNERSHIP          str
OWNERNAME          str
dtype: object


================================================================================
STRUCTURAL VALIDATION - claims_transactions.csv
================================================================================
Total rows: 711,238
Total columns: 33
Duplicate complete rows: 0

Missing values:
MODIFIER2             711238
MODIFIER1             711238
LINENOTE              711238
ADJUSTMENTS           711238
DIAGNOSISREF4         698843
DIAGNOSISREF3         667976
TRANSFEROUTID         591147
DIAGNOSISREF2         516000
UNITAMOUNT            492517
TRANSFERS             471056
PAYMENTS              458903
METHOD                458903
AMOUNT                372426
TRANSFERTYPE          372426
OUTSTANDING           218721
PATIENTINSURANCEID     89738
dtype: int64

Numeric columns:
CHARGEID -> negative: 0 | zero: 1
AMOUNT -> negative: 0 | zero: 44,612
PROCEDURECODE -> negative: 0 | zero: 0
MODIFIER1 -> negative: 0 | zero: 0
MODIFIER2 -> negative: 0 | zero: 0
DIAGNOSISREF1 -> negative: 0 | zero: 0
DIAGNOSISREF2 -> negative: 0 | zero: 0
DIAGNOSISREF3 -> negative: 0 | zero: 0
DIAGNOSISREF4 -> negative: 0 | zero: 0
UNITS -> negative: 0 | zero: 0
DEPARTMENTID -> negative: 0 | zero: 0
UNITAMOUNT -> negative: 0 | zero: 44,612
TRANSFEROUTID -> negative: 0 | zero: 0
PAYMENTS -> negative: 0 | zero: 0
ADJUSTMENTS -> negative: 0 | zero: 0
TRANSFERS -> negative: 0 | zero: 0
OUTSTANDING -> negative: 0 | zero: 174,109
LINENOTE -> negative: 0 | zero: 0
FEESCHEDULEID -> negative: 0 | zero: 0

================================================================================
STRUCTURAL VALIDATION - medications.csv
================================================================================
Total rows: 56,430
Total columns: 13
Duplicate complete rows: 0

Missing values:
REASONCODE           15471
REASONDESCRIPTION    15471
STOP                  2713
dtype: int64

Numeric columns:
CODE -> negative: 0 | zero: 0
BASE_COST -> negative: 0 | zero: 0
PAYER_COVERAGE -> negative: 0 | zero: 48,918
DISPENSES -> negative: 0 | zero: 0
TOTALCOST -> negative: 0 | zero: 0
REASONCODE -> negative: 0 | zero: 0

================================================================================
STRUCTURAL VALIDATION - observations.csv
================================================================================
Total rows: 531,144
Total columns: 9
Duplicate complete rows: 249

Missing values:
UNITS        185017
ENCOUNTER     31662
CATEGORY      31662
dtype: int64

================================================================================
STRUCTURAL VALIDATION - careplans.csv
================================================================================
Total rows: 3,931
Total columns: 9
Duplicate complete rows: 0
Unique IDs: 3,931
Duplicate IDs: 0
Missing IDs: 0

Missing values:
STOP                 1679
REASONCODE            558
REASONDESCRIPTION     558
dtype: int64

Numeric columns:
CODE -> negative: 0 | zero: 0
REASONCODE -> negative: 0 | zero: 0

================================================================================
STRUCTURAL VALIDATION - imaging_studies.csv
================================================================================
Total rows: 151,637
Total columns: 13
Duplicate complete rows: 0
Unique IDs: 920
Duplicate IDs: 150,717
Missing IDs: 0

Missing values:
No missing values.

Numeric columns:
BODYSITE_CODE -> negative: 0 | zero: 0
PROCEDURE_CODE -> negative: 0 | zero: 0

================================================================================
STRUCTURAL VALIDATION - allergies.csv
================================================================================
Total rows: 794
Total columns: 15
Duplicate complete rows: 0

Missing values:
STOP            794
DESCRIPTION2    535
REACTION2       535
SEVERITY2       535
REACTION1       384
DESCRIPTION1    384
SEVERITY1       384
dtype: int64

Numeric columns:
STOP -> negative: 0 | zero: 0
CODE -> negative: 0 | zero: 0
REACTION1 -> negative: 0 | zero: 0
REACTION2 -> negative: 0 | zero: 0

================================================================================
STRUCTURAL VALIDATION - immunizations.csv
================================================================================
Total rows: 17,009
Total columns: 6
Duplicate complete rows: 0

Missing values:
No missing values.

Numeric columns:
CODE -> negative: 0 | zero: 0
BASE_COST -> negative: 0 | zero: 0

================================================================================
STRUCTURAL VALIDATION - payer_transitions.csv
================================================================================
Total rows: 53,101
Total columns: 8
Duplicate complete rows: 0

Missing values:
SECONDARY_PAYER    51121
MEMBERID            9546
OWNERSHIP           9546
OWNERNAME           9546
dtype: int64

================================================================================
PATIENT REFERENCE VALIDATION
================================================================================

claims_transactions.csv -> PATIENTID
Unique patient references: 1,163
Missing patient references: 0
✓ All patient references are valid.

medications.csv -> PATIENT
Unique patient references: 1,117
Missing patient references: 0
✓ All patient references are valid.

observations.csv -> PATIENT
Unique patient references: 1,163
Missing patient references: 0
✓ All patient references are valid.

careplans.csv -> PATIENT
Unique patient references: 1,068
Missing patient references: 0
✓ All patient references are valid.

imaging_studies.csv -> PATIENT
Unique patient references: 238
Missing patient references: 0
✓ All patient references are valid.

allergies.csv -> PATIENT
Unique patient references: 179
Missing patient references: 0
✓ All patient references are valid.

immunizations.csv -> PATIENT
Unique patient references: 1,158
Missing patient references: 0
✓ All patient references are valid.

payer_transitions.csv -> PATIENT
Unique patient references: 1,163
Missing patient references: 0
✓ All patient references are valid.

================================================================================
PROVIDER REFERENCE VALIDATION
================================================================================

claims_transactions.csv -> PROVIDERID
Unique provider references: 1,123
Missing provider references: 0
✓ All provider references are valid.

claims_transactions.csv -> SUPERVISINGPROVIDERID
Unique provider references: 1,123
Missing provider references: 0
✓ All provider references are valid.

================================================================================
ENCOUNTER REFERENCE VALIDATION
================================================================================

medications.csv -> ENCOUNTER
Unique encounter references: 26,871
Missing encounter references: 0
✓ All encounter references are valid.

observations.csv -> ENCOUNTER
Unique encounter references: 21,025
Missing encounter references: 0
✓ All encounter references are valid.

careplans.csv -> ENCOUNTER
Unique encounter references: 3,849
Missing encounter references: 0
✓ All encounter references are valid.

imaging_studies.csv -> ENCOUNTER
Unique encounter references: 920
Missing encounter references: 0
✓ All encounter references are valid.

allergies.csv -> ENCOUNTER
Unique encounter references: 179
Missing encounter references: 0
✓ All encounter references are valid.

immunizations.csv -> ENCOUNTER
Unique encounter references: 11,796
Missing encounter references: 0
✓ All encounter references are valid.

================================================================================
PAYER REFERENCE VALIDATION
================================================================================

medications.csv -> PAYER
Unique payer references: 10
Missing payer references: 0
✓ All payer references are valid.

medications.csv -> PAYER_COVERAGE
Unique payer references: 5,911
Missing payer references: 5,911
⚠ Some payer references are not present in payers.csv.

payer_transitions.csv -> PAYER
Unique payer references: 10
Missing payer references: 0
✓ All payer references are valid.

payer_transitions.csv -> SECONDARY_PAYER
Unique payer references: 6
Missing payer references: 0
✓ All payer references are valid.

================================================================================
DATE COLUMN VALIDATION
================================================================================

--- claims_transactions.csv ---
FROMDATE -> Invalid values: 0 | Missing after conversion: 0
TODATE -> Invalid values: 0 | Missing after conversion: 0

--- medications.csv ---
START -> Invalid values: 0 | Missing after conversion: 0
STOP -> Invalid values: 0 | Missing after conversion: 2,713

--- observations.csv ---
DATE -> Invalid values: 0 | Missing after conversion: 0

--- careplans.csv ---
START -> Invalid values: 0 | Missing after conversion: 0
STOP -> Invalid values: 0 | Missing after conversion: 1,679

--- imaging_studies.csv ---
DATE -> Invalid values: 0 | Missing after conversion: 0

--- allergies.csv ---
START -> Invalid values: 0 | Missing after conversion: 0
STOP -> Invalid values: 0 | Missing after conversion: 794

--- immunizations.csv ---
DATE -> Invalid values: 0 | Missing after conversion: 0

--- payer_transitions.csv ---
START_YEAR -> Invalid values: 0 | Missing after conversion: 0

================================================================================
NEGATIVE VALUE CHECK
================================================================================

--- claims_transactions.csv ---
No negative numeric values found.

--- medications.csv ---
No negative numeric values found.

--- careplans.csv ---
No negative numeric values found.

--- imaging_studies.csv ---
No negative numeric values found.

--- allergies.csv ---
No negative numeric values found.

--- immunizations.csv ---
No negative numeric values found.

================================================================================
REMAINING DATASETS VALIDATION SUMMARY
================================================================================
                Dataset   Rows  Columns  Duplicate Rows  Missing Cells
claims_transactions.csv 711238       33               0        8253608
        medications.csv  56430       13               0          33655
       observations.csv 531144        9             249         248341
          careplans.csv   3931        9               0           2795
    imaging_studies.csv 151637       13               0              0
          allergies.csv    794       15               0           3551
      immunizations.csv  17009        6               0              0
  payer_transitions.csv  53101        8               0          79759

================================================================================
ALL REMAINING DATASET VALIDATIONS COMPLETED
================================================================================

In [2]:
# ============================================================
# FINAL TARGETED VALIDATION
# Observations + Imaging + Claims Transactions
# ============================================================

# ============================================================
# 1. OBSERVATIONS - INVESTIGATE EXACT DUPLICATES
# ============================================================

print("=" * 80)
print("OBSERVATIONS - DUPLICATE INVESTIGATION")
print("=" * 80)

observations = data["observations.csv"]

duplicate_observations = observations[
    observations.duplicated(keep=False)
].sort_values(
    by=observations.columns.tolist()
)

print(f"Total exact duplicate rows: {observations.duplicated().sum():,}")
print(f"Rows involved in exact duplicates: {len(duplicate_observations):,}")

print("\nSample duplicate observations:")
print(duplicate_observations.head(20).to_string(index=False))


# ============================================================
# 2. IMAGING STUDIES - IDENTIFIER INVESTIGATION
# ============================================================

print("\n" + "=" * 80)
print("IMAGING STUDIES - IDENTIFIER VALIDATION")
print("=" * 80)

imaging = data["imaging_studies.csv"]

for col in [
    "Id",
    "SERIES_UID",
    "INSTANCE_UID",
    "ENCOUNTER",
    "PATIENT"
]:

    if col in imaging.columns:

        print(
            f"{col}: "
            f"Rows={len(imaging):,} | "
            f"Unique={imaging[col].nunique(dropna=True):,} | "
            f"Missing={imaging[col].isna().sum():,}"
        )

print("\nDuplicate counts:")

for col in [
    "Id",
    "SERIES_UID",
    "INSTANCE_UID"
]:

    if col in imaging.columns:

        print(
            f"{col} duplicate rows: "
            f"{imaging[col].duplicated().sum():,}"
        )


# ============================================================
# 3. CLAIMS TRANSACTIONS - FINANCIAL VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("CLAIMS TRANSACTIONS - FINANCIAL VALIDATION")
print("=" * 80)

transactions = data["claims_transactions.csv"]

financial_columns = [
    "AMOUNT",
    "UNITAMOUNT",
    "PAYMENTS",
    "ADJUSTMENTS",
    "TRANSFERS",
    "OUTSTANDING"
]

existing_financial_columns = [
    col for col in financial_columns
    if col in transactions.columns
]

print("Financial columns:")
print(existing_financial_columns)

print("\nFinancial summary:")

print(
    transactions[existing_financial_columns]
    .describe()
    .T
)

print("\nNegative values:")

for col in existing_financial_columns:

    negative = (transactions[col] < 0).sum()

    print(
        f"{col} -> negative values: {negative:,}"
    )


# ============================================================
# 4. CLAIMS TRANSACTIONS - DATE LOGIC
# ============================================================

print("\n" + "=" * 80)
print("CLAIMS TRANSACTIONS - DATE LOGIC")
print("=" * 80)

from_date = pd.to_datetime(
    transactions["FROMDATE"],
    errors="coerce",
    utc=True
)

to_date = pd.to_datetime(
    transactions["TODATE"],
    errors="coerce",
    utc=True
)

invalid_date_order = (
    (to_date < from_date)
).sum()

print(
    f"TODATE before FROMDATE: "
    f"{invalid_date_order:,}"
)


# ============================================================
# 5. CLAIM TRANSACTION / CLAIM REFERENCE CHECK
# ============================================================

print("\n" + "=" * 80)
print("CLAIM TRANSACTION -> CLAIM REFERENCE")
print("=" * 80)

claims = pd.read_csv(DATA_PATH / "claims.csv")

claim_ids = set(claims["Id"].dropna())

transaction_claim_ids = set(
    transactions["CLAIMID"].dropna()
)

missing_claim_refs = (
    transaction_claim_ids - claim_ids
)

print(
    f"Unique CLAIMID references: "
    f"{len(transaction_claim_ids):,}"
)

print(
    f"Missing CLAIMID references: "
    f"{len(missing_claim_refs):,}"
)

if len(missing_claim_refs) == 0:
    print("✓ All transaction claim references are valid.")
else:
    print(
        "⚠ Some transaction claim references "
        "are not present in claims.csv."
    )


# ============================================================
# 6. FINAL
# ============================================================

print("\n" + "=" * 80)
print("TARGETED VALIDATION COMPLETED")
print("=" * 80)

================================================================================
OBSERVATIONS - DUPLICATE INVESTIGATION
================================================================================
Total exact duplicate rows: 249
Rows involved in exact duplicates: 498

Sample duplicate observations:
                DATE                              PATIENT                            ENCOUNTER   CATEGORY    CODE    DESCRIPTION VALUE  UNITS    TYPE
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory 20565-8 Carbon Dioxide  26.7 mmol/L numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory 20565-8 Carbon Dioxide  26.7 mmol/L numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory  2069-3       Chloride 105.7 mmol/L numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory  2069-3       Chloride 105.7 mmol/L numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory  2339-0        Glucose 103.3  mg/dL numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory  2339-0        Glucose 103.3  mg/dL numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory  2947-0         Sodium 143.7 mmol/L numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory  2947-0         Sodium 143.7 mmol/L numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory 49765-1        Calcium   9.1  mg/dL numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory 49765-1        Calcium   9.1  mg/dL numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory  6298-4      Potassium   4.2 mmol/L numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory  6298-4      Potassium   4.2 mmol/L numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory  6299-2  Urea Nitrogen  15.2  mg/dL numeric
1988-08-19T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 746da882-3498-0191-5226-2300ea80efcd laboratory  6299-2  Urea Nitrogen  15.2  mg/dL numeric
1988-10-14T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 20d1e885-d0c9-246f-bfa4-da22f8ca2d37 laboratory 20565-8 Carbon Dioxide  20.3 mmol/L numeric
1988-10-14T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 20d1e885-d0c9-246f-bfa4-da22f8ca2d37 laboratory 20565-8 Carbon Dioxide  20.3 mmol/L numeric
1988-10-14T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 20d1e885-d0c9-246f-bfa4-da22f8ca2d37 laboratory  2069-3       Chloride 106.5 mmol/L numeric
1988-10-14T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 20d1e885-d0c9-246f-bfa4-da22f8ca2d37 laboratory  2069-3       Chloride 106.5 mmol/L numeric
1988-10-14T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 20d1e885-d0c9-246f-bfa4-da22f8ca2d37 laboratory  2339-0        Glucose 122.3  mg/dL numeric
1988-10-14T05:11:58Z db2bac5f-730a-7f2a-a600-50d75bdf16c8 20d1e885-d0c9-246f-bfa4-da22f8ca2d37 laboratory  2339-0        Glucose 122.3  mg/dL numeric

================================================================================
IMAGING STUDIES - IDENTIFIER VALIDATION
================================================================================
Id: Rows=151,637 | Unique=920 | Missing=0
SERIES_UID: Rows=151,637 | Unique=920 | Missing=0
INSTANCE_UID: Rows=151,637 | Unique=151,414 | Missing=0
ENCOUNTER: Rows=151,637 | Unique=920 | Missing=0
PATIENT: Rows=151,637 | Unique=238 | Missing=0

Duplicate counts:
Id duplicate rows: 150,717
SERIES_UID duplicate rows: 150,717
INSTANCE_UID duplicate rows: 223

================================================================================
CLAIMS TRANSACTIONS - FINANCIAL VALIDATION
================================================================================
Financial columns:
['AMOUNT', 'UNITAMOUNT', 'PAYMENTS', 'ADJUSTMENTS', 'TRANSFERS', 'OUTSTANDING']

Financial summary:
                count        mean          std   min    25%     50%     75%  \
AMOUNT       338812.0  801.658868  3607.974565  0.00   3.46  103.33  140.52
UNITAMOUNT   218721.0  945.960263  3807.737821  0.00   0.02  129.16  179.27
PAYMENTS     252335.0  822.249597  3420.660506  0.01  40.00   75.00  140.52
ADJUSTMENTS       0.0         NaN          NaN   NaN    NaN     NaN     NaN
TRANSFERS    240182.0  538.843624  3195.699939  0.01  12.49   74.16  140.52
OUTSTANDING  492517.0  289.878651  2260.807199  0.00   0.00    8.16  103.33

                   max
AMOUNT       623241.97
UNITAMOUNT   623241.97
PAYMENTS     623241.97
ADJUSTMENTS        NaN
TRANSFERS    623241.97
OUTSTANDING  623241.97

Negative values:
AMOUNT -> negative values: 0
UNITAMOUNT -> negative values: 0
PAYMENTS -> negative values: 0
ADJUSTMENTS -> negative values: 0
TRANSFERS -> negative values: 0
OUTSTANDING -> negative values: 0

================================================================================
CLAIMS TRANSACTIONS - DATE LOGIC
================================================================================
TODATE before FROMDATE: 70,733

================================================================================
CLAIM TRANSACTION -> CLAIM REFERENCE
================================================================================
Unique CLAIMID references: 117,889
Missing CLAIMID references: 0
✓ All transaction claim references are valid.

================================================================================
TARGETED VALIDATION COMPLETED
================================================================================

In [3]:
# ============================================================
# CLAIMS TRANSACTIONS - DATE ISSUE INVESTIGATION
# ============================================================

transactions = data["claims_transactions.csv"].copy()

transactions["FROMDATE_DT"] = pd.to_datetime(
    transactions["FROMDATE"],
    errors="coerce",
    utc=True
)

transactions["TODATE_DT"] = pd.to_datetime(
    transactions["TODATE"],
    errors="coerce",
    utc=True
)

# Records where TODATE is before FROMDATE
invalid_dates = transactions[
    transactions["TODATE_DT"] < transactions["FROMDATE_DT"]
]

print("=" * 80)
print("CLAIMS TRANSACTIONS - DATE ISSUE BY TYPE")
print("=" * 80)

print(
    invalid_dates["TYPE"]
    .value_counts(dropna=False)
)

print("\nTotal records with TODATE before FROMDATE:",
      len(invalid_dates))

print("\nSample records:")

print(
    invalid_dates[
        [
            "ID",
            "CLAIMID",
            "TYPE",
            "FROMDATE",
            "TODATE",
            "AMOUNT",
            "PAYMENTS",
            "TRANSFERS",
            "OUTSTANDING"
        ]
    ].head(20).to_string(index=False)
)

print("\n" + "=" * 80)
print("ALL TRANSACTION TYPES")
print("=" * 80)

print(
    transactions["TYPE"]
    .value_counts(dropna=False)
)

================================================================================
CLAIMS TRANSACTIONS - DATE ISSUE BY TYPE
================================================================================
TYPE
PAYMENT        21062
CHARGE         19575
TRANSFEROUT    15048
TRANSFERIN     15048
Name: count, dtype: int64

Total records with TODATE before FROMDATE: 70733

Sample records:
                                  ID                              CLAIMID        TYPE             FROMDATE               TODATE  AMOUNT  PAYMENTS  TRANSFERS  OUTSTANDING
0c2bcad5-4bc3-a2d3-8888-6e5d7d024892 e413105d-6f23-34ef-724a-b42adab9df22      CHARGE 2019-02-17T05:07:38Z 1970-01-01T00:00:00Z  140.52       NaN        NaN          NaN
f7f2ee75-9376-7739-d715-b87cc92f71e0 e413105d-6f23-34ef-724a-b42adab9df22     PAYMENT 2019-02-17T05:07:38Z 1970-01-01T00:00:00Z     NaN    133.49        NaN         7.03
ab740c53-6d17-9e1f-91d0-0125b8550d6e e413105d-6f23-34ef-724a-b42adab9df22 TRANSFEROUT 2019-02-17T05:07:38Z 1970-01-01T00:00:00Z     NaN       NaN       7.03         7.03
c6bea013-6fdb-7cc7-e9dc-f1d5e446b243 e413105d-6f23-34ef-724a-b42adab9df22  TRANSFERIN 2019-02-17T05:07:38Z 1970-01-01T00:00:00Z    7.03       NaN       7.03         7.03
02679218-1f6e-cc87-2d53-32275c133e36 e413105d-6f23-34ef-724a-b42adab9df22     PAYMENT 2019-02-17T05:07:38Z 1970-01-01T00:00:00Z     NaN      7.03        NaN         0.00
3be0738a-e802-9d5b-77f7-9274b5558661 8e430d76-6628-c3ac-8950-2acabeb34f86      CHARGE 2019-03-24T05:07:38Z 1970-01-01T00:00:00Z  140.52       NaN        NaN          NaN
21a6f273-3bfb-013e-525b-ba64b031ab1f 8e430d76-6628-c3ac-8950-2acabeb34f86     PAYMENT 2019-03-24T05:07:38Z 1970-01-01T00:00:00Z     NaN    133.49        NaN         7.03
b590f748-2378-66d4-fbe7-dd4ad66a80a1 8e430d76-6628-c3ac-8950-2acabeb34f86 TRANSFEROUT 2019-03-24T05:07:38Z 1970-01-01T00:00:00Z     NaN       NaN       7.03         7.03
19611de0-fb7c-a985-b359-e538fb3c902a 8e430d76-6628-c3ac-8950-2acabeb34f86  TRANSFERIN 2019-03-24T05:07:38Z 1970-01-01T00:00:00Z    7.03       NaN       7.03         7.03
65b29bcb-592c-3b1e-641f-bcdce8ec0706 8e430d76-6628-c3ac-8950-2acabeb34f86     PAYMENT 2019-03-24T05:07:38Z 1970-01-01T00:00:00Z     NaN      7.03        NaN         0.00
308bc217-15a0-95d4-f193-141f086ef3ad 3a69d5f0-26d8-fe66-4a1b-1a7c9ab618c8      CHARGE 2019-05-26T05:07:38Z 1970-01-01T00:00:00Z  140.52       NaN        NaN          NaN
bcbd4cb6-71d7-1efa-b597-85ebc89333f9 3a69d5f0-26d8-fe66-4a1b-1a7c9ab618c8     PAYMENT 2019-05-26T05:07:38Z 1970-01-01T00:00:00Z     NaN    133.49        NaN         7.03
4480f89a-fc0b-675f-c08c-f775b6b80f2d 3a69d5f0-26d8-fe66-4a1b-1a7c9ab618c8 TRANSFEROUT 2019-05-26T05:07:38Z 1970-01-01T00:00:00Z     NaN       NaN       7.03         7.03
d91d4634-689b-bf05-3913-d79be43ff16d 3a69d5f0-26d8-fe66-4a1b-1a7c9ab618c8  TRANSFERIN 2019-05-26T05:07:38Z 1970-01-01T00:00:00Z    7.03       NaN       7.03         7.03
3581e139-ef9f-66e6-5178-5202d889c4c5 3a69d5f0-26d8-fe66-4a1b-1a7c9ab618c8     PAYMENT 2019-05-26T05:07:38Z 1970-01-01T00:00:00Z     NaN      7.03        NaN         0.00
43206128-174e-ad3a-7449-5e81787b8e47 3a69d5f0-26d8-fe66-4a1b-1a7c9ab618c8      CHARGE 2019-05-26T05:07:38Z 1970-01-01T00:00:00Z  140.52       NaN        NaN          NaN
5225908e-2df4-e71e-b168-edbb616dee22 3a69d5f0-26d8-fe66-4a1b-1a7c9ab618c8     PAYMENT 2019-05-26T05:07:38Z 1970-01-01T00:00:00Z     NaN    133.49        NaN         7.03
51fadb30-a767-3380-d67a-3f33a5429d59 3a69d5f0-26d8-fe66-4a1b-1a7c9ab618c8 TRANSFEROUT 2019-05-26T05:07:38Z 1970-01-01T00:00:00Z     NaN       NaN       7.03         7.03
c3cc4470-458b-4104-1dd7-ea67668638df 3a69d5f0-26d8-fe66-4a1b-1a7c9ab618c8  TRANSFERIN 2019-05-26T05:07:38Z 1970-01-01T00:00:00Z    7.03       NaN       7.03         7.03
44843224-91f0-684b-2a03-bbdaffd7dbca 3a69d5f0-26d8-fe66-4a1b-1a7c9ab618c8     PAYMENT 2019-05-26T05:07:38Z 1970-01-01T00:00:00Z     NaN      7.03        NaN         0.00

================================================================================
ALL TRANSACTION TYPES
================================================================================
TYPE
PAYMENT        252335
CHARGE         218721
TRANSFEROUT    120091
TRANSFERIN     120091
Name: count, dtype: int64

In [5]:
import pandas as pd
from pathlib import Path

RAW_PATH = Path(r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Raw_Datasets")

for file_name in ["devices.csv", "supplies.csv"]:
    print("\n" + "=" * 80)
    print(f"{file_name.upper()}")
    print("=" * 80)

    df = pd.read_csv(RAW_PATH / file_name)

    print("\n--- Shape ---")
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

    print("\n--- Columns ---")
    print(df.columns.tolist())

    print("\n--- Missing Values ---")
    missing = df.isna().sum()
    missing = missing[missing > 0].sort_values(ascending=False)
    print(missing if len(missing) > 0 else "No missing values")

    print("\n--- Duplicate Complete Rows ---")
    print(df.duplicated().sum())

    if "Id" in df.columns:
        print("\n--- ID Check ---")
        print("Unique IDs:", df["Id"].nunique())
        print("Duplicate IDs:", df["Id"].duplicated().sum())
        print("Missing IDs:", df["Id"].isna().sum())

    if "PATIENT" in df.columns:
        print("\n--- Patient Reference ---")
        print("Unique patients:", df["PATIENT"].nunique())
        print("Missing patient references:", df["PATIENT"].isna().sum())

    if "ENCOUNTER" in df.columns:
        print("\n--- Encounter Reference ---")
        print("Unique encounters:", df["ENCOUNTER"].nunique())
        print("Missing encounter references:", df["ENCOUNTER"].isna().sum())

    print("\n--- Data Types ---")
    print(df.dtypes)

    print("\n--- First 5 Rows ---")
    display(df.head())

================================================================================
DEVICES.CSV
================================================================================

--- Shape ---
Rows: 89
Columns: 7

--- Columns ---
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'UDI']

--- Missing Values ---
STOP    75
dtype: int64

--- Duplicate Complete Rows ---
0

--- Patient Reference ---
Unique patients: 76
Missing patient references: 0

--- Encounter Reference ---
Unique encounters: 77
Missing encounter references: 0

--- Data Types ---
START            str
STOP             str
PATIENT          str
ENCOUNTER        str
CODE           int64
DESCRIPTION      str
UDI              str
dtype: object

--- First 5 Rows ---

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,UDI
0,2017-09-25T17:26:19Z,NaN,d1822991-eb4f-aafe-6a88-cd5279b4385b,bd2f33cd-4a24-6e32-1cd2-bf075ba9ed77,72506001,Implantable defibrillator device (physical ob...,(01)32224845419831(11)170904(17)420919(10)7079...
1,1987-09-21T02:27:51Z,NaN,04f25f73-04b2-469c-3806-540417a0d61c,807a0ee3-a9b1-30e1-3b19-bc2bddf952e8,72506001,Implantable defibrillator device (physical ob...,(01)84789768157847(11)870830(17)120913(10)3106...
2,2015-07-12T12:58:53Z,NaN,e000e5c8-30f7-7a53-a324-7f3e431ba008,5dfe5aec-2194-02ba-e4db-d16b42d28338,72506001,Implantable defibrillator device (physical ob...,(01)87802513365737(11)150621(17)400705(10)2864...
3,1983-07-18T16:34:31Z,NaN,89464607-f8af-06a3-fe2f-227495c12550,ea2d35e3-1cca-d560-f8ee-21bcfd480a9c,72506001,Implantable defibrillator device (physical ob...,(01)71493530635894(11)830627(17)080711(10)6970...
4,2008-04-04T12:43:40Z,NaN,ff0e4d0e-6181-e36e-d817-64dbcaecb5d0,9ac93727-a73c-5479-6d06-35999c01756d,705643001,Coronary artery stent (physical object),(01)60616412587042(11)080314(17)330329(10)1877...

================================================================================
SUPPLIES.CSV
================================================================================

--- Shape ---
Rows: 1573
Columns: 6

--- Columns ---
['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'QUANTITY']

--- Missing Values ---
No missing values

--- Duplicate Complete Rows ---
0

--- Patient Reference ---
Unique patients: 20
Missing patient references: 0

--- Encounter Reference ---
Unique encounters: 25
Missing encounter references: 0

--- Data Types ---
DATE             str
PATIENT          str
ENCOUNTER        str
CODE           int64
DESCRIPTION      str
QUANTITY       int64
dtype: object

--- First 5 Rows ---

,DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,QUANTITY
0,2021-02-08,8fa5a097-1970-9370-4193-a7baa3d235b5,b6358095-06f1-cc6a-ac12-3d46550a254a,409534002,Disposable air-purifying respirator (physical ...,2
1,2021-02-08,8fa5a097-1970-9370-4193-a7baa3d235b5,b6358095-06f1-cc6a-ac12-3d46550a254a,713779008,Nitrile examination/treatment glove non-powde...,24
2,2021-02-08,8fa5a097-1970-9370-4193-a7baa3d235b5,b6358095-06f1-cc6a-ac12-3d46550a254a,469673003,Isolation gown single-use (physical object),12
3,2021-02-08,8fa5a097-1970-9370-4193-a7baa3d235b5,b6358095-06f1-cc6a-ac12-3d46550a254a,706724001,Face shield (physical object),2
4,2021-02-08,8fa5a097-1970-9370-4193-a7baa3d235b5,b6358095-06f1-cc6a-ac12-3d46550a254a,419343004,Alcohol disinfectant (substance),1