In [3]:
from pathlib import Path

# Project path
PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)

# Dataset paths
RAW_PATH = PROJECT_PATH / "data" / "Raw_Datasets"
CLEAN_PATH = PROJECT_PATH / "data" / "Cleaned_Datasets"

print("Raw dataset folder:")
print(RAW_PATH)

print("\nCleaned dataset folder:")
print(CLEAN_PATH)

Raw dataset folder:
C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Raw_Datasets

Cleaned dataset folder:
C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets

In [4]:
import pandas as pd

# Load the raw encounters dataset
encounters = pd.read_csv(RAW_PATH / "encounters.csv")

# Check the dataset
print("Shape:", encounters.shape)
print("\nColumns:")
print(encounters.columns.tolist())

Shape: (61459, 15)

Columns:
['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PROVIDER', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION']

In [3]:
# Check missing values in each column
missing_values = encounters.isnull().sum()

print(missing_values)

Id                         0
START                      0
STOP                       0
PATIENT                    0
ORGANIZATION               0
PROVIDER                   0
PAYER                      0
ENCOUNTERCLASS             0
CODE                       0
DESCRIPTION                0
BASE_ENCOUNTER_COST        0
TOTAL_CLAIM_COST           0
PAYER_COVERAGE             0
REASONCODE             45502
REASONDESCRIPTION      45502
dtype: int64

In [4]:
# Check for duplicate rows
duplicate_rows = encounters.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

Duplicate rows: 0

In [5]:
# Check for duplicate encounter IDs
duplicate_ids = encounters["Id"].duplicated().sum()

print("Duplicate encounter IDs:", duplicate_ids)

Duplicate encounter IDs: 0

In [6]:
# Convert START and STOP to datetime
encounters["START"] = pd.to_datetime(encounters["START"], errors="coerce")
encounters["STOP"] = pd.to_datetime(encounters["STOP"], errors="coerce")

# Check missing dates after conversion
print("Missing START:", encounters["START"].isna().sum())
print("Missing STOP:", encounters["STOP"].isna().sum())

# Check if STOP occurs before START
invalid_dates = (encounters["STOP"] < encounters["START"]).sum()

print("STOP before START:", invalid_dates)

Missing START: 0
Missing STOP: 0
STOP before START: 0

In [7]:
# Check financial columns for negative values
financial_columns = [
    "BASE_ENCOUNTER_COST",
    "TOTAL_CLAIM_COST",
    "PAYER_COVERAGE"
]

for column in financial_columns:
    print(f"\n{column}")
    print("Missing:", encounters[column].isna().sum())
    print("Negative:", (encounters[column] < 0).sum())
    print("Minimum:", encounters[column].min())
    print("Maximum:", encounters[column].max())

BASE_ENCOUNTER_COST
Missing: 0
Negative: 0
Minimum: 77.49
Maximum: 129.16

TOTAL_CLAIM_COST
Missing: 0
Negative: 0
Minimum: 0.0
Maximum: 873646.19

PAYER_COVERAGE
Missing: 0
Negative: 0
Minimum: 0.0
Maximum: 227851.81

In [8]:
# Check whether payer coverage exceeds total claim cost
invalid_coverage = (
    encounters["PAYER_COVERAGE"] > encounters["TOTAL_CLAIM_COST"]
).sum()

print("PAYER_COVERAGE > TOTAL_CLAIM_COST:", invalid_coverage)

PAYER_COVERAGE > TOTAL_CLAIM_COST: 0

In [9]:
# Check encounter class values and their frequencies
encounter_class_counts = encounters["ENCOUNTERCLASS"].value_counts()

print(encounter_class_counts)

ENCOUNTERCLASS
wellness      24038
ambulatory    20124
outpatient    10837
urgentcare     2564
emergency      2168
inpatient      1728
Name: count, dtype: int64

In [10]:
# Check important ID/reference columns
reference_columns = [
    "PATIENT",
    "ORGANIZATION",
    "PROVIDER",
    "PAYER"
]

for column in reference_columns:
    print(f"{column}: {encounters[column].isna().sum()} missing")

PATIENT: 0 missing
ORGANIZATION: 0 missing
PROVIDER: 0 missing
PAYER: 0 missing

In [11]:
# Final validation of the cleaned encounters dataset

print("Final shape:", encounters.shape)
print("Duplicate rows:", encounters.duplicated().sum())
print("Duplicate encounter IDs:", encounters["Id"].duplicated().sum())
print("Missing values:", encounters.isna().sum().sum())

Final shape: (61459, 15)
Duplicate rows: 0
Duplicate encounter IDs: 0
Missing values: 91004

In [12]:
# Save the cleaned encounters dataset
cleaned_encounters_path = CLEAN_PATH / "encounters_cleaned.csv"

encounters.to_csv(cleaned_encounters_path, index=False)

print("Cleaned encounters dataset saved successfully!")
print(cleaned_encounters_path)

Cleaned encounters dataset saved successfully!
C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\encounters_cleaned.csv

In [14]:
# Verify the saved cleaned dataset
cleaned_encounters = pd.read_csv(cleaned_encounters_path)

print("Saved dataset shape:", cleaned_encounters.shape)
print("\nColumns:")
print(cleaned_encounters.columns.tolist())

Saved dataset shape: (61459, 15)

Columns:
['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PROVIDER', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION']

In [15]:
# Load the raw patients dataset
patients = pd.read_csv(RAW_PATH / "patients.csv")

# Check the dataset
print("Shape:", patients.shape)

print("\nColumns:")
print(patients.columns.tolist())

Shape: (1163, 25)

Columns:
['Id', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT', 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE']

In [16]:
# Check missing values in each column
patients_missing = patients.isnull().sum()

print(patients_missing)

Id                        0
BIRTHDATE                 0
DEATHDATE              1000
SSN                       0
DRIVERS                 215
PASSPORT                276
PREFIX                  245
FIRST                     0
LAST                      0
SUFFIX                 1147
MAIDEN                  832
MARITAL                 384
RACE                      0
ETHNICITY                 0
GENDER                    0
BIRTHPLACE                0
ADDRESS                   0
CITY                      0
STATE                     0
COUNTY                    0
ZIP                     545
LAT                       0
LON                       0
HEALTHCARE_EXPENSES       0
HEALTHCARE_COVERAGE       0
dtype: int64

In [17]:
# Check duplicate patient IDs
duplicate_patient_ids = patients["Id"].duplicated().sum()

print("Duplicate patient IDs:", duplicate_patient_ids)

Duplicate patient IDs: 0

In [18]:
# Convert date columns to datetime
patients["BIRTHDATE"] = pd.to_datetime(
    patients["BIRTHDATE"], errors="coerce"
)

patients["DEATHDATE"] = pd.to_datetime(
    patients["DEATHDATE"], errors="coerce"
)

# Check date validity
print("Missing BIRTHDATE:", patients["BIRTHDATE"].isna().sum())
print("Missing DEATHDATE:", patients["DEATHDATE"].isna().sum())

# Check future birthdates
future_birthdates = (
    patients["BIRTHDATE"] > pd.Timestamp.today()
).sum()

# Check death before birth
invalid_lifespans = (
    patients["DEATHDATE"] < patients["BIRTHDATE"]
).sum()

print("Future BIRTHDATE:", future_birthdates)
print("DEATHDATE before BIRTHDATE:", invalid_lifespans)

Missing BIRTHDATE: 0
Missing DEATHDATE: 1000
Future BIRTHDATE: 0
DEATHDATE before BIRTHDATE: 0

In [19]:
# Check patient-level financial fields
patient_financial_columns = [
    "HEALTHCARE_EXPENSES",
    "HEALTHCARE_COVERAGE"
]

for column in patient_financial_columns:
    print(f"\n{column}")
    print("Missing:", patients[column].isna().sum())
    print("Negative:", (patients[column] < 0).sum())
    print("Minimum:", patients[column].min())
    print("Maximum:", patients[column].max())

HEALTHCARE_EXPENSES
Missing: 0
Negative: 0
Minimum: 825.9920000000001
Maximum: 23116549.359000005

HEALTHCARE_COVERAGE
Missing: 0
Negative: 0
Minimum: 0.0
Maximum: 13562280.328000002

In [20]:
# Check unique values and frequencies for key demographic fields

demographic_columns = [
    "MARITAL",
    "RACE",
    "ETHNICITY",
    "GENDER"
]

for column in demographic_columns:
    print(f"\n--- {column} ---")
    print(patients[column].value_counts(dropna=False))

--- MARITAL ---
MARITAL
M      625
NaN    384
S      154
Name: count, dtype: int64

--- RACE ---
RACE
white       963
black        96
asian        73
hawaiian     18
other        11
native        2
Name: count, dtype: int64

--- ETHNICITY ---
ETHNICITY
nonhispanic    1058
hispanic        105
Name: count, dtype: int64

--- GENDER ---
GENDER
F    616
M    547
Name: count, dtype: int64

In [21]:
# Check patient location fields

location_columns = [
    "CITY",
    "STATE",
    "COUNTY",
    "ZIP",
    "LAT",
    "LON"
]

for column in location_columns:
    print(f"{column}: {patients[column].isna().sum()} missing")

print("\nLatitude range:")
print("Minimum:", patients["LAT"].min())
print("Maximum:", patients["LAT"].max())

print("\nLongitude range:")
print("Minimum:", patients["LON"].min())
print("Maximum:", patients["LON"].max())

CITY: 0 missing
STATE: 0 missing
COUNTY: 0 missing
ZIP: 545 missing
LAT: 0 missing
LON: 0 missing

Latitude range:
Minimum: 41.299941849839286
Maximum: 42.888532327017366

Longitude range:
Minimum: -73.44516489242905
Maximum: -69.97883129100411

In [6]:

# Reload project paths after restarting the notebook

from pathlib import Path
import pandas as pd

PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)

RAW_PATH = PROJECT_PATH / "data" / "Raw_Datasets"
CLEAN_PATH = PROJECT_PATH / "data" / "Cleaned_Datasets"

# Reload the datasets needed for the current step
encounters = pd.read_csv(RAW_PATH / "encounters.csv")
patients = pd.read_csv(RAW_PATH / "patients.csv")

# Convert patient date columns again
patients["BIRTHDATE"] = pd.to_datetime(
    patients["BIRTHDATE"], errors="coerce"
)

patients["DEATHDATE"] = pd.to_datetime(
    patients["DEATHDATE"], errors="coerce"
)

print("Encounters loaded:", encounters.shape)
print("Patients loaded:", patients.shape)

Encounters loaded: (61459, 15)
Patients loaded: (1163, 25)

In [7]:
# Check that all encounter patient IDs exist in the patients dataset

encounter_patient_ids = set(encounters["PATIENT"])
patient_ids = set(patients["Id"])

missing_patient_references = encounter_patient_ids - patient_ids

print("Unique patient IDs in encounters:", len(encounter_patient_ids))
print("Unique patient IDs in patients:", len(patient_ids))
print("Patient IDs missing from patients dataset:", len(missing_patient_references))

Unique patient IDs in encounters: 1163
Unique patient IDs in patients: 1163
Patient IDs missing from patients dataset: 0

In [8]:
# Final validation of the patients dataset

print("Final shape:", patients.shape)
print("Duplicate rows:", patients.duplicated().sum())
print("Duplicate patient IDs:", patients["Id"].duplicated().sum())
print("Total missing values:", patients.isna().sum().sum())

Final shape: (1163, 25)
Duplicate rows: 0
Duplicate patient IDs: 0
Total missing values: 4644

In [9]:
# Save the cleaned patients dataset
cleaned_patients_path = CLEAN_PATH / "patients_cleaned.csv"

patients.to_csv(cleaned_patients_path, index=False)

print("Cleaned patients dataset saved successfully!")
print(cleaned_patients_path)

Cleaned patients dataset saved successfully!
C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\patients_cleaned.csv

In [10]:
# DATASET 3 — PROVIDERS
# STEP 1: LOAD DATASET
import pandas as pd

providers = pd.read_csv(
    RAW_PATH / "providers.csv"
)

print("Providers dataset loaded successfully!")
print("Shape:", providers.shape)

print("\nColumns:")
print(providers.columns.tolist())

Providers dataset loaded successfully!
Shape: (5056, 12)

Columns:
['Id', 'ORGANIZATION', 'NAME', 'GENDER', 'SPECIALITY', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON', 'UTILIZATION']

In [11]:
# ============================================================
# STEP 2: CHECK MISSING VALUES
# ============================================================

providers_missing = providers.isnull().sum()

print("Missing values in providers.csv:")
print(providers_missing)

Missing values in providers.csv:
Id              0
ORGANIZATION    0
NAME            0
GENDER          0
SPECIALITY      0
ADDRESS         0
CITY            0
STATE           0
ZIP             0
LAT             0
LON             0
UTILIZATION     0
dtype: int64

In [12]:
# ============================================================
# STEP 3: CHECK DUPLICATE RECORDS AND PROVIDER IDs
# ============================================================

duplicate_rows = providers.duplicated().sum()

duplicate_provider_ids = providers["Id"].duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)
print("Duplicate Provider IDs:", duplicate_provider_ids)

Duplicate complete rows: 0
Duplicate Provider IDs: 0

In [13]:
# ============================================================
# STEP 4: CHECK PROVIDER UTILIZATION
# ============================================================

print("UTILIZATION summary:")
print(providers["UTILIZATION"].describe())

print("\nNegative UTILIZATION values:")
print((providers["UTILIZATION"] < 0).sum())

print("\nZero UTILIZATION values:")
print((providers["UTILIZATION"] == 0).sum())

print("\nMaximum UTILIZATION:")
print(providers["UTILIZATION"].max())

UTILIZATION summary:
count    5056.000000
mean       28.670095
std       187.393116
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max      3954.000000
Name: UTILIZATION, dtype: float64

Negative UTILIZATION values:
0

Zero UTILIZATION values:
3928

Maximum UTILIZATION:
3954

In [14]:
# ============================================================
# STEP 5: CHECK PROVIDER REFERENCE INTEGRITY
# ============================================================

encounter_provider_ids = set(encounters["PROVIDER"])
provider_ids = set(providers["Id"])

missing_provider_references = (
    encounter_provider_ids - provider_ids
)

print("Unique provider IDs in encounters.csv:",
      len(encounter_provider_ids))

print("Unique provider IDs in providers.csv:",
      len(provider_ids))

print("Provider IDs missing from providers.csv:",
      len(missing_provider_references))

Unique provider IDs in encounters.csv: 1123
Unique provider IDs in providers.csv: 5056
Provider IDs missing from providers.csv: 0

In [15]:
# ============================================================
# STEP 6: FINAL VALIDATION — PROVIDERS
# ============================================================

print("Final shape:", providers.shape)
print("Duplicate rows:", providers.duplicated().sum())
print("Duplicate Provider IDs:", providers["Id"].duplicated().sum())
print("Total missing values:", providers.isna().sum().sum())
print("Negative UTILIZATION values:", (providers["UTILIZATION"] < 0).sum())

Final shape: (5056, 12)
Duplicate rows: 0
Duplicate Provider IDs: 0
Total missing values: 0
Negative UTILIZATION values: 0

In [16]:
# ============================================================
# STEP 7: SAVE CLEANED PROVIDERS DATASET
# ============================================================

cleaned_providers_path = CLEAN_PATH / "providers_cleaned.csv"

providers.to_csv(
    cleaned_providers_path,
    index=False
)

print("Cleaned providers dataset saved successfully!")
print(cleaned_providers_path)

Cleaned providers dataset saved successfully!
C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\providers_cleaned.csv

In [17]:
# ============================================================
# STEP 8: VERIFY SAVED PROVIDERS DATASET
# ============================================================

cleaned_providers = pd.read_csv(cleaned_providers_path)

print("Saved dataset shape:", cleaned_providers.shape)

print("\nColumns:")
print(cleaned_providers.columns.tolist())

Saved dataset shape: (5056, 12)

Columns:
['Id', 'ORGANIZATION', 'NAME', 'GENDER', 'SPECIALITY', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON', 'UTILIZATION']

In [18]:
# ============================================================
# PHASE 2 — DATA CLEANING & PREPARATION
# DATASET 4 — ORGANIZATIONS
# STEP 1: LOAD DATASET
# ============================================================

organizations = pd.read_csv(
    RAW_PATH / "organizations.csv"
)

print("Organizations dataset loaded successfully!")
print("Shape:", organizations.shape)

print("\nColumns:")
print(organizations.columns.tolist())

Organizations dataset loaded successfully!
Shape: (1127, 11)

Columns:
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON', 'PHONE', 'REVENUE', 'UTILIZATION']

In [19]:
# ============================================================
# STEP 2: CHECK MISSING VALUES
# ============================================================

organizations_missing = organizations.isnull().sum()

print("Missing values in organizations.csv:")
print(organizations_missing)

Missing values in organizations.csv:
Id               0
NAME             0
ADDRESS          0
CITY             0
STATE            0
ZIP              0
LAT              0
LON              0
PHONE          153
REVENUE          0
UTILIZATION      0
dtype: int64

In [20]:
# ============================================================
# STEP 3: CHECK DUPLICATE RECORDS AND ORGANIZATION IDs
# ============================================================

duplicate_rows = organizations.duplicated().sum()

duplicate_organization_ids = organizations["Id"].duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)
print("Duplicate Organization IDs:", duplicate_organization_ids)

Duplicate complete rows: 0
Duplicate Organization IDs: 0

In [21]:
# ============================================================
# STEP 4: CHECK ORGANIZATION REVENUE
# ============================================================

print("REVENUE summary:")
print(organizations["REVENUE"].describe())

print("\nUnique REVENUE values:")
print(organizations["REVENUE"].unique())

print("\nNumber of zero REVENUE values:")
print((organizations["REVENUE"] == 0).sum())

print("\nNegative REVENUE values:")
print((organizations["REVENUE"] < 0).sum())

REVENUE summary:
count    1127.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: REVENUE, dtype: float64

Unique REVENUE values:
[0.]

Number of zero REVENUE values:
1127

Negative REVENUE values:
0

In [22]:
# ============================================================
# STEP 5: CHECK ORGANIZATION UTILIZATION
# ============================================================

print("UTILIZATION summary:")
print(organizations["UTILIZATION"].describe())

print("\nNegative UTILIZATION values:")
print((organizations["UTILIZATION"] < 0).sum())

print("\nZero UTILIZATION values:")
print((organizations["UTILIZATION"] == 0).sum())

print("\nMaximum UTILIZATION:")
print(organizations["UTILIZATION"].max())

UTILIZATION summary:
count    1127.000000
mean      128.621118
std       380.502441
min         2.000000
25%        28.000000
50%        42.000000
75%        69.000000
max      3954.000000
Name: UTILIZATION, dtype: float64

Negative UTILIZATION values:
0

Zero UTILIZATION values:
0

Maximum UTILIZATION:
3954

In [23]:
# ============================================================
# STEP 6: CHECK ORGANIZATION REFERENCE INTEGRITY
# ============================================================

encounter_organization_ids = set(encounters["ORGANIZATION"])
organization_ids = set(organizations["Id"])

missing_organization_references = (
    encounter_organization_ids - organization_ids
)

print("Unique organization IDs in encounters.csv:",
      len(encounter_organization_ids))

print("Unique organization IDs in organizations.csv:",
      len(organization_ids))

print("Organization IDs missing from organizations.csv:",
      len(missing_organization_references))

Unique organization IDs in encounters.csv: 1122
Unique organization IDs in organizations.csv: 1127
Organization IDs missing from organizations.csv: 0

In [24]:
# ============================================================
# STEP 7: FINAL VALIDATION — ORGANIZATIONS
# ============================================================

print("Final shape:", organizations.shape)
print("Duplicate rows:", organizations.duplicated().sum())
print("Duplicate Organization IDs:", organizations["Id"].duplicated().sum())
print("Total missing values:", organizations.isna().sum().sum())
print("Negative REVENUE values:", (organizations["REVENUE"] < 0).sum())
print("Negative UTILIZATION values:", (organizations["UTILIZATION"] < 0).sum())

Final shape: (1127, 11)
Duplicate rows: 0
Duplicate Organization IDs: 0
Total missing values: 153
Negative REVENUE values: 0
Negative UTILIZATION values: 0

In [25]:
# ============================================================
# STEP 8: SAVE CLEANED ORGANIZATIONS DATASET
# ============================================================

cleaned_organizations_path = CLEAN_PATH / "organizations_cleaned.csv"

organizations.to_csv(
    cleaned_organizations_path,
    index=False
)

print("Cleaned organizations dataset saved successfully!")
print(cleaned_organizations_path)

Cleaned organizations dataset saved successfully!
C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\organizations_cleaned.csv

In [26]:
# ============================================================
# STEP 9: VERIFY SAVED ORGANIZATIONS DATASET
# ============================================================

cleaned_organizations = pd.read_csv(
    cleaned_organizations_path
)

print("Saved dataset shape:", cleaned_organizations.shape)

print("\nColumns:")
print(cleaned_organizations.columns.tolist())

Saved dataset shape: (1127, 11)

Columns:
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON', 'PHONE', 'REVENUE', 'UTILIZATION']

In [27]:
# ============================================================
# PHASE 2 — DATA CLEANING & PREPARATION
# DATASET 5 — PAYERS
# STEP 1: LOAD DATASET
# ============================================================

payers = pd.read_csv(
    RAW_PATH / "payers.csv"
)

print("Payers dataset loaded successfully!")
print("Shape:", payers.shape)

print("\nColumns:")
print(payers.columns.tolist())

Payers dataset loaded successfully!
Shape: (10, 21)

Columns:
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE_HEADQUARTERED', 'ZIP', 'PHONE', 'AMOUNT_COVERED', 'AMOUNT_UNCOVERED', 'REVENUE', 'COVERED_ENCOUNTERS', 'UNCOVERED_ENCOUNTERS', 'COVERED_MEDICATIONS', 'UNCOVERED_MEDICATIONS', 'COVERED_PROCEDURES', 'UNCOVERED_PROCEDURES', 'COVERED_IMMUNIZATIONS', 'UNCOVERED_IMMUNIZATIONS', 'UNIQUE_CUSTOMERS', 'QOLS_AVG', 'MEMBER_MONTHS']

In [28]:
# ============================================================
# STEP 2: CHECK MISSING VALUES
# ============================================================

payers_missing = payers.isnull().sum()

print("Missing values in payers.csv:")
print(payers_missing)

Missing values in payers.csv:
Id                         0
NAME                       0
ADDRESS                    1
CITY                       1
STATE_HEADQUARTERED        1
ZIP                        1
PHONE                      1
AMOUNT_COVERED             0
AMOUNT_UNCOVERED           0
REVENUE                    0
COVERED_ENCOUNTERS         0
UNCOVERED_ENCOUNTERS       0
COVERED_MEDICATIONS        0
UNCOVERED_MEDICATIONS      0
COVERED_PROCEDURES         0
UNCOVERED_PROCEDURES       0
COVERED_IMMUNIZATIONS      0
UNCOVERED_IMMUNIZATIONS    0
UNIQUE_CUSTOMERS           0
QOLS_AVG                   0
MEMBER_MONTHS              0
dtype: int64

In [29]:
# ============================================================
# STEP 3: CHECK DUPLICATE RECORDS AND PAYER IDs
# ============================================================

duplicate_rows = payers.duplicated().sum()

duplicate_payer_ids = payers["Id"].duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)
print("Duplicate Payer IDs:", duplicate_payer_ids)

Duplicate complete rows: 0
Duplicate Payer IDs: 0

In [30]:
# ============================================================
# STEP 4: CHECK PAYER REFERENCE INTEGRITY
# ============================================================

encounter_payer_ids = set(encounters["PAYER"])
payer_ids = set(payers["Id"])

missing_payer_references = (
    encounter_payer_ids - payer_ids
)

print("Unique payer IDs in encounters.csv:",
      len(encounter_payer_ids))

print("Unique payer IDs in payers.csv:",
      len(payer_ids))

print("Payer IDs missing from payers.csv:",
      len(missing_payer_references))

Unique payer IDs in encounters.csv: 10
Unique payer IDs in payers.csv: 10
Payer IDs missing from payers.csv: 0

In [31]:
# ============================================================
# STEP 5: VALIDATE PAYER FINANCIAL COLUMNS
# ============================================================

payer_financial_columns = [
    "AMOUNT_COVERED",
    "AMOUNT_UNCOVERED",
    "REVENUE"
]

for column in payer_financial_columns:
    print(f"\n--- {column} ---")
    print("Missing:", payers[column].isna().sum())
    print("Negative:", (payers[column] < 0).sum())
    print("Minimum:", payers[column].min())
    print("Maximum:", payers[column].max())
    print("Mean:", payers[column].mean())

--- AMOUNT_COVERED ---
Missing: 0
Negative: 0
Minimum: 0.0
Maximum: 119913069.99
Mean: 19976579.533

--- AMOUNT_UNCOVERED ---
Missing: 0
Negative: 0
Minimum: 358233.14
Maximum: 321243274.87
Mean: 55940960.862

--- REVENUE ---
Missing: 0
Negative: 0
Minimum: 0.0
Maximum: 159838800.0
Mean: 90157335.0

In [32]:
# ============================================================
# STEP 6: VALIDATE PAYER COVERAGE & ACTIVITY FIELDS
# ============================================================

payer_activity_columns = [
    "COVERED_ENCOUNTERS",
    "UNCOVERED_ENCOUNTERS",
    "COVERED_MEDICATIONS",
    "UNCOVERED_MEDICATIONS",
    "COVERED_PROCEDURES",
    "UNCOVERED_PROCEDURES",
    "COVERED_IMMUNIZATIONS",
    "UNCOVERED_IMMUNIZATIONS",
    "UNIQUE_CUSTOMERS",
    "MEMBER_MONTHS"
]

for column in payer_activity_columns:
    print(f"\n--- {column} ---")
    print("Missing:", payers[column].isna().sum())
    print("Negative:", (payers[column] < 0).sum())
    print("Minimum:", payers[column].min())
    print("Maximum:", payers[column].max())

--- COVERED_ENCOUNTERS ---
Missing: 0
Negative: 0
Minimum: 0
Maximum: 17058

--- UNCOVERED_ENCOUNTERS ---
Missing: 0
Negative: 0
Minimum: 0
Maximum: 35195

--- COVERED_MEDICATIONS ---
Missing: 0
Negative: 0
Minimum: 0
Maximum: 10455

--- UNCOVERED_MEDICATIONS ---
Missing: 0
Negative: 0
Minimum: 0
Maximum: 13776

--- COVERED_PROCEDURES ---
Missing: 0
Negative: 0
Minimum: 0
Maximum: 32913

--- UNCOVERED_PROCEDURES ---
Missing: 0
Negative: 0
Minimum: 0
Maximum: 53599

--- COVERED_IMMUNIZATIONS ---
Missing: 0
Negative: 0
Minimum: 0
Maximum: 7612

--- UNCOVERED_IMMUNIZATIONS ---
Missing: 0
Negative: 0
Minimum: 0
Maximum: 7844

--- UNIQUE_CUSTOMERS ---
Missing: 0
Negative: 0
Minimum: 20
Maximum: 954

--- MEMBER_MONTHS ---
Missing: 0
Negative: 0
Minimum: 3060
Maximum: 78384

In [33]:
# ============================================================
# STEP 7: VALIDATE QOLS_AVG
# ============================================================

print("QOLS_AVG summary:")
print(payers["QOLS_AVG"].describe())

print("\nMissing QOLS_AVG values:")
print(payers["QOLS_AVG"].isna().sum())

print("\nNegative QOLS_AVG values:")
print((payers["QOLS_AVG"] < 0).sum())

print("\nMinimum QOLS_AVG:")
print(payers["QOLS_AVG"].min())

print("\nMaximum QOLS_AVG:")
print(payers["QOLS_AVG"].max())

QOLS_AVG summary:
count    10.000000
mean      0.904887
std       0.372492
min       0.537055
25%       0.818868
50%       0.824410
75%       0.840917
max       1.931809
Name: QOLS_AVG, dtype: float64

Missing QOLS_AVG values:
0

Negative QOLS_AVG values:
0

Minimum QOLS_AVG:
0.5370553777293092

Maximum QOLS_AVG:
1.9318087533676167

In [35]:
# ============================================================
# STEP 8: FINAL VALIDATION — PAYERS
# ============================================================

print("Final shape:", payers.shape)
print("Duplicate rows:", payers.duplicated().sum())
print("Duplicate Payer IDs:", payers["Id"].duplicated().sum())
print("Total missing values:", payers.isna().sum().sum())

print(
    "Negative financial values:",
    (
        (payers["AMOUNT_COVERED"] < 0) |
        (payers["AMOUNT_UNCOVERED"] < 0) |
        (payers["REVENUE"] < 0)
    ).sum()
)

print(
    "Negative activity values:",
    (
        (payers["COVERED_ENCOUNTERS"] < 0) |
        (payers["UNCOVERED_ENCOUNTERS"] < 0) |
        (payers["COVERED_MEDICATIONS"] < 0) |
        (payers["UNCOVERED_MEDICATIONS"] < 0) |
        (payers["COVERED_PROCEDURES"] < 0) |
        (payers["UNCOVERED_PROCEDURES"] < 0) |
        (payers["COVERED_IMMUNIZATIONS"] < 0) |
        (payers["UNCOVERED_IMMUNIZATIONS"] < 0) |
        (payers["UNIQUE_CUSTOMERS"] < 0) |
        (payers["MEMBER_MONTHS"] < 0)
    ).sum()
)

print("Negative QOLS_AVG values:", (payers["QOLS_AVG"] < 0).sum())

Final shape: (10, 21)
Duplicate rows: 0
Duplicate Payer IDs: 0
Total missing values: 5
Negative financial values: 0
Negative activity values: 0
Negative QOLS_AVG values: 0

In [38]:
# ============================================================
# STEP 9: SAVE CLEANED PAYERS DATASET
# ============================================================

cleaned_payers_path = CLEAN_PATH / "payers_cleaned.csv"

payers.to_csv(
    cleaned_payers_path,
    index=False
)

print("Cleaned payers dataset saved successfully!")
print(cleaned_payers_path)

Cleaned payers dataset saved successfully!
C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\payers_cleaned.csv

In [39]:
# ============================================================
# STEP 10: VERIFY SAVED PAYERS DATASET
# ============================================================

cleaned_payers = pd.read_csv(
    cleaned_payers_path
)

print("Saved dataset shape:", cleaned_payers.shape)

print("\nColumns:")
print(cleaned_payers.columns.tolist())

Saved dataset shape: (10, 21)

Columns:
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE_HEADQUARTERED', 'ZIP', 'PHONE', 'AMOUNT_COVERED', 'AMOUNT_UNCOVERED', 'REVENUE', 'COVERED_ENCOUNTERS', 'UNCOVERED_ENCOUNTERS', 'COVERED_MEDICATIONS', 'UNCOVERED_MEDICATIONS', 'COVERED_PROCEDURES', 'UNCOVERED_PROCEDURES', 'COVERED_IMMUNIZATIONS', 'UNCOVERED_IMMUNIZATIONS', 'UNIQUE_CUSTOMERS', 'QOLS_AVG', 'MEMBER_MONTHS']

In [40]:
# ============================================================
# PHASE 2 — DATA CLEANING & PREPARATION
# DATASET 6 — CONDITIONS
# STEP 1: LOAD DATASET
# ============================================================

conditions = pd.read_csv(
    RAW_PATH / "conditions.csv"
)

print("Conditions dataset loaded successfully!")
print("Shape:", conditions.shape)

print("\nColumns:")
print(conditions.columns.tolist())

Conditions dataset loaded successfully!
Shape: (38094, 6)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION']

In [41]:
# ============================================================
# STEP 2: CHECK MISSING VALUES
# ============================================================

conditions_missing = conditions.isnull().sum()

print("Missing values in conditions.csv:")
print(conditions_missing)

Missing values in conditions.csv:
START             0
STOP           8169
PATIENT           0
ENCOUNTER         0
CODE              0
DESCRIPTION       0
dtype: int64

In [42]:
# ============================================================
# STEP 3: CHECK DUPLICATE ROWS
# ============================================================

duplicate_rows = conditions.duplicated().sum()

print("Number of duplicate rows:", duplicate_rows)

Number of duplicate rows: 0

In [43]:
# ============================================================
# STEP 4: CONVERT AND VALIDATE DATES
# ============================================================

# Convert START and STOP to datetime
conditions["START"] = pd.to_datetime(conditions["START"], errors="coerce")
conditions["STOP"] = pd.to_datetime(conditions["STOP"], errors="coerce")

print("Date conversion completed.")

print("\nData types:")
print(conditions[["START", "STOP"]].dtypes)

# Check invalid date conversion
print("\nInvalid START dates:", conditions["START"].isna().sum())
print("Invalid STOP dates:", conditions["STOP"].isna().sum())

# Check whether STOP occurs before START
invalid_date_order = (
    conditions["STOP"].notna() &
    (conditions["STOP"] < conditions["START"])
).sum()

print("\nSTOP dates before START dates:", invalid_date_order)

Date conversion completed.

Data types:
START    datetime64[us]
STOP     datetime64[us]
dtype: object

Invalid START dates: 0
Invalid STOP dates: 8169

STOP dates before START dates: 0

In [44]:
# ============================================================
# STEP 5: CHECK CONDITION CODE AND DESCRIPTION
# ============================================================

print("Missing CODE values:", conditions["CODE"].isna().sum())
print("Missing DESCRIPTION values:", conditions["DESCRIPTION"].isna().sum())

print("\nUnique condition codes:", conditions["CODE"].nunique())
print("Unique condition descriptions:", conditions["DESCRIPTION"].nunique())

print("\nSample condition records:")
print(conditions[["CODE", "DESCRIPTION"]].head(10))

Missing CODE values: 0
Missing DESCRIPTION values: 0

Unique condition codes: 202
Unique condition descriptions: 204

Sample condition records:
        CODE                              DESCRIPTION
0   10509002              Acute bronchitis (disorder)
1  283371005                    Laceration of forearm
2  444814009               Viral sinusitis (disorder)
3  444814009               Viral sinusitis (disorder)
4   16114001                        Fracture of ankle
5   44465007                          Sprain of ankle
6  160968000      Risk activity involvement (finding)
7   44465007                          Sprain of ankle
8  162864005  Body mass index 30+ - obesity (finding)
9   59621000                             Hypertension

In [45]:
# ============================================================
# STEP 6: CHECK PATIENT AND ENCOUNTER REFERENCES
# ============================================================

# Get valid IDs from cleaned datasets
valid_patient_ids = set(patients["Id"])
valid_encounter_ids = set(encounters["Id"])

# Find condition records with invalid patient references
invalid_patient_refs = (~conditions["PATIENT"].isin(valid_patient_ids)).sum()

# Find condition records with invalid encounter references
invalid_encounter_refs = (~conditions["ENCOUNTER"].isin(valid_encounter_ids)).sum()

print("Invalid PATIENT references:", invalid_patient_refs)
print("Invalid ENCOUNTER references:", invalid_encounter_refs)

# Show number of unique patients and encounters in conditions
print("\nUnique patients in conditions:", conditions["PATIENT"].nunique())
print("Unique encounters in conditions:", conditions["ENCOUNTER"].nunique())

Invalid PATIENT references: 0
Invalid ENCOUNTER references: 0

Unique patients in conditions: 1147
Unique encounters in conditions: 26904

In [46]:
# ============================================================
# STEP 7: CHECK CONDITIONS PER ENCOUNTER
# ============================================================

conditions_per_encounter = (
    conditions.groupby("ENCOUNTER")
    .size()
)

print("Conditions per encounter:")
print(conditions_per_encounter.describe())

print("\nMinimum conditions for an encounter:",
      conditions_per_encounter.min())

print("Maximum conditions for an encounter:",
      conditions_per_encounter.max())

print("Median conditions per encounter:",
      conditions_per_encounter.median())

print("Average conditions per encounter:",
      conditions_per_encounter.mean())

Conditions per encounter:
count    26904.000000
mean         1.415923
std          0.753878
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         13.000000
dtype: float64

Minimum conditions for an encounter: 1
Maximum conditions for an encounter: 13
Median conditions per encounter: 1.0
Average conditions per encounter: 1.4159232827832293

In [47]:
# ============================================================
# STEP 8: FINAL VALIDATION
# ============================================================

print("Final Conditions Dataset Validation")
print("=" * 50)

print("Shape:", conditions.shape)
print("Duplicate rows:", conditions.duplicated().sum())
print("Missing values:")
print(conditions.isna().sum())

print("\nDate validation:")
print("Invalid START dates:", conditions["START"].isna().sum())
print("Invalid STOP before START:",
      (
          conditions["STOP"].notna() &
          (conditions["STOP"] < conditions["START"])
      ).sum())

print("\nReference validation:")
print("Invalid PATIENT references:",
      (~conditions["PATIENT"].isin(valid_patient_ids)).sum())
print("Invalid ENCOUNTER references:",
      (~conditions["ENCOUNTER"].isin(valid_encounter_ids)).sum())

print("\nCondition validation:")
print("Missing CODE:", conditions["CODE"].isna().sum())
print("Missing DESCRIPTION:", conditions["DESCRIPTION"].isna().sum())
print("Unique condition codes:", conditions["CODE"].nunique())

print("\nFinal data types:")
print(conditions.dtypes)

Final Conditions Dataset Validation
==================================================
Shape: (38094, 6)
Duplicate rows: 0
Missing values:
START             0
STOP           8169
PATIENT           0
ENCOUNTER         0
CODE              0
DESCRIPTION       0
dtype: int64

Date validation:
Invalid START dates: 0
Invalid STOP before START: 0

Reference validation:
Invalid PATIENT references: 0
Invalid ENCOUNTER references: 0

Condition validation:
Missing CODE: 0
Missing DESCRIPTION: 0
Unique condition codes: 202

Final data types:
START          datetime64[us]
STOP           datetime64[us]
PATIENT                   str
ENCOUNTER                 str
CODE                    int64
DESCRIPTION               str
dtype: object

In [48]:
# ============================================================
# STEP 9: SAVE CLEANED CONDITIONS DATASET
# ============================================================

conditions_cleaned_path = CLEAN_PATH / "conditions_cleaned.csv"

conditions.to_csv(
    conditions_cleaned_path,
    index=False
)

print("Cleaned conditions dataset saved successfully!")
print("File:", conditions_cleaned_path)

Cleaned conditions dataset saved successfully!
File: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\conditions_cleaned.csv

In [49]:
# ============================================================
# STEP 10: VERIFY SAVED FILE
# ============================================================

conditions_check = pd.read_csv(
    conditions_cleaned_path
)

print("Reloaded cleaned conditions dataset successfully!")
print("Shape:", conditions_check.shape)

print("\nColumns:")
print(conditions_check.columns.tolist())

print("\nDuplicate rows:", conditions_check.duplicated().sum())

Reloaded cleaned conditions dataset successfully!
Shape: (38094, 6)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION']

Duplicate rows: 0

In [50]:
# ============================================================
# PHASE 2 — DATA CLEANING & PREPARATION
# DATASET 7 — PROCEDURES
# COMPLETE CLEANING & VALIDATION
# ============================================================

# ------------------------------------------------------------
# STEP 1: LOAD DATASET
# ------------------------------------------------------------

procedures = pd.read_csv(
    RAW_PATH / "procedures.csv"
)

print("=" * 70)
print("DATASET 7 — PROCEDURES")
print("=" * 70)

print("\nProcedures dataset loaded successfully!")
print("Shape:", procedures.shape)

print("\nColumns:")
print(procedures.columns.tolist())


# ------------------------------------------------------------
# STEP 2: CHECK MISSING VALUES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 2 — MISSING VALUE CHECK")
print("=" * 70)

print(procedures.isna().sum())


# ------------------------------------------------------------
# STEP 3: CHECK DUPLICATE ROWS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 3 — DUPLICATE CHECK")
print("=" * 70)

duplicate_rows = procedures.duplicated().sum()

print("Duplicate rows:", duplicate_rows)


# ------------------------------------------------------------
# STEP 4: CONVERT AND VALIDATE DATES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 4 — DATE CONVERSION & VALIDATION")
print("=" * 70)

procedures["START"] = pd.to_datetime(
    procedures["START"],
    errors="coerce"
)

procedures["STOP"] = pd.to_datetime(
    procedures["STOP"],
    errors="coerce"
)

print("Date conversion completed.")

print("\nDate data types:")
print(procedures[["START", "STOP"]].dtypes)

print("\nInvalid START dates:",
      procedures["START"].isna().sum())

print("Invalid STOP dates:",
      procedures["STOP"].isna().sum())

invalid_date_order = (
    procedures["STOP"].notna() &
    (procedures["STOP"] < procedures["START"])
).sum()

print("STOP dates before START dates:",
      invalid_date_order)


# ------------------------------------------------------------
# STEP 5: CHECK PROCEDURE CODE AND DESCRIPTION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 5 — CODE & DESCRIPTION VALIDATION")
print("=" * 70)

print("Missing CODE:",
      procedures["CODE"].isna().sum())

print("Missing DESCRIPTION:",
      procedures["DESCRIPTION"].isna().sum())

print("Unique procedure codes:",
      procedures["CODE"].nunique())

print("Unique procedure descriptions:",
      procedures["DESCRIPTION"].nunique())

print("\nSample procedure records:")
print(
    procedures[
        ["CODE", "DESCRIPTION"]
    ].head(10)
)


# ------------------------------------------------------------
# STEP 6: CHECK BASE COST
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 6 — BASE COST VALIDATION")
print("=" * 70)

print("Missing BASE_COST:",
      procedures["BASE_COST"].isna().sum())

print("Minimum BASE_COST:",
      procedures["BASE_COST"].min())

print("Maximum BASE_COST:",
      procedures["BASE_COST"].max())

print("Negative BASE_COST values:",
      (procedures["BASE_COST"] < 0).sum())

print("\nBASE_COST statistics:")
print(
    procedures["BASE_COST"].describe()
)


# ------------------------------------------------------------
# STEP 7: PATIENT AND ENCOUNTER REFERENCE VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 7 — PATIENT & ENCOUNTER REFERENCE VALIDATION")
print("=" * 70)

# Valid IDs from cleaned datasets
valid_patient_ids = set(patients["Id"])
valid_encounter_ids = set(encounters["Id"])

# Invalid patient references
invalid_patient_refs = (
    ~procedures["PATIENT"].isin(valid_patient_ids)
).sum()

# Invalid encounter references
invalid_encounter_refs = (
    ~procedures["ENCOUNTER"].isin(valid_encounter_ids)
).sum()

print("Invalid PATIENT references:",
      invalid_patient_refs)

print("Invalid ENCOUNTER references:",
      invalid_encounter_refs)

print("\nUnique patients in procedures:",
      procedures["PATIENT"].nunique())

print("Unique encounters in procedures:",
      procedures["ENCOUNTER"].nunique())


# ------------------------------------------------------------
# STEP 8: CHECK PROCEDURES PER ENCOUNTER
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 8 — PROCEDURES PER ENCOUNTER")
print("=" * 70)

procedures_per_encounter = (
    procedures
    .groupby("ENCOUNTER")
    .size()
)

print("Procedures per encounter:")
print(
    procedures_per_encounter.describe()
)

print("\nMinimum procedures per encounter:",
      procedures_per_encounter.min())

print("Maximum procedures per encounter:",
      procedures_per_encounter.max())

print("Median procedures per encounter:",
      procedures_per_encounter.median())

print("Average procedures per encounter:",
      procedures_per_encounter.mean())


# ------------------------------------------------------------
# STEP 9: CHECK REASON FIELDS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 9 — REASON FIELD VALIDATION")
print("=" * 70)

print("Missing REASONCODE:",
      procedures["REASONCODE"].isna().sum())

print("Missing REASONDESCRIPTION:",
      procedures["REASONDESCRIPTION"].isna().sum())


# ------------------------------------------------------------
# STEP 10: FINAL VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 10 — FINAL VALIDATION")
print("=" * 70)

print("Final shape:", procedures.shape)

print("Duplicate rows:",
      procedures.duplicated().sum())

print("\nMissing values:")
print(procedures.isna().sum())

print("\nDate validation:")

print("Invalid START dates:",
      procedures["START"].isna().sum())

print(
    "Invalid STOP before START:",
    (
        procedures["STOP"].notna() &
        (procedures["STOP"] < procedures["START"])
    ).sum()
)

print("\nReference validation:")

print(
    "Invalid PATIENT references:",
    (~procedures["PATIENT"].isin(valid_patient_ids)).sum()
)

print(
    "Invalid ENCOUNTER references:",
    (~procedures["ENCOUNTER"].isin(valid_encounter_ids)).sum()
)

print("\nProcedure validation:")

print(
    "Missing CODE:",
    procedures["CODE"].isna().sum()
)

print(
    "Missing DESCRIPTION:",
    procedures["DESCRIPTION"].isna().sum()
)

print(
    "Missing BASE_COST:",
    procedures["BASE_COST"].isna().sum()
)

print(
    "Negative BASE_COST:",
    (procedures["BASE_COST"] < 0).sum()
)

print("\nFinal data types:")
print(procedures.dtypes)


# ------------------------------------------------------------
# STEP 11: SAVE CLEANED DATASET
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 11 — SAVE CLEANED DATASET")
print("=" * 70)

procedures_cleaned_path = (
    CLEAN_PATH / "procedures_cleaned.csv"
)

procedures.to_csv(
    procedures_cleaned_path,
    index=False
)

print("Cleaned procedures dataset saved successfully!")
print("File:", procedures_cleaned_path)


# ------------------------------------------------------------
# STEP 12: RELOAD AND VERIFY SAVED FILE
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 12 — VERIFY SAVED FILE")
print("=" * 70)

procedures_check = pd.read_csv(
    procedures_cleaned_path
)

print("Reloaded cleaned procedures dataset successfully!")

print("Shape:",
      procedures_check.shape)

print("\nColumns:")
print(procedures_check.columns.tolist())

print("\nDuplicate rows:",
      procedures_check.duplicated().sum())

print("\nSaved file verification completed!")

======================================================================
DATASET 7 — PROCEDURES
======================================================================

Procedures dataset loaded successfully!
Shape: (83823, 9)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION']

======================================================================
STEP 2 — MISSING VALUE CHECK
======================================================================
START                    0
STOP                     0
PATIENT                  0
ENCOUNTER                0
CODE                     0
DESCRIPTION              0
BASE_COST                0
REASONCODE           63226
REASONDESCRIPTION    63226
dtype: int64

======================================================================
STEP 3 — DUPLICATE CHECK
======================================================================
Duplicate rows: 0

======================================================================
STEP 4 — DATE CONVERSION & VALIDATION
======================================================================
Date conversion completed.

Date data types:
START    datetime64[us, UTC]
STOP     datetime64[us, UTC]
dtype: object

Invalid START dates: 0
Invalid STOP dates: 0
STOP dates before START dates: 0

======================================================================
STEP 5 — CODE & DESCRIPTION VALIDATION
======================================================================
Missing CODE: 0
Missing DESCRIPTION: 0
Unique procedure codes: 170
Unique procedure descriptions: 178

Sample procedure records:
        CODE                                      DESCRIPTION
0  430193006            Medication Reconciliation (procedure)
1  430193006            Medication Reconciliation (procedure)
2  430193006            Medication Reconciliation (procedure)
3  395142003                           Allergy screening test
4  430193006            Medication Reconciliation (procedure)
5  430193006            Medication Reconciliation (procedure)
6   23426006  Measurement of respiratory function (procedure)
7  288086009                                Suture open wound
8  384700001                   Injection of tetanus antitoxin
9  430193006            Medication Reconciliation (procedure)

======================================================================
STEP 6 — BASE COST VALIDATION
======================================================================
Missing BASE_COST: 0
Minimum BASE_COST: 0.73
Maximum BASE_COST: 623241.97
Negative BASE_COST values: 0

BASE_COST statistics:
count     83823.000000
mean       2507.677607
std        6199.434459
min           0.730000
25%         516.650000
50%         516.650000
75%        1819.535000
max      623241.970000
Name: BASE_COST, dtype: float64

======================================================================
STEP 7 — PATIENT & ENCOUNTER REFERENCE VALIDATION
======================================================================
Invalid PATIENT references: 0
Invalid ENCOUNTER references: 0

Unique patients in procedures: 1162
Unique encounters in procedures: 25854

======================================================================
STEP 8 — PROCEDURES PER ENCOUNTER
======================================================================
Procedures per encounter:
count    25854.000000
mean         3.242168
std          2.986637
min          1.000000
25%          1.000000
50%          2.000000
75%          5.000000
max         27.000000
dtype: float64

Minimum procedures per encounter: 1
Maximum procedures per encounter: 27
Median procedures per encounter: 2.0
Average procedures per encounter: 3.2421675562775585

======================================================================
STEP 9 — REASON FIELD VALIDATION
======================================================================
Missing REASONCODE: 63226
Missing REASONDESCRIPTION: 63226

======================================================================
STEP 10 — FINAL VALIDATION
======================================================================
Final shape: (83823, 9)
Duplicate rows: 0

Missing values:
START                    0
STOP                     0
PATIENT                  0
ENCOUNTER                0
CODE                     0
DESCRIPTION              0
BASE_COST                0
REASONCODE           63226
REASONDESCRIPTION    63226
dtype: int64

Date validation:
Invalid START dates: 0
Invalid STOP before START: 0

Reference validation:
Invalid PATIENT references: 0
Invalid ENCOUNTER references: 0

Procedure validation:
Missing CODE: 0
Missing DESCRIPTION: 0
Missing BASE_COST: 0
Negative BASE_COST: 0

Final data types:
START                datetime64[us, UTC]
STOP                 datetime64[us, UTC]
PATIENT                              str
ENCOUNTER                            str
CODE                               int64
DESCRIPTION                          str
BASE_COST                        float64
REASONCODE                       float64
REASONDESCRIPTION                    str
dtype: object

======================================================================
STEP 11 — SAVE CLEANED DATASET
======================================================================
Cleaned procedures dataset saved successfully!
File: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\procedures_cleaned.csv

======================================================================
STEP 12 — VERIFY SAVED FILE
======================================================================
Reloaded cleaned procedures dataset successfully!
Shape: (83823, 9)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION']

Duplicate rows: 0

Saved file verification completed!

In [51]:
# ============================================================
# PHASE 2 — DATA CLEANING & PREPARATION
# DATASET 8 — CLAIMS
# COMPLETE CLEANING & VALIDATION
# ============================================================

# ------------------------------------------------------------
# STEP 1: LOAD DATASET
# ------------------------------------------------------------

claims = pd.read_csv(
    RAW_PATH / "claims.csv"
)

print("=" * 70)
print("DATASET 8 — CLAIMS")
print("=" * 70)

print("\nClaims dataset loaded successfully!")
print("Shape:", claims.shape)

print("\nColumns:")
print(claims.columns.tolist())


# ------------------------------------------------------------
# STEP 2: CHECK MISSING VALUES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 2 — MISSING VALUE CHECK")
print("=" * 70)

print(claims.isna().sum())


# ------------------------------------------------------------
# STEP 3: CHECK DUPLICATE ROWS AND CLAIM IDs
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 3 — DUPLICATE CHECK")
print("=" * 70)

duplicate_rows = claims.duplicated().sum()
duplicate_claim_ids = claims["Id"].duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)
print("Duplicate claim IDs:", duplicate_claim_ids)


# ------------------------------------------------------------
# STEP 4: DATE CONVERSION & VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 4 — DATE CONVERSION & VALIDATION")
print("=" * 70)

date_columns = [
    "CURRENTILLNESSDATE",
    "SERVICEDATE",
    "LASTBILLEDDATE1",
    "LASTBILLEDDATE2",
    "LASTBILLEDDATEP"
]

for col in date_columns:
    claims[col] = pd.to_datetime(
        claims[col],
        errors="coerce"
    )

print("Date conversion completed.")

print("\nDate data types:")
print(claims[date_columns].dtypes)

print("\nMissing / invalid date values:")

for col in date_columns:
    print(
        f"{col}:",
        claims[col].isna().sum()
    )


# ------------------------------------------------------------
# STEP 5: CHECK DATE LOGIC
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 5 — DATE LOGIC VALIDATION")
print("=" * 70)

# CURRENTILLNESSDATE should not be after SERVICEDATE
invalid_illness_service = (
    claims["CURRENTILLNESSDATE"].notna() &
    claims["SERVICEDATE"].notna() &
    (claims["CURRENTILLNESSDATE"] > claims["SERVICEDATE"])
).sum()

print(
    "CURRENTILLNESSDATE after SERVICEDATE:",
    invalid_illness_service
)

# LASTBILLEDDATE1 should not be before SERVICEDATE
invalid_lastbill1 = (
    claims["LASTBILLEDDATE1"].notna() &
    claims["SERVICEDATE"].notna() &
    (claims["LASTBILLEDDATE1"] < claims["SERVICEDATE"])
).sum()

print(
    "LASTBILLEDDATE1 before SERVICEDATE:",
    invalid_lastbill1
)

# LASTBILLEDDATE2 should not be before SERVICEDATE
invalid_lastbill2 = (
    claims["LASTBILLEDDATE2"].notna() &
    claims["SERVICEDATE"].notna() &
    (claims["LASTBILLEDDATE2"] < claims["SERVICEDATE"])
).sum()

print(
    "LASTBILLEDDATE2 before SERVICEDATE:",
    invalid_lastbill2
)

# LASTBILLEDDATEP should not be before SERVICEDATE
invalid_lastbillp = (
    claims["LASTBILLEDDATEP"].notna() &
    claims["SERVICEDATE"].notna() &
    (claims["LASTBILLEDDATEP"] < claims["SERVICEDATE"])
).sum()

print(
    "LASTBILLEDDATEP before SERVICEDATE:",
    invalid_lastbillp
)


# ------------------------------------------------------------
# STEP 6: CHECK PATIENT AND PROVIDER REFERENCES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 6 — PATIENT & PROVIDER REFERENCE VALIDATION")
print("=" * 70)

valid_patient_ids = set(patients["Id"])
valid_provider_ids = set(providers["Id"])

invalid_patient_refs = (
    ~claims["PATIENTID"].isin(valid_patient_ids)
).sum()

invalid_provider_refs = (
    ~claims["PROVIDERID"].isin(valid_provider_ids)
).sum()

invalid_referring_provider_refs = (
    claims["REFERRINGPROVIDERID"].notna() &
    ~claims["REFERRINGPROVIDERID"].isin(valid_provider_ids)
).sum()

invalid_supervising_provider_refs = (
    claims["SUPERVISINGPROVIDERID"].notna() &
    ~claims["SUPERVISINGPROVIDERID"].isin(valid_provider_ids)
).sum()

print(
    "Invalid PATIENTID references:",
    invalid_patient_refs
)

print(
    "Invalid PROVIDERID references:",
    invalid_provider_refs
)

print(
    "Invalid REFERRINGPROVIDERID references:",
    invalid_referring_provider_refs
)

print(
    "Invalid SUPERVISINGPROVIDERID references:",
    invalid_supervising_provider_refs
)

print("\nUnique patients:", claims["PATIENTID"].nunique())
print("Unique providers:", claims["PROVIDERID"].nunique())


# ------------------------------------------------------------
# STEP 7: CHECK INSURANCE REFERENCES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 7 — INSURANCE REFERENCE VALIDATION")
print("=" * 70)

valid_payer_ids = set(payers["Id"])

invalid_primary_insurance = (
    claims["PRIMARYPATIENTINSURANCEID"].notna() &
    ~claims["PRIMARYPATIENTINSURANCEID"].isin(valid_payer_ids)
).sum()

invalid_secondary_insurance = (
    claims["SECONDARYPATIENTINSURANCEID"].notna() &
    ~claims["SECONDARYPATIENTINSURANCEID"].isin(valid_payer_ids)
).sum()

print(
    "Invalid PRIMARYPATIENTINSURANCEID references:",
    invalid_primary_insurance
)

print(
    "Invalid SECONDARYPATIENTINSURANCEID references:",
    invalid_secondary_insurance
)

print(
    "\nUnique primary insurance IDs:",
    claims["PRIMARYPATIENTINSURANCEID"].nunique()
)

print(
    "Unique secondary insurance IDs:",
    claims["SECONDARYPATIENTINSURANCEID"].nunique()
)


# ------------------------------------------------------------
# STEP 8: CHECK DIAGNOSIS FIELDS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 8 — DIAGNOSIS FIELD VALIDATION")
print("=" * 70)

diagnosis_columns = [
    "DIAGNOSIS1",
    "DIAGNOSIS2",
    "DIAGNOSIS3",
    "DIAGNOSIS4",
    "DIAGNOSIS5",
    "DIAGNOSIS6",
    "DIAGNOSIS7",
    "DIAGNOSIS8"
]

for col in diagnosis_columns:
    print(
        f"{col} missing:",
        claims[col].isna().sum()
    )

print("\nNumber of diagnosis fields populated per claim:")

diagnosis_count = claims[diagnosis_columns].notna().sum(axis=1)

print(diagnosis_count.describe())


# ------------------------------------------------------------
# STEP 9: CHECK CLAIM STATUS FIELDS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 9 — CLAIM STATUS VALIDATION")
print("=" * 70)

status_columns = [
    "STATUS1",
    "STATUS2",
    "STATUSP"
]

for col in status_columns:
    print(f"\n{col}:")
    print(claims[col].value_counts(dropna=False))


# ------------------------------------------------------------
# STEP 10: CHECK OUTSTANDING FIELDS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 10 — OUTSTANDING FIELD VALIDATION")
print("=" * 70)

outstanding_columns = [
    "OUTSTANDING1",
    "OUTSTANDING2",
    "OUTSTANDINGP"
]

for col in outstanding_columns:
    print(f"\n{col}:")
    print("Missing:", claims[col].isna().sum())
    print("Non-zero:", (claims[col].fillna(0) != 0).sum())

    if claims[col].notna().any():
        print("Minimum:", claims[col].min())
        print("Maximum:", claims[col].max())


# ------------------------------------------------------------
# STEP 11: CHECK CLAIM TYPES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 11 — CLAIM TYPE VALIDATION")
print("=" * 70)

claim_type_columns = [
    "HEALTHCARECLAIMTYPEID1",
    "HEALTHCARECLAIMTYPEID2"
]

for col in claim_type_columns:
    print(f"\n{col}:")
    print(claims[col].value_counts(dropna=False))


# ------------------------------------------------------------
# STEP 12: CHECK DEPARTMENT FIELDS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 12 — DEPARTMENT VALIDATION")
print("=" * 70)

print(
    "Unique DEPARTMENTID:",
    claims["DEPARTMENTID"].nunique()
)

print(
    "Unique PATIENTDEPARTMENTID:",
    claims["PATIENTDEPARTMENTID"].nunique()
)

print(
    "DEPARTMENTID = PATIENTDEPARTMENTID:",
    (
        claims["DEPARTMENTID"] ==
        claims["PATIENTDEPARTMENTID"]
    ).sum()
)

print("\nDEPARTMENTID distribution:")
print(claims["DEPARTMENTID"].value_counts())


# ------------------------------------------------------------
# STEP 13: CHECK CLAIM IDs AND BASIC IDENTIFIERS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 13 — IDENTIFIER VALIDATION")
print("=" * 70)

print("Missing claim IDs:", claims["Id"].isna().sum())
print("Unique claim IDs:", claims["Id"].nunique())
print("Total claim rows:", len(claims))

print(
    "Missing PATIENTID:",
    claims["PATIENTID"].isna().sum()
)

print(
    "Missing PROVIDERID:",
    claims["PROVIDERID"].isna().sum()
)


# ------------------------------------------------------------
# STEP 14: FINAL VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 14 — FINAL VALIDATION")
print("=" * 70)

print("Final shape:", claims.shape)

print("Duplicate rows:",
      claims.duplicated().sum())

print("Duplicate claim IDs:",
      claims["Id"].duplicated().sum())

print("\nMissing values:")
print(claims.isna().sum())

print("\nReference validation:")

print(
    "Invalid PATIENTID:",
    (~claims["PATIENTID"].isin(valid_patient_ids)).sum()
)

print(
    "Invalid PROVIDERID:",
    (~claims["PROVIDERID"].isin(valid_provider_ids)).sum()
)

print(
    "Invalid PRIMARYPATIENTINSURANCEID:",
    (
        claims["PRIMARYPATIENTINSURANCEID"].notna() &
        ~claims["PRIMARYPATIENTINSURANCEID"].isin(valid_payer_ids)
    ).sum()
)

print(
    "Invalid SECONDARYPATIENTINSURANCEID:",
    (
        claims["SECONDARYPATIENTINSURANCEID"].notna() &
        ~claims["SECONDARYPATIENTINSURANCEID"].isin(valid_payer_ids)
    ).sum()
)

print("\nOutstanding field validation:")

for col in outstanding_columns:
    print(
        f"{col} non-zero:",
        (claims[col].fillna(0) != 0).sum()
    )

print("\nFinal data types:")
print(claims.dtypes)


# ------------------------------------------------------------
# STEP 15: SAVE CLEANED DATASET
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 15 — SAVE CLEANED DATASET")
print("=" * 70)

claims_cleaned_path = (
    CLEAN_PATH / "claims_cleaned.csv"
)

claims.to_csv(
    claims_cleaned_path,
    index=False
)

print("Cleaned claims dataset saved successfully!")
print("File:", claims_cleaned_path)


# ------------------------------------------------------------
# STEP 16: RELOAD AND VERIFY SAVED FILE
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 16 — VERIFY SAVED FILE")
print("=" * 70)

claims_check = pd.read_csv(
    claims_cleaned_path
)

print("Reloaded cleaned claims dataset successfully!")

print("Shape:",
      claims_check.shape)

print("\nColumns:")
print(claims_check.columns.tolist())

print(
    "\nDuplicate rows:",
    claims_check.duplicated().sum()
)

print(
    "Duplicate claim IDs:",
    claims_check["Id"].duplicated().sum()
)

print("\nSaved file verification completed!")

======================================================================
DATASET 8 — CLAIMS
======================================================================

Claims dataset loaded successfully!
Shape: (117889, 31)

Columns:
['Id', 'PATIENTID', 'PROVIDERID', 'PRIMARYPATIENTINSURANCEID', 'SECONDARYPATIENTINSURANCEID', 'DEPARTMENTID', 'PATIENTDEPARTMENTID', 'DIAGNOSIS1', 'DIAGNOSIS2', 'DIAGNOSIS3', 'DIAGNOSIS4', 'DIAGNOSIS5', 'DIAGNOSIS6', 'DIAGNOSIS7', 'DIAGNOSIS8', 'REFERRINGPROVIDERID', 'APPOINTMENTID', 'CURRENTILLNESSDATE', 'SERVICEDATE', 'SUPERVISINGPROVIDERID', 'STATUS1', 'STATUS2', 'STATUSP', 'OUTSTANDING1', 'OUTSTANDING2', 'OUTSTANDINGP', 'LASTBILLEDDATE1', 'LASTBILLEDDATE2', 'LASTBILLEDDATEP', 'HEALTHCARECLAIMTYPEID1', 'HEALTHCARECLAIMTYPEID2']

======================================================================
STEP 2 — MISSING VALUE CHECK
======================================================================
Id                                  0
PATIENTID                           0
PROVIDERID                          0
PRIMARYPATIENTINSURANCEID           0
SECONDARYPATIENTINSURANCEID         0
DEPARTMENTID                        0
PATIENTDEPARTMENTID                 0
DIAGNOSIS1                          0
DIAGNOSIS2                      89378
DIAGNOSIS3                     111855
DIAGNOSIS4                     116212
DIAGNOSIS5                     117411
DIAGNOSIS6                     117757
DIAGNOSIS7                     117822
DIAGNOSIS8                     117859
REFERRINGPROVIDERID            117889
APPOINTMENTID                       0
CURRENTILLNESSDATE                  0
SERVICEDATE                         0
SUPERVISINGPROVIDERID               0
STATUS1                             0
STATUS2                        103727
STATUSP                             0
OUTSTANDING1                        0
OUTSTANDING2                   103727
OUTSTANDINGP                        0
LASTBILLEDDATE1                     0
LASTBILLEDDATE2                103727
LASTBILLEDDATEP                     0
HEALTHCARECLAIMTYPEID1              0
HEALTHCARECLAIMTYPEID2              0
dtype: int64

======================================================================
STEP 3 — DUPLICATE CHECK
======================================================================
Duplicate complete rows: 0
Duplicate claim IDs: 0

======================================================================
STEP 4 — DATE CONVERSION & VALIDATION
======================================================================
Date conversion completed.

Date data types:
CURRENTILLNESSDATE    datetime64[us, UTC]
SERVICEDATE           datetime64[us, UTC]
LASTBILLEDDATE1       datetime64[us, UTC]
LASTBILLEDDATE2       datetime64[us, UTC]
LASTBILLEDDATEP       datetime64[us, UTC]
dtype: object

Missing / invalid date values:
CURRENTILLNESSDATE: 0
SERVICEDATE: 0
LASTBILLEDDATE1: 0
LASTBILLEDDATE2: 103727
LASTBILLEDDATEP: 0

======================================================================
STEP 5 — DATE LOGIC VALIDATION
======================================================================
CURRENTILLNESSDATE after SERVICEDATE: 0
LASTBILLEDDATE1 before SERVICEDATE: 0
LASTBILLEDDATE2 before SERVICEDATE: 0
LASTBILLEDDATEP before SERVICEDATE: 0

======================================================================
STEP 6 — PATIENT & PROVIDER REFERENCE VALIDATION
======================================================================
Invalid PATIENTID references: 0
Invalid PROVIDERID references: 0
Invalid REFERRINGPROVIDERID references: 0
Invalid SUPERVISINGPROVIDERID references: 0

Unique patients: 1163
Unique providers: 1123

======================================================================
STEP 7 — INSURANCE REFERENCE VALIDATION
======================================================================
Invalid PRIMARYPATIENTINSURANCEID references: 25967
Invalid SECONDARYPATIENTINSURANCEID references: 103719

Unique primary insurance IDs: 11
Unique secondary insurance IDs: 8

======================================================================
STEP 8 — DIAGNOSIS FIELD VALIDATION
======================================================================
DIAGNOSIS1 missing: 0
DIAGNOSIS2 missing: 89378
DIAGNOSIS3 missing: 111855
DIAGNOSIS4 missing: 116212
DIAGNOSIS5 missing: 117411
DIAGNOSIS6 missing: 117757
DIAGNOSIS7 missing: 117822
DIAGNOSIS8 missing: 117859

Number of diagnosis fields populated per claim:
count    117889.000000
mean          1.313252
std           0.645306
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           8.000000
dtype: float64

======================================================================
STEP 9 — CLAIM STATUS VALIDATION
======================================================================

STATUS1:
STATUS1
CLOSED    117732
BILLED       157
Name: count, dtype: int64

STATUS2:
STATUS2
NaN       103727
CLOSED     14118
BILLED        44
Name: count, dtype: int64

STATUSP:
STATUSP
CLOSED    117732
BILLED       157
Name: count, dtype: int64

======================================================================
STEP 10 — OUTSTANDING FIELD VALIDATION
======================================================================

OUTSTANDING1:
Missing: 0
Non-zero: 0
Minimum: 0.0
Maximum: 0.0

OUTSTANDING2:
Missing: 103727
Non-zero: 0
Minimum: 0.0
Maximum: 0.0

OUTSTANDINGP:
Missing: 0
Non-zero: 0
Minimum: 0.0
Maximum: 0.0

======================================================================
STEP 11 — CLAIM TYPE VALIDATION
======================================================================

HEALTHCARECLAIMTYPEID1:
HEALTHCARECLAIMTYPEID1
2    69039
1    48850
Name: count, dtype: int64

HEALTHCARECLAIMTYPEID2:
HEALTHCARECLAIMTYPEID2
0    103727
2     10186
1      3976
Name: count, dtype: int64

======================================================================
STEP 12 — DEPARTMENT VALIDATION
======================================================================
Unique DEPARTMENTID: 7
Unique PATIENTDEPARTMENTID: 7
DEPARTMENTID = PATIENTDEPARTMENTID: 117889

DEPARTMENTID distribution:
DEPARTMENTID
20    47558
1     28480
2     26379
10     6207
3      3403
4      3286
5      2576
Name: count, dtype: int64

======================================================================
STEP 13 — IDENTIFIER VALIDATION
======================================================================
Missing claim IDs: 0
Unique claim IDs: 117889
Total claim rows: 117889
Missing PATIENTID: 0
Missing PROVIDERID: 0

======================================================================
STEP 14 — FINAL VALIDATION
======================================================================
Final shape: (117889, 31)
Duplicate rows: 0
Duplicate claim IDs: 0

Missing values:
Id                                  0
PATIENTID                           0
PROVIDERID                          0
PRIMARYPATIENTINSURANCEID           0
SECONDARYPATIENTINSURANCEID         0
DEPARTMENTID                        0
PATIENTDEPARTMENTID                 0
DIAGNOSIS1                          0
DIAGNOSIS2                      89378
DIAGNOSIS3                     111855
DIAGNOSIS4                     116212
DIAGNOSIS5                     117411
DIAGNOSIS6                     117757
DIAGNOSIS7                     117822
DIAGNOSIS8                     117859
REFERRINGPROVIDERID            117889
APPOINTMENTID                       0
CURRENTILLNESSDATE                  0
SERVICEDATE                         0
SUPERVISINGPROVIDERID               0
STATUS1                             0
STATUS2                        103727
STATUSP                             0
OUTSTANDING1                        0
OUTSTANDING2                   103727
OUTSTANDINGP                        0
LASTBILLEDDATE1                     0
LASTBILLEDDATE2                103727
LASTBILLEDDATEP                     0
HEALTHCARECLAIMTYPEID1              0
HEALTHCARECLAIMTYPEID2              0
dtype: int64

Reference validation:
Invalid PATIENTID: 0
Invalid PROVIDERID: 0
Invalid PRIMARYPATIENTINSURANCEID: 25967
Invalid SECONDARYPATIENTINSURANCEID: 103719

Outstanding field validation:
OUTSTANDING1 non-zero: 0
OUTSTANDING2 non-zero: 0
OUTSTANDINGP non-zero: 0

Final data types:
Id                                             str
PATIENTID                                      str
PROVIDERID                                     str
PRIMARYPATIENTINSURANCEID                      str
SECONDARYPATIENTINSURANCEID                    str
DEPARTMENTID                                 int64
PATIENTDEPARTMENTID                          int64
DIAGNOSIS1                                   int64
DIAGNOSIS2                                 float64
DIAGNOSIS3                                 float64
DIAGNOSIS4                                 float64
DIAGNOSIS5                                 float64
DIAGNOSIS6                                 float64
DIAGNOSIS7                                 float64
DIAGNOSIS8                                 float64
REFERRINGPROVIDERID                        float64
APPOINTMENTID                                  str
CURRENTILLNESSDATE             datetime64[us, UTC]
SERVICEDATE                    datetime64[us, UTC]
SUPERVISINGPROVIDERID                          str
STATUS1                                        str
STATUS2                                        str
STATUSP                                        str
OUTSTANDING1                               float64
OUTSTANDING2                               float64
OUTSTANDINGP                               float64
LASTBILLEDDATE1                datetime64[us, UTC]
LASTBILLEDDATE2                datetime64[us, UTC]
LASTBILLEDDATEP                datetime64[us, UTC]
HEALTHCARECLAIMTYPEID1                       int64
HEALTHCARECLAIMTYPEID2                       int64
dtype: object

======================================================================
STEP 15 — SAVE CLEANED DATASET
======================================================================
Cleaned claims dataset saved successfully!
File: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\claims_cleaned.csv

======================================================================
STEP 16 — VERIFY SAVED FILE
======================================================================
Reloaded cleaned claims dataset successfully!
Shape: (117889, 31)

Columns:
['Id', 'PATIENTID', 'PROVIDERID', 'PRIMARYPATIENTINSURANCEID', 'SECONDARYPATIENTINSURANCEID', 'DEPARTMENTID', 'PATIENTDEPARTMENTID', 'DIAGNOSIS1', 'DIAGNOSIS2', 'DIAGNOSIS3', 'DIAGNOSIS4', 'DIAGNOSIS5', 'DIAGNOSIS6', 'DIAGNOSIS7', 'DIAGNOSIS8', 'REFERRINGPROVIDERID', 'APPOINTMENTID', 'CURRENTILLNESSDATE', 'SERVICEDATE', 'SUPERVISINGPROVIDERID', 'STATUS1', 'STATUS2', 'STATUSP', 'OUTSTANDING1', 'OUTSTANDING2', 'OUTSTANDINGP', 'LASTBILLEDDATE1', 'LASTBILLEDDATE2', 'LASTBILLEDDATEP', 'HEALTHCARECLAIMTYPEID1', 'HEALTHCARECLAIMTYPEID2']

Duplicate rows: 0
Duplicate claim IDs: 0

Saved file verification completed!

In [52]:
# ============================================================
# DATASET 9 — CLAIMS TRANSACTIONS
# DATA CLEANING & VALIDATION
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ------------------------------------------------------------
# 1. PROJECT PATHS
# ------------------------------------------------------------

PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)

RAW_PATH = PROJECT_PATH / "data" / "Raw_Datasets"
CLEAN_PATH = PROJECT_PATH / "data" / "Cleaned_Datasets"

INPUT_FILE = RAW_PATH / "claims_transactions.csv"
OUTPUT_FILE = CLEAN_PATH / "claims_transactions_cleaned.csv"


# ------------------------------------------------------------
# 2. LOAD DATA
# ------------------------------------------------------------

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("=" * 70)
print("DATASET 9 — CLAIMS TRANSACTIONS")
print("=" * 70)

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())


# ------------------------------------------------------------
# 3. DATA TYPES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATA TYPES")
print("=" * 70)

print(df.dtypes)


# ------------------------------------------------------------
# 4. MISSING VALUES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MISSING VALUES")
print("=" * 70)

missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

print("\nTotal missing values:")
print(df.isnull().sum().sum())


# ------------------------------------------------------------
# 5. DUPLICATE CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DUPLICATE CHECK")
print("=" * 70)

duplicate_rows = df.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)

if "ID" in df.columns:
    duplicate_ids = df["ID"].duplicated().sum()
    print("Duplicate IDs:", duplicate_ids)

if "CLAIMID" in df.columns:
    duplicate_claim_ids = df["CLAIMID"].duplicated().sum()
    print("Repeated CLAIMID values:", duplicate_claim_ids)


# ------------------------------------------------------------
# 6. DATE CONVERSION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATE VALIDATION")
print("=" * 70)

date_columns = []

for col in ["FROMDATE", "TODATE"]:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)
        date_columns.append(col)

print("Date columns converted:")
print(date_columns)

for col in date_columns:
    print(f"\n{col}")
    print("Missing:", df[col].isna().sum())
    print("Minimum:", df[col].min())
    print("Maximum:", df[col].max())


# ------------------------------------------------------------
# 7. HANDLE INVALID TODATE PLACEHOLDER
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TODATE PLACEHOLDER CHECK")
print("=" * 70)

if "TODATE" in df.columns:

    placeholder_date = pd.Timestamp("1970-01-01", tz="UTC")

    placeholder_count = (df["TODATE"] == placeholder_date).sum()

    print("TODATE = 1970-01-01 records:", placeholder_count)

    # Treat 1970-01-01 as an invalid/missing end date.
    # We retain the transaction itself.
    df.loc[df["TODATE"] == placeholder_date, "TODATE"] = pd.NaT

    print(
        "TODATE missing after placeholder handling:",
        df["TODATE"].isna().sum()
    )


# ------------------------------------------------------------
# 8. DATE LOGIC CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATE ORDER CHECK")
print("=" * 70)

if "FROMDATE" in df.columns and "TODATE" in df.columns:

    invalid_date_order = (
        df["FROMDATE"].notna()
        & df["TODATE"].notna()
        & (df["TODATE"] < df["FROMDATE"])
    )

    print(
        "TODATE earlier than FROMDATE after cleaning:",
        invalid_date_order.sum()
    )


# ------------------------------------------------------------
# 9. TRANSACTION TYPE CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TRANSACTION TYPES")
print("=" * 70)

if "TYPE" in df.columns:
    print(df["TYPE"].value_counts(dropna=False))


# ------------------------------------------------------------
# 10. FINANCIAL COLUMN CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINANCIAL VALIDATION")
print("=" * 70)

financial_columns = [
    "AMOUNT",
    "UNITAMOUNT",
    "PAYMENTS",
    "ADJUSTMENTS",
    "TRANSFERS",
    "OUTSTANDING"
]

for col in financial_columns:

    if col in df.columns:

        print(f"\n--- {col} ---")

        print("Non-missing:", df[col].notna().sum())
        print("Missing:", df[col].isna().sum())

        if df[col].notna().any():

            print("Minimum:", df[col].min())
            print("Maximum:", df[col].max())
            print("Mean:", df[col].mean())
            print("Median:", df[col].median())

            negative_count = (df[col] < 0).sum()

            print("Negative values:", negative_count)


# ------------------------------------------------------------
# 11. REFERENCE VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("REFERENCE VALIDATION")
print("=" * 70)

# Load master datasets
patients = pd.read_csv(
    CLEAN_PATH / "patients_cleaned.csv",
    low_memory=False
)

providers = pd.read_csv(
    CLEAN_PATH / "providers_cleaned.csv",
    low_memory=False
)

claims = pd.read_csv(
    CLEAN_PATH / "claims_cleaned.csv",
    low_memory=False
)


# Patient references
if "PATIENTID" in df.columns and "Id" in patients.columns:

    invalid_patients = (
        ~df["PATIENTID"].isin(patients["Id"])
    ).sum()

    print("Invalid PATIENTID references:", invalid_patients)


# Provider references
if "PROVIDERID" in df.columns and "Id" in providers.columns:

    invalid_providers = (
        ~df["PROVIDERID"].isin(providers["Id"])
    ).sum()

    print("Invalid PROVIDERID references:", invalid_providers)


# Claim references
if "CLAIMID" in df.columns and "Id" in claims.columns:

    invalid_claims = (
        ~df["CLAIMID"].isin(claims["Id"])
    ).sum()

    print("Invalid CLAIMID references:", invalid_claims)


# Supervising provider
if "SUPERVISINGPROVIDERID" in df.columns:

    valid_supervising = (
        df["SUPERVISINGPROVIDERID"].notna()
        & ~df["SUPERVISINGPROVIDERID"].isin(providers["Id"])
    ).sum()

    print(
        "Invalid SUPERVISINGPROVIDERID references:",
        valid_supervising
    )


# ------------------------------------------------------------
# 12. TRANSACTION-SPECIFIC CHECKS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TRANSACTION-SPECIFIC CHECKS")
print("=" * 70)

if "TYPE" in df.columns:

    for transaction_type in sorted(df["TYPE"].dropna().unique()):

        subset = df[df["TYPE"] == transaction_type]

        print(
            f"{transaction_type}:",
            len(subset),
            "records"
        )


# ------------------------------------------------------------
# 13. INSURANCE REFERENCE CHECK
# ------------------------------------------------------------

if "PATIENTINSURANCEID" in df.columns:

    print("\n" + "=" * 70)
    print("PATIENT INSURANCE REFERENCE CHECK")
    print("=" * 70)

    payers = pd.read_csv(
        CLEAN_PATH / "payers_cleaned.csv",
        low_memory=False
    )

    invalid_insurance = (
        df["PATIENTINSURANCEID"].notna()
        & ~df["PATIENTINSURANCEID"].isin(payers["Id"])
    ).sum()

    print(
        "Unmatched PATIENTINSURANCEID references:",
        invalid_insurance
    )


# ------------------------------------------------------------
# 14. FINAL NEGATIVE-VALUE CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL NEGATIVE VALUE CHECK")
print("=" * 70)

for col in financial_columns:

    if col in df.columns:

        negative_count = (
            pd.to_numeric(df[col], errors="coerce") < 0
        ).sum()

        print(f"{col}: {negative_count} negative values")


# ------------------------------------------------------------
# 15. FINAL DATASET VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL DATASET VALIDATION")
print("=" * 70)

print("Final shape:", df.shape)
print("Duplicate complete rows:", df.duplicated().sum())

if "ID" in df.columns:
    print("Duplicate IDs:", df["ID"].duplicated().sum())

print("\nFinal missing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])


# ------------------------------------------------------------
# 16. SAVE CLEANED DATASET
# ------------------------------------------------------------

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print("\n" + "=" * 70)
print("FILE SAVED")
print("=" * 70)

print(OUTPUT_FILE)


# ------------------------------------------------------------
# 17. RELOAD AND VERIFY SAVED FILE
# ------------------------------------------------------------

verified_df = pd.read_csv(
    OUTPUT_FILE,
    low_memory=False
)

print("\n" + "=" * 70)
print("RELOAD VERIFICATION")
print("=" * 70)

print("Reloaded shape:", verified_df.shape)
print(
    "Reloaded duplicate rows:",
    verified_df.duplicated().sum()
)

if "ID" in verified_df.columns:
    print(
        "Reloaded duplicate IDs:",
        verified_df["ID"].duplicated().sum()
    )

print("\nDataset 9 cleaning completed successfully.")

======================================================================
DATASET 9 — CLAIMS TRANSACTIONS
======================================================================

Shape:
(711238, 33)

Columns:
['ID', 'CLAIMID', 'CHARGEID', 'PATIENTID', 'TYPE', 'AMOUNT', 'METHOD', 'FROMDATE', 'TODATE', 'PLACEOFSERVICE', 'PROCEDURECODE', 'MODIFIER1', 'MODIFIER2', 'DIAGNOSISREF1', 'DIAGNOSISREF2', 'DIAGNOSISREF3', 'DIAGNOSISREF4', 'UNITS', 'DEPARTMENTID', 'NOTES', 'UNITAMOUNT', 'TRANSFEROUTID', 'TRANSFERTYPE', 'PAYMENTS', 'ADJUSTMENTS', 'TRANSFERS', 'OUTSTANDING', 'APPOINTMENTID', 'LINENOTE', 'PATIENTINSURANCEID', 'FEESCHEDULEID', 'PROVIDERID', 'SUPERVISINGPROVIDERID']

======================================================================
DATA TYPES
======================================================================
ID                           str
CLAIMID                      str
CHARGEID                   int64
PATIENTID                    str
TYPE                         str
AMOUNT                   float64
METHOD                       str
FROMDATE                     str
TODATE                       str
PLACEOFSERVICE               str
PROCEDURECODE              int64
MODIFIER1                float64
MODIFIER2                float64
DIAGNOSISREF1              int64
DIAGNOSISREF2            float64
DIAGNOSISREF3            float64
DIAGNOSISREF4            float64
UNITS                      int64
DEPARTMENTID               int64
NOTES                        str
UNITAMOUNT               float64
TRANSFEROUTID            float64
TRANSFERTYPE                 str
PAYMENTS                 float64
ADJUSTMENTS              float64
TRANSFERS                float64
OUTSTANDING              float64
APPOINTMENTID                str
LINENOTE                 float64
PATIENTINSURANCEID           str
FEESCHEDULEID              int64
PROVIDERID                   str
SUPERVISINGPROVIDERID        str
dtype: object

======================================================================
MISSING VALUES
======================================================================
MODIFIER2             711238
MODIFIER1             711238
LINENOTE              711238
ADJUSTMENTS           711238
DIAGNOSISREF4         698843
DIAGNOSISREF3         667976
TRANSFEROUTID         591147
DIAGNOSISREF2         516000
UNITAMOUNT            492517
TRANSFERS             471056
PAYMENTS              458903
METHOD                458903
AMOUNT                372426
TRANSFERTYPE          372426
OUTSTANDING           218721
PATIENTINSURANCEID     89738
dtype: int64

Total missing values:
8253608

======================================================================
DUPLICATE CHECK
======================================================================
Duplicate complete rows: 0
Duplicate IDs: 0
Repeated CLAIMID values: 593349

======================================================================
DATE VALIDATION
======================================================================
Date columns converted:
['FROMDATE', 'TODATE']

FROMDATE
Missing: 0
Minimum: 1912-09-26 02:47:25+00:00
Maximum: 2021-11-19 16:50:22+00:00

TODATE
Missing: 0
Minimum: 1912-09-26 03:02:25+00:00
Maximum: 2021-11-19 17:06:35+00:00

======================================================================
TODATE PLACEHOLDER CHECK
======================================================================
TODATE = 1970-01-01 records: 71060
TODATE missing after placeholder handling: 71060

======================================================================
DATE ORDER CHECK
======================================================================
TODATE earlier than FROMDATE after cleaning: 22

======================================================================
TRANSACTION TYPES
======================================================================
TYPE
PAYMENT        252335
CHARGE         218721
TRANSFEROUT    120091
TRANSFERIN     120091
Name: count, dtype: int64

======================================================================
FINANCIAL VALIDATION
======================================================================

--- AMOUNT ---
Non-missing: 338812
Missing: 372426
Minimum: 0.0
Maximum: 623241.97
Mean: 801.6588681038451
Median: 103.33
Negative values: 0

--- UNITAMOUNT ---
Non-missing: 218721
Missing: 492517
Minimum: 0.0
Maximum: 623241.97
Mean: 945.960263440639
Median: 129.16
Negative values: 0

--- PAYMENTS ---
Non-missing: 252335
Missing: 458903
Minimum: 0.01
Maximum: 623241.97
Mean: 822.2495973606514
Median: 75.0
Negative values: 0

--- ADJUSTMENTS ---
Non-missing: 0
Missing: 711238

--- TRANSFERS ---
Non-missing: 240182
Missing: 471056
Minimum: 0.01
Maximum: 623241.97
Mean: 538.8436239185285
Median: 74.16
Negative values: 0

--- OUTSTANDING ---
Non-missing: 492517
Missing: 218721
Minimum: 0.0
Maximum: 623241.97
Mean: 289.878650726777
Median: 8.16
Negative values: 0

======================================================================
REFERENCE VALIDATION
======================================================================
Invalid PATIENTID references: 0
Invalid PROVIDERID references: 0
Invalid CLAIMID references: 0
Invalid SUPERVISINGPROVIDERID references: 0

======================================================================
TRANSACTION-SPECIFIC CHECKS
======================================================================
CHARGE: 218721 records
PAYMENT: 252335 records
TRANSFERIN: 120091 records
TRANSFEROUT: 120091 records

======================================================================
PATIENT INSURANCE REFERENCE CHECK
======================================================================
Unmatched PATIENTINSURANCEID references: 621500

======================================================================
FINAL NEGATIVE VALUE CHECK
======================================================================
AMOUNT: 0 negative values
UNITAMOUNT: 0 negative values
PAYMENTS: 0 negative values
ADJUSTMENTS: 0 negative values
TRANSFERS: 0 negative values
OUTSTANDING: 0 negative values

======================================================================
FINAL DATASET VALIDATION
======================================================================
Final shape: (711238, 33)
Duplicate complete rows: 0
Duplicate IDs: 0

Final missing values:
AMOUNT                372426
METHOD                458903
TODATE                 71060
MODIFIER1             711238
MODIFIER2             711238
DIAGNOSISREF2         516000
DIAGNOSISREF3         667976
DIAGNOSISREF4         698843
UNITAMOUNT            492517
TRANSFEROUTID         591147
TRANSFERTYPE          372426
PAYMENTS              458903
ADJUSTMENTS           711238
TRANSFERS             471056
OUTSTANDING           218721
LINENOTE              711238
PATIENTINSURANCEID     89738
dtype: int64

======================================================================
FILE SAVED
======================================================================
C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\claims_transactions_cleaned.csv

======================================================================
RELOAD VERIFICATION
======================================================================
Reloaded shape: (711238, 33)
Reloaded duplicate rows: 0
Reloaded duplicate IDs: 0

Dataset 9 cleaning completed successfully.

In [53]:
# ============================================================
# INVESTIGATE THE 22 REMAINING INVALID DATE RECORDS
# ============================================================

invalid_date_records = df[
    df["FROMDATE"].notna()
    & df["TODATE"].notna()
    & (df["TODATE"] < df["FROMDATE"])
].copy()

print("Number of remaining invalid date records:")
print(len(invalid_date_records))

print("\nInvalid records:")
display(
    invalid_date_records[
        [
            "ID",
            "CLAIMID",
            "CHARGEID",
            "PATIENTID",
            "TYPE",
            "AMOUNT",
            "FROMDATE",
            "TODATE",
            "PROVIDERID"
        ]
    ]
)

Number of remaining invalid date records:
22

Invalid records:

,ID,CLAIMID,CHARGEID,PATIENTID,TYPE,AMOUNT,FROMDATE,TODATE,PROVIDERID
121360,390573d5-3336-481d-6c9e-c481301191ef,90708c15-958b-acf1-6543-995edb2b4f56,158944,859e5c6f-f1db-308d-0e33-57d392c1bf04,CHARGE,66.93,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121361,38f1a094-6694-41be-db84-9ff2cbf891d6,90708c15-958b-acf1-6543-995edb2b4f56,158945,859e5c6f-f1db-308d-0e33-57d392c1bf04,TRANSFEROUT,NaN,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121362,b28c5ca7-8d74-2191-0527-67387452eb64,90708c15-958b-acf1-6543-995edb2b4f56,158946,859e5c6f-f1db-308d-0e33-57d392c1bf04,TRANSFERIN,66.93,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121363,ca3ca1f1-70ae-fc65-8c5b-e5a946e1c383,90708c15-958b-acf1-6543-995edb2b4f56,158947,859e5c6f-f1db-308d-0e33-57d392c1bf04,PAYMENT,NaN,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121364,2ae12fe1-0479-848a-f46f-acfdd5f1fc67,e2e1abf0-b00e-b3bd-0f5a-f5a72665b38a,158949,859e5c6f-f1db-308d-0e33-57d392c1bf04,CHARGE,16.66,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121365,40eb8c31-3621-478b-e906-dce5482c3c1e,e2e1abf0-b00e-b3bd-0f5a-f5a72665b38a,158950,859e5c6f-f1db-308d-0e33-57d392c1bf04,TRANSFEROUT,NaN,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121366,43d7b8be-34ee-22a3-83c2-4c9e48b85af3,e2e1abf0-b00e-b3bd-0f5a-f5a72665b38a,158951,859e5c6f-f1db-308d-0e33-57d392c1bf04,TRANSFERIN,16.66,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121367,049c7619-cb3a-8862-5d1c-2a3f90b26e51,e2e1abf0-b00e-b3bd-0f5a-f5a72665b38a,158952,859e5c6f-f1db-308d-0e33-57d392c1bf04,PAYMENT,NaN,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121368,cc53e8c3-0553-ee4b-046d-612bba30f3b9,aec6ee85-f6d6-58ee-8145-bcedca38b2c6,158954,859e5c6f-f1db-308d-0e33-57d392c1bf04,CHARGE,36.26,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121369,327cabc6-0008-932c-5b32-2dc1d953f726,aec6ee85-f6d6-58ee-8145-bcedca38b2c6,158955,859e5c6f-f1db-308d-0e33-57d392c1bf04,TRANSFEROUT,NaN,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121370,21883c77-58b0-bb8f-4fcf-b89b04e0b155,aec6ee85-f6d6-58ee-8145-bcedca38b2c6,158956,859e5c6f-f1db-308d-0e33-57d392c1bf04,TRANSFERIN,36.26,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121371,7487cf7e-0cc0-e9cc-2464-affd245b8a7c,aec6ee85-f6d6-58ee-8145-bcedca38b2c6,158957,859e5c6f-f1db-308d-0e33-57d392c1bf04,PAYMENT,NaN,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121372,6c6f6af4-06a5-7dd2-17ce-bce167e45e47,50a9710a-3a70-ddee-8971-a85210abaccb,158959,859e5c6f-f1db-308d-0e33-57d392c1bf04,CHARGE,262.03,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121373,0bf2d4aa-85b2-c858-5a80-6e9f85cab14d,50a9710a-3a70-ddee-8971-a85210abaccb,158960,859e5c6f-f1db-308d-0e33-57d392c1bf04,TRANSFEROUT,NaN,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121374,fe4506fd-4c07-d997-029f-adbff10792c5,50a9710a-3a70-ddee-8971-a85210abaccb,158961,859e5c6f-f1db-308d-0e33-57d392c1bf04,TRANSFERIN,262.03,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
121375,d5f1fdd7-1228-5573-dda9-8ac5bc55b1aa,50a9710a-3a70-ddee-8971-a85210abaccb,158962,859e5c6f-f1db-308d-0e33-57d392c1bf04,PAYMENT,NaN,2011-02-27 02:25:00+00:00,2011-02-26 02:25:00+00:00,3e02c30e-8c70-3559-9d8c-2c09f7a7453e
508003,5a72c57e-1d5e-cd8b-4833-7e242253d16f,63bd7dc4-26f6-766e-4ae2-67c81db6022b,667195,d25c159a-033b-593f-dbbf-b1e9de3b2fc4,CHARGE,263.49,2014-02-18 06:29:35+00:00,2014-02-11 19:34:38+00:00,3b8927d3-3447-3932-9fa5-06a25cd48280
508005,22afd058-b53f-0e26-0690-043fbe528013,63bd7dc4-26f6-766e-4ae2-67c81db6022b,667196,d25c159a-033b-593f-dbbf-b1e9de3b2fc4,PAYMENT,NaN,2014-02-18 06:29:35+00:00,2014-02-11 19:34:38+00:00,3b8927d3-3447-3932-9fa5-06a25cd48280
508006,8d7a0a05-52a6-ac2c-ef1f-82dc398b6b6e,63bd7dc4-26f6-766e-4ae2-67c81db6022b,667198,d25c159a-033b-593f-dbbf-b1e9de3b2fc4,PAYMENT,NaN,2014-02-18 06:29:35+00:00,2014-02-11 19:34:38+00:00,3b8927d3-3447-3932-9fa5-06a25cd48280
508008,a17582ea-9789-c780-eda2-44c8b191f81a,63bd7dc4-26f6-766e-4ae2-67c81db6022b,667199,d25c159a-033b-593f-dbbf-b1e9de3b2fc4,TRANSFEROUT,NaN,2014-02-18 06:29:35+00:00,2014-02-11 19:34:38+00:00,3b8927d3-3447-3932-9fa5-06a25cd48280
508009,895a9b6f-7e6a-2fea-e0e5-3dceaeadb90b,63bd7dc4-26f6-766e-4ae2-67c81db6022b,667201,d25c159a-033b-593f-dbbf-b1e9de3b2fc4,TRANSFERIN,10.17,2014-02-18 06:29:35+00:00,2014-02-11 19:34:38+00:00,3b8927d3-3447-3932-9fa5-06a25cd48280
508011,20049f73-f1f8-344e-c052-fbcfe06773e2,63bd7dc4-26f6-766e-4ae2-67c81db6022b,667202,d25c159a-033b-593f-dbbf-b1e9de3b2fc4,PAYMENT,NaN,2014-02-18 06:29:35+00:00,2014-02-11 19:34:38+00:00,3b8927d3-3447-3932-9fa5-06a25cd48280

In [54]:
# Treat the remaining logically invalid TODATE values as missing
invalid_date_order = (
    df["FROMDATE"].notna()
    & df["TODATE"].notna()
    & (df["TODATE"] < df["FROMDATE"])
)

print("Invalid TODATE values before correction:",
      invalid_date_order.sum())

df.loc[invalid_date_order, "TODATE"] = pd.NaT

print("Invalid TODATE values after correction:",
      (
          df["FROMDATE"].notna()
          & df["TODATE"].notna()
          & (df["TODATE"] < df["FROMDATE"])
      ).sum())

print("Total missing TODATE:", df["TODATE"].isna().sum())

Invalid TODATE values before correction: 22
Invalid TODATE values after correction: 0
Total missing TODATE: 71082

In [56]:
df.to_csv(OUTPUT_FILE, index=False)

print("Cleaned file updated successfully:")
print(OUTPUT_FILE)

Cleaned file updated successfully:
C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\claims_transactions_cleaned.csv

In [57]:
# ============================================================
# FINAL CHECK — CLEANED CLAIMS TRANSACTIONS FILE
# ============================================================

from pathlib import Path
import pandas as pd

PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)

CLEAN_FILE = (
    PROJECT_PATH
    / "data"
    / "Cleaned_Datasets"
    / "claims_transactions_cleaned.csv"
)

print("=" * 70)
print("FINAL SAVED FILE CHECK")
print("=" * 70)

# Check whether file exists
print("\nFile exists:")
print(CLEAN_FILE.exists())

print("\nFile path:")
print(CLEAN_FILE)

# Load the actual saved file
cleaned_transactions = pd.read_csv(
    CLEAN_FILE,
    low_memory=False
)

# Convert dates again for validation
cleaned_transactions["FROMDATE"] = pd.to_datetime(
    cleaned_transactions["FROMDATE"],
    errors="coerce",
    utc=True
)

cleaned_transactions["TODATE"] = pd.to_datetime(
    cleaned_transactions["TODATE"],
    errors="coerce",
    utc=True
)

print("\n" + "=" * 70)
print("SAVED FILE VALIDATION")
print("=" * 70)

print("\nShape:")
print(cleaned_transactions.shape)

print("\nDuplicate complete rows:")
print(cleaned_transactions.duplicated().sum())

print("\nDuplicate IDs:")
print(cleaned_transactions["ID"].duplicated().sum())

print("\nMissing TODATE:")
print(cleaned_transactions["TODATE"].isna().sum())

# Check that no TODATE is earlier than FROMDATE
invalid_dates = (
    cleaned_transactions["FROMDATE"].notna()
    & cleaned_transactions["TODATE"].notna()
    & (
        cleaned_transactions["TODATE"]
        < cleaned_transactions["FROMDATE"]
    )
)

print("\nTODATE earlier than FROMDATE:")
print(invalid_dates.sum())

print("\n" + "=" * 70)
print("FINAL STATUS")
print("=" * 70)

if (
    cleaned_transactions.shape == (711238, 33)
    and cleaned_transactions.duplicated().sum() == 0
    and cleaned_transactions["ID"].duplicated().sum() == 0
    and invalid_dates.sum() == 0
):
    print("✅ CLEANED DATASET SAVED AND VERIFIED SUCCESSFULLY")
else:
    print("⚠️ PLEASE REVIEW THE RESULTS ABOVE")

======================================================================
FINAL SAVED FILE CHECK
======================================================================

File exists:
True

File path:
C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\claims_transactions_cleaned.csv

======================================================================
SAVED FILE VALIDATION
======================================================================

Shape:
(711238, 33)

Duplicate complete rows:
0

Duplicate IDs:
0

Missing TODATE:
71082

TODATE earlier than FROMDATE:
0

======================================================================
FINAL STATUS
======================================================================
✅ CLEANED DATASET SAVED AND VERIFIED SUCCESSFULLY

In [58]:
# ============================================================
# DATASET 10 — MEDICATIONS.CSV
# Data Cleaning & Preparation
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ------------------------------------------------------------
# 1. PATHS
# ------------------------------------------------------------

PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)

RAW_PATH = PROJECT_PATH / "data" / "Raw_Datasets"
CLEAN_PATH = PROJECT_PATH / "data" / "Cleaned_Datasets"

RAW_FILE = RAW_PATH / "medications.csv"
CLEAN_FILE = CLEAN_PATH / "medications_cleaned.csv"

print("Raw file:", RAW_FILE)
print("Cleaned file:", CLEAN_FILE)


# ------------------------------------------------------------
# 2. LOAD DATASET
# ------------------------------------------------------------

medications = pd.read_csv(RAW_FILE)

print("\n========== BASIC INFORMATION ==========")
print("Shape:", medications.shape)
print("\nColumns:")
print(medications.columns.tolist())

print("\nData types:")
print(medications.dtypes)


# ------------------------------------------------------------
# 3. CHECK MISSING VALUES
# ------------------------------------------------------------

print("\n========== MISSING VALUES ==========")

missing_values = medications.isnull().sum()

missing_summary = pd.DataFrame({
    "Missing_Count": missing_values,
    "Missing_Percentage": (
        missing_values / len(medications) * 100
    ).round(2)
})

print(missing_summary[missing_summary["Missing_Count"] > 0])


# ------------------------------------------------------------
# 4. CHECK DUPLICATES
# ------------------------------------------------------------

print("\n========== DUPLICATE CHECK ==========")

duplicate_rows = medications.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)


# ------------------------------------------------------------
# 5. DATE CONVERSION
# ------------------------------------------------------------

print("\n========== DATE CLEANING ==========")

for col in ["START", "STOP"]:
    if col in medications.columns:
        medications[col] = pd.to_datetime(
            medications[col],
            errors="coerce",
            utc=True
        )

        print(f"\n{col}:")
        print("Missing:", medications[col].isna().sum())
        print("Minimum:", medications[col].min())
        print("Maximum:", medications[col].max())


# ------------------------------------------------------------
# 6. VALIDATE DATE ORDER
# ------------------------------------------------------------

if "START" in medications.columns and "STOP" in medications.columns:

    invalid_date_order = (
        medications["STOP"].notna()
        & medications["START"].notna()
        & (medications["STOP"] < medications["START"])
    ).sum()

    print("\nSTOP earlier than START:", invalid_date_order)

    # Display problematic records if any
    if invalid_date_order > 0:
        print("\nRecords with STOP earlier than START:")
        print(
            medications.loc[
                medications["STOP"].notna()
                & medications["START"].notna()
                & (medications["STOP"] < medications["START"])
            ].head(10)
        )


# ------------------------------------------------------------
# 7. FINANCIAL / NUMERIC VALIDATION
# ------------------------------------------------------------

print("\n========== FINANCIAL / NUMERIC VALIDATION ==========")

numeric_columns = [
    "BASE_COST",
    "PAYER_COVERAGE",
    "TOTALCOST",
    "DISPENSES"
]

for col in numeric_columns:

    if col in medications.columns:

        print(f"\n--- {col} ---")

        print("Missing:", medications[col].isna().sum())

        print("Minimum:", medications[col].min())
        print("Maximum:", medications[col].max())
        print("Mean:", medications[col].mean())
        print("Median:", medications[col].median())

        negative_count = (
            medications[col].dropna() < 0
        ).sum()

        print("Negative values:", negative_count)


# ------------------------------------------------------------
# 8. MEDICATION CODE / DESCRIPTION VALIDATION
# ------------------------------------------------------------

print("\n========== MEDICATION INFORMATION ==========")

if "CODE" in medications.columns:
    print("Missing CODE:", medications["CODE"].isna().sum())
    print("Unique medication codes:", medications["CODE"].nunique())

if "DESCRIPTION" in medications.columns:
    print(
        "Missing DESCRIPTION:",
        medications["DESCRIPTION"].isna().sum()
    )
    print(
        "Unique medication descriptions:",
        medications["DESCRIPTION"].nunique()
    )

    print("\nTop 10 medication descriptions:")
    print(
        medications["DESCRIPTION"]
        .value_counts()
        .head(10)
    )


# ------------------------------------------------------------
# 9. REASON INFORMATION
# ------------------------------------------------------------

print("\n========== REASON INFORMATION ==========")

for col in ["REASONCODE", "REASONDESCRIPTION"]:

    if col in medications.columns:

        print(f"\n{col}")
        print("Missing:", medications[col].isna().sum())
        print(
            "Missing percentage:",
            round(
                medications[col].isna().mean() * 100,
                2
            ),
            "%"
        )


# ------------------------------------------------------------
# 10. REFERENCE INTEGRITY CHECK
# ------------------------------------------------------------

print("\n========== REFERENCE INTEGRITY ==========")

# Load cleaned master datasets

patients_clean = pd.read_csv(
    CLEAN_PATH / "patients_cleaned.csv"
)

encounters_clean = pd.read_csv(
    CLEAN_PATH / "encounters_cleaned.csv"
)

payers_clean = pd.read_csv(
    CLEAN_PATH / "payers_cleaned.csv"
)


# PATIENT reference

if "PATIENT" in medications.columns:

    valid_patients = set(
        patients_clean["Id"].astype(str)
    )

    medication_patients = (
        medications["PATIENT"]
        .dropna()
        .astype(str)
    )

    invalid_patients = (
        ~medication_patients.isin(valid_patients)
    ).sum()

    print(
        "Invalid PATIENT references:",
        invalid_patients
    )


# ENCOUNTER reference

if "ENCOUNTER" in medications.columns:

    valid_encounters = set(
        encounters_clean["Id"].astype(str)
    )

    medication_encounters = (
        medications["ENCOUNTER"]
        .dropna()
        .astype(str)
    )

    invalid_encounters = (
        ~medication_encounters.isin(valid_encounters)
    ).sum()

    print(
        "Invalid ENCOUNTER references:",
        invalid_encounters
    )


# PAYER reference

if "PAYER" in medications.columns:

    valid_payers = set(
        payers_clean["Id"].astype(str)
    )

    medication_payers = (
        medications["PAYER"]
        .dropna()
        .astype(str)
    )

    invalid_payers = (
        ~medication_payers.isin(valid_payers)
    ).sum()

    print(
        "Invalid PAYER references:",
        invalid_payers
    )


# ------------------------------------------------------------
# 11. MEDICATIONS PER ENCOUNTER
# ------------------------------------------------------------

print("\n========== MEDICATIONS PER ENCOUNTER ==========")

if "ENCOUNTER" in medications.columns:

    medication_counts = (
        medications.groupby("ENCOUNTER")
        .size()
    )

    print(
        "Mean medications per encounter:",
        medication_counts.mean()
    )

    print(
        "Median medications per encounter:",
        medication_counts.median()
    )

    print(
        "Maximum medications per encounter:",
        medication_counts.max()
    )


# ------------------------------------------------------------
# 12. CHECK FOR NEGATIVE FINANCIAL VALUES
# ------------------------------------------------------------

print("\n========== NEGATIVE VALUE CHECK ==========")

for col in ["BASE_COST", "PAYER_COVERAGE", "TOTALCOST"]:

    if col in medications.columns:

        negative_records = medications[
            medications[col].notna()
            & (medications[col] < 0)
        ]

        print(
            f"{col} negative records:",
            len(negative_records)
        )


# ------------------------------------------------------------
# 13. CLEANING DECISIONS
# ------------------------------------------------------------

print("\n========== CLEANING DECISIONS ==========")

print("""
Cleaning decisions:

1. START and STOP converted to datetime.
2. Missing STOP values are retained because medication
   records may not have a recorded end date.
3. Missing REASONCODE and REASONDESCRIPTION are retained.
4. Financial fields are retained as numeric values.
5. No negative financial values are expected.
6. Valid PATIENT, ENCOUNTER and PAYER references are retained.
7. No rows are deleted solely because of missing optional fields.
8. PAYER_COVERAGE is treated as a monetary field, NOT as a
   payer identifier.
9. Duplicate complete rows, if present, will be removed.
""")


# ------------------------------------------------------------
# 14. REMOVE EXACT DUPLICATE ROWS
# ------------------------------------------------------------

before_duplicates = len(medications)

medications = medications.drop_duplicates().copy()

after_duplicates = len(medications)

print("\n========== DUPLICATE REMOVAL ==========")
print("Rows before:", before_duplicates)
print("Rows after:", after_duplicates)
print("Duplicates removed:", before_duplicates - after_duplicates)


# ------------------------------------------------------------
# 15. FINAL VALIDATION
# ------------------------------------------------------------

print("\n========== FINAL VALIDATION ==========")

print("Final shape:", medications.shape)

print(
    "Duplicate rows:",
    medications.duplicated().sum()
)

if "START" in medications.columns:
    print(
        "Missing START:",
        medications["START"].isna().sum()
    )

if "STOP" in medications.columns:
    print(
        "Missing STOP:",
        medications["STOP"].isna().sum()
    )

if "CODE" in medications.columns:
    print(
        "Missing CODE:",
        medications["CODE"].isna().sum()
    )

if "DESCRIPTION" in medications.columns:
    print(
        "Missing DESCRIPTION:",
        medications["DESCRIPTION"].isna().sum()
    )


# ------------------------------------------------------------
# 16. SAVE CLEANED DATASET
# ------------------------------------------------------------

CLEAN_PATH.mkdir(
    parents=True,
    exist_ok=True
)

medications.to_csv(
    CLEAN_FILE,
    index=False
)

print("\n========== FILE SAVED ==========")
print("Saved successfully to:")
print(CLEAN_FILE)


# ------------------------------------------------------------
# 17. RELOAD AND VERIFY SAVED FILE
# ------------------------------------------------------------

medications_check = pd.read_csv(
    CLEAN_FILE
)

print("\n========== SAVED FILE VERIFICATION ==========")

print("File exists:", CLEAN_FILE.exists())
print("Reloaded shape:", medications_check.shape)
print(
    "Reloaded duplicate rows:",
    medications_check.duplicated().sum()
)

print("\nFinal columns:")
print(medications_check.columns.tolist())

print("\n==============================================")
print("DATASET 10 — MEDICATIONS CLEANED SUCCESSFULLY")
print("==============================================")

Raw file: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Raw_Datasets\medications.csv
Cleaned file: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\medications_cleaned.csv

========== BASIC INFORMATION ==========
Shape: (56430, 13)

Columns:
['START', 'STOP', 'PATIENT', 'PAYER', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'PAYER_COVERAGE', 'DISPENSES', 'TOTALCOST', 'REASONCODE', 'REASONDESCRIPTION']

Data types:
START                    str
STOP                     str
PATIENT                  str
PAYER                    str
ENCOUNTER                str
CODE                   int64
DESCRIPTION              str
BASE_COST            float64
PAYER_COVERAGE       float64
DISPENSES              int64
TOTALCOST            float64
REASONCODE           float64
REASONDESCRIPTION        str
dtype: object

========== MISSING VALUES ==========
                   Missing_Count  Missing_Percentage
STOP                        2713                4.81
REASONCODE                 15471               27.42
REASONDESCRIPTION          15471               27.42

========== DUPLICATE CHECK ==========
Duplicate complete rows: 0

========== DATE CLEANING ==========

START:
Missing: 0
Minimum: 1922-05-22 07:30:25+00:00
Maximum: 2021-11-18 14:01:22+00:00

STOP:
Missing: 2713
Minimum: 1922-08-31 16:46:25+00:00
Maximum: 2021-11-18 15:08:27+00:00

STOP earlier than START: 5

Records with STOP earlier than START:
                          START                      STOP  \
7513  2011-02-27 02:25:00+00:00 2011-02-26 02:25:00+00:00
7514  2011-02-27 02:25:00+00:00 2011-02-26 02:25:00+00:00
7515  2011-02-27 02:25:00+00:00 2011-02-26 02:25:00+00:00
7516  2011-02-27 02:25:00+00:00 2011-02-26 02:25:00+00:00
39293 2014-02-18 06:29:35+00:00 2014-02-11 19:34:38+00:00

                                    PATIENT  \
7513   859e5c6f-f1db-308d-0e33-57d392c1bf04
7514   859e5c6f-f1db-308d-0e33-57d392c1bf04
7515   859e5c6f-f1db-308d-0e33-57d392c1bf04
7516   859e5c6f-f1db-308d-0e33-57d392c1bf04
39293  d25c159a-033b-593f-dbbf-b1e9de3b2fc4

                                      PAYER  \
7513   5059a55e-5d6e-34d1-b6cb-d83d16e57bcf
7514   5059a55e-5d6e-34d1-b6cb-d83d16e57bcf
7515   5059a55e-5d6e-34d1-b6cb-d83d16e57bcf
7516   5059a55e-5d6e-34d1-b6cb-d83d16e57bcf
39293  7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a

                                  ENCOUNTER    CODE  \
7513   53f74a12-0a01-fa9a-d47c-e313a7cf39cd  309362
7514   53f74a12-0a01-fa9a-d47c-e313a7cf39cd  312961
7515   53f74a12-0a01-fa9a-d47c-e313a7cf39cd  197361
7516   53f74a12-0a01-fa9a-d47c-e313a7cf39cd  705129
39293  b56495c7-4fb0-1de0-7bc1-5f85cba730df  206905

                                     DESCRIPTION  BASE_COST  PAYER_COVERAGE  \
7513               Clopidogrel 75 MG Oral Tablet      66.93            0.00
7514               Simvastatin 20 MG Oral Tablet      16.66            0.00
7515                 Amlodipine 5 MG Oral Tablet      36.26            0.00
7516   Nitroglycerin 0.4 MG/ACTUAT Mucosal Spray     262.03            0.00
39293         Ibuprofen 400 MG Oral Tablet [Ibu]     263.49          193.32

       DISPENSES  TOTALCOST  REASONCODE REASONDESCRIPTION
7513           1      66.93         NaN               NaN
7514           1      16.66         NaN               NaN
7515           1      36.26         NaN               NaN
7516           1     262.03         NaN               NaN
39293          3     790.47         NaN               NaN

========== FINANCIAL / NUMERIC VALIDATION ==========

--- BASE_COST ---
Missing: 0
Minimum: 0.01
Maximum: 7011.48
Mean: 194.01243629275206
Median: 18.14
Negative values: 0

--- PAYER_COVERAGE ---
Missing: 0
Minimum: 0.0
Maximum: 6546.4
Mean: 32.706898281056176
Median: 0.0
Negative values: 0

--- TOTALCOST ---
Missing: 0
Minimum: 0.01
Maximum: 2197449.71
Mean: 1309.7255436824385
Median: 35.27
Negative values: 0

--- DISPENSES ---
Missing: 0
Minimum: 1
Maximum: 8469
Mean: 82.15176324650008
Median: 12.0
Negative values: 0

========== MEDICATION INFORMATION ==========
Missing CODE: 0
Unique medication codes: 170
Missing DESCRIPTION: 0
Unique medication descriptions: 176

Top 10 medication descriptions:
DESCRIPTION
lisinopril 10 MG Oral Tablet                                                                            8166
Hydrochlorothiazide 25 MG Oral Tablet                                                                   7509
amLODIPine 2.5 MG Oral Tablet                                                                           5942
insulin human  isophane 70 UNT/ML / Regular Insulin  Human 30 UNT/ML Injectable Suspension [Humulin]    4068
24 HR Metformin hydrochloride 500 MG Extended Release Oral Tablet                                       2996
Simvastatin 10 MG Oral Tablet                                                                           2489
NDA020503 200 ACTUAT Albuterol 0.09 MG/ACTUAT Metered Dose Inhaler                                      2341
120 ACTUAT Fluticasone propionate 0.044 MG/ACTUAT Metered Dose Inhaler                                  2337
Nitroglycerin 0.4 MG/ACTUAT Mucosal Spray                                                               1635
Simvastatin 20 MG Oral Tablet                                                                           1335
Name: count, dtype: int64

========== REASON INFORMATION ==========

REASONCODE
Missing: 15471
Missing percentage: 27.42 %

REASONDESCRIPTION
Missing: 15471
Missing percentage: 27.42 %

========== REFERENCE INTEGRITY ==========
Invalid PATIENT references: 0
Invalid ENCOUNTER references: 0
Invalid PAYER references: 0

========== MEDICATIONS PER ENCOUNTER ==========
Mean medications per encounter: 2.100033493357151
Median medications per encounter: 2.0
Maximum medications per encounter: 13

========== NEGATIVE VALUE CHECK ==========
BASE_COST negative records: 0
PAYER_COVERAGE negative records: 0
TOTALCOST negative records: 0

========== CLEANING DECISIONS ==========

Cleaning decisions:

1. START and STOP converted to datetime.
2. Missing STOP values are retained because medication
   records may not have a recorded end date.
3. Missing REASONCODE and REASONDESCRIPTION are retained.
4. Financial fields are retained as numeric values.
5. No negative financial values are expected.
6. Valid PATIENT, ENCOUNTER and PAYER references are retained.
7. No rows are deleted solely because of missing optional fields.
8. PAYER_COVERAGE is treated as a monetary field, NOT as a
   payer identifier.
9. Duplicate complete rows, if present, will be removed.


========== DUPLICATE REMOVAL ==========
Rows before: 56430
Rows after: 56430
Duplicates removed: 0

========== FINAL VALIDATION ==========
Final shape: (56430, 13)
Duplicate rows: 0
Missing START: 0
Missing STOP: 2713
Missing CODE: 0
Missing DESCRIPTION: 0

========== FILE SAVED ==========
Saved successfully to:
C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\medications_cleaned.csv

========== SAVED FILE VERIFICATION ==========
File exists: True
Reloaded shape: (56430, 13)
Reloaded duplicate rows: 0

Final columns:
['START', 'STOP', 'PATIENT', 'PAYER', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'PAYER_COVERAGE', 'DISPENSES', 'TOTALCOST', 'REASONCODE', 'REASONDESCRIPTION']

==============================================
DATASET 10 — MEDICATIONS CLEANED SUCCESSFULLY
==============================================

In [59]:
# ============================================================
# DATASET 10 — FIX INVALID STOP DATES
# ============================================================

# Identify records where STOP is earlier than START
invalid_stop_mask = (
    medications["STOP"].notna()
    & medications["START"].notna()
    & (medications["STOP"] < medications["START"])
)

print("Invalid STOP dates found:", invalid_stop_mask.sum())

# Set only the invalid STOP dates to missing
medications.loc[invalid_stop_mask, "STOP"] = pd.NaT

print(
    "Invalid STOP dates converted to missing:",
    invalid_stop_mask.sum()
)

# Verify date order
remaining_invalid_dates = (
    medications["STOP"].notna()
    & medications["START"].notna()
    & (medications["STOP"] < medications["START"])
).sum()

print(
    "Remaining STOP earlier than START:",
    remaining_invalid_dates
)

print(
    "Final missing STOP:",
    medications["STOP"].isna().sum()
)

# Save corrected dataset
medications.to_csv(
    CLEAN_FILE,
    index=False
)

# Reload and verify
medications_check = pd.read_csv(CLEAN_FILE)

print("\n========== FINAL FILE VERIFICATION ==========")
print("File exists:", CLEAN_FILE.exists())
print("Final shape:", medications_check.shape)
print("Duplicate rows:", medications_check.duplicated().sum())
print("Final missing STOP:", medications_check["STOP"].isna().sum())

print("\n==============================================")
print("DATASET 10 — DATE ISSUE FIXED AND FILE SAVED")
print("==============================================")

Invalid STOP dates found: 5
Invalid STOP dates converted to missing: 5
Remaining STOP earlier than START: 0
Final missing STOP: 2718

========== FINAL FILE VERIFICATION ==========
File exists: True
Final shape: (56430, 13)
Duplicate rows: 0
Final missing STOP: 2718

==============================================
DATASET 10 — DATE ISSUE FIXED AND FILE SAVED
==============================================

In [60]:
# ============================================================
# DATASET 11 — OBSERVATIONS.CSV
# Data Cleaning & Preparation
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ------------------------------------------------------------
# 1. PATHS
# ------------------------------------------------------------

PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)

RAW_PATH = PROJECT_PATH / "data" / "Raw_Datasets"
CLEAN_PATH = PROJECT_PATH / "data" / "Cleaned_Datasets"

RAW_FILE = RAW_PATH / "observations.csv"
CLEAN_FILE = CLEAN_PATH / "observations_cleaned.csv"

print("Raw file:", RAW_FILE)
print("Cleaned file:", CLEAN_FILE)


# ------------------------------------------------------------
# 2. LOAD DATASET
# ------------------------------------------------------------

observations = pd.read_csv(RAW_FILE)

print("\n========== BASIC INFORMATION ==========")
print("Shape:", observations.shape)

print("\nColumns:")
print(observations.columns.tolist())

print("\nData types:")
print(observations.dtypes)


# ------------------------------------------------------------
# 3. MISSING VALUES
# ------------------------------------------------------------

print("\n========== MISSING VALUES ==========")

missing_values = observations.isnull().sum()

missing_summary = pd.DataFrame({
    "Missing_Count": missing_values,
    "Missing_Percentage": (
        missing_values / len(observations) * 100
    ).round(2)
})

print(
    missing_summary[
        missing_summary["Missing_Count"] > 0
    ]
)


# ------------------------------------------------------------
# 4. DUPLICATE CHECK
# ------------------------------------------------------------

print("\n========== DUPLICATE CHECK ==========")

duplicate_rows = observations.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)


# ------------------------------------------------------------
# 5. DATE CONVERSION
# ------------------------------------------------------------

print("\n========== DATE CLEANING ==========")

for col in ["DATE"]:

    if col in observations.columns:

        observations[col] = pd.to_datetime(
            observations[col],
            errors="coerce",
            utc=True
        )

        print(f"\n{col}:")
        print("Missing:", observations[col].isna().sum())
        print("Minimum:", observations[col].min())
        print("Maximum:", observations[col].max())


# ------------------------------------------------------------
# 6. VALUE VALIDATION
# ------------------------------------------------------------

print("\n========== OBSERVATION VALUE VALIDATION ==========")

if "VALUE" in observations.columns:

    print("\nVALUE data type:")
    print(observations["VALUE"].dtype)

    print("\nMissing VALUE:")
    print(observations["VALUE"].isna().sum())

    print("\nVALUE summary:")
    print(observations["VALUE"].describe())

    print("\nUnique VALUE entries:")
    print(observations["VALUE"].nunique())


# ------------------------------------------------------------
# 7. UNIT VALIDATION
# ------------------------------------------------------------

print("\n========== UNIT VALIDATION ==========")

if "UNITS" in observations.columns:

    print("Missing UNITS:")
    print(observations["UNITS"].isna().sum())

    print(
        "\nUnique units:",
        observations["UNITS"].nunique()
    )

    print("\nTop units:")
    print(
        observations["UNITS"]
        .value_counts(dropna=False)
        .head(20)
    )


# ------------------------------------------------------------
# 8. OBSERVATION CODE / DESCRIPTION
# ------------------------------------------------------------

print("\n========== OBSERVATION INFORMATION ==========")

if "CODE" in observations.columns:

    print("Missing CODE:")
    print(observations["CODE"].isna().sum())

    print(
        "Unique observation codes:",
        observations["CODE"].nunique()
    )


if "DESCRIPTION" in observations.columns:

    print("\nMissing DESCRIPTION:")
    print(observations["DESCRIPTION"].isna().sum())

    print(
        "Unique observation descriptions:",
        observations["DESCRIPTION"].nunique()
    )

    print("\nTop 15 observation descriptions:")

    print(
        observations["DESCRIPTION"]
        .value_counts()
        .head(15)
    )


# ------------------------------------------------------------
# 9. REFERENCE INTEGRITY
# ------------------------------------------------------------

print("\n========== REFERENCE INTEGRITY ==========")

patients_clean = pd.read_csv(
    CLEAN_PATH / "patients_cleaned.csv"
)

encounters_clean = pd.read_csv(
    CLEAN_PATH / "encounters_cleaned.csv"
)


# PATIENT reference

if "PATIENT" in observations.columns:

    valid_patients = set(
        patients_clean["Id"].astype(str)
    )

    observation_patients = (
        observations["PATIENT"]
        .dropna()
        .astype(str)
    )

    invalid_patients = (
        ~observation_patients.isin(valid_patients)
    ).sum()

    print(
        "Invalid PATIENT references:",
        invalid_patients
    )


# ENCOUNTER reference

if "ENCOUNTER" in observations.columns:

    valid_encounters = set(
        encounters_clean["Id"].astype(str)
    )

    observation_encounters = (
        observations["ENCOUNTER"]
        .dropna()
        .astype(str)
    )

    invalid_encounters = (
        ~observation_encounters.isin(valid_encounters)
    ).sum()

    print(
        "Invalid ENCOUNTER references:",
        invalid_encounters
    )


# ------------------------------------------------------------
# 10. OBSERVATIONS PER ENCOUNTER
# ------------------------------------------------------------

print("\n========== OBSERVATIONS PER ENCOUNTER ==========")

if "ENCOUNTER" in observations.columns:

    observation_counts = (
        observations
        .groupby("ENCOUNTER")
        .size()
    )

    print(
        "Mean observations per encounter:",
        observation_counts.mean()
    )

    print(
        "Median observations per encounter:",
        observation_counts.median()
    )

    print(
        "Maximum observations per encounter:",
        observation_counts.max()
    )


# ------------------------------------------------------------
# 11. PATIENT-LEVEL OBSERVATION COUNTS
# ------------------------------------------------------------

print("\n========== OBSERVATIONS PER PATIENT ==========")

if "PATIENT" in observations.columns:

    patient_observation_counts = (
        observations
        .groupby("PATIENT")
        .size()
    )

    print(
        "Mean observations per patient:",
        patient_observation_counts.mean()
    )

    print(
        "Median observations per patient:",
        patient_observation_counts.median()
    )

    print(
        "Maximum observations per patient:",
        patient_observation_counts.max()
    )


# ------------------------------------------------------------
# 12. CHECK FOR NUMERIC VALUE ISSUES
# ------------------------------------------------------------

print("\n========== NUMERIC VALUE CHECK ==========")

if "VALUE" in observations.columns:

    numeric_value = pd.to_numeric(
        observations["VALUE"],
        errors="coerce"
    )

    conversion_failures = (
        observations["VALUE"].notna()
        & numeric_value.isna()
    ).sum()

    print(
        "Values that could not be interpreted as numeric:",
        conversion_failures
    )

    if conversion_failures == 0:

        print(
            "Negative numeric values:",
            (numeric_value < 0).sum()
        )

        print(
            "Zero numeric values:",
            (numeric_value == 0).sum()
        )


# ------------------------------------------------------------
# 13. CLEANING DECISIONS
# ------------------------------------------------------------

print("\n========== CLEANING DECISIONS ==========")

print("""
Cleaning decisions:

1. DATE is converted to datetime.
2. Missing observation values are retained unless
   they represent an invalid record.
3. Observation codes and descriptions are retained.
4. Units are retained because they provide context
   for observation values.
5. Patient and encounter references are validated.
6. Exact duplicate rows are removed if present.
7. Observation records are not directly joined to
   encounter-level data without aggregation because
   multiple observations can belong to one encounter.
""")


# ------------------------------------------------------------
# 14. REMOVE EXACT DUPLICATE ROWS
# ------------------------------------------------------------

before_duplicates = len(observations)

observations = observations.drop_duplicates().copy()

after_duplicates = len(observations)

print("\n========== DUPLICATE REMOVAL ==========")

print("Rows before:", before_duplicates)
print("Rows after:", after_duplicates)
print(
    "Duplicates removed:",
    before_duplicates - after_duplicates
)


# ------------------------------------------------------------
# 15. FINAL VALIDATION
# ------------------------------------------------------------

print("\n========== FINAL VALIDATION ==========")

print("Final shape:", observations.shape)

print(
    "Duplicate rows:",
    observations.duplicated().sum()
)

if "DATE" in observations.columns:

    print(
        "Missing DATE:",
        observations["DATE"].isna().sum()
    )

if "PATIENT" in observations.columns:

    print(
        "Missing PATIENT:",
        observations["PATIENT"].isna().sum()
    )

if "ENCOUNTER" in observations.columns:

    print(
        "Missing ENCOUNTER:",
        observations["ENCOUNTER"].isna().sum()
    )

if "CODE" in observations.columns:

    print(
        "Missing CODE:",
        observations["CODE"].isna().sum()
    )

if "DESCRIPTION" in observations.columns:

    print(
        "Missing DESCRIPTION:",
        observations["DESCRIPTION"].isna().sum()
    )


# ------------------------------------------------------------
# 16. SAVE CLEANED DATASET
# ------------------------------------------------------------

CLEAN_PATH.mkdir(
    parents=True,
    exist_ok=True
)

observations.to_csv(
    CLEAN_FILE,
    index=False
)

print("\n========== FILE SAVED ==========")

print("Saved successfully to:")
print(CLEAN_FILE)


# ------------------------------------------------------------
# 17. RELOAD AND VERIFY
# ------------------------------------------------------------

observations_check = pd.read_csv(
    CLEAN_FILE
)

print("\n========== SAVED FILE VERIFICATION ==========")

print(
    "File exists:",
    CLEAN_FILE.exists()
)

print(
    "Reloaded shape:",
    observations_check.shape
)

print(
    "Reloaded duplicate rows:",
    observations_check.duplicated().sum()
)

print("\nFinal columns:")
print(observations_check.columns.tolist())


print("\n==============================================")
print("DATASET 11 — OBSERVATIONS CLEANED SUCCESSFULLY")
print("==============================================")

Raw file: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Raw_Datasets\observations.csv
Cleaned file: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\observations_cleaned.csv

========== BASIC INFORMATION ==========
Shape: (531144, 9)

Columns:
['DATE', 'PATIENT', 'ENCOUNTER', 'CATEGORY', 'CODE', 'DESCRIPTION', 'VALUE', 'UNITS', 'TYPE']

Data types:
DATE           str
PATIENT        str
ENCOUNTER      str
CATEGORY       str
CODE           str
DESCRIPTION    str
VALUE          str
UNITS          str
TYPE           str
dtype: object

========== MISSING VALUES ==========
           Missing_Count  Missing_Percentage
ENCOUNTER          31662                5.96
CATEGORY           31662                5.96
UNITS             185017               34.83

========== DUPLICATE CHECK ==========
Duplicate complete rows: 249

========== DATE CLEANING ==========

DATE:
Missing: 0
Minimum: 1932-06-21 11:58:49+00:00
Maximum: 2021-11-19 07:15:57+00:00

========== OBSERVATION VALUE VALIDATION ==========

VALUE data type:
str

Missing VALUE:
0

VALUE summary:
count     531144
unique      6804
top           No
freq       63663
Name: VALUE, dtype: object

Unique VALUE entries:
6804

========== UNIT VALIDATION ==========
Missing UNITS:
185017

Unique units: 43

Top units:
UNITS
NaN          185017
mg/dL         53791
{score}       49301
mm[Hg]        29125
mmol/L        27794
/min          26028
a             21108
%             15814
cm            14358
kg            14354
kg/m2         11571
fL            11212
g/dL          10829
{#}           10737
/a             8886
10*3/uL        7584
U/L            7001
{nominal}      6581
10*6/uL        3166
pg             3162
Name: count, dtype: int64

========== OBSERVATION INFORMATION ==========
Missing CODE:
0
Unique observation codes: 234

Missing DESCRIPTION:
0
Unique observation descriptions: 247

Top 15 observation descriptions:
DESCRIPTION
Pain severity - 0-10 verbal numeric rating [Score] - Reported            14537
Diastolic Blood Pressure                                                 14467
Systolic Blood Pressure                                                  14467
Body Weight                                                              13275
Heart rate                                                               13014
Respiratory rate                                                         13014
Body Height                                                              12699
Tobacco smoking status NHIS                                              12666
Body Mass Index                                                          11571
QALY                                                                     10554
DALY                                                                     10554
QOLS                                                                     10554
In the past year  have you been afraid of your partner or ex-partner?     8886
Do you feel physically and emotionally safe where you currently live?     8886
Are you a refugee?                                                        8886
Name: count, dtype: int64

========== REFERENCE INTEGRITY ==========
Invalid PATIENT references: 0
Invalid ENCOUNTER references: 0

========== OBSERVATIONS PER ENCOUNTER ==========
Mean observations per encounter: 23.756575505350774
Median observations per encounter: 20.0
Maximum observations per encounter: 678

========== OBSERVATIONS PER PATIENT ==========
Mean observations per patient: 456.7016337059329
Median observations per patient: 362.0
Maximum observations per patient: 9297

========== NUMERIC VALUE CHECK ==========
Values that could not be interpreted as numeric: 191092

========== CLEANING DECISIONS ==========

Cleaning decisions:

1. DATE is converted to datetime.
2. Missing observation values are retained unless
   they represent an invalid record.
3. Observation codes and descriptions are retained.
4. Units are retained because they provide context
   for observation values.
5. Patient and encounter references are validated.
6. Exact duplicate rows are removed if present.
7. Observation records are not directly joined to
   encounter-level data without aggregation because
   multiple observations can belong to one encounter.


========== DUPLICATE REMOVAL ==========
Rows before: 531144
Rows after: 530895
Duplicates removed: 249

========== FINAL VALIDATION ==========
Final shape: (530895, 9)
Duplicate rows: 0
Missing DATE: 0
Missing PATIENT: 0
Missing ENCOUNTER: 31662
Missing CODE: 0
Missing DESCRIPTION: 0

========== FILE SAVED ==========
Saved successfully to:
C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\observations_cleaned.csv

========== SAVED FILE VERIFICATION ==========
File exists: True
Reloaded shape: (530895, 9)
Reloaded duplicate rows: 0

Final columns:
['DATE', 'PATIENT', 'ENCOUNTER', 'CATEGORY', 'CODE', 'DESCRIPTION', 'VALUE', 'UNITS', 'TYPE']

==============================================
DATASET 11 — OBSERVATIONS CLEANED SUCCESSFULLY
==============================================

In [65]:
# ============================================================
# DATASET 12 — IMMUNIZATIONS
# Data Cleaning & Preparation
# ============================================================

import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# 1. Load dataset
# ------------------------------------------------------------

file_path = RAW_PATH / "immunizations.csv"

immunizations = pd.read_csv(file_path)

print("========== IMMUNIZATIONS DATASET ==========")
print("Raw Shape:", immunizations.shape)
print("\nColumns:")
print(immunizations.columns.tolist())

# ------------------------------------------------------------
# 2. Basic information
# ------------------------------------------------------------

print("\n========== DATA TYPES ==========")
print(immunizations.dtypes)

print("\n========== FIRST 5 ROWS ==========")
display(immunizations.head())

# ------------------------------------------------------------
# 3. Missing value analysis
# ------------------------------------------------------------

print("\n========== MISSING VALUES ==========")

missing = pd.DataFrame({
    "Missing_Count": immunizations.isna().sum(),
    "Missing_Percentage": (
        immunizations.isna().mean() * 100
    ).round(2)
})

display(missing[missing["Missing_Count"] > 0])

# ------------------------------------------------------------
# 4. Duplicate analysis
# ------------------------------------------------------------

print("\n========== DUPLICATE ANALYSIS ==========")

duplicate_rows = immunizations.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)

# ------------------------------------------------------------
# 5. Date column analysis
# ------------------------------------------------------------

print("\n========== DATE ANALYSIS ==========")

print("DATE datatype before conversion:",
      immunizations["DATE"].dtype)

immunizations["DATE"] = pd.to_datetime(
    immunizations["DATE"],
    errors="coerce",
    utc=True
)

print("DATE datatype after conversion:",
      immunizations["DATE"].dtype)

print("Missing DATE after conversion:",
      immunizations["DATE"].isna().sum())

print("Minimum DATE:",
      immunizations["DATE"].min())

print("Maximum DATE:",
      immunizations["DATE"].max())

# ------------------------------------------------------------
# 6. Important categorical columns
# ------------------------------------------------------------

for col in ["CODE", "DESCRIPTION"]:
    if col in immunizations.columns:
        print(f"\n========== {col} ANALYSIS ==========")
        print("Unique values:", immunizations[col].nunique())
        print("Missing values:", immunizations[col].isna().sum())

        print("\nTop 10 values:")
        display(
            immunizations[col]
            .value_counts(dropna=False)
            .head(10)
        )

# ------------------------------------------------------------
# 7. Patient reference validation
# ------------------------------------------------------------

print("\n========== PATIENT REFERENCE VALIDATION ==========")

patients_clean_path = CLEAN_PATH / "patients_cleaned.csv"

if patients_clean_path.exists():

    patients_cleaned = pd.read_csv(
        patients_clean_path,
        usecols=["Id"]
    )

    valid_patient_ids = set(
        patients_cleaned["Id"].astype(str)
    )

    immunization_patient_ids = set(
        immunizations["PATIENT"]
        .dropna()
        .astype(str)
    )

    invalid_patient_ids = (
        immunization_patient_ids - valid_patient_ids
    )

    invalid_patient_rows = immunizations[
        immunizations["PATIENT"].notna()
        &
        ~immunizations["PATIENT"].astype(str).isin(valid_patient_ids)
    ]

    print("Unique patient IDs in immunizations:",
          len(immunization_patient_ids))

    print("Invalid patient IDs:",
          len(invalid_patient_ids))

    print("Rows with invalid patient references:",
          len(invalid_patient_rows))

else:
    print("patients_cleaned.csv not found.")

# ------------------------------------------------------------
# 8. Encounter reference validation
# ------------------------------------------------------------

print("\n========== ENCOUNTER REFERENCE VALIDATION ==========")

encounters_clean_path = CLEAN_PATH / "encounters_cleaned.csv"

if encounters_clean_path.exists():

    encounters_cleaned = pd.read_csv(
        encounters_clean_path,
        usecols=["Id"]
    )

    valid_encounter_ids = set(
        encounters_cleaned["Id"].astype(str)
    )

    immunization_encounter_ids = set(
        immunizations["ENCOUNTER"]
        .dropna()
        .astype(str)
    )

    invalid_encounter_ids = (
        immunization_encounter_ids - valid_encounter_ids
    )

    invalid_encounter_rows = immunizations[
        immunizations["ENCOUNTER"].notna()
        &
        ~immunizations["ENCOUNTER"].astype(str).isin(
            valid_encounter_ids
        )
    ]

    print("Unique encounter IDs in immunizations:",
          len(immunization_encounter_ids))

    print("Invalid encounter IDs:",
          len(invalid_encounter_ids))

    print("Rows with invalid encounter references:",
          len(invalid_encounter_rows))

else:
    print("encounters_cleaned.csv not found.")

# ------------------------------------------------------------
# 9. Utilization analysis
# ------------------------------------------------------------

print("\n========== UTILIZATION ANALYSIS ==========")

print("Unique patients:",
      immunizations["PATIENT"].nunique())

print("Unique encounters:",
      immunizations["ENCOUNTER"].nunique())

print("\nImmunizations per patient:")
display(
    immunizations.groupby("PATIENT").size()
    .describe()
)

print("\nImmunizations per encounter:")
display(
    immunizations.groupby("ENCOUNTER").size()
    .describe()
)

# ------------------------------------------------------------
# 10. Financial / quantity columns if available
# ------------------------------------------------------------

print("\n========== NUMERIC COLUMN ANALYSIS ==========")

numeric_columns = immunizations.select_dtypes(
    include="number"
).columns.tolist()

print("Numeric columns:", numeric_columns)

for col in numeric_columns:

    print(f"\n--- {col} ---")

    print(
        immunizations[col].describe()
    )

    print(
        "Negative values:",
        (immunizations[col] < 0).sum()
    )

# ------------------------------------------------------------
# 11. Remove exact duplicate rows
# ------------------------------------------------------------

print("\n========== DUPLICATE REMOVAL ==========")

rows_before = len(immunizations)

immunizations_cleaned = (
    immunizations
    .drop_duplicates()
    .copy()
)

rows_after = len(immunizations_cleaned)

print("Rows before:", rows_before)
print("Rows after:", rows_after)
print("Duplicates removed:",
      rows_before - rows_after)

# ------------------------------------------------------------
# 12. Final validation
# ------------------------------------------------------------

print("\n========== FINAL VALIDATION ==========")

print("Final shape:",
      immunizations_cleaned.shape)

print("Duplicate rows:",
      immunizations_cleaned.duplicated().sum())

print("Missing DATE:",
      immunizations_cleaned["DATE"].isna().sum())

print("Missing PATIENT:",
      immunizations_cleaned["PATIENT"].isna().sum())

print("Missing ENCOUNTER:",
      immunizations_cleaned["ENCOUNTER"].isna().sum())

print("Missing CODE:",
      immunizations_cleaned["CODE"].isna().sum())

print("Missing DESCRIPTION:",
      immunizations_cleaned["DESCRIPTION"].isna().sum())

# ------------------------------------------------------------
# 13. Save cleaned dataset
# ------------------------------------------------------------

output_path = CLEAN_PATH / "immunizations_cleaned.csv"

immunizations_cleaned.to_csv(
    output_path,
    index=False
)

print("\n========== FILE SAVED ==========")
print("Saved to:", output_path)
print("File exists:", output_path.exists())

# ------------------------------------------------------------
# 14. Reload verification
# ------------------------------------------------------------

verification = pd.read_csv(output_path)

print("\n========== RELOAD VERIFICATION ==========")

print("Reloaded shape:",
      verification.shape)

print("Reloaded duplicate rows:",
      verification.duplicated().sum())

print("\nDATASET 12 — IMMUNIZATIONS CLEANING COMPLETED")

========== IMMUNIZATIONS DATASET ==========
Raw Shape: (17009, 6)

Columns:
['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST']

========== DATA TYPES ==========
DATE               str
PATIENT            str
ENCOUNTER          str
CODE             int64
DESCRIPTION        str
BASE_COST      float64
dtype: object

========== FIRST 5 ROWS ==========

,DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST
0,2019-02-17T05:07:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,748f8357-6cc7-551d-f31a-32fa2cf84126,8,Hep B adolescent or pediatric,140.52
1,2019-03-24T05:07:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,5a4735ae-423f-6563-28ab-b3d11b49b2d4,8,Hep B adolescent or pediatric,140.52
2,2019-05-26T05:07:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,49,Hib (PRP-OMP),140.52
3,2019-05-26T05:07:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,119,rotavirus monovalent,140.52
4,2019-05-26T05:07:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,10,IPV,140.52

========== MISSING VALUES ==========

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

========== DUPLICATE ANALYSIS ==========
Duplicate complete rows: 0

========== DATE ANALYSIS ==========
DATE datatype before conversion: str
DATE datatype after conversion: datetime64[us, UTC]
Missing DATE after conversion: 0
Minimum DATE: 1945-03-31 10:04:43+00:00
Maximum DATE: 2021-11-18 10:36:25+00:00

========== CODE ANALYSIS ==========
Unique values: 21
Missing values: 0

Top 10 values:

CODE
140    9538
113     815
208     725
20      604
133     559
207     533
10      500
62      438
114     432
49      360
Name: count, dtype: int64

========== DESCRIPTION ANALYSIS ==========
Unique values: 21
Missing values: 0

Top 10 values:

DESCRIPTION
Influenza  seasonal  injectable  preservative free                                                9538
Td (adult) preservative free                                                                       815
SARS-COV-2 (COVID-19) vaccine  mRNA  spike protein  LNP  preservative free  30 mcg/0.3mL dose      725
DTaP                                                                                               604
Pneumococcal conjugate PCV 13                                                                      559
SARS-COV-2 (COVID-19) vaccine  mRNA  spike protein  LNP  preservative free  100 mcg/0.5mL dose     533
IPV                                                                                                500
HPV  quadrivalent                                                                                  438
meningococcal MCV4P                                                                                432
Hib (PRP-OMP)                                                                                      360
Name: count, dtype: int64

========== PATIENT REFERENCE VALIDATION ==========
Unique patient IDs in immunizations: 1158
Invalid patient IDs: 0
Rows with invalid patient references: 0

========== ENCOUNTER REFERENCE VALIDATION ==========
Unique encounter IDs in immunizations: 11796
Invalid encounter IDs: 0
Rows with invalid encounter references: 0

========== UTILIZATION ANALYSIS ==========
Unique patients: 1158
Unique encounters: 11796

Immunizations per patient:

count    1158.000000
mean       14.688256
std         6.270926
min         1.000000
25%        11.000000
50%        13.000000
75%        16.000000
max        36.000000
dtype: float64

Immunizations per encounter:

count    11796.000000
mean         1.441929
std          1.018407
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          5.000000
dtype: float64

========== NUMERIC COLUMN ANALYSIS ==========
Numeric columns: ['CODE', 'BASE_COST']

--- CODE ---
count    17009.000000
mean       118.944559
std         50.794039
min          3.000000
25%        113.000000
50%        140.000000
75%        140.000000
max        212.000000
Name: CODE, dtype: float64
Negative values: 0

--- BASE_COST ---
count    1.700900e+04
mean     1.405200e+02
std      2.842254e-14
min      1.405200e+02
25%      1.405200e+02
50%      1.405200e+02
75%      1.405200e+02
max      1.405200e+02
Name: BASE_COST, dtype: float64
Negative values: 0

========== DUPLICATE REMOVAL ==========
Rows before: 17009
Rows after: 17009
Duplicates removed: 0

========== FINAL VALIDATION ==========
Final shape: (17009, 6)
Duplicate rows: 0
Missing DATE: 0
Missing PATIENT: 0
Missing ENCOUNTER: 0
Missing CODE: 0
Missing DESCRIPTION: 0

========== FILE SAVED ==========
Saved to: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\immunizations_cleaned.csv
File exists: True

========== RELOAD VERIFICATION ==========
Reloaded shape: (17009, 6)
Reloaded duplicate rows: 0

DATASET 12 — IMMUNIZATIONS CLEANING COMPLETED

In [66]:
# ============================================================
# DATASET 13 — PAYER TRANSITIONS
# Data Cleaning & Preparation
# ============================================================

import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# 1. Load dataset
# ------------------------------------------------------------

file_path = RAW_PATH / "payer_transitions.csv"

payer_transitions = pd.read_csv(file_path)

print("========== PAYER TRANSITIONS DATASET ==========")
print("Raw Shape:", payer_transitions.shape)

print("\nColumns:")
print(payer_transitions.columns.tolist())

# ------------------------------------------------------------
# 2. Data types
# ------------------------------------------------------------

print("\n========== DATA TYPES ==========")
print(payer_transitions.dtypes)

# ------------------------------------------------------------
# 3. First rows
# ------------------------------------------------------------

print("\n========== FIRST 5 ROWS ==========")
display(payer_transitions.head())

# ------------------------------------------------------------
# 4. Missing value analysis
# ------------------------------------------------------------

print("\n========== MISSING VALUES ==========")

missing = pd.DataFrame({
    "Missing_Count": payer_transitions.isna().sum(),
    "Missing_Percentage": (
        payer_transitions.isna().mean() * 100
    ).round(2)
})

display(
    missing[missing["Missing_Count"] > 0]
)

# ------------------------------------------------------------
# 5. Duplicate analysis
# ------------------------------------------------------------

print("\n========== DUPLICATE ANALYSIS ==========")

duplicate_rows = payer_transitions.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)

# ------------------------------------------------------------
# 6. Date analysis
# ------------------------------------------------------------

print("\n========== DATE ANALYSIS ==========")

date_columns = [
    col for col in payer_transitions.columns
    if col.upper() in ["START", "STOP", "DATE"]
    or "DATE" in col.upper()
]

print("Detected date columns:", date_columns)

for col in date_columns:

    payer_transitions[col] = pd.to_datetime(
        payer_transitions[col],
        errors="coerce",
        utc=True
    )

    print(f"\n--- {col} ---")
    print("Datatype:", payer_transitions[col].dtype)
    print("Missing:", payer_transitions[col].isna().sum())
    print("Minimum:", payer_transitions[col].min())
    print("Maximum:", payer_transitions[col].max())

# ------------------------------------------------------------
# 7. Categorical / identifier analysis
# ------------------------------------------------------------

print("\n========== COLUMN VALUE ANALYSIS ==========")

for col in payer_transitions.columns:

    print(f"\n--- {col} ---")
    print("Unique values:", payer_transitions[col].nunique())
    print("Missing values:", payer_transitions[col].isna().sum())

    # Show top values for non-date columns
    if col not in date_columns:
        print("Top 10 values:")
        display(
            payer_transitions[col]
            .value_counts(dropna=False)
            .head(10)
        )

# ------------------------------------------------------------
# 8. Patient reference validation
# ------------------------------------------------------------

print("\n========== PATIENT REFERENCE VALIDATION ==========")

if "PATIENT" in payer_transitions.columns:

    patients_clean_path = CLEAN_PATH / "patients_cleaned.csv"

    if patients_clean_path.exists():

        patients_cleaned = pd.read_csv(
            patients_clean_path,
            usecols=["Id"]
        )

        valid_patient_ids = set(
            patients_cleaned["Id"].astype(str)
        )

        transition_patient_ids = set(
            payer_transitions["PATIENT"]
            .dropna()
            .astype(str)
        )

        invalid_patient_ids = (
            transition_patient_ids - valid_patient_ids
        )

        invalid_patient_rows = payer_transitions[
            payer_transitions["PATIENT"].notna()
            &
            ~payer_transitions["PATIENT"]
            .astype(str)
            .isin(valid_patient_ids)
        ]

        print(
            "Unique patient IDs in payer transitions:",
            len(transition_patient_ids)
        )

        print(
            "Invalid patient IDs:",
            len(invalid_patient_ids)
        )

        print(
            "Rows with invalid patient references:",
            len(invalid_patient_rows)
        )

    else:
        print("patients_cleaned.csv not found.")

else:
    print("PATIENT column not present.")

# ------------------------------------------------------------
# 9. Payer reference validation
# ------------------------------------------------------------

print("\n========== PAYER REFERENCE VALIDATION ==========")

if "PAYER" in payer_transitions.columns:

    payers_clean_path = CLEAN_PATH / "payers_cleaned.csv"

    if payers_clean_path.exists():

        payers_cleaned = pd.read_csv(
            payers_clean_path,
            usecols=["Id"]
        )

        valid_payer_ids = set(
            payers_cleaned["Id"].astype(str)
        )

        transition_payer_ids = set(
            payer_transitions["PAYER"]
            .dropna()
            .astype(str)
        )

        invalid_payer_ids = (
            transition_payer_ids - valid_payer_ids
        )

        invalid_payer_rows = payer_transitions[
            payer_transitions["PAYER"].notna()
            &
            ~payer_transitions["PAYER"]
            .astype(str)
            .isin(valid_payer_ids)
        ]

        print(
            "Unique payer IDs in transitions:",
            len(transition_payer_ids)
        )

        print(
            "Invalid payer IDs:",
            len(invalid_payer_ids)
        )

        print(
            "Rows with invalid payer references:",
            len(invalid_payer_rows)
        )

    else:
        print("payers_cleaned.csv not found.")

else:
    print("PAYER column not present.")

# ------------------------------------------------------------
# 10. Logical date validation
# ------------------------------------------------------------

print("\n========== DATE LOGICAL VALIDATION ==========")

if "START" in payer_transitions.columns and \
   "STOP" in payer_transitions.columns:

    start_before_stop_issue = (
        payer_transitions["STOP"]
        < payer_transitions["START"]
    ).sum()

    print(
        "STOP earlier than START:",
        start_before_stop_issue
    )

# ------------------------------------------------------------
# 11. Utilization analysis
# ------------------------------------------------------------

print("\n========== UTILIZATION ANALYSIS ==========")

if "PATIENT" in payer_transitions.columns:

    print(
        "Unique patients:",
        payer_transitions["PATIENT"].nunique()
    )

    print("\nTransitions per patient:")

    display(
        payer_transitions.groupby("PATIENT")
        .size()
        .describe()
    )

if "PAYER" in payer_transitions.columns:

    print(
        "\nUnique payers:",
        payer_transitions["PAYER"].nunique()
    )

# ------------------------------------------------------------
# 12. Numeric column analysis
# ------------------------------------------------------------

print("\n========== NUMERIC COLUMN ANALYSIS ==========")

numeric_columns = payer_transitions.select_dtypes(
    include="number"
).columns.tolist()

print("Numeric columns:", numeric_columns)

for col in numeric_columns:

    print(f"\n--- {col} ---")

    display(
        payer_transitions[col].describe()
    )

    print(
        "Negative values:",
        (payer_transitions[col] < 0).sum()
    )

# ------------------------------------------------------------
# 13. Remove exact duplicate rows
# ------------------------------------------------------------

print("\n========== DUPLICATE REMOVAL ==========")

rows_before = len(payer_transitions)

payer_transitions_cleaned = (
    payer_transitions
    .drop_duplicates()
    .copy()
)

rows_after = len(payer_transitions_cleaned)

print("Rows before:", rows_before)
print("Rows after:", rows_after)
print(
    "Duplicates removed:",
    rows_before - rows_after
)

# ------------------------------------------------------------
# 14. Final validation
# ------------------------------------------------------------

print("\n========== FINAL VALIDATION ==========")

print(
    "Final shape:",
    payer_transitions_cleaned.shape
)

print(
    "Duplicate rows:",
    payer_transitions_cleaned.duplicated().sum()
)

for col in payer_transitions_cleaned.columns:

    print(
        f"Missing {col}:",
        payer_transitions_cleaned[col].isna().sum()
    )

# ------------------------------------------------------------
# 15. Save cleaned dataset
# ------------------------------------------------------------

output_path = (
    CLEAN_PATH /
    "payer_transitions_cleaned.csv"
)

payer_transitions_cleaned.to_csv(
    output_path,
    index=False
)

print("\n========== FILE SAVED ==========")

print("Saved to:", output_path)
print("File exists:", output_path.exists())

# ------------------------------------------------------------
# 16. Reload verification
# ------------------------------------------------------------

verification = pd.read_csv(output_path)

print("\n========== RELOAD VERIFICATION ==========")

print(
    "Reloaded shape:",
    verification.shape
)

print(
    "Reloaded duplicate rows:",
    verification.duplicated().sum()
)

print("\nDATASET 13 — PAYER TRANSITIONS CLEANING COMPLETED")

========== PAYER TRANSITIONS DATASET ==========
Raw Shape: (53101, 8)

Columns:
['PATIENT', 'MEMBERID', 'START_YEAR', 'END_YEAR', 'PAYER', 'SECONDARY_PAYER', 'OWNERSHIP', 'OWNERNAME']

========== DATA TYPES ==========
PATIENT            str
MEMBERID           str
START_YEAR         str
END_YEAR           str
PAYER              str
SECONDARY_PAYER    str
OWNERSHIP          str
OWNERNAME          str
dtype: object

========== FIRST 5 ROWS ==========

,PATIENT,MEMBERID,START_YEAR,END_YEAR,PAYER,SECONDARY_PAYER,OWNERSHIP,OWNERNAME
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,bca22051-b39b-7591-74d4-47e10a94c52e,2019-02-24T05:07:38Z,2020-03-01T05:07:38Z,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,NaN,Self,Damon455 Langosh790
1,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,bca22051-b39b-7591-74d4-47e10a94c52e,2020-03-01T05:07:38Z,2021-03-07T05:07:38Z,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,NaN,Self,Damon455 Langosh790
2,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,bca22051-b39b-7591-74d4-47e10a94c52e,2021-03-07T05:07:38Z,2022-03-07T05:07:38Z,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,NaN,Self,Damon455 Langosh790
3,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,579bba4d-6d19-32f4-e5fe-720eb34328e0,2005-07-11T08:20:52Z,2006-07-17T08:20:52Z,6e2f1a2d-27bd-3701-8d08-dae202c58632,NaN,Guardian,Adalberto916 Wunsch504
4,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,5656e5a0-b468-6067-f89f-afaf4c49dfc3,2006-07-17T08:20:52Z,2007-07-23T08:20:52Z,4d71f845-a6a9-3c39-b242-14d25ef86a8d,NaN,Guardian,Adalberto916 Wunsch504

========== MISSING VALUES ==========

                 Missing_Count  Missing_Percentage
MEMBERID                  9546               17.98
SECONDARY_PAYER          51121               96.27
OWNERSHIP                 9546               17.98
OWNERNAME                 9546               17.98

========== DUPLICATE ANALYSIS ==========
Duplicate complete rows: 0

========== DATE ANALYSIS ==========
Detected date columns: []

========== COLUMN VALUE ANALYSIS ==========

--- PATIENT ---
Unique values: 1163
Missing values: 0
Top 10 values:

PATIENT
e23c7a6e-6ef2-3932-1361-b73b4c8a3961    255
81b2098d-e476-7d41-46b1-1c86fa027785    175
55c5b8d3-99d0-58ad-8444-e42bb81bd5c7    160
ec56f618-56ed-cf49-78fd-4d561bf7cba3    134
0d281c81-6c94-4578-c69f-217929d12245    131
ef167059-cef0-12c4-49db-993ca3a20c01    130
7bc66758-5d59-0b38-1532-29a33fa146c1    130
60b0873c-9665-b3f0-61f4-d09ae9667a27    128
3f8f669e-a86e-7ed2-9cd3-af981a89dfa1    124
30813a62-aa9f-3c7c-cc52-6c3957a3c1b1    122
Name: count, dtype: int64

--- MEMBERID ---
Unique values: 32119
Missing values: 9546
Top 10 values:

MEMBERID
NaN                                     9546
7f70dd21-d310-77fb-f341-41f0a8a0fe53      47
3b4c3eb8-103b-bf00-efa7-c3c4ac740da7      46
990e7ff3-b785-bcb7-fcdd-77a00793321a      46
b0d6b495-cbae-565d-5485-f946533746b3      46
535e7967-b4d1-c723-d264-1e607163054b      46
81088fc7-7dae-1bf3-4a3a-413b8393ff10      46
d91182cd-6018-1563-cdba-f981f776aa1c      46
b69e93c8-06cb-22e8-d03e-d29a381509c3      46
c51e4611-c8d5-e23b-3201-855c77ad82b2      46
Name: count, dtype: int64

--- START_YEAR ---
Unique values: 47005
Missing values: 0
Top 10 values:

START_YEAR
1913-06-17T21:04:17Z    11
1914-06-23T21:04:17Z    11
1915-06-29T21:04:17Z    11
1916-07-04T21:04:17Z    11
1917-07-10T21:04:17Z    11
1918-07-16T21:04:17Z    11
1919-07-22T21:04:17Z    11
1920-07-27T21:04:17Z    11
1921-08-02T21:04:17Z    11
1922-08-08T21:04:17Z    11
Name: count, dtype: int64

--- END_YEAR ---
Unique values: 47162
Missing values: 0
Top 10 values:

END_YEAR
1914-06-23T21:04:17Z    11
1915-06-29T21:04:17Z    11
1916-07-04T21:04:17Z    11
1917-07-10T21:04:17Z    11
1918-07-16T21:04:17Z    11
1919-07-22T21:04:17Z    11
1920-07-27T21:04:17Z    11
1921-08-02T21:04:17Z    11
1922-08-08T21:04:17Z    11
1923-08-14T21:04:17Z    11
Name: count, dtype: int64

--- PAYER ---
Unique values: 10
Missing values: 0
Top 10 values:

PAYER
b1c428d6-4f07-31e0-90f0-68ffa6ff8c76    9546
d47b3510-2895-3b70-9897-342d681c769d    6249
4d71f845-a6a9-3c39-b242-14d25ef86a8d    6044
5059a55e-5d6e-34d1-b6cb-d83d16e57bcf    6043
6e2f1a2d-27bd-3701-8d08-dae202c58632    5938
047f6ec3-6215-35eb-9608-f9dda363a44c    5828
42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a    5821
7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a    4803
7caa7254-5050-3b5e-9eae-bd5ea30e809c    2574
b3221cfc-24fb-339e-823d-bc4136cbc4ed     255
Name: count, dtype: int64

--- SECONDARY_PAYER ---
Unique values: 6
Missing values: 51121
Top 10 values:

SECONDARY_PAYER
NaN                                     51121
047f6ec3-6215-35eb-9608-f9dda363a44c      356
6e2f1a2d-27bd-3701-8d08-dae202c58632      349
4d71f845-a6a9-3c39-b242-14d25ef86a8d      349
5059a55e-5d6e-34d1-b6cb-d83d16e57bcf      328
42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a      315
d47b3510-2895-3b70-9897-342d681c769d      283
Name: count, dtype: int64

--- OWNERSHIP ---
Unique values: 3
Missing values: 9546
Top 10 values:

OWNERSHIP
Self        20558
Guardian    15537
NaN          9546
Spouse       7460
Name: count, dtype: int64

--- OWNERNAME ---
Unique values: 3619
Missing values: 9546
Top 10 values:

OWNERNAME
NaN                          9546
Zachariah133 Bergstrom287      89
Mr. Bosco882                   83
Merrill415 Jones311            82
Mitchell808 Harber290          82
Mr. Gerlach374                 80
Boyd728 Gleichner915           76
Elena945 Otero621              76
Raul814 Heller342              70
Betsey110 Funk324              70
Name: count, dtype: int64

========== PATIENT REFERENCE VALIDATION ==========
Unique patient IDs in payer transitions: 1163
Invalid patient IDs: 0
Rows with invalid patient references: 0

========== PAYER REFERENCE VALIDATION ==========
Unique payer IDs in transitions: 10
Invalid payer IDs: 0
Rows with invalid payer references: 0

========== DATE LOGICAL VALIDATION ==========

========== UTILIZATION ANALYSIS ==========
Unique patients: 1163

Transitions per patient:

count    1163.000000
mean       45.658641
std        28.218405
min         1.000000
25%        23.000000
50%        45.000000
75%        65.000000
max       255.000000
dtype: float64

Unique payers: 10

========== NUMERIC COLUMN ANALYSIS ==========
Numeric columns: []

========== DUPLICATE REMOVAL ==========
Rows before: 53101
Rows after: 53101
Duplicates removed: 0

========== FINAL VALIDATION ==========
Final shape: (53101, 8)
Duplicate rows: 0
Missing PATIENT: 0
Missing MEMBERID: 9546
Missing START_YEAR: 0
Missing END_YEAR: 0
Missing PAYER: 0
Missing SECONDARY_PAYER: 51121
Missing OWNERSHIP: 9546
Missing OWNERNAME: 9546

========== FILE SAVED ==========
Saved to: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\payer_transitions_cleaned.csv
File exists: True

========== RELOAD VERIFICATION ==========
Reloaded shape: (53101, 8)
Reloaded duplicate rows: 0

DATASET 13 — PAYER TRANSITIONS CLEANING COMPLETED

In [67]:
# ============================================================
# DATASET 13 — DATE CORRECTION
# Convert START_YEAR and END_YEAR to datetime
# ============================================================

print("========== DATE CORRECTION ==========")

# Convert timestamp columns to UTC datetime
payer_transitions_cleaned["START_YEAR"] = pd.to_datetime(
    payer_transitions_cleaned["START_YEAR"],
    errors="coerce",
    utc=True
)

payer_transitions_cleaned["END_YEAR"] = pd.to_datetime(
    payer_transitions_cleaned["END_YEAR"],
    errors="coerce",
    utc=True
)

# ------------------------------------------------------------
# Check conversion
# ------------------------------------------------------------

print("START_YEAR datatype:",
      payer_transitions_cleaned["START_YEAR"].dtype)

print("END_YEAR datatype:",
      payer_transitions_cleaned["END_YEAR"].dtype)

print("\nMissing START_YEAR:",
      payer_transitions_cleaned["START_YEAR"].isna().sum())

print("Missing END_YEAR:",
      payer_transitions_cleaned["END_YEAR"].isna().sum())

print("\nMinimum START_YEAR:",
      payer_transitions_cleaned["START_YEAR"].min())

print("Maximum START_YEAR:",
      payer_transitions_cleaned["START_YEAR"].max())

print("\nMinimum END_YEAR:",
      payer_transitions_cleaned["END_YEAR"].min())

print("Maximum END_YEAR:",
      payer_transitions_cleaned["END_YEAR"].max())

# ------------------------------------------------------------
# Logical date validation
# ------------------------------------------------------------

invalid_date_order = (
    payer_transitions_cleaned["END_YEAR"]
    < payer_transitions_cleaned["START_YEAR"]
).sum()

print("\nEND_YEAR earlier than START_YEAR:",
      invalid_date_order)

# ------------------------------------------------------------
# Save corrected dataset
# ------------------------------------------------------------

output_path = CLEAN_PATH / "payer_transitions_cleaned.csv"

payer_transitions_cleaned.to_csv(
    output_path,
    index=False
)

print("\n========== CORRECTED FILE SAVED ==========")
print("Saved to:", output_path)
print("File exists:", output_path.exists())

# ------------------------------------------------------------
# Reload verification
# ------------------------------------------------------------

verification = pd.read_csv(
    output_path,
    parse_dates=["START_YEAR", "END_YEAR"]
)

print("\n========== RELOAD VERIFICATION ==========")

print("Reloaded shape:",
      verification.shape)

print("START_YEAR datatype:",
      verification["START_YEAR"].dtype)

print("END_YEAR datatype:",
      verification["END_YEAR"].dtype)

print("Duplicate rows:",
      verification.duplicated().sum())

print(
    "END_YEAR earlier than START_YEAR:",
    (
        verification["END_YEAR"]
        < verification["START_YEAR"]
    ).sum()
)

print("\nDATASET 13 — DATE CORRECTION VERIFIED")

========== DATE CORRECTION ==========
START_YEAR datatype: datetime64[us, UTC]
END_YEAR datatype: datetime64[us, UTC]

Missing START_YEAR: 0
Missing END_YEAR: 0

Minimum START_YEAR: 1911-07-21 18:47:25+00:00
Maximum START_YEAR: 2021-11-26 14:20:29+00:00

Minimum END_YEAR: 1912-07-26 18:47:25+00:00
Maximum END_YEAR: 2022-11-26 14:20:29+00:00

END_YEAR earlier than START_YEAR: 0

========== CORRECTED FILE SAVED ==========
Saved to: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\payer_transitions_cleaned.csv
File exists: True

========== RELOAD VERIFICATION ==========
Reloaded shape: (53101, 8)
START_YEAR datatype: datetime64[us, UTC]
END_YEAR datatype: datetime64[us, UTC]
Duplicate rows: 0
END_YEAR earlier than START_YEAR: 0

DATASET 13 — DATE CORRECTION VERIFIED

In [68]:
# ============================================================
# DATASET 14 — ALLERGIES.CSV
# Cleaning + Validation + Save
# ============================================================

import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# 1. PATHS
# ------------------------------------------------------------

PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)

RAW_PATH = PROJECT_PATH / "data" / "Raw_Datasets"
CLEAN_PATH = PROJECT_PATH / "data" / "Cleaned_Datasets"

input_file = RAW_PATH / "allergies.csv"
output_file = CLEAN_PATH / "allergies_cleaned.csv"


# ------------------------------------------------------------
# 2. LOAD DATA
# ------------------------------------------------------------

allergies = pd.read_csv(input_file)

print("========== RAW DATASET ==========")
print("Shape:", allergies.shape)
print("\nColumns:")
print(allergies.columns.tolist())
print("\nData types:")
print(allergies.dtypes)


# ------------------------------------------------------------
# 3. MISSING VALUE CHECK
# ------------------------------------------------------------

print("\n========== MISSING VALUES ==========")

missing_values = allergies.isna().sum()
missing_percent = (missing_values / len(allergies) * 100).round(2)

missing_summary = pd.DataFrame({
    "Missing_Count": missing_values,
    "Missing_Percent": missing_percent
})

print(missing_summary)


# ------------------------------------------------------------
# 4. DUPLICATE CHECK
# ------------------------------------------------------------

print("\n========== DUPLICATE CHECK ==========")

duplicate_rows = allergies.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)


# ------------------------------------------------------------
# 5. DATE CONVERSION
# ------------------------------------------------------------

print("\n========== DATE CONVERSION ==========")

date_columns = []

for col in allergies.columns:
    if col.upper() in ["START", "STOP", "DATE"]:
        date_columns.append(col)

for col in date_columns:
    allergies[col] = pd.to_datetime(
        allergies[col],
        errors="coerce",
        utc=True
    )

print("Date columns converted:", date_columns)

for col in date_columns:
    print(f"\n{col} datatype:", allergies[col].dtype)
    print(f"Missing {col}:", allergies[col].isna().sum())

    if allergies[col].notna().any():
        print(f"Minimum {col}:", allergies[col].min())
        print(f"Maximum {col}:", allergies[col].max())


# ------------------------------------------------------------
# 6. DATE LOGICAL VALIDATION
# ------------------------------------------------------------

if "START" in allergies.columns and "STOP" in allergies.columns:

    print("\n========== DATE LOGICAL VALIDATION ==========")

    invalid_dates = (
        allergies["STOP"].notna()
        & allergies["START"].notna()
        & (allergies["STOP"] < allergies["START"])
    ).sum()

    print("STOP earlier than START:", invalid_dates)

    # Correct only logically invalid STOP values
    if invalid_dates > 0:
        allergies.loc[
            allergies["STOP"] < allergies["START"],
            "STOP"
        ] = pd.NaT

        print("Invalid STOP dates converted to missing (NaT).")
    else:
        print("No invalid date ranges found.")


# ------------------------------------------------------------
# 7. IDENTIFIER VALIDATION
# ------------------------------------------------------------

print("\n========== IDENTIFIER VALIDATION ==========")

if "PATIENT" in allergies.columns:
    print("Missing PATIENT:", allergies["PATIENT"].isna().sum())
    print("Unique PATIENT values:", allergies["PATIENT"].nunique())

if "ENCOUNTER" in allergies.columns:
    print("Missing ENCOUNTER:", allergies["ENCOUNTER"].isna().sum())
    print("Unique ENCOUNTER values:", allergies["ENCOUNTER"].nunique())


# ------------------------------------------------------------
# 8. CODE / DESCRIPTION VALIDATION
# ------------------------------------------------------------

print("\n========== CODE / DESCRIPTION VALIDATION ==========")

if "CODE" in allergies.columns:
    print("Missing CODE:", allergies["CODE"].isna().sum())
    print("Unique allergy codes:", allergies["CODE"].nunique())

if "DESCRIPTION" in allergies.columns:
    print("Missing DESCRIPTION:", allergies["DESCRIPTION"].isna().sum())
    print("Unique allergy descriptions:", allergies["DESCRIPTION"].nunique())


# ------------------------------------------------------------
# 9. NEGATIVE / FINANCIAL CHECK
# ------------------------------------------------------------

print("\n========== NUMERIC / FINANCIAL CHECK ==========")

numeric_columns = allergies.select_dtypes(include="number").columns.tolist()

print("Numeric columns:", numeric_columns)

for col in numeric_columns:
    print(f"\n{col}")
    print("Minimum:", allergies[col].min())
    print("Maximum:", allergies[col].max())
    print("Negative values:", (allergies[col] < 0).sum())


# ------------------------------------------------------------
# 10. REFERENCE INTEGRITY
# ------------------------------------------------------------

print("\n========== REFERENCE INTEGRITY ==========")

patients_file = CLEAN_PATH / "patients_cleaned.csv"
encounters_file = CLEAN_PATH / "encounters_cleaned.csv"

if "PATIENT" in allergies.columns and patients_file.exists():

    patients = pd.read_csv(patients_file, usecols=["Id"])

    invalid_patients = (
        ~allergies["PATIENT"].isin(patients["Id"])
    ).sum()

    print("Invalid PATIENT references:", invalid_patients)

if "ENCOUNTER" in allergies.columns and encounters_file.exists():

    encounters = pd.read_csv(encounters_file, usecols=["Id"])

    invalid_encounters = (
        ~allergies["ENCOUNTER"].isin(encounters["Id"])
    ).sum()

    print("Invalid ENCOUNTER references:", invalid_encounters)


# ------------------------------------------------------------
# 11. UTILIZATION CHECK
# ------------------------------------------------------------

print("\n========== UTILIZATION CHECK ==========")

if "ENCOUNTER" in allergies.columns:

    allergies_per_encounter = allergies.groupby(
        "ENCOUNTER"
    ).size()

    print(
        "Average allergies per encounter:",
        allergies_per_encounter.mean()
    )

    print(
        "Median allergies per encounter:",
        allergies_per_encounter.median()
    )

    print(
        "Maximum allergies per encounter:",
        allergies_per_encounter.max()
    )

if "PATIENT" in allergies.columns:

    allergies_per_patient = allergies.groupby(
        "PATIENT"
    ).size()

    print(
        "Average allergies per patient:",
        allergies_per_patient.mean()
    )

    print(
        "Median allergies per patient:",
        allergies_per_patient.median()
    )

    print(
        "Maximum allergies per patient:",
        allergies_per_patient.max()
    )


# ------------------------------------------------------------
# 12. REMOVE EXACT DUPLICATES
# ------------------------------------------------------------

print("\n========== DUPLICATE REMOVAL ==========")

before_duplicates = len(allergies)

allergies = allergies.drop_duplicates().copy()

after_duplicates = len(allergies)

print("Rows before duplicate removal:", before_duplicates)
print("Rows after duplicate removal:", after_duplicates)
print("Rows removed:", before_duplicates - after_duplicates)


# ------------------------------------------------------------
# 13. FINAL VALIDATION
# ------------------------------------------------------------

print("\n========== FINAL VALIDATION ==========")

print("Final shape:", allergies.shape)
print("Duplicate rows:", allergies.duplicated().sum())

for col in date_columns:
    print(f"Missing {col}:", allergies[col].isna().sum())

if "PATIENT" in allergies.columns:
    print("Missing PATIENT:", allergies["PATIENT"].isna().sum())

if "ENCOUNTER" in allergies.columns:
    print("Missing ENCOUNTER:", allergies["ENCOUNTER"].isna().sum())

if "CODE" in allergies.columns:
    print("Missing CODE:", allergies["CODE"].isna().sum())

if "DESCRIPTION" in allergies.columns:
    print("Missing DESCRIPTION:", allergies["DESCRIPTION"].isna().sum())


# ------------------------------------------------------------
# 14. SAVE CLEANED DATASET
# ------------------------------------------------------------

allergies.to_csv(output_file, index=False)

print("\n========== CLEANED FILE SAVED ==========")
print("Saved to:", output_file)
print("File exists:", output_file.exists())


# ------------------------------------------------------------
# 15. RELOAD VERIFICATION
# ------------------------------------------------------------

verified = pd.read_csv(output_file)

for col in date_columns:
    verified[col] = pd.to_datetime(
        verified[col],
        errors="coerce",
        utc=True
    )

print("\n========== RELOAD VERIFICATION ==========")

print("Reloaded shape:", verified.shape)
print("Duplicate rows:", verified.duplicated().sum())

for col in date_columns:
    print(f"{col} datatype:", verified[col].dtype)

    if col == "START" and "STOP" in verified.columns:
        invalid_after_reload = (
            verified["STOP"].notna()
            & verified["START"].notna()
            & (verified["STOP"] < verified["START"])
        ).sum()

        print(
            "STOP earlier than START after reload:",
            invalid_after_reload
        )

print("\nDATASET 14 — ALLERGIES CLEANING COMPLETED")

========== RAW DATASET ==========
Shape: (794, 15)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'SYSTEM', 'DESCRIPTION', 'TYPE', 'CATEGORY', 'REACTION1', 'DESCRIPTION1', 'SEVERITY1', 'REACTION2', 'DESCRIPTION2', 'SEVERITY2']

Data types:
START               str
STOP            float64
PATIENT             str
ENCOUNTER           str
CODE              int64
SYSTEM              str
DESCRIPTION         str
TYPE                str
CATEGORY            str
REACTION1       float64
DESCRIPTION1        str
SEVERITY1           str
REACTION2       float64
DESCRIPTION2        str
SEVERITY2           str
dtype: object

========== MISSING VALUES ==========
              Missing_Count  Missing_Percent
START                     0             0.00
STOP                    794           100.00
PATIENT                   0             0.00
ENCOUNTER                 0             0.00
CODE                      0             0.00
SYSTEM                    0             0.00
DESCRIPTION               0             0.00
TYPE                      0             0.00
CATEGORY                  0             0.00
REACTION1               384            48.36
DESCRIPTION1            384            48.36
SEVERITY1               384            48.36
REACTION2               535            67.38
DESCRIPTION2            535            67.38
SEVERITY2               535            67.38

========== DUPLICATE CHECK ==========
Duplicate complete rows: 0

========== DATE CONVERSION ==========
Date columns converted: ['START', 'STOP']

START datatype: datetime64[us, UTC]
Missing START: 0
Minimum START: 1912-10-08 00:00:00+00:00
Maximum START: 2021-02-15 00:00:00+00:00

STOP datatype: datetime64[s, UTC]
Missing STOP: 794

========== DATE LOGICAL VALIDATION ==========
STOP earlier than START: 0
No invalid date ranges found.

========== IDENTIFIER VALIDATION ==========
Missing PATIENT: 0
Unique PATIENT values: 179
Missing ENCOUNTER: 0
Unique ENCOUNTER values: 179

========== CODE / DESCRIPTION VALIDATION ==========
Missing CODE: 0
Unique allergy codes: 21
Missing DESCRIPTION: 0
Unique allergy descriptions: 21

========== NUMERIC / FINANCIAL CHECK ==========
Numeric columns: ['CODE', 'REACTION1', 'REACTION2']

CODE
Minimum: 1191
Maximum: 442571000124108
Negative values: 0

REACTION1
Minimum: 21522001.0
Maximum: 878820003.0
Negative values: 0

REACTION2
Minimum: 21626009.0
Maximum: 878820003.0
Negative values: 0

========== REFERENCE INTEGRITY ==========
Invalid PATIENT references: 0
Invalid ENCOUNTER references: 0

========== UTILIZATION CHECK ==========
Average allergies per encounter: 4.435754189944134
Median allergies per encounter: 3.0
Maximum allergies per encounter: 12
Average allergies per patient: 4.435754189944134
Median allergies per patient: 3.0
Maximum allergies per patient: 12

========== DUPLICATE REMOVAL ==========
Rows before duplicate removal: 794
Rows after duplicate removal: 794
Rows removed: 0

========== FINAL VALIDATION ==========
Final shape: (794, 15)
Duplicate rows: 0
Missing START: 0
Missing STOP: 794
Missing PATIENT: 0
Missing ENCOUNTER: 0
Missing CODE: 0
Missing DESCRIPTION: 0

========== CLEANED FILE SAVED ==========
Saved to: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\allergies_cleaned.csv
File exists: True

========== RELOAD VERIFICATION ==========
Reloaded shape: (794, 15)
Duplicate rows: 0
START datatype: datetime64[us, UTC]
STOP earlier than START after reload: 0
STOP datatype: datetime64[s, UTC]

DATASET 14 — ALLERGIES CLEANING COMPLETED

In [69]:
# ============================================================
# DATASET 15 — CAREPLANS.CSV
# Cleaning + Validation + Save
# ============================================================

import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# 1. PATHS
# ------------------------------------------------------------

PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)

RAW_PATH = PROJECT_PATH / "data" / "Raw_Datasets"
CLEAN_PATH = PROJECT_PATH / "data" / "Cleaned_Datasets"

input_file = RAW_PATH / "careplans.csv"
output_file = CLEAN_PATH / "careplans_cleaned.csv"


# ------------------------------------------------------------
# 2. LOAD DATA
# ------------------------------------------------------------

careplans = pd.read_csv(input_file)

print("========== RAW DATASET ==========")
print("Shape:", careplans.shape)

print("\nColumns:")
print(careplans.columns.tolist())

print("\nData types:")
print(careplans.dtypes)


# ------------------------------------------------------------
# 3. MISSING VALUE CHECK
# ------------------------------------------------------------

print("\n========== MISSING VALUES ==========")

missing_values = careplans.isna().sum()
missing_percent = (missing_values / len(careplans) * 100).round(2)

missing_summary = pd.DataFrame({
    "Missing_Count": missing_values,
    "Missing_Percent": missing_percent
})

print(missing_summary)


# ------------------------------------------------------------
# 4. DUPLICATE CHECK
# ------------------------------------------------------------

print("\n========== DUPLICATE CHECK ==========")

duplicate_rows = careplans.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)


# ------------------------------------------------------------
# 5. DATE CONVERSION
# ------------------------------------------------------------

print("\n========== DATE CONVERSION ==========")

date_columns = []

for col in careplans.columns:
    if col.upper() in ["START", "STOP", "DATE"]:
        date_columns.append(col)

for col in date_columns:
    careplans[col] = pd.to_datetime(
        careplans[col],
        errors="coerce",
        utc=True
    )

print("Date columns converted:", date_columns)

for col in date_columns:

    print(f"\n{col} datatype:", careplans[col].dtype)
    print(f"Missing {col}:", careplans[col].isna().sum())

    if careplans[col].notna().any():
        print(f"Minimum {col}:", careplans[col].min())
        print(f"Maximum {col}:", careplans[col].max())


# ------------------------------------------------------------
# 6. DATE LOGICAL VALIDATION
# ------------------------------------------------------------

if "START" in careplans.columns and "STOP" in careplans.columns:

    print("\n========== DATE LOGICAL VALIDATION ==========")

    invalid_dates = (
        careplans["STOP"].notna()
        & careplans["START"].notna()
        & (careplans["STOP"] < careplans["START"])
    ).sum()

    print("STOP earlier than START:", invalid_dates)

    if invalid_dates > 0:

        careplans.loc[
            careplans["STOP"] < careplans["START"],
            "STOP"
        ] = pd.NaT

        print("Invalid STOP dates converted to missing (NaT).")

    else:
        print("No invalid date ranges found.")


# ------------------------------------------------------------
# 7. IDENTIFIER VALIDATION
# ------------------------------------------------------------

print("\n========== IDENTIFIER VALIDATION ==========")

if "PATIENT" in careplans.columns:

    print(
        "Missing PATIENT:",
        careplans["PATIENT"].isna().sum()
    )

    print(
        "Unique PATIENT values:",
        careplans["PATIENT"].nunique()
    )

if "ENCOUNTER" in careplans.columns:

    print(
        "Missing ENCOUNTER:",
        careplans["ENCOUNTER"].isna().sum()
    )

    print(
        "Unique ENCOUNTER values:",
        careplans["ENCOUNTER"].nunique()
    )


# ------------------------------------------------------------
# 8. CODE / DESCRIPTION VALIDATION
# ------------------------------------------------------------

print("\n========== CODE / DESCRIPTION VALIDATION ==========")

if "CODE" in careplans.columns:

    print(
        "Missing CODE:",
        careplans["CODE"].isna().sum()
    )

    print(
        "Unique CODE values:",
        careplans["CODE"].nunique()
    )

if "DESCRIPTION" in careplans.columns:

    print(
        "Missing DESCRIPTION:",
        careplans["DESCRIPTION"].isna().sum()
    )

    print(
        "Unique DESCRIPTION values:",
        careplans["DESCRIPTION"].nunique()
    )


# ------------------------------------------------------------
# 9. NUMERIC / FINANCIAL CHECK
# ------------------------------------------------------------

print("\n========== NUMERIC / FINANCIAL CHECK ==========")

numeric_columns = careplans.select_dtypes(
    include="number"
).columns.tolist()

print("Numeric columns:", numeric_columns)

for col in numeric_columns:

    print(f"\n{col}")

    print(
        "Minimum:",
        careplans[col].min()
    )

    print(
        "Maximum:",
        careplans[col].max()
    )

    print(
        "Negative values:",
        (careplans[col] < 0).sum()
    )


# ------------------------------------------------------------
# 10. REFERENCE INTEGRITY
# ------------------------------------------------------------

print("\n========== REFERENCE INTEGRITY ==========")

patients_file = CLEAN_PATH / "patients_cleaned.csv"
encounters_file = CLEAN_PATH / "encounters_cleaned.csv"

if "PATIENT" in careplans.columns and patients_file.exists():

    patients = pd.read_csv(
        patients_file,
        usecols=["Id"]
    )

    invalid_patients = (
        ~careplans["PATIENT"].isin(
            patients["Id"]
        )
    ).sum()

    print(
        "Invalid PATIENT references:",
        invalid_patients
    )


if "ENCOUNTER" in careplans.columns and encounters_file.exists():

    encounters = pd.read_csv(
        encounters_file,
        usecols=["Id"]
    )

    invalid_encounters = (
        ~careplans["ENCOUNTER"].isin(
            encounters["Id"]
        )
    ).sum()

    print(
        "Invalid ENCOUNTER references:",
        invalid_encounters
    )


# ------------------------------------------------------------
# 11. UTILIZATION CHECK
# ------------------------------------------------------------

print("\n========== UTILIZATION CHECK ==========")

if "ENCOUNTER" in careplans.columns:

    careplans_per_encounter = (
        careplans.groupby("ENCOUNTER")
        .size()
    )

    print(
        "Average careplans per encounter:",
        careplans_per_encounter.mean()
    )

    print(
        "Median careplans per encounter:",
        careplans_per_encounter.median()
    )

    print(
        "Maximum careplans per encounter:",
        careplans_per_encounter.max()
    )


if "PATIENT" in careplans.columns:

    careplans_per_patient = (
        careplans.groupby("PATIENT")
        .size()
    )

    print(
        "Average careplans per patient:",
        careplans_per_patient.mean()
    )

    print(
        "Median careplans per patient:",
        careplans_per_patient.median()
    )

    print(
        "Maximum careplans per patient:",
        careplans_per_patient.max()
    )


# ------------------------------------------------------------
# 12. REMOVE EXACT DUPLICATES
# ------------------------------------------------------------

print("\n========== DUPLICATE REMOVAL ==========")

before_duplicates = len(careplans)

careplans = careplans.drop_duplicates().copy()

after_duplicates = len(careplans)

print(
    "Rows before duplicate removal:",
    before_duplicates
)

print(
    "Rows after duplicate removal:",
    after_duplicates
)

print(
    "Rows removed:",
    before_duplicates - after_duplicates
)


# ------------------------------------------------------------
# 13. FINAL VALIDATION
# ------------------------------------------------------------

print("\n========== FINAL VALIDATION ==========")

print("Final shape:", careplans.shape)

print(
    "Duplicate rows:",
    careplans.duplicated().sum()
)

for col in date_columns:

    print(
        f"Missing {col}:",
        careplans[col].isna().sum()
    )

if "PATIENT" in careplans.columns:

    print(
        "Missing PATIENT:",
        careplans["PATIENT"].isna().sum()
    )

if "ENCOUNTER" in careplans.columns:

    print(
        "Missing ENCOUNTER:",
        careplans["ENCOUNTER"].isna().sum()
    )

if "CODE" in careplans.columns:

    print(
        "Missing CODE:",
        careplans["CODE"].isna().sum()
    )

if "DESCRIPTION" in careplans.columns:

    print(
        "Missing DESCRIPTION:",
        careplans["DESCRIPTION"].isna().sum()
    )


# ------------------------------------------------------------
# 14. SAVE CLEANED DATASET
# ------------------------------------------------------------

careplans.to_csv(
    output_file,
    index=False
)

print("\n========== CLEANED FILE SAVED ==========")

print(
    "Saved to:",
    output_file
)

print(
    "File exists:",
    output_file.exists()
)


# ------------------------------------------------------------
# 15. RELOAD VERIFICATION
# ------------------------------------------------------------

verified = pd.read_csv(output_file)

for col in date_columns:

    verified[col] = pd.to_datetime(
        verified[col],
        errors="coerce",
        utc=True
    )

print("\n========== RELOAD VERIFICATION ==========")

print(
    "Reloaded shape:",
    verified.shape
)

print(
    "Duplicate rows:",
    verified.duplicated().sum()
)

for col in date_columns:

    print(
        f"{col} datatype:",
        verified[col].dtype
    )

if "START" in verified.columns and "STOP" in verified.columns:

    invalid_after_reload = (
        verified["STOP"].notna()
        & verified["START"].notna()
        & (verified["STOP"] < verified["START"])
    ).sum()

    print(
        "STOP earlier than START after reload:",
        invalid_after_reload
    )


print("\nDATASET 15 — CAREPLANS CLEANING COMPLETED")

========== RAW DATASET ==========
Shape: (3931, 9)

Columns:
['Id', 'START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'REASONCODE', 'REASONDESCRIPTION']

Data types:
Id                       str
START                    str
STOP                     str
PATIENT                  str
ENCOUNTER                str
CODE                   int64
DESCRIPTION              str
REASONCODE           float64
REASONDESCRIPTION        str
dtype: object

========== MISSING VALUES ==========
                   Missing_Count  Missing_Percent
Id                             0             0.00
START                          0             0.00
STOP                        1679            42.71
PATIENT                        0             0.00
ENCOUNTER                      0             0.00
CODE                           0             0.00
DESCRIPTION                    0             0.00
REASONCODE                   558            14.19
REASONDESCRIPTION            558            14.19

========== DUPLICATE CHECK ==========
Duplicate complete rows: 0

========== DATE CONVERSION ==========
Date columns converted: ['START', 'STOP']

START datatype: datetime64[us, UTC]
Missing START: 0
Minimum START: 1912-09-25 00:00:00+00:00
Maximum START: 2021-11-15 00:00:00+00:00

STOP datatype: datetime64[us, UTC]
Missing STOP: 1679
Minimum STOP: 1921-07-05 00:00:00+00:00
Maximum STOP: 2021-11-18 00:00:00+00:00

========== DATE LOGICAL VALIDATION ==========
STOP earlier than START: 0
No invalid date ranges found.

========== IDENTIFIER VALIDATION ==========
Missing PATIENT: 0
Unique PATIENT values: 1068
Missing ENCOUNTER: 0
Unique ENCOUNTER values: 3849

========== CODE / DESCRIPTION VALIDATION ==========
Missing CODE: 0
Unique CODE values: 37
Missing DESCRIPTION: 0
Unique DESCRIPTION values: 37

========== NUMERIC / FINANCIAL CHECK ==========
Numeric columns: ['CODE', 'REASONCODE']

CODE
Minimum: 47387005
Maximum: 869761000000107
Negative values: 0

REASONCODE
Minimum: 1734006.0
Maximum: 840544004.0
Negative values: 0

========== REFERENCE INTEGRITY ==========
Invalid PATIENT references: 0
Invalid ENCOUNTER references: 0

========== UTILIZATION CHECK ==========
Average careplans per encounter: 1.021304234866199
Median careplans per encounter: 1.0
Maximum careplans per encounter: 2
Average careplans per patient: 3.6807116104868913
Median careplans per patient: 3.0
Maximum careplans per patient: 16

========== DUPLICATE REMOVAL ==========
Rows before duplicate removal: 3931
Rows after duplicate removal: 3931
Rows removed: 0

========== FINAL VALIDATION ==========
Final shape: (3931, 9)
Duplicate rows: 0
Missing START: 0
Missing STOP: 1679
Missing PATIENT: 0
Missing ENCOUNTER: 0
Missing CODE: 0
Missing DESCRIPTION: 0

========== CLEANED FILE SAVED ==========
Saved to: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\careplans_cleaned.csv
File exists: True

========== RELOAD VERIFICATION ==========
Reloaded shape: (3931, 9)
Duplicate rows: 0
START datatype: datetime64[us, UTC]
STOP datatype: datetime64[us, UTC]
STOP earlier than START after reload: 0

DATASET 15 — CAREPLANS CLEANING COMPLETED

In [70]:
# ============================================================
# DATASET 16 — DEVICES.CSV
# Cleaning + Validation + Save
# ============================================================

import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# 1. PATHS
# ------------------------------------------------------------

PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)

RAW_PATH = PROJECT_PATH / "data" / "Raw_Datasets"
CLEAN_PATH = PROJECT_PATH / "data" / "Cleaned_Datasets"

input_file = RAW_PATH / "devices.csv"
output_file = CLEAN_PATH / "devices_cleaned.csv"


# ------------------------------------------------------------
# 2. LOAD DATA
# ------------------------------------------------------------

devices = pd.read_csv(input_file)

print("========== RAW DATASET ==========")
print("Shape:", devices.shape)

print("\nColumns:")
print(devices.columns.tolist())

print("\nData types:")
print(devices.dtypes)


# ------------------------------------------------------------
# 3. MISSING VALUE CHECK
# ------------------------------------------------------------

print("\n========== MISSING VALUES ==========")

missing_values = devices.isna().sum()
missing_percent = (missing_values / len(devices) * 100).round(2)

missing_summary = pd.DataFrame({
    "Missing_Count": missing_values,
    "Missing_Percent": missing_percent
})

print(missing_summary)


# ------------------------------------------------------------
# 4. DUPLICATE CHECK
# ------------------------------------------------------------

print("\n========== DUPLICATE CHECK ==========")

duplicate_rows = devices.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)


# ------------------------------------------------------------
# 5. DATE CONVERSION
# ------------------------------------------------------------

print("\n========== DATE CONVERSION ==========")

date_columns = []

for col in devices.columns:

    if col.upper() in ["START", "STOP", "DATE"]:

        date_columns.append(col)


for col in date_columns:

    devices[col] = pd.to_datetime(
        devices[col],
        errors="coerce",
        utc=True
    )


print("Date columns converted:", date_columns)


for col in date_columns:

    print(
        f"\n{col} datatype:",
        devices[col].dtype
    )

    print(
        f"Missing {col}:",
        devices[col].isna().sum()
    )

    if devices[col].notna().any():

        print(
            f"Minimum {col}:",
            devices[col].min()
        )

        print(
            f"Maximum {col}:",
            devices[col].max()
        )


# ------------------------------------------------------------
# 6. DATE LOGICAL VALIDATION
# ------------------------------------------------------------

if "START" in devices.columns and "STOP" in devices.columns:

    print("\n========== DATE LOGICAL VALIDATION ==========")

    invalid_dates = (
        devices["STOP"].notna()
        & devices["START"].notna()
        & (devices["STOP"] < devices["START"])
    ).sum()

    print(
        "STOP earlier than START:",
        invalid_dates
    )

    if invalid_dates > 0:

        devices.loc[
            devices["STOP"] < devices["START"],
            "STOP"
        ] = pd.NaT

        print(
            "Invalid STOP dates converted to missing (NaT)."
        )

    else:

        print(
            "No invalid date ranges found."
        )


# ------------------------------------------------------------
# 7. IDENTIFIER VALIDATION
# ------------------------------------------------------------

print("\n========== IDENTIFIER VALIDATION ==========")

if "PATIENT" in devices.columns:

    print(
        "Missing PATIENT:",
        devices["PATIENT"].isna().sum()
    )

    print(
        "Unique PATIENT values:",
        devices["PATIENT"].nunique()
    )


if "ENCOUNTER" in devices.columns:

    print(
        "Missing ENCOUNTER:",
        devices["ENCOUNTER"].isna().sum()
    )

    print(
        "Unique ENCOUNTER values:",
        devices["ENCOUNTER"].nunique()
    )


# ------------------------------------------------------------
# 8. CODE / DESCRIPTION VALIDATION
# ------------------------------------------------------------

print("\n========== CODE / DESCRIPTION VALIDATION ==========")

if "CODE" in devices.columns:

    print(
        "Missing CODE:",
        devices["CODE"].isna().sum()
    )

    print(
        "Unique device codes:",
        devices["CODE"].nunique()
    )


if "DESCRIPTION" in devices.columns:

    print(
        "Missing DESCRIPTION:",
        devices["DESCRIPTION"].isna().sum()
    )

    print(
        "Unique device descriptions:",
        devices["DESCRIPTION"].nunique()
    )


# ------------------------------------------------------------
# 9. NUMERIC / FINANCIAL CHECK
# ------------------------------------------------------------

print("\n========== NUMERIC / FINANCIAL CHECK ==========")

numeric_columns = devices.select_dtypes(
    include="number"
).columns.tolist()

print(
    "Numeric columns:",
    numeric_columns
)

for col in numeric_columns:

    print(f"\n{col}")

    print(
        "Minimum:",
        devices[col].min()
    )

    print(
        "Maximum:",
        devices[col].max()
    )

    print(
        "Negative values:",
        (devices[col] < 0).sum()
    )


# ------------------------------------------------------------
# 10. REFERENCE INTEGRITY
# ------------------------------------------------------------

print("\n========== REFERENCE INTEGRITY ==========")

patients_file = CLEAN_PATH / "patients_cleaned.csv"
encounters_file = CLEAN_PATH / "encounters_cleaned.csv"

if "PATIENT" in devices.columns and patients_file.exists():

    patients = pd.read_csv(
        patients_file,
        usecols=["Id"]
    )

    invalid_patients = (
        ~devices["PATIENT"].isin(
            patients["Id"]
        )
    ).sum()

    print(
        "Invalid PATIENT references:",
        invalid_patients
    )


if "ENCOUNTER" in devices.columns and encounters_file.exists():

    encounters = pd.read_csv(
        encounters_file,
        usecols=["Id"]
    )

    invalid_encounters = (
        ~devices["ENCOUNTER"].isin(
            encounters["Id"]
        )
    ).sum()

    print(
        "Invalid ENCOUNTER references:",
        invalid_encounters
    )


# ------------------------------------------------------------
# 11. UTILIZATION CHECK
# ------------------------------------------------------------

print("\n========== UTILIZATION CHECK ==========")

if "ENCOUNTER" in devices.columns:

    devices_per_encounter = (
        devices.groupby("ENCOUNTER")
        .size()
    )

    print(
        "Average devices per encounter:",
        devices_per_encounter.mean()
    )

    print(
        "Median devices per encounter:",
        devices_per_encounter.median()
    )

    print(
        "Maximum devices per encounter:",
        devices_per_encounter.max()
    )


if "PATIENT" in devices.columns:

    devices_per_patient = (
        devices.groupby("PATIENT")
        .size()
    )

    print(
        "Average devices per patient:",
        devices_per_patient.mean()
    )

    print(
        "Median devices per patient:",
        devices_per_patient.median()
    )

    print(
        "Maximum devices per patient:",
        devices_per_patient.max()
    )


# ------------------------------------------------------------
# 12. REMOVE EXACT DUPLICATES
# ------------------------------------------------------------

print("\n========== DUPLICATE REMOVAL ==========")

before_duplicates = len(devices)

devices = devices.drop_duplicates().copy()

after_duplicates = len(devices)

print(
    "Rows before duplicate removal:",
    before_duplicates
)

print(
    "Rows after duplicate removal:",
    after_duplicates
)

print(
    "Rows removed:",
    before_duplicates - after_duplicates
)


# ------------------------------------------------------------
# 13. FINAL VALIDATION
# ------------------------------------------------------------

print("\n========== FINAL VALIDATION ==========")

print(
    "Final shape:",
    devices.shape
)

print(
    "Duplicate rows:",
    devices.duplicated().sum()
)

for col in date_columns:

    print(
        f"Missing {col}:",
        devices[col].isna().sum()
    )


if "PATIENT" in devices.columns:

    print(
        "Missing PATIENT:",
        devices["PATIENT"].isna().sum()
    )


if "ENCOUNTER" in devices.columns:

    print(
        "Missing ENCOUNTER:",
        devices["ENCOUNTER"].isna().sum()
    )


if "CODE" in devices.columns:

    print(
        "Missing CODE:",
        devices["CODE"].isna().sum()
    )


if "DESCRIPTION" in devices.columns:

    print(
        "Missing DESCRIPTION:",
        devices["DESCRIPTION"].isna().sum()
    )


# ------------------------------------------------------------
# 14. SAVE CLEANED DATASET
# ------------------------------------------------------------

devices.to_csv(
    output_file,
    index=False
)

print("\n========== CLEANED FILE SAVED ==========")

print(
    "Saved to:",
    output_file
)

print(
    "File exists:",
    output_file.exists()
)


# ------------------------------------------------------------
# 15. RELOAD VERIFICATION
# ------------------------------------------------------------

verified = pd.read_csv(output_file)

for col in date_columns:

    verified[col] = pd.to_datetime(
        verified[col],
        errors="coerce",
        utc=True
    )


print("\n========== RELOAD VERIFICATION ==========")

print(
    "Reloaded shape:",
    verified.shape
)

print(
    "Duplicate rows:",
    verified.duplicated().sum()
)

for col in date_columns:

    print(
        f"{col} datatype:",
        verified[col].dtype
    )


if "START" in verified.columns and "STOP" in verified.columns:

    invalid_after_reload = (
        verified["STOP"].notna()
        & verified["START"].notna()
        & (verified["STOP"] < verified["START"])
    ).sum()

    print(
        "STOP earlier than START after reload:",
        invalid_after_reload
    )


print("\nDATASET 16 — DEVICES CLEANING COMPLETED")

========== RAW DATASET ==========
Shape: (89, 7)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'UDI']

Data types:
START            str
STOP             str
PATIENT          str
ENCOUNTER        str
CODE           int64
DESCRIPTION      str
UDI              str
dtype: object

========== MISSING VALUES ==========
             Missing_Count  Missing_Percent
START                    0             0.00
STOP                    75            84.27
PATIENT                  0             0.00
ENCOUNTER                0             0.00
CODE                     0             0.00
DESCRIPTION              0             0.00
UDI                      0             0.00

========== DUPLICATE CHECK ==========
Duplicate complete rows: 0

========== DATE CONVERSION ==========
Date columns converted: ['START', 'STOP']

START datatype: datetime64[us, UTC]
Missing START: 0
Minimum START: 1945-10-20 10:04:43+00:00
Maximum START: 2021-10-23 05:05:30+00:00

STOP datatype: datetime64[us, UTC]
Missing STOP: 75
Minimum STOP: 2021-01-06 01:13:51+00:00
Maximum STOP: 2021-01-20 05:41:03+00:00

========== DATE LOGICAL VALIDATION ==========
STOP earlier than START: 0
No invalid date ranges found.

========== IDENTIFIER VALIDATION ==========
Missing PATIENT: 0
Unique PATIENT values: 76
Missing ENCOUNTER: 0
Unique ENCOUNTER values: 77

========== CODE / DESCRIPTION VALIDATION ==========
Missing CODE: 0
Unique device codes: 6
Missing DESCRIPTION: 0
Unique device descriptions: 6

========== NUMERIC / FINANCIAL CHECK ==========
Numeric columns: ['CODE']

CODE
Minimum: 36965003
Maximum: 706004007
Negative values: 0

========== REFERENCE INTEGRITY ==========
Invalid PATIENT references: 0
Invalid ENCOUNTER references: 0

========== UTILIZATION CHECK ==========
Average devices per encounter: 1.155844155844156
Median devices per encounter: 1.0
Maximum devices per encounter: 12
Average devices per patient: 1.1710526315789473
Median devices per patient: 1.0
Maximum devices per patient: 12

========== DUPLICATE REMOVAL ==========
Rows before duplicate removal: 89
Rows after duplicate removal: 89
Rows removed: 0

========== FINAL VALIDATION ==========
Final shape: (89, 7)
Duplicate rows: 0
Missing START: 0
Missing STOP: 75
Missing PATIENT: 0
Missing ENCOUNTER: 0
Missing CODE: 0
Missing DESCRIPTION: 0

========== CLEANED FILE SAVED ==========
Saved to: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\devices_cleaned.csv
File exists: True

========== RELOAD VERIFICATION ==========
Reloaded shape: (89, 7)
Duplicate rows: 0
START datatype: datetime64[us, UTC]
STOP datatype: datetime64[us, UTC]
STOP earlier than START after reload: 0

DATASET 16 — DEVICES CLEANING COMPLETED

In [71]:
# ============================================================
# DATASET 17 — IMAGING_STUDIES.CSV
# Cleaning + Validation + Save
# ============================================================

import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# 1. PATHS
# ------------------------------------------------------------

PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)

RAW_PATH = PROJECT_PATH / "data" / "Raw_Datasets"
CLEAN_PATH = PROJECT_PATH / "data" / "Cleaned_Datasets"

input_file = RAW_PATH / "imaging_studies.csv"
output_file = CLEAN_PATH / "imaging_studies_cleaned.csv"


# ------------------------------------------------------------
# 2. LOAD DATA
# ------------------------------------------------------------

imaging = pd.read_csv(input_file)

print("========== RAW DATASET ==========")
print("Shape:", imaging.shape)

print("\nColumns:")
print(imaging.columns.tolist())

print("\nData types:")
print(imaging.dtypes)


# ------------------------------------------------------------
# 3. MISSING VALUE CHECK
# ------------------------------------------------------------

print("\n========== MISSING VALUES ==========")

missing_values = imaging.isna().sum()
missing_percent = (missing_values / len(imaging) * 100).round(2)

missing_summary = pd.DataFrame({
    "Missing_Count": missing_values,
    "Missing_Percent": missing_percent
})

print(missing_summary)


# ------------------------------------------------------------
# 4. DUPLICATE CHECK
# ------------------------------------------------------------

print("\n========== DUPLICATE CHECK ==========")

duplicate_rows = imaging.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)


# ------------------------------------------------------------
# 5. DATE CONVERSION
# ------------------------------------------------------------

print("\n========== DATE CONVERSION ==========")

date_columns = []

for col in imaging.columns:

    if col.upper() in ["START", "STOP", "DATE"]:

        date_columns.append(col)


for col in date_columns:

    imaging[col] = pd.to_datetime(
        imaging[col],
        errors="coerce",
        utc=True
    )


print("Date columns converted:", date_columns)


for col in date_columns:

    print(
        f"\n{col} datatype:",
        imaging[col].dtype
    )

    print(
        f"Missing {col}:",
        imaging[col].isna().sum()
    )

    if imaging[col].notna().any():

        print(
            f"Minimum {col}:",
            imaging[col].min()
        )

        print(
            f"Maximum {col}:",
            imaging[col].max()
        )


# ------------------------------------------------------------
# 6. DATE LOGICAL VALIDATION
# ------------------------------------------------------------

if "START" in imaging.columns and "STOP" in imaging.columns:

    print("\n========== DATE LOGICAL VALIDATION ==========")

    invalid_dates = (
        imaging["STOP"].notna()
        & imaging["START"].notna()
        & (imaging["STOP"] < imaging["START"])
    ).sum()

    print(
        "STOP earlier than START:",
        invalid_dates
    )

    if invalid_dates > 0:

        imaging.loc[
            imaging["STOP"] < imaging["START"],
            "STOP"
        ] = pd.NaT

        print(
            "Invalid STOP dates converted to missing (NaT)."
        )

    else:

        print(
            "No invalid date ranges found."
        )


# ------------------------------------------------------------
# 7. IDENTIFIER VALIDATION
# ------------------------------------------------------------

print("\n========== IDENTIFIER VALIDATION ==========")

if "PATIENT" in imaging.columns:

    print(
        "Missing PATIENT:",
        imaging["PATIENT"].isna().sum()
    )

    print(
        "Unique PATIENT values:",
        imaging["PATIENT"].nunique()
    )


if "ENCOUNTER" in imaging.columns:

    print(
        "Missing ENCOUNTER:",
        imaging["ENCOUNTER"].isna().sum()
    )

    print(
        "Unique ENCOUNTER values:",
        imaging["ENCOUNTER"].nunique()
    )


# ------------------------------------------------------------
# 8. CODE / DESCRIPTION VALIDATION
# ------------------------------------------------------------

print("\n========== CODE / DESCRIPTION VALIDATION ==========")

if "CODE" in imaging.columns:

    print(
        "Missing CODE:",
        imaging["CODE"].isna().sum()
    )

    print(
        "Unique CODE values:",
        imaging["CODE"].nunique()
    )


if "DESCRIPTION" in imaging.columns:

    print(
        "Missing DESCRIPTION:",
        imaging["DESCRIPTION"].isna().sum()
    )

    print(
        "Unique DESCRIPTION values:",
        imaging["DESCRIPTION"].nunique()
    )


# ------------------------------------------------------------
# 9. MODALITY / BODYSITE VALIDATION
# ------------------------------------------------------------

print("\n========== IMAGING FIELD VALIDATION ==========")

if "MODALITY_CODE" in imaging.columns:

    print(
        "Missing MODALITY_CODE:",
        imaging["MODALITY_CODE"].isna().sum()
    )

    print(
        "Unique MODALITY_CODE values:",
        imaging["MODALITY_CODE"].nunique()
    )


if "MODALITY_DESCRIPTION" in imaging.columns:

    print(
        "Missing MODALITY_DESCRIPTION:",
        imaging["MODALITY_DESCRIPTION"].isna().sum()
    )

    print(
        "Unique MODALITY_DESCRIPTION values:",
        imaging["MODALITY_DESCRIPTION"].nunique()
    )


if "BODYSITE_CODE" in imaging.columns:

    print(
        "Missing BODYSITE_CODE:",
        imaging["BODYSITE_CODE"].isna().sum()
    )

    print(
        "Unique BODYSITE_CODE values:",
        imaging["BODYSITE_CODE"].nunique()
    )


if "BODYSITE_DESCRIPTION" in imaging.columns:

    print(
        "Missing BODYSITE_DESCRIPTION:",
        imaging["BODYSITE_DESCRIPTION"].isna().sum()
    )

    print(
        "Unique BODYSITE_DESCRIPTION values:",
        imaging["BODYSITE_DESCRIPTION"].nunique()
    )


# ------------------------------------------------------------
# 10. NUMERIC / FINANCIAL CHECK
# ------------------------------------------------------------

print("\n========== NUMERIC / FINANCIAL CHECK ==========")

numeric_columns = imaging.select_dtypes(
    include="number"
).columns.tolist()

print(
    "Numeric columns:",
    numeric_columns
)

for col in numeric_columns:

    print(f"\n{col}")

    print(
        "Minimum:",
        imaging[col].min()
    )

    print(
        "Maximum:",
        imaging[col].max()
    )

    print(
        "Negative values:",
        (imaging[col] < 0).sum()
    )


# ------------------------------------------------------------
# 11. REFERENCE INTEGRITY
# ------------------------------------------------------------

print("\n========== REFERENCE INTEGRITY ==========")

patients_file = CLEAN_PATH / "patients_cleaned.csv"
encounters_file = CLEAN_PATH / "encounters_cleaned.csv"

if "PATIENT" in imaging.columns and patients_file.exists():

    patients = pd.read_csv(
        patients_file,
        usecols=["Id"]
    )

    invalid_patients = (
        ~imaging["PATIENT"].isin(
            patients["Id"]
        )
    ).sum()

    print(
        "Invalid PATIENT references:",
        invalid_patients
    )


if "ENCOUNTER" in imaging.columns and encounters_file.exists():

    encounters = pd.read_csv(
        encounters_file,
        usecols=["Id"]
    )

    invalid_encounters = (
        ~imaging["ENCOUNTER"].isin(
            encounters["Id"]
        )
    ).sum()

    print(
        "Invalid ENCOUNTER references:",
        invalid_encounters
    )


# ------------------------------------------------------------
# 12. UTILIZATION CHECK
# ------------------------------------------------------------

print("\n========== UTILIZATION CHECK ==========")

if "ENCOUNTER" in imaging.columns:

    imaging_per_encounter = (
        imaging.groupby("ENCOUNTER")
        .size()
    )

    print(
        "Average imaging records per encounter:",
        imaging_per_encounter.mean()
    )

    print(
        "Median imaging records per encounter:",
        imaging_per_encounter.median()
    )

    print(
        "Maximum imaging records per encounter:",
        imaging_per_encounter.max()
    )


if "PATIENT" in imaging.columns:

    imaging_per_patient = (
        imaging.groupby("PATIENT")
        .size()
    )

    print(
        "Average imaging records per patient:",
        imaging_per_patient.mean()
    )

    print(
        "Median imaging records per patient:",
        imaging_per_patient.median()
    )

    print(
        "Maximum imaging records per patient:",
        imaging_per_patient.max()
    )


# ------------------------------------------------------------
# 13. REMOVE EXACT DUPLICATES
# ------------------------------------------------------------

print("\n========== DUPLICATE REMOVAL ==========")

before_duplicates = len(imaging)

imaging = imaging.drop_duplicates().copy()

after_duplicates = len(imaging)

print(
    "Rows before duplicate removal:",
    before_duplicates
)

print(
    "Rows after duplicate removal:",
    after_duplicates
)

print(
    "Rows removed:",
    before_duplicates - after_duplicates
)


# ------------------------------------------------------------
# 14. FINAL VALIDATION
# ------------------------------------------------------------

print("\n========== FINAL VALIDATION ==========")

print(
    "Final shape:",
    imaging.shape
)

print(
    "Duplicate rows:",
    imaging.duplicated().sum()
)

for col in date_columns:

    print(
        f"Missing {col}:",
        imaging[col].isna().sum()
    )


if "PATIENT" in imaging.columns:

    print(
        "Missing PATIENT:",
        imaging["PATIENT"].isna().sum()
    )


if "ENCOUNTER" in imaging.columns:

    print(
        "Missing ENCOUNTER:",
        imaging["ENCOUNTER"].isna().sum()
    )


if "CODE" in imaging.columns:

    print(
        "Missing CODE:",
        imaging["CODE"].isna().sum()
    )


if "DESCRIPTION" in imaging.columns:

    print(
        "Missing DESCRIPTION:",
        imaging["DESCRIPTION"].isna().sum()
    )


# ------------------------------------------------------------
# 15. SAVE CLEANED DATASET
# ------------------------------------------------------------

imaging.to_csv(
    output_file,
    index=False
)

print("\n========== CLEANED FILE SAVED ==========")

print(
    "Saved to:",
    output_file
)

print(
    "File exists:",
    output_file.exists()
)


# ------------------------------------------------------------
# 16. RELOAD VERIFICATION
# ------------------------------------------------------------

verified = pd.read_csv(output_file)

for col in date_columns:

    verified[col] = pd.to_datetime(
        verified[col],
        errors="coerce",
        utc=True
    )


print("\n========== RELOAD VERIFICATION ==========")

print(
    "Reloaded shape:",
    verified.shape
)

print(
    "Duplicate rows:",
    verified.duplicated().sum()
)

for col in date_columns:

    print(
        f"{col} datatype:",
        verified[col].dtype
    )


if "START" in verified.columns and "STOP" in verified.columns:

    invalid_after_reload = (
        verified["STOP"].notna()
        & verified["START"].notna()
        & (verified["STOP"] < verified["START"])
    ).sum()

    print(
        "STOP earlier than START after reload:",
        invalid_after_reload
    )


print("\nDATASET 17 — IMAGING STUDIES CLEANING COMPLETED")

========== RAW DATASET ==========
Shape: (151637, 13)

Columns:
['Id', 'DATE', 'PATIENT', 'ENCOUNTER', 'SERIES_UID', 'BODYSITE_CODE', 'BODYSITE_DESCRIPTION', 'MODALITY_CODE', 'MODALITY_DESCRIPTION', 'INSTANCE_UID', 'SOP_CODE', 'SOP_DESCRIPTION', 'PROCEDURE_CODE']

Data types:
Id                        str
DATE                      str
PATIENT                   str
ENCOUNTER                 str
SERIES_UID                str
BODYSITE_CODE           int64
BODYSITE_DESCRIPTION      str
MODALITY_CODE             str
MODALITY_DESCRIPTION      str
INSTANCE_UID              str
SOP_CODE                  str
SOP_DESCRIPTION           str
PROCEDURE_CODE          int64
dtype: object

========== MISSING VALUES ==========
                      Missing_Count  Missing_Percent
Id                                0              0.0
DATE                              0              0.0
PATIENT                           0              0.0
ENCOUNTER                         0              0.0
SERIES_UID                        0              0.0
BODYSITE_CODE                     0              0.0
BODYSITE_DESCRIPTION              0              0.0
MODALITY_CODE                     0              0.0
MODALITY_DESCRIPTION              0              0.0
INSTANCE_UID                      0              0.0
SOP_CODE                          0              0.0
SOP_DESCRIPTION                   0              0.0
PROCEDURE_CODE                    0              0.0

========== DUPLICATE CHECK ==========
Duplicate complete rows: 0

========== DATE CONVERSION ==========
Date columns converted: ['DATE']

DATE datatype: datetime64[us, UTC]
Missing DATE: 0
Minimum DATE: 1931-07-31 08:46:25+00:00
Maximum DATE: 2021-11-18 16:26:22+00:00

========== IDENTIFIER VALIDATION ==========
Missing PATIENT: 0
Unique PATIENT values: 238
Missing ENCOUNTER: 0
Unique ENCOUNTER values: 920

========== CODE / DESCRIPTION VALIDATION ==========

========== IMAGING FIELD VALIDATION ==========
Missing MODALITY_CODE: 0
Unique MODALITY_CODE values: 4
Missing MODALITY_DESCRIPTION: 0
Unique MODALITY_DESCRIPTION values: 4
Missing BODYSITE_CODE: 0
Unique BODYSITE_CODE values: 9
Missing BODYSITE_DESCRIPTION: 0
Unique BODYSITE_DESCRIPTION values: 10

========== NUMERIC / FINANCIAL CHECK ==========
Numeric columns: ['BODYSITE_CODE', 'PROCEDURE_CODE']

BODYSITE_CODE
Minimum: 344001
Maximum: 80891009
Negative values: 0

PROCEDURE_CODE
Minimum: 1225002
Maximum: 16335031000119103
Negative values: 0

========== REFERENCE INTEGRITY ==========
Invalid PATIENT references: 0
Invalid ENCOUNTER references: 0

========== UTILIZATION CHECK ==========
Average imaging records per encounter: 164.82282608695652
Median imaging records per encounter: 1.0
Maximum imaging records per encounter: 500
Average imaging records per patient: 637.1302521008404
Median imaging records per patient: 1.0
Maximum imaging records per patient: 27816

========== DUPLICATE REMOVAL ==========
Rows before duplicate removal: 151637
Rows after duplicate removal: 151637
Rows removed: 0

========== FINAL VALIDATION ==========
Final shape: (151637, 13)
Duplicate rows: 0
Missing DATE: 0
Missing PATIENT: 0
Missing ENCOUNTER: 0

========== CLEANED FILE SAVED ==========
Saved to: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\imaging_studies_cleaned.csv
File exists: True

========== RELOAD VERIFICATION ==========
Reloaded shape: (151637, 13)
Duplicate rows: 0
DATE datatype: datetime64[us, UTC]

DATASET 17 — IMAGING STUDIES CLEANING COMPLETED

In [72]:
# ============================================================
# DATASET 18 — SUPPLIES.CSV
# DATA CLEANING & VALIDATION
# ============================================================

import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# 1. PATHS
# ------------------------------------------------------------

PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)

RAW_PATH = PROJECT_PATH / "data" / "Raw_Datasets"
CLEAN_PATH = PROJECT_PATH / "data" / "Cleaned_Datasets"

INPUT_FILE = RAW_PATH / "supplies.csv"
OUTPUT_FILE = CLEAN_PATH / "supplies_cleaned.csv"


# ------------------------------------------------------------
# 2. LOAD RAW DATASET
# ------------------------------------------------------------

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("========== RAW DATASET ==========")
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)


# ------------------------------------------------------------
# 3. MISSING VALUE CHECK
# ------------------------------------------------------------

print("\n========== MISSING VALUES ==========")

missing = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percent": (df.isna().mean() * 100).round(2)
})

print(missing)


# ------------------------------------------------------------
# 4. DUPLICATE CHECK
# ------------------------------------------------------------

print("\n========== DUPLICATE CHECK ==========")

duplicate_rows = df.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)


# ------------------------------------------------------------
# 5. DATE COLUMN DETECTION & CONVERSION
# ------------------------------------------------------------

print("\n========== DATE CONVERSION ==========")

date_columns = [
    col for col in df.columns
    if col.upper() in ["DATE", "START", "STOP"]
]

for col in date_columns:
    df[col] = pd.to_datetime(
        df[col],
        errors="coerce",
        utc=True
    )

print("Date columns converted:", date_columns)

for col in date_columns:
    print(f"\n{col} datatype:", df[col].dtype)
    print(f"Missing {col}:", df[col].isna().sum())

    if df[col].notna().any():
        print(f"Minimum {col}:", df[col].min())
        print(f"Maximum {col}:", df[col].max())


# ------------------------------------------------------------
# 6. DATE LOGICAL VALIDATION
# ------------------------------------------------------------

if "START" in df.columns and "STOP" in df.columns:

    print("\n========== DATE LOGICAL VALIDATION ==========")

    invalid_dates = (
        (df["STOP"].notna()) &
        (df["START"].notna()) &
        (df["STOP"] < df["START"])
    ).sum()

    print("STOP earlier than START:", invalid_dates)

    # Set logically invalid STOP values to missing
    if invalid_dates > 0:
        df.loc[
            df["STOP"] < df["START"],
            "STOP"
        ] = pd.NaT

        print(
            "Invalid STOP values converted to missing:",
            invalid_dates
        )


# ------------------------------------------------------------
# 7. IDENTIFIER VALIDATION
# ------------------------------------------------------------

print("\n========== IDENTIFIER VALIDATION ==========")

for col in ["PATIENT", "ENCOUNTER"]:

    if col in df.columns:
        print(f"Missing {col}:", df[col].isna().sum())
        print(
            f"Unique {col} values:",
            df[col].nunique()
        )


# ------------------------------------------------------------
# 8. CODE / DESCRIPTION VALIDATION
# ------------------------------------------------------------

print("\n========== CODE / DESCRIPTION VALIDATION ==========")

for col in [
    "CODE",
    "DESCRIPTION"
]:

    if col in df.columns:

        print(f"\n{col}")

        print(
            "Missing:",
            df[col].isna().sum()
        )

        print(
            "Unique values:",
            df[col].nunique()
        )


# ------------------------------------------------------------
# 9. NUMERIC / FINANCIAL VALIDATION
# ------------------------------------------------------------

print("\n========== NUMERIC / FINANCIAL CHECK ==========")

numeric_columns = df.select_dtypes(
    include=["number"]
).columns.tolist()

print("Numeric columns:", numeric_columns)

for col in numeric_columns:

    print(f"\n{col}")

    print("Minimum:", df[col].min())
    print("Maximum:", df[col].max())
    print(
        "Negative values:",
        (df[col] < 0).sum()
    )


# ------------------------------------------------------------
# 10. REFERENCE INTEGRITY
# ------------------------------------------------------------

print("\n========== REFERENCE INTEGRITY ==========")


# Patient reference validation
if "PATIENT" in df.columns:

    patients_file = CLEAN_PATH / "patients_cleaned.csv"

    if patients_file.exists():

        patients = pd.read_csv(
            patients_file,
            usecols=["Id"]
        )

        valid_patients = set(
            patients["Id"].dropna()
        )

        invalid_patient_refs = (
            ~df["PATIENT"].isin(valid_patients)
        ).sum()

        print(
            "Invalid PATIENT references:",
            invalid_patient_refs
        )

    else:
        print(
            "patients_cleaned.csv not found — "
            "patient reference validation skipped."
        )


# Encounter reference validation
if "ENCOUNTER" in df.columns:

    encounters_file = CLEAN_PATH / "encounters_cleaned.csv"

    if encounters_file.exists():

        encounters = pd.read_csv(
            encounters_file,
            usecols=["Id"]
        )

        valid_encounters = set(
            encounters["Id"].dropna()
        )

        invalid_encounter_refs = (
            ~df["ENCOUNTER"].isin(valid_encounters)
        ).sum()

        print(
            "Invalid ENCOUNTER references:",
            invalid_encounter_refs
        )

    else:
        print(
            "encounters_cleaned.csv not found — "
            "encounter reference validation skipped."
        )


# ------------------------------------------------------------
# 11. UTILIZATION CHECK
# ------------------------------------------------------------

print("\n========== UTILIZATION CHECK ==========")

if "ENCOUNTER" in df.columns:

    encounter_counts = df.groupby(
        "ENCOUNTER"
    ).size()

    print(
        "Average supplies records per encounter:",
        encounter_counts.mean()
    )

    print(
        "Median supplies records per encounter:",
        encounter_counts.median()
    )

    print(
        "Maximum supplies records per encounter:",
        encounter_counts.max()
    )


if "PATIENT" in df.columns:

    patient_counts = df.groupby(
        "PATIENT"
    ).size()

    print(
        "Average supplies records per patient:",
        patient_counts.mean()
    )

    print(
        "Median supplies records per patient:",
        patient_counts.median()
    )

    print(
        "Maximum supplies records per patient:",
        patient_counts.max()
    )


# ------------------------------------------------------------
# 12. REMOVE EXACT DUPLICATES
# ------------------------------------------------------------

print("\n========== DUPLICATE REMOVAL ==========")

rows_before = len(df)

df = df.drop_duplicates().reset_index(drop=True)

rows_after = len(df)

print("Rows before duplicate removal:", rows_before)
print("Rows after duplicate removal:", rows_after)
print("Rows removed:", rows_before - rows_after)


# ------------------------------------------------------------
# 13. FINAL VALIDATION
# ------------------------------------------------------------

print("\n========== FINAL VALIDATION ==========")

print("Final shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())

if "DATE" in df.columns:
    print("Missing DATE:", df["DATE"].isna().sum())

if "START" in df.columns:
    print("Missing START:", df["START"].isna().sum())

if "STOP" in df.columns:
    print("Missing STOP:", df["STOP"].isna().sum())

if "PATIENT" in df.columns:
    print("Missing PATIENT:", df["PATIENT"].isna().sum())

if "ENCOUNTER" in df.columns:
    print("Missing ENCOUNTER:", df["ENCOUNTER"].isna().sum())


# ------------------------------------------------------------
# 14. SAVE CLEANED DATASET
# ------------------------------------------------------------

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print("\n========== CLEANED FILE SAVED ==========")

print("Saved to:", OUTPUT_FILE)
print("File exists:", OUTPUT_FILE.exists())


# ------------------------------------------------------------
# 15. RELOAD VERIFICATION
# ------------------------------------------------------------

print("\n========== RELOAD VERIFICATION ==========")

df_check = pd.read_csv(
    OUTPUT_FILE,
    low_memory=False
)

print("Reloaded shape:", df_check.shape)
print(
    "Duplicate rows:",
    df_check.duplicated().sum()
)

for col in ["DATE", "START", "STOP"]:

    if col in df_check.columns:

        # Convert only for verification
        df_check[col] = pd.to_datetime(
            df_check[col],
            errors="coerce",
            utc=True
        )

        print(
            f"{col} datatype:",
            df_check[col].dtype
        )


print("\nDATASET 18 — SUPPLIES CLEANING COMPLETED")

========== RAW DATASET ==========
Shape: (1573, 6)

Columns:
['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'QUANTITY']

Data types:
DATE             str
PATIENT          str
ENCOUNTER        str
CODE           int64
DESCRIPTION      str
QUANTITY       int64
dtype: object

========== MISSING VALUES ==========
             Missing_Count  Missing_Percent
DATE                     0              0.0
PATIENT                  0              0.0
ENCOUNTER                0              0.0
CODE                     0              0.0
DESCRIPTION              0              0.0
QUANTITY                 0              0.0

========== DUPLICATE CHECK ==========
Duplicate complete rows: 0

========== DATE CONVERSION ==========
Date columns converted: ['DATE']

DATE datatype: datetime64[us, UTC]
Missing DATE: 0
Minimum DATE: 2020-05-02 00:00:00+00:00
Maximum DATE: 2021-09-01 00:00:00+00:00

========== IDENTIFIER VALIDATION ==========
Missing PATIENT: 0
Unique PATIENT values: 20
Missing ENCOUNTER: 0
Unique ENCOUNTER values: 25

========== CODE / DESCRIPTION VALIDATION ==========

CODE
Missing: 0
Unique values: 20

DESCRIPTION
Missing: 0
Unique values: 20

========== NUMERIC / FINANCIAL CHECK ==========
Numeric columns: ['CODE', 'QUANTITY']

CODE
Minimum: 17102003
Maximum: 827149008
Negative values: 0

QUANTITY
Minimum: 1
Maximum: 44
Negative values: 0

========== REFERENCE INTEGRITY ==========
Invalid PATIENT references: 0
Invalid ENCOUNTER references: 0

========== UTILIZATION CHECK ==========
Average supplies records per encounter: 62.92
Median supplies records per encounter: 66.0
Maximum supplies records per encounter: 88
Average supplies records per patient: 78.65
Median supplies records per patient: 72.0
Maximum supplies records per patient: 148

========== DUPLICATE REMOVAL ==========
Rows before duplicate removal: 1573
Rows after duplicate removal: 1573
Rows removed: 0

========== FINAL VALIDATION ==========
Final shape: (1573, 6)
Duplicate rows: 0
Missing DATE: 0
Missing PATIENT: 0
Missing ENCOUNTER: 0

========== CLEANED FILE SAVED ==========
Saved to: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\supplies_cleaned.csv
File exists: True

========== RELOAD VERIFICATION ==========
Reloaded shape: (1573, 6)
Duplicate rows: 0
DATE datatype: datetime64[us, UTC]

DATASET 18 — SUPPLIES CLEANING COMPLETED