In [109]:
from pathlib import Path
import pandas as pd

# ============================================================
# 1. PROJECT PATH
# ============================================================

PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)


# ============================================================
# 2. FOLDER PATHS
# ============================================================

CLEAN_PATH = PROJECT_PATH / "data" / "Cleaned_Datasets"

ANALYTICAL_PATH = PROJECT_PATH / "data" / "Analytical_Dataset"


# ============================================================
# 3. LOAD THE BASE DATASET
# ============================================================

# Our analytical grain is:
# 1 row = 1 healthcare encounter

encounters = pd.read_csv(
    CLEAN_PATH / "encounters_cleaned.csv"
)


# ============================================================
# 4. CHECK WHETHER DATA LOADED CORRECTLY
# ============================================================

print("Encounters dataset loaded successfully!")
print()

print("Number of rows and columns:")
print(encounters.shape)

print()

print("Column names:")
print(encounters.columns.tolist())

print()

print("First 5 rows:")
display(encounters.head())

Encounters dataset loaded successfully!

Number of rows and columns:
(61459, 15)

Column names:
['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PROVIDER', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION']

First 5 rows:

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,748f8357-6cc7-551d-f31a-32fa2cf84126,2019-02-17 05:07:38+00:00,2019-02-17 05:22:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,877.79,833.90,NaN,NaN
1,5a4735ae-423f-6563-28ab-b3d11b49b2d4,2019-03-24 05:07:38+00:00,2019-03-24 05:22:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,269.68,256.20,NaN,NaN
2,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,2019-05-26 05:07:38+00:00,2019-05-26 05:22:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,1292.75,1228.11,NaN,NaN
3,6e93bcf9-45a4-8528-0120-1c1eaa930faf,2019-07-28 05:07:38+00:00,2019-07-28 05:22:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,1323.87,1257.68,NaN,NaN
4,8b6787c3-4316-a0cb-899d-4746525c319f,2019-10-27 05:07:38+00:00,2019-10-27 05:22:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,831.76,790.17,NaN,NaN

In [110]:
# ============================================================
# STEP 2 — VALIDATE THE BASE ENCOUNTERS DATASET
# ============================================================

print("Checking the base encounters dataset...")
print()


# ------------------------------------------------------------
# 1. CHECK DUPLICATE ENCOUNTER IDs
# ------------------------------------------------------------

duplicate_ids = encounters["Id"].duplicated().sum()

print("Duplicate Encounter IDs:", duplicate_ids)


# ------------------------------------------------------------
# 2. CHECK DUPLICATE COMPLETE ROWS
# ------------------------------------------------------------

duplicate_rows = encounters.duplicated().sum()

print("Duplicate Complete Rows:", duplicate_rows)


# ------------------------------------------------------------
# 3. CHECK MISSING ENCOUNTER IDs
# ------------------------------------------------------------

missing_ids = encounters["Id"].isna().sum()

print("Missing Encounter IDs:", missing_ids)


# ------------------------------------------------------------
# 4. CHECK MISSING TOTAL CLAIM COST
# ------------------------------------------------------------

missing_cost = encounters["TOTAL_CLAIM_COST"].isna().sum()

print("Missing TOTAL_CLAIM_COST:", missing_cost)


# ------------------------------------------------------------
# 5. CHECK NEGATIVE TOTAL CLAIM COST
# ------------------------------------------------------------

negative_cost = (encounters["TOTAL_CLAIM_COST"] < 0).sum()

print("Negative TOTAL_CLAIM_COST:", negative_cost)


# ------------------------------------------------------------
# 6. FINAL SUMMARY
# ------------------------------------------------------------

print()
print("Total Encounters:", len(encounters))

print()
print("Base dataset validation completed.")

Checking the base encounters dataset...

Duplicate Encounter IDs: 0
Duplicate Complete Rows: 0
Missing Encounter IDs: 0
Missing TOTAL_CLAIM_COST: 0
Negative TOTAL_CLAIM_COST: 0

Total Encounters: 61459

Base dataset validation completed.

In [111]:
# ============================================================
# STEP 3 — LOAD AND VALIDATE PATIENTS DATASET
# ============================================================

# ------------------------------------------------------------
# 1. LOAD PATIENTS DATASET
# ------------------------------------------------------------

patients = pd.read_csv(
    CLEAN_PATH / "patients_cleaned.csv"
)

print("Patients dataset loaded successfully!")
print()


# ------------------------------------------------------------
# 2. BASIC INFORMATION
# ------------------------------------------------------------

print("Number of rows and columns:")
print(patients.shape)

print()

print("Column names:")
print(patients.columns.tolist())

print()

print("First 5 rows:")
display(patients.head())


# ------------------------------------------------------------
# 3. CHECK PATIENT IDs
# ------------------------------------------------------------

print()
print("Checking Patient IDs...")

duplicate_patient_ids = patients["Id"].duplicated().sum()
missing_patient_ids = patients["Id"].isna().sum()

print("Duplicate Patient IDs:", duplicate_patient_ids)
print("Missing Patient IDs:", missing_patient_ids)


# ------------------------------------------------------------
# 4. CHECK WHETHER ALL ENCOUNTER PATIENT IDs
#    EXIST IN THE PATIENTS DATASET
# ------------------------------------------------------------

encounter_patient_ids = set(encounters["PATIENT"].dropna())
patient_ids = set(patients["Id"].dropna())

missing_patient_references = encounter_patient_ids - patient_ids

print()
print(
    "Patient IDs in encounters but missing from patients:",
    len(missing_patient_references)
)


# ------------------------------------------------------------
# 5. FINAL VALIDATION
# ------------------------------------------------------------

print()
print("Patients dataset validation completed.")

Patients dataset loaded successfully!

Number of rows and columns:
(1163, 25)

Column names:
['Id', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT', 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE']

First 5 rows:

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,2019-02-17,NaN,999-65-3251,NaN,NaN,NaN,Damon455,Langosh790,NaN,...,Middleborough Massachusetts US,620 Lynch Tunnel Apt 0,Springfield,Massachusetts,Hampden County,1104.0,42.080389,-72.480431,9039.1645,7964.1255
1,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,2005-07-04,NaN,999-49-3323,S99941126,NaN,NaN,Thi53,Wunsch504,NaN,...,Danvers Massachusetts US,972 Tillman Branch Suite 48,Bellingham,Massachusetts,Norfolk County,NaN,42.035213,-71.482519,402723.4150,14064.1350
2,339144f8-50e1-633e-a013-f361391c4cff,1998-05-11,NaN,999-10-8743,S99996708,X75063318X,Mr.,Chi716,Greenfelder433,NaN,...,Athens Athens Prefecture GR,1060 Bernhard Crossroad Suite 15,Boston,Massachusetts,Suffolk County,2131.0,42.292557,-71.061160,571935.8725,787.5375
3,d488232e-bf14-4bed-08c0-a82f34b6a197,2003-01-28,NaN,999-56-6057,S99929424,NaN,Ms.,Phillis443,Walter473,NaN,...,Boston Massachusetts US,677 Ritchie Terrace,Hingham,Massachusetts,Plymouth County,2043.0,42.200491,-70.916076,582557.8030,104782.2070
4,217f95a3-4e10-bd5d-fb67-0cfb5e8ba075,1993-12-23,NaN,999-91-4320,S99991143,X44132498X,Mr.,Jerrold404,Herzog843,NaN,...,Boston Massachusetts US,276 Bernier Branch,Revere,Massachusetts,Suffolk County,NaN,42.381875,-70.999286,475826.8550,18067.0950

Checking Patient IDs...
Duplicate Patient IDs: 0
Missing Patient IDs: 0

Patient IDs in encounters but missing from patients: 0

Patients dataset validation completed.

In [112]:
# ============================================================
# STEP 4 — PREPARE PATIENT INFORMATION (CORRECTED)
# ============================================================

# ------------------------------------------------------------
# 1. SELECT ONLY THE PATIENT COLUMNS WE NEED
# ------------------------------------------------------------

patient_features = patients[
    [
        "Id",
        "BIRTHDATE",
        "GENDER",
        "RACE",
        "ETHNICITY",
        "MARITAL"
    ]
].copy()


# ------------------------------------------------------------
# 2. CONVERT DATES
# ------------------------------------------------------------

patient_features["BIRTHDATE"] = pd.to_datetime(
    patient_features["BIRTHDATE"],
    errors="coerce",
    utc=True
)

encounters["START"] = pd.to_datetime(
    encounters["START"],
    errors="coerce",
    utc=True
)


# ------------------------------------------------------------
# 3. MERGE PATIENT INFORMATION WITH ENCOUNTERS
# ------------------------------------------------------------

master = encounters.merge(
    patient_features,
    left_on="PATIENT",
    right_on="Id",
    how="left",
    suffixes=("", "_PATIENT")
)


# ------------------------------------------------------------
# 4. CALCULATE AGE AT THE TIME OF ENCOUNTER
# ------------------------------------------------------------

master["AGE_AT_ENCOUNTER"] = (
    (master["START"] - master["BIRTHDATE"]).dt.days / 365.25
).round(1)


# ------------------------------------------------------------
# 5. REMOVE THE PATIENT TABLE ID
# ------------------------------------------------------------

master.drop(
    columns=["Id_PATIENT"],
    inplace=True,
    errors="ignore"
)


# ------------------------------------------------------------
# 6. CHECK THE RESULT
# ------------------------------------------------------------

print("Patient information added successfully!")
print()

print("Master dataset shape:", master.shape)

print()

print("Master dataset columns:")
print(master.columns.tolist())

print()

print("Patient-related information:")
display(
    master[
        [
            "PATIENT",
            "START",
            "TOTAL_CLAIM_COST",
            "AGE_AT_ENCOUNTER",
            "GENDER",
            "RACE",
            "ETHNICITY",
            "MARITAL"
        ]
    ].head()
)

Patient information added successfully!

Master dataset shape: (61459, 21)

Master dataset columns:
['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PROVIDER', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION', 'BIRTHDATE', 'GENDER', 'RACE', 'ETHNICITY', 'MARITAL', 'AGE_AT_ENCOUNTER']

Patient-related information:

,PATIENT,START,TOTAL_CLAIM_COST,AGE_AT_ENCOUNTER,GENDER,RACE,ETHNICITY,MARITAL
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,2019-02-17 05:07:38+00:00,877.79,0.0,M,white,nonhispanic,NaN
1,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,2019-03-24 05:07:38+00:00,269.68,0.1,M,white,nonhispanic,NaN
2,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,2019-05-26 05:07:38+00:00,1292.75,0.3,M,white,nonhispanic,NaN
3,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,2019-07-28 05:07:38+00:00,1323.87,0.4,M,white,nonhispanic,NaN
4,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,2019-10-27 05:07:38+00:00,831.76,0.7,M,white,nonhispanic,NaN

In [113]:
# ============================================================
# STEP 5 — VALIDATE PATIENT INFORMATION MERGE
# ============================================================

print("Validating patient information in the master dataset...")
print()


# ------------------------------------------------------------
# 1. CHECK MASTER ROW COUNT
# ------------------------------------------------------------

print("Master rows:", len(master))
print("Original encounter rows:", len(encounters))


# ------------------------------------------------------------
# 2. CHECK DUPLICATE ENCOUNTER IDs
# ------------------------------------------------------------

duplicate_master_ids = master["Id"].duplicated().sum()

print()
print("Duplicate Encounter IDs in master:", duplicate_master_ids)


# ------------------------------------------------------------
# 3. CHECK MISSING PATIENT INFORMATION
# ------------------------------------------------------------

missing_gender = master["GENDER"].isna().sum()
missing_race = master["RACE"].isna().sum()
missing_ethnicity = master["ETHNICITY"].isna().sum()
missing_birthdate = master["BIRTHDATE"].isna().sum()

print()
print("Missing GENDER:", missing_gender)
print("Missing RACE:", missing_race)
print("Missing ETHNICITY:", missing_ethnicity)
print("Missing BIRTHDATE:", missing_birthdate)


# ------------------------------------------------------------
# 4. CHECK AGE VALUES
# ------------------------------------------------------------

negative_age = (master["AGE_AT_ENCOUNTER"] < 0).sum()

print()
print("Negative AGE_AT_ENCOUNTER:", negative_age)


# ------------------------------------------------------------
# 5. CHECK AGE SUMMARY
# ------------------------------------------------------------

print()
print("Age summary:")

display(
    master["AGE_AT_ENCOUNTER"].describe()
)


# ------------------------------------------------------------
# 6. FINAL CHECK
# ------------------------------------------------------------

print()
print("Patient merge validation completed.")

Validating patient information in the master dataset...

Master rows: 61459
Original encounter rows: 61459

Duplicate Encounter IDs in master: 0

Missing GENDER: 0
Missing RACE: 0
Missing ETHNICITY: 0
Missing BIRTHDATE: 0

Negative AGE_AT_ENCOUNTER: 0

Age summary:

count    61459.000000
mean        42.991300
std         24.133173
min          0.000000
25%         22.900000
50%         42.000000
75%         60.900000
max        109.900000
Name: AGE_AT_ENCOUNTER, dtype: float64

Patient merge validation completed.

In [114]:
conditions = pd.read_csv(
    CLEAN_PATH / "conditions_cleaned.csv"
)

print("Conditions dataset loaded successfully!")
print()
print("Shape:")
print(conditions.shape)
print()
print("Columns:")
print(conditions.columns.tolist())
print()
print("First 5 rows:")
display(conditions.head())

Conditions dataset loaded successfully!

Shape:
(38094, 6)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION']

First 5 rows:

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION
0,2013-06-24,2013-07-02,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,0b2794bd-ec2b-d34f-0610-2523b3b7fcf0,10509002,Acute bronchitis (disorder)
1,2016-02-27,2016-03-14,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,a6d818dd-0983-fd1c-eefa-3d2295532c45,283371005,Laceration of forearm
2,2016-08-11,2016-08-22,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,36d2e781-4655-0a11-1f70-c69856e02019,444814009,Viral sinusitis (disorder)
3,2016-11-27,2016-12-17,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,c8eaaf41-958b-31ab-7de5-568cee8751f3,444814009,Viral sinusitis (disorder)
4,2017-02-22,2017-06-02,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,6474f606-5a1b-48c0-bbbf-ad6dcbc24d4e,16114001,Fracture of ankle

In [116]:
# Conditions-la irukkura Encounter IDs
condition_encounters = set(conditions["ENCOUNTER"].dropna())

# Master-la irukkura Encounter IDs
master_encounters = set(master["Id"].dropna())

# Conditions-la irundhu Master-la illaadha Encounter IDs
invalid_condition_encounters = condition_encounters - master_encounters

print("Unique Encounter IDs in Conditions:", len(condition_encounters))
print("Unique Encounter IDs in Master:", len(master_encounters))
print("Condition Encounter IDs not found in Master:", len(invalid_condition_encounters))

Unique Encounter IDs in Conditions: 26904
Unique Encounter IDs in Master: 61459
Condition Encounter IDs not found in Master: 0

In [117]:
condition_summary = (
    conditions
    .groupby("ENCOUNTER")
    .size()
    .reset_index(name="condition_count")
)

print("Condition summary created successfully!")
print()
print("Shape:", condition_summary.shape)
print()
print("First 5 rows:")
display(condition_summary.head())

Condition summary created successfully!

Shape: (26904, 2)

First 5 rows:

                              ENCOUNTER  condition_count
0  00028cd4-8eec-a663-514b-36e3822858d4                1
1  0005f642-bbdc-155f-e9f0-f28e8f042b35                3
2  00067119-65e8-91d6-c8b5-4dcb2e8b55bf                2
3  000bdc1d-5ad5-704d-1756-7ec7232c7f21                1
4  00153ad0-c3ca-6dcd-42ea-9f5df0d65f63                1

In [118]:
master = master.merge(
    condition_summary,
    left_on="Id",
    right_on="ENCOUNTER",
    how="left"
)

# Conditions record illaadha encounters-ku 0
master["condition_count"] = (
    master["condition_count"]
    .fillna(0)
    .astype(int)
)

# Extra ENCOUNTER column remove pannuvom
master.drop(
    columns=["ENCOUNTER"],
    inplace=True
)

print("Conditions merged into master successfully!")
print()
print("Master shape:", master.shape)
print()
print("First 5 rows:")
display(
    master[
        ["Id", "PATIENT", "ENCOUNTERCLASS", "TOTAL_CLAIM_COST", "condition_count"]
    ].head()
)

Conditions merged into master successfully!

Master shape: (61459, 22)

First 5 rows:

,Id,PATIENT,ENCOUNTERCLASS,TOTAL_CLAIM_COST,condition_count
0,748f8357-6cc7-551d-f31a-32fa2cf84126,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,wellness,877.79,0
1,5a4735ae-423f-6563-28ab-b3d11b49b2d4,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,wellness,269.68,0
2,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,wellness,1292.75,0
3,6e93bcf9-45a4-8528-0120-1c1eaa930faf,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,wellness,1323.87,0
4,8b6787c3-4316-a0cb-899d-4746525c319f,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,wellness,831.76,0

In [119]:
print("Master rows:", len(master))
print("Duplicate Encounter IDs:", master["Id"].duplicated().sum())
print("Missing condition_count:", master["condition_count"].isna().sum())
print("Minimum condition_count:", master["condition_count"].min())
print("Maximum condition_count:", master["condition_count"].max())

Master rows: 61459
Duplicate Encounter IDs: 0
Missing condition_count: 0
Minimum condition_count: 0
Maximum condition_count: 13

In [120]:
from pathlib import Path
import pandas as pd

PROJECT_PATH = Path(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics"
)

CLEAN_PATH = PROJECT_PATH / "data" / "Cleaned_Datasets"
ANALYTICAL_PATH = PROJECT_PATH / "data" / "Analytical_Dataset"

print("Setup completed successfully!")

Setup completed successfully!

In [121]:
procedures = pd.read_csv(
    CLEAN_PATH / "procedures_cleaned.csv"
)

print("Procedures dataset loaded successfully!")
print()
print("Shape:")
print(procedures.shape)
print()
print("Columns:")
print(procedures.columns.tolist())
print()
print("First 5 rows:")
display(procedures.head())

Procedures dataset loaded successfully!

Shape:
(83823, 9)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION']

First 5 rows:

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,REASONCODE,REASONDESCRIPTION
0,2019-02-17 05:07:38+00:00,2019-02-17 05:22:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,748f8357-6cc7-551d-f31a-32fa2cf84126,430193006,Medication Reconciliation (procedure),608.11,NaN,NaN
1,2019-05-26 05:07:38+00:00,2019-05-26 05:22:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,430193006,Medication Reconciliation (procedure),460.99,NaN,NaN
2,2019-07-28 05:07:38+00:00,2019-07-28 05:22:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,6e93bcf9-45a4-8528-0120-1c1eaa930faf,430193006,Medication Reconciliation (procedure),492.11,NaN,NaN
3,2020-02-17 10:07:38+00:00,2020-02-17 10:40:32+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,01efcc52-15d6-51e9-faa2-bee069fcbe44,395142003,Allergy screening test,516.65,NaN,NaN
4,2020-04-26 05:07:38+00:00,2020-04-26 05:22:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,1a7debfc-9582-7f23-a109-4f154a182ee2,430193006,Medication Reconciliation (procedure),783.20,NaN,NaN

In [122]:
# Load Encounters
encounters = pd.read_csv(
    CLEAN_PATH / "encounters_cleaned.csv"
)

# Load Patients
patients = pd.read_csv(
    CLEAN_PATH / "patients_cleaned.csv"
)

# Select patient features
patient_features = patients[
    ["Id", "BIRTHDATE", "GENDER", "RACE", "ETHNICITY", "MARITAL"]
].copy()

# Convert dates
patient_features["BIRTHDATE"] = pd.to_datetime(
    patient_features["BIRTHDATE"],
    errors="coerce",
    utc=True
)

encounters["START"] = pd.to_datetime(
    encounters["START"],
    errors="coerce",
    utc=True
)

# Merge patient information into encounters
master = encounters.merge(
    patient_features,
    left_on="PATIENT",
    right_on="Id",
    how="left",
    suffixes=("", "_PATIENT")
)

# Calculate age at encounter
master["AGE_AT_ENCOUNTER"] = (
    (master["START"] - master["BIRTHDATE"]).dt.days / 365.25
).round(1)

# Remove duplicate patient ID column
master.drop(
    columns=["Id_PATIENT"],
    inplace=True,
    errors="ignore"
)

print("Base master recreated successfully!")
print("Master shape:", master.shape)

Base master recreated successfully!
Master shape: (61459, 21)

In [123]:
# Load Conditions dataset again

conditions = pd.read_csv(
    CLEAN_PATH / "conditions_cleaned.csv"
)

print("Conditions dataset loaded successfully!")
print("Shape:", conditions.shape)

Conditions dataset loaded successfully!
Shape: (38094, 6)

In [124]:
condition_summary = (
    conditions
    .groupby("ENCOUNTER")
    .size()
    .reset_index(name="condition_count")
)

print("Condition summary recreated successfully!")
print("Shape:", condition_summary.shape)

Condition summary recreated successfully!
Shape: (26904, 2)

In [125]:
master = master.merge(
    condition_summary,
    left_on="Id",
    right_on="ENCOUNTER",
    how="left"
)

# Condition record illaadha encounters-ku 0
master["condition_count"] = (
    master["condition_count"]
    .fillna(0)
    .astype(int)
)

# Extra ENCOUNTER column remove pannuvom
master.drop(
    columns=["ENCOUNTER"],
    inplace=True
)

print("Conditions merged into master successfully!")
print()
print("Master shape:", master.shape)

Conditions merged into master successfully!

Master shape: (61459, 22)

In [126]:
print("Master rows:", len(master))
print("Duplicate Encounter IDs:", master["Id"].duplicated().sum())
print("Missing condition_count:", master["condition_count"].isna().sum())
print("Minimum condition_count:", master["condition_count"].min())
print("Maximum condition_count:", master["condition_count"].max())

Master rows: 61459
Duplicate Encounter IDs: 0
Missing condition_count: 0
Minimum condition_count: 0
Maximum condition_count: 13

In [127]:
procedure_encounters = set(
    procedures["ENCOUNTER"].dropna()
)

master_encounters = set(
    master["Id"].dropna()
)

invalid_procedure_encounters = (
    procedure_encounters - master_encounters
)

print("Unique Encounter IDs in Procedures:", len(procedure_encounters))
print("Unique Encounter IDs in Master:", len(master_encounters))
print(
    "Procedure Encounter IDs not found in Master:",
    len(invalid_procedure_encounters)
)

Unique Encounter IDs in Procedures: 25854
Unique Encounter IDs in Master: 61459
Procedure Encounter IDs not found in Master: 0

In [128]:
procedure_summary = (
    procedures
    .groupby("ENCOUNTER")
    .agg(
        procedure_count=("CODE", "count"),
        procedure_cost=("BASE_COST", "sum")
    )
    .reset_index()
)

print("Procedure summary created successfully!")
print()
print("Shape:", procedure_summary.shape)
print()
print("First 5 rows:")
display(procedure_summary.head())

Procedure summary created successfully!

Shape: (25854, 3)

First 5 rows:

                              ENCOUNTER  procedure_count  procedure_cost
0  00067119-65e8-91d6-c8b5-4dcb2e8b55bf                4         1587.47
1  0007a338-100f-eb37-d4d3-1d38a085b663                2        13935.54
2  0017333f-3c9d-6e96-e8fb-387bb51e9a91                6         3099.90
3  00198a9d-085f-1890-67ad-49fbc95ba255                5         2583.25
4  001a8512-23f4-0048-1ddb-73556dc47cc2                1          675.71

In [129]:
master = master.merge(
    procedure_summary,
    left_on="Id",
    right_on="ENCOUNTER",
    how="left"
)

# Procedure record illaadha encounters-ku 0
master["procedure_count"] = (
    master["procedure_count"]
    .fillna(0)
    .astype(int)
)

master["procedure_cost"] = (
    master["procedure_cost"]
    .fillna(0)
)

# Extra ENCOUNTER column remove pannuvom
master.drop(
    columns=["ENCOUNTER"],
    inplace=True
)

print("Procedures merged into master successfully!")
print()
print("Master shape:", master.shape)

Procedures merged into master successfully!

Master shape: (61459, 24)

In [130]:
print("Master rows:", len(master))
print("Duplicate Encounter IDs:", master["Id"].duplicated().sum())
print("Missing procedure_count:", master["procedure_count"].isna().sum())
print("Missing procedure_cost:", master["procedure_cost"].isna().sum())
print("Minimum procedure_count:", master["procedure_count"].min())
print("Maximum procedure_count:", master["procedure_count"].max())
print("Minimum procedure_cost:", master["procedure_cost"].min())
print("Maximum procedure_cost:", master["procedure_cost"].max())

Master rows: 61459
Duplicate Encounter IDs: 0
Missing procedure_count: 0
Missing procedure_cost: 0
Minimum procedure_count: 0
Maximum procedure_count: 27
Minimum procedure_cost: 0.0
Maximum procedure_cost: 625825.22

In [131]:
medications = pd.read_csv(
    CLEAN_PATH / "medications_cleaned.csv"
)

print("Medications dataset loaded successfully!")
print()
print("Shape:")
print(medications.shape)
print()
print("Columns:")
print(medications.columns.tolist())
print()
print("First 5 rows:")
display(medications.head())

Medications dataset loaded successfully!

Shape:
(56430, 13)

Columns:
['START', 'STOP', 'PATIENT', 'PAYER', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'PAYER_COVERAGE', 'DISPENSES', 'TOTALCOST', 'REASONCODE', 'REASONDESCRIPTION']

First 5 rows:

,START,STOP,PATIENT,PAYER,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,REASONDESCRIPTION
0,2020-02-17 10:40:32+00:00,NaN,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,01efcc52-15d6-51e9-faa2-bee069fcbe44,1014676,cetirizine hydrochloride 5 MG Oral Tablet,21.45,0.0,21,450.45,NaN,NaN
1,2020-02-17 10:40:32+00:00,NaN,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,01efcc52-15d6-51e9-faa2-bee069fcbe44,1870230,NDA020800 0.3 ML Epinephrine 1 MG/ML Auto-Inje...,231.58,0.0,21,4863.18,NaN,NaN
2,2013-06-24 06:39:19+00:00,2013-07-02 06:39:19+00:00,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,0b2794bd-ec2b-d34f-0610-2523b3b7fcf0,1043400,Acetaminophen 21.7 MG/ML / Dextromethorphan Hy...,7.59,0.0,1,7.59,10509002.0,Acute bronchitis (disorder)
3,2016-02-27 08:52:29+00:00,2016-03-14 08:52:29+00:00,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,6e2f1a2d-27bd-3701-8d08-dae202c58632,a6d818dd-0983-fd1c-eefa-3d2295532c45,198405,Ibuprofen 100 MG Oral Tablet,12.48,0.0,1,12.48,NaN,NaN
4,2017-02-22 09:25:31+00:00,2017-06-02 09:25:31+00:00,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,047f6ec3-6215-35eb-9608-f9dda363a44c,6474f606-5a1b-48c0-bbbf-ad6dcbc24d4e,313820,Acetaminophen 160 MG Chewable Tablet,4.77,0.0,3,14.31,NaN,NaN

In [133]:
# Medications-la irukkura Encounter IDs
medication_encounters = set(
    medications["ENCOUNTER"].dropna()
)

# Master-la irukkura Encounter IDs
master_encounters = set(
    master["Id"].dropna()
)

# Medications-la irundhu Master-la illaadha Encounter IDs
invalid_medication_encounters = (
    medication_encounters - master_encounters
)

print("Unique Encounter IDs in Medications:", len(medication_encounters))
print("Unique Encounter IDs in Master:", len(master_encounters))
print(
    "Medication Encounter IDs not found in Master:",
    len(invalid_medication_encounters)
)

Unique Encounter IDs in Medications: 26871
Unique Encounter IDs in Master: 61459
Medication Encounter IDs not found in Master: 0

In [134]:
medication_summary = (
    medications
    .groupby("ENCOUNTER")
    .agg(
        medication_count=("CODE", "count"),
        medication_cost=("TOTALCOST", "sum")
    )
    .reset_index()
)

print("Medication summary created successfully!")
print("Shape:", medication_summary.shape)
print()
print(medication_summary.head())

Medication summary created successfully!
Shape: (26871, 3)

                              ENCOUNTER  medication_count  medication_cost
0  00001605-edaf-eddc-22fe-a53e31355361                 3            15.08
1  00028cd4-8eec-a663-514b-36e3822858d4                 2          1264.92
2  0006105b-61df-6f6b-9879-9c547cda949c                 3            14.96
3  00067119-65e8-91d6-c8b5-4dcb2e8b55bf                 1             0.24
4  000a0431-272d-3445-78e6-3da8a6840dbf                 2          2327.99

In [135]:
master = master.merge(
    medication_summary,
    left_on="Id",
    right_on="ENCOUNTER",
    how="left"
)

# Encounters without medication records
# will have 0 medication count and 0 medication cost
master["medication_count"] = (
    master["medication_count"]
    .fillna(0)
    .astype(int)
)

master["medication_cost"] = (
    master["medication_cost"]
    .fillna(0)
)

# Remove duplicate join column
master.drop(
    columns=["ENCOUNTER"],
    inplace=True
)

print("Medications merged successfully!")
print("Master shape:", master.shape)

Medications merged successfully!
Master shape: (61459, 26)

In [136]:
print("Master rows:", len(master))
print("Duplicate Encounter IDs:", master["Id"].duplicated().sum())
print("Missing medication_count:", master["medication_count"].isna().sum())
print("Missing medication_cost:", master["medication_cost"].isna().sum())
print("Minimum medication_count:", master["medication_count"].min())
print("Maximum medication_count:", master["medication_count"].max())
print("Minimum medication_cost:", master["medication_cost"].min())
print("Maximum medication_cost:", master["medication_cost"].max())

Master rows: 61459
Duplicate Encounter IDs: 0
Missing medication_count: 0
Missing medication_cost: 0
Minimum medication_count: 0
Maximum medication_count: 13
Minimum medication_cost: 0.0
Maximum medication_cost: 2197449.71

In [137]:
immunizations = pd.read_csv(
    CLEAN_PATH / "immunizations_cleaned.csv"
)

print("Immunizations dataset loaded successfully!")
print()
print("Shape:")
print(immunizations.shape)
print()
print("Columns:")
print(immunizations.columns.tolist())
print()
print("First 5 rows:")
display(immunizations.head())

Immunizations dataset loaded successfully!

Shape:
(17009, 6)

Columns:
['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST']

First 5 rows:

,DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST
0,2019-02-17 05:07:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,748f8357-6cc7-551d-f31a-32fa2cf84126,8,Hep B adolescent or pediatric,140.52
1,2019-03-24 05:07:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,5a4735ae-423f-6563-28ab-b3d11b49b2d4,8,Hep B adolescent or pediatric,140.52
2,2019-05-26 05:07:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,49,Hib (PRP-OMP),140.52
3,2019-05-26 05:07:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,119,rotavirus monovalent,140.52
4,2019-05-26 05:07:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,10,IPV,140.52

In [138]:
# Immunizations-la irukkura Encounter IDs
immunization_encounters = set(
    immunizations["ENCOUNTER"].dropna()
)

# Master-la irukkura Encounter IDs
master_encounters = set(
    master["Id"].dropna()
)

# Immunizations-la irundhu Master-la illaadha Encounter IDs
invalid_immunization_encounters = (
    immunization_encounters - master_encounters
)

print(
    "Unique Encounter IDs in Immunizations:",
    len(immunization_encounters)
)

print(
    "Unique Encounter IDs in Master:",
    len(master_encounters)
)

print(
    "Immunization Encounter IDs not found in Master:",
    len(invalid_immunization_encounters)
)

Unique Encounter IDs in Immunizations: 11796
Unique Encounter IDs in Master: 61459
Immunization Encounter IDs not found in Master: 0

In [139]:
immunization_summary = (
    immunizations
    .groupby("ENCOUNTER")
    .agg(
        immunization_count=("CODE", "count"),
        immunization_cost=("BASE_COST", "sum")
    )
    .reset_index()
)

print("Immunization summary created successfully!")
print("Shape:", immunization_summary.shape)
print()
print(immunization_summary.head())

Immunization summary created successfully!
Shape: (11796, 3)

                              ENCOUNTER  immunization_count  immunization_cost
0  00123b9a-aa74-43b1-fce6-8e8117016dae                   1             140.52
1  0017333f-3c9d-6e96-e8fb-387bb51e9a91                   2             281.04
2  00179b79-53a4-138d-e38d-4fd57bbb7564                   1             140.52
3  00198a9d-085f-1890-67ad-49fbc95ba255                   1             140.52
4  0022b630-e70b-c2a8-c8e9-959ca4179228                   4             562.08

In [140]:
master = master.merge(
    immunization_summary,
    left_on="Id",
    right_on="ENCOUNTER",
    how="left"
)

# Immunization record illaadha encounters-ku 0
master["immunization_count"] = (
    master["immunization_count"]
    .fillna(0)
    .astype(int)
)

master["immunization_cost"] = (
    master["immunization_cost"]
    .fillna(0)
)

# Extra join column remove pannuvom
master.drop(
    columns=["ENCOUNTER"],
    inplace=True
)

print("Immunizations merged successfully!")
print("Master shape:", master.shape)

Immunizations merged successfully!
Master shape: (61459, 28)

In [141]:
print("Master rows:", len(master))
print("Duplicate Encounter IDs:", master["Id"].duplicated().sum())
print("Missing immunization_count:", master["immunization_count"].isna().sum())
print("Missing immunization_cost:", master["immunization_cost"].isna().sum())
print("Minimum immunization_count:", master["immunization_count"].min())
print("Maximum immunization_count:", master["immunization_count"].max())
print("Minimum immunization_cost:", master["immunization_cost"].min())
print("Maximum immunization_cost:", master["immunization_cost"].max())

Master rows: 61459
Duplicate Encounter IDs: 0
Missing immunization_count: 0
Missing immunization_cost: 0
Minimum immunization_count: 0
Maximum immunization_count: 5
Minimum immunization_cost: 0.0
Maximum immunization_cost: 702.6

In [142]:
observations = pd.read_csv(
    CLEAN_PATH / "observations_cleaned.csv"
)

print("Observations dataset loaded successfully!")
print()
print("Shape:")
print(observations.shape)
print()
print("Columns:")
print(observations.columns.tolist())
print()
print("First 5 rows:")
display(observations.head())

Observations dataset loaded successfully!

Shape:
(530895, 9)

Columns:
['DATE', 'PATIENT', 'ENCOUNTER', 'CATEGORY', 'CODE', 'DESCRIPTION', 'VALUE', 'UNITS', 'TYPE']

First 5 rows:

,DATE,PATIENT,ENCOUNTER,CATEGORY,CODE,DESCRIPTION,VALUE,UNITS,TYPE
0,2019-02-17 05:07:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,748f8357-6cc7-551d-f31a-32fa2cf84126,vital-signs,8302-2,Body Height,51.4,cm,numeric
1,2019-02-17 05:07:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,748f8357-6cc7-551d-f31a-32fa2cf84126,vital-signs,72514-3,Pain severity - 0-10 verbal numeric rating [Sc...,1.0,{score},numeric
2,2019-02-17 05:07:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,748f8357-6cc7-551d-f31a-32fa2cf84126,vital-signs,29463-7,Body Weight,3.8,kg,numeric
3,2019-02-17 05:07:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,748f8357-6cc7-551d-f31a-32fa2cf84126,vital-signs,77606-2,Weight-for-length Per age and sex,57.9,%,numeric
4,2019-02-17 05:07:38+00:00,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,748f8357-6cc7-551d-f31a-32fa2cf84126,vital-signs,9843-4,Head Occipital-frontal circumference,34.8,cm,numeric

In [144]:
# Observations-la irukkura Encounter IDs
observation_encounters = set(
    observations["ENCOUNTER"].dropna()
)

# Master-la irukkura Encounter IDs
master_encounters = set(
    master["Id"].dropna()
)

# Observations-la irundhu Master-la illaadha Encounter IDs
invalid_observation_encounters = (
    observation_encounters - master_encounters
)

print(
    "Unique Encounter IDs in Observations:",
    len(observation_encounters)
)

print(
    "Unique Encounter IDs in Master:",
    len(master_encounters)
)

print(
    "Observation Encounter IDs not found in Master:",
    len(invalid_observation_encounters)
)

Unique Encounter IDs in Observations: 21025
Unique Encounter IDs in Master: 61459
Observation Encounter IDs not found in Master: 0

In [145]:
observation_summary = (
    observations
    .dropna(subset=["ENCOUNTER"])
    .groupby("ENCOUNTER")
    .size()
    .reset_index(name="observation_count")
)

print("Observation summary created successfully!")
print("Shape:", observation_summary.shape)
print()
print(observation_summary.head())

Observation summary created successfully!
Shape: (21025, 2)

                              ENCOUNTER  observation_count
0  00067119-65e8-91d6-c8b5-4dcb2e8b55bf                 44
1  00123b9a-aa74-43b1-fce6-8e8117016dae                 21
2  0017333f-3c9d-6e96-e8fb-387bb51e9a91                 33
3  00179b79-53a4-138d-e38d-4fd57bbb7564                 10
4  00198a9d-085f-1890-67ad-49fbc95ba255                 36

In [146]:
master = master.merge(
    observation_summary,
    left_on="Id",
    right_on="ENCOUNTER",
    how="left"
)

# Observation record illaadha encounters-ku 0
master["observation_count"] = (
    master["observation_count"]
    .fillna(0)
    .astype(int)
)

# Extra join column remove pannuvom
master.drop(
    columns=["ENCOUNTER"],
    inplace=True
)

print("Observations merged successfully!")
print("Master shape:", master.shape)

Observations merged successfully!
Master shape: (61459, 29)

In [147]:
print("Master rows:", len(master))
print("Duplicate Encounter IDs:", master["Id"].duplicated().sum())
print("Missing observation_count:", master["observation_count"].isna().sum())
print("Minimum observation_count:", master["observation_count"].min())
print("Maximum observation_count:", master["observation_count"].max())

Master rows: 61459
Duplicate Encounter IDs: 0
Missing observation_count: 0
Minimum observation_count: 0
Maximum observation_count: 678

In [148]:
allergies = pd.read_csv(
    CLEAN_PATH / "allergies_cleaned.csv"
)

print("Allergies dataset loaded successfully!")
print()
print("Shape:")
print(allergies.shape)
print()
print("Columns:")
print(allergies.columns.tolist())
print()
print("First 5 rows:")
display(allergies.head())

Allergies dataset loaded successfully!

Shape:
(794, 15)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'SYSTEM', 'DESCRIPTION', 'TYPE', 'CATEGORY', 'REACTION1', 'DESCRIPTION1', 'SEVERITY1', 'REACTION2', 'DESCRIPTION2', 'SEVERITY2']

First 5 rows:

,START,STOP,PATIENT,ENCOUNTER,CODE,SYSTEM,DESCRIPTION,TYPE,CATEGORY,REACTION1,DESCRIPTION1,SEVERITY1,REACTION2,DESCRIPTION2,SEVERITY2
0,2020-02-17 00:00:00+00:00,NaN,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,01efcc52-15d6-51e9-faa2-bee069fcbe44,111088007,Unknown,Latex (substance),allergy,environment,247472004.0,Wheal (finding),MILD,NaN,NaN,NaN
1,2020-02-17 00:00:00+00:00,NaN,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,01efcc52-15d6-51e9-faa2-bee069fcbe44,84489001,Unknown,Mold (organism),allergy,environment,76067001.0,Sneezing,MILD,NaN,NaN,NaN
2,2020-02-17 00:00:00+00:00,NaN,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,01efcc52-15d6-51e9-faa2-bee069fcbe44,260147004,Unknown,House dust mite (organism),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-17 00:00:00+00:00,NaN,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,01efcc52-15d6-51e9-faa2-bee069fcbe44,264287008,Unknown,Animal dander (substance),allergy,environment,878820003.0,Rhinoconjunctivitis (disorder),MODERATE,271807003.0,Eruption of skin (disorder),MILD
4,2020-02-17 00:00:00+00:00,NaN,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,01efcc52-15d6-51e9-faa2-bee069fcbe44,256277009,Unknown,Grass pollen (substance),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN

In [149]:
# Allergies-la irukkura Encounter IDs
allergy_encounters = set(
    allergies["ENCOUNTER"].dropna()
)

# Master-la irukkura Encounter IDs
master_encounters = set(
    master["Id"].dropna()
)

# Allergies-la irundhu Master-la illaadha Encounter IDs
invalid_allergy_encounters = (
    allergy_encounters - master_encounters
)

print(
    "Unique Encounter IDs in Allergies:",
    len(allergy_encounters)
)

print(
    "Unique Encounter IDs in Master:",
    len(master_encounters)
)

print(
    "Allergy Encounter IDs not found in Master:",
    len(invalid_allergy_encounters)
)

Unique Encounter IDs in Allergies: 179
Unique Encounter IDs in Master: 61459
Allergy Encounter IDs not found in Master: 0

In [150]:
allergy_summary = (
    allergies
    .groupby("ENCOUNTER")
    .size()
    .reset_index(name="allergy_count")
)

print("Allergy summary created successfully!")
print("Shape:", allergy_summary.shape)
print()
print(allergy_summary.head())

Allergy summary created successfully!
Shape: (179, 2)

                              ENCOUNTER  allergy_count
0  01efcc52-15d6-51e9-faa2-bee069fcbe44              9
1  02262e22-41e7-534e-eec2-d83160ed0a7b              9
2  04d64fc5-6137-3d7a-06b6-dd6dc2d6a7c1              9
3  04effe72-a3c5-e479-b6d3-5f6fb7ac8601              2
4  05a3333c-d841-b3b0-db3f-ecc75edbec27              1

In [151]:
master = master.merge(
    allergy_summary,
    left_on="Id",
    right_on="ENCOUNTER",
    how="left"
)

# Allergy record illaadha encounters-ku 0
master["allergy_count"] = (
    master["allergy_count"]
    .fillna(0)
    .astype(int)
)

# Extra join column remove pannuvom
master.drop(
    columns=["ENCOUNTER"],
    inplace=True
)

print("Allergies merged successfully!")
print("Master shape:", master.shape)

Allergies merged successfully!
Master shape: (61459, 30)

In [152]:
print("Master rows:", len(master))
print("Duplicate Encounter IDs:", master["Id"].duplicated().sum())
print("Missing allergy_count:", master["allergy_count"].isna().sum())
print("Minimum allergy_count:", master["allergy_count"].min())
print("Maximum allergy_count:", master["allergy_count"].max())

Master rows: 61459
Duplicate Encounter IDs: 0
Missing allergy_count: 0
Minimum allergy_count: 0
Maximum allergy_count: 12

In [153]:
careplans = pd.read_csv(
    CLEAN_PATH / "careplans_cleaned.csv"
)

print("Careplans dataset loaded successfully!")
print()
print("Shape:")
print(careplans.shape)
print()
print("Columns:")
print(careplans.columns.tolist())
print()
print("First 5 rows:")
display(careplans.head())

Careplans dataset loaded successfully!

Shape:
(3931, 9)

Columns:
['Id', 'START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'REASONCODE', 'REASONDESCRIPTION']

First 5 rows:

,Id,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,REASONCODE,REASONDESCRIPTION
0,6d10e8ad-cdf8-db60-ff71-688eae2861c2,2020-02-05 00:00:00+00:00,NaN,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,fb15e123-fea7-cae8-6d49-ee9d2a85fc84,384758001,Self-care interventions (procedure),NaN,NaN
1,73f93524-dc7c-ed80-8c0f-b12605033d9a,2013-06-24 00:00:00+00:00,2014-07-07 00:00:00+00:00,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,0b2794bd-ec2b-d34f-0610-2523b3b7fcf0,53950000,Respiratory therapy,10509002.0,Acute bronchitis (disorder)
2,fd741eee-5295-1185-8307-96cce2d592b4,2016-02-27 00:00:00+00:00,2016-03-14 00:00:00+00:00,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,a6d818dd-0983-fd1c-eefa-3d2295532c45,225358003,Wound care,283371005.0,Laceration of forearm
3,cb2fead4-d300-c0cb-4b87-c5869ba9ffba,2017-02-22 00:00:00+00:00,2017-06-02 00:00:00+00:00,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,6474f606-5a1b-48c0-bbbf-ad6dcbc24d4e,385691007,Fracture care,16114001.0,Fracture of ankle
4,7f73e1a4-1bbb-bd5b-c478-09bf05e7fb36,2020-02-06 00:00:00+00:00,2020-03-14 00:00:00+00:00,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,a6da4c61-bc91-17a7-14a2-fda9023536a3,91251008,Physical therapy procedure,44465007.0,Sprain of ankle

In [155]:
# Careplans-la irukkura Encounter IDs
careplan_encounters = set(
    careplans["ENCOUNTER"].dropna()
)

# Master-la irukkura Encounter IDs
master_encounters = set(
    master["Id"].dropna()
)

# Careplans-la irundhu Master-la illaadha Encounter IDs
invalid_careplan_encounters = (
    careplan_encounters - master_encounters
)

print(
    "Unique Encounter IDs in Careplans:",
    len(careplan_encounters)
)

print(
    "Unique Encounter IDs in Master:",
    len(master_encounters)
)

print(
    "Careplan Encounter IDs not found in Master:",
    len(invalid_careplan_encounters)
)

Unique Encounter IDs in Careplans: 3849
Unique Encounter IDs in Master: 61459
Careplan Encounter IDs not found in Master: 0

In [156]:
careplan_summary = (
    careplans
    .groupby("ENCOUNTER")
    .size()
    .reset_index(name="careplan_count")
)

print("Careplan summary created successfully!")
print()
print("Shape:", careplan_summary.shape)
print()
print(careplan_summary.head())

Careplan summary created successfully!

Shape: (3849, 2)

                              ENCOUNTER  careplan_count
0  0005f642-bbdc-155f-e9f0-f28e8f042b35               1
1  001b0467-5831-35a5-21c0-3c57c174cac5               1
2  003d123b-b14f-9f8b-c557-2998ffd4fc8d               1
3  007435f0-e72d-3cef-48fc-a45b151f6a3c               1
4  008a72d6-8214-b465-aaa7-2119c4e90294               1

In [157]:
master = master.merge(
    careplan_summary,
    how="left",
    left_on="Id",
    right_on="ENCOUNTER"
)

# Remove the duplicate ENCOUNTER column after merging
master.drop(columns=["ENCOUNTER"], inplace=True)

# Careplan count = 0 when no careplan exists for that encounter
master["careplan_count"] = master["careplan_count"].fillna(0).astype(int)

print("Careplans merged successfully!")
print()
print("Master shape:", master.shape)
print()
print("Duplicate Encounter IDs:", master["Id"].duplicated().sum())
print()
print("Missing careplan_count:", master["careplan_count"].isna().sum())
print()
print("Minimum careplan_count:", master["careplan_count"].min())
print("Maximum careplan_count:", master["careplan_count"].max())

Careplans merged successfully!

Master shape: (61459, 31)

Duplicate Encounter IDs: 0

Missing careplan_count: 0

Minimum careplan_count: 0
Maximum careplan_count: 2

In [158]:
devices = pd.read_csv(
    CLEAN_PATH / "devices_cleaned.csv"
)

print("Devices dataset loaded successfully!")
print()
print("Shape:")
print(devices.shape)
print()
print("Columns:")
print(devices.columns.tolist())
print()
print("First 5 rows:")
display(devices.head())

Devices dataset loaded successfully!

Shape:
(89, 7)

Columns:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'UDI']

First 5 rows:

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,UDI
0,2017-09-25 17:26:19+00:00,NaN,d1822991-eb4f-aafe-6a88-cd5279b4385b,bd2f33cd-4a24-6e32-1cd2-bf075ba9ed77,72506001,Implantable defibrillator device (physical ob...,(01)32224845419831(11)170904(17)420919(10)7079...
1,1987-09-21 02:27:51+00:00,NaN,04f25f73-04b2-469c-3806-540417a0d61c,807a0ee3-a9b1-30e1-3b19-bc2bddf952e8,72506001,Implantable defibrillator device (physical ob...,(01)84789768157847(11)870830(17)120913(10)3106...
2,2015-07-12 12:58:53+00:00,NaN,e000e5c8-30f7-7a53-a324-7f3e431ba008,5dfe5aec-2194-02ba-e4db-d16b42d28338,72506001,Implantable defibrillator device (physical ob...,(01)87802513365737(11)150621(17)400705(10)2864...
3,1983-07-18 16:34:31+00:00,NaN,89464607-f8af-06a3-fe2f-227495c12550,ea2d35e3-1cca-d560-f8ee-21bcfd480a9c,72506001,Implantable defibrillator device (physical ob...,(01)71493530635894(11)830627(17)080711(10)6970...
4,2008-04-04 12:43:40+00:00,NaN,ff0e4d0e-6181-e36e-d817-64dbcaecb5d0,9ac93727-a73c-5479-6d06-35999c01756d,705643001,Coronary artery stent (physical object),(01)60616412587042(11)080314(17)330329(10)1877...

In [159]:
device_encounters = set(
    devices["ENCOUNTER"].dropna()
)

master_encounters = set(
    master["Id"].dropna()
)

invalid_device_encounters = (
    device_encounters - master_encounters
)

print(
    "Unique Encounter IDs in Devices:",
    len(device_encounters)
)

print(
    "Unique Encounter IDs in Master:",
    len(master_encounters)
)

print(
    "Device Encounter IDs not found in Master:",
    len(invalid_device_encounters)
)

Unique Encounter IDs in Devices: 77
Unique Encounter IDs in Master: 61459
Device Encounter IDs not found in Master: 0

In [160]:
device_summary = (
    devices
    .groupby("ENCOUNTER")
    .size()
    .reset_index(name="device_count")
)

print("Device summary created successfully!")
print()
print("Shape:", device_summary.shape)
print()
print(device_summary.head())

Device summary created successfully!

Shape: (77, 2)

                              ENCOUNTER  device_count
0  00979e82-0f46-8bd8-4e3c-09cf85c27fcd             1
1  00f64ad2-061f-3fe7-8b06-b668350e4f8b             1
2  012287a0-4eda-9363-e722-0f9e2f56d0a2             1
3  028e89c3-3d0e-8305-7b16-2edf9a59762c             1
4  05a65147-095d-14d1-e77e-da0b1f6f4272             1

In [161]:
master = master.merge(
    device_summary,
    how="left",
    left_on="Id",
    right_on="ENCOUNTER"
)

# Remove duplicate encounter key
master.drop(columns=["ENCOUNTER"], inplace=True)

# Encounters without a device record get 0
master["device_count"] = (
    master["device_count"]
    .fillna(0)
    .astype(int)
)

print("Devices merged successfully!")
print()
print("Master shape:", master.shape)
print()
print("Duplicate Encounter IDs:", master["Id"].duplicated().sum())
print()
print("Missing device_count:", master["device_count"].isna().sum())
print()
print("Minimum device_count:", master["device_count"].min())
print("Maximum device_count:", master["device_count"].max())

Devices merged successfully!

Master shape: (61459, 32)

Duplicate Encounter IDs: 0

Missing device_count: 0

Minimum device_count: 0
Maximum device_count: 12

In [162]:
imaging_studies = pd.read_csv(
    CLEAN_PATH / "imaging_studies_cleaned.csv"
)

print("Imaging Studies dataset loaded successfully!")
print()
print("Shape:")
print(imaging_studies.shape)
print()
print("Columns:")
print(imaging_studies.columns.tolist())
print()
print("First 5 rows:")
display(imaging_studies.head())

Imaging Studies dataset loaded successfully!

Shape:
(151637, 13)

Columns:
['Id', 'DATE', 'PATIENT', 'ENCOUNTER', 'SERIES_UID', 'BODYSITE_CODE', 'BODYSITE_DESCRIPTION', 'MODALITY_CODE', 'MODALITY_DESCRIPTION', 'INSTANCE_UID', 'SOP_CODE', 'SOP_DESCRIPTION', 'PROCEDURE_CODE']

First 5 rows:

,Id,DATE,PATIENT,ENCOUNTER,SERIES_UID,BODYSITE_CODE,BODYSITE_DESCRIPTION,MODALITY_CODE,MODALITY_DESCRIPTION,INSTANCE_UID,SOP_CODE,SOP_DESCRIPTION,PROCEDURE_CODE
0,d94924cd-75ca-e71f-21f6-ec92f074baf8,2017-02-22 08:52:29+00:00,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,6474f606-5a1b-48c0-bbbf-ad6dcbc24d4e,1.2.840.99999999.1.55919593.1487753549732,344001,Ankle,DX,Digital Radiography,1.2.840.99999999.1.1.39611853.1487753549732,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage,19490002
1,c882815b-3466-d8ef-22d0-622f07f3fd17,2014-07-13 19:50:58+00:00,dc6c06d0-a7d8-100f-c08b-46c93700c188,1997235c-9bd0-8051-644d-c47750bcb1fd,1.2.840.99999999.1.23608646.1405281058743,344001,Ankle,DX,Digital Radiography,1.2.840.99999999.1.1.47276688.1405281058743,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage,19490002
2,4f2443d0-5f1f-8f0c-5c03-3ed753aaa892,2006-06-01 05:26:03+00:00,55a6a46e-a1a4-0298-e58f-c0cb27cbb022,0ef24554-5f04-31dc-799e-9f6351675554,1.2.840.99999999.1.23843468.1149139563021,40983000,Arm,DX,Digital Radiography,1.2.840.99999999.1.1.90574741.1149139563021,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage,1225002
3,9449c317-88e9-8f66-9a59-34c8ac7a7096,2016-08-30 06:59:20+00:00,98e4223a-5ad8-94e0-2d73-ee5203dd4e2b,9a066f56-66a3-500a-4c09-3b2149a11ba0,1.2.840.99999999.1.83176807.1472540360199,40983000,Arm,DX,Digital Radiography,1.2.840.99999999.1.1.50517790.1472540360199,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage,1225002
4,34ec2be3-cf9c-31c5-04d2-db54e785d43d,2017-11-03 07:32:26+00:00,98e4223a-5ad8-94e0-2d73-ee5203dd4e2b,3071e5d9-2c60-ca59-7c99-6ea1caa7f8e4,1.2.840.99999999.1.48905823.1509694346199,51299004,Clavicle,DX,Digital Radiography,1.2.840.99999999.1.1.16476903.1509694346199,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage,168594001

In [163]:
imaging_encounters = set(
    imaging_studies["ENCOUNTER"].dropna()
)

master_encounters = set(
    master["Id"].dropna()
)

invalid_imaging_encounters = (
    imaging_encounters - master_encounters
)

print(
    "Unique Encounter IDs in Imaging Studies:",
    len(imaging_encounters)
)

print(
    "Unique Encounter IDs in Master:",
    len(master_encounters)
)

print(
    "Imaging Encounter IDs not found in Master:",
    len(invalid_imaging_encounters)
)

Unique Encounter IDs in Imaging Studies: 920
Unique Encounter IDs in Master: 61459
Imaging Encounter IDs not found in Master: 0

In [164]:
imaging_summary = (
    imaging_studies
    .groupby("ENCOUNTER")
    .size()
    .reset_index(name="imaging_count")
)

print("Imaging summary created successfully!")
print()
print("Shape:", imaging_summary.shape)
print()
print(imaging_summary.head())

Imaging summary created successfully!

Shape: (920, 2)

                              ENCOUNTER  imaging_count
0  001a934e-e4da-f3ed-66ff-dc3a7fa3f2e5              1
1  002f5656-49ff-0c73-0f02-f85bd7903761            459
2  0071f0e2-3635-844e-1556-c357c990e0d7            396
3  0089e4ac-1431-2a5e-dd99-e9c9f0eb83a1            459
4  008a72d6-8214-b465-aaa7-2119c4e90294              1

In [165]:
print("Imaging count distribution")
print()

print("Maximum imaging_count:", imaging_summary["imaging_count"].max())
print()

print("Encounters with more than 1 imaging record:",
      (imaging_summary["imaging_count"] > 1).sum())

print("Encounters with more than 10 imaging records:",
      (imaging_summary["imaging_count"] > 10).sum())

print("Encounters with more than 50 imaging records:",
      (imaging_summary["imaging_count"] > 50).sum())

print("Encounters with more than 100 imaging records:",
      (imaging_summary["imaging_count"] > 100).sum())

print("Encounters with more than 200 imaging records:",
      (imaging_summary["imaging_count"] > 200).sum())

print("Encounters with more than 400 imaging records:",
      (imaging_summary["imaging_count"] > 400).sum())

Imaging count distribution

Maximum imaging_count: 500

Encounters with more than 1 imaging record: 377
Encounters with more than 10 imaging records: 377
Encounters with more than 50 imaging records: 377
Encounters with more than 100 imaging records: 377
Encounters with more than 200 imaging records: 377
Encounters with more than 400 imaging records: 198

In [167]:
print("Total Imaging Study rows:", len(imaging_studies))
print(
    "Unique SERIES_UID:",
    imaging_studies["SERIES_UID"].nunique()
)
print(
    "Unique INSTANCE_UID:",
    imaging_studies["INSTANCE_UID"].nunique()
)
print(
    "Unique ENCOUNTER:",
    imaging_studies["ENCOUNTER"].nunique()
)

Total Imaging Study rows: 151637
Unique SERIES_UID: 920
Unique INSTANCE_UID: 151414
Unique ENCOUNTER: 920

In [168]:
series_per_encounter = (
    imaging_studies
    .groupby("ENCOUNTER")["SERIES_UID"]
    .nunique()
)

print("Maximum Series UID per Encounter:",
      series_per_encounter.max())

print("Encounters with more than 1 Series UID:",
      (series_per_encounter > 1).sum())

print()
print("Series UID count distribution:")
print(series_per_encounter.value_counts().sort_index())

Maximum Series UID per Encounter: 1
Encounters with more than 1 Series UID: 0

Series UID count distribution:
SERIES_UID
1    920
Name: count, dtype: int64

In [169]:
imaging_summary = (
    imaging_studies
    .groupby("ENCOUNTER")["SERIES_UID"]
    .nunique()
    .reset_index(name="imaging_study_count")
)

print("Imaging summary created successfully!")
print()
print("Shape:", imaging_summary.shape)
print()
print(imaging_summary.head())

Imaging summary created successfully!

Shape: (920, 2)

                              ENCOUNTER  imaging_study_count
0  001a934e-e4da-f3ed-66ff-dc3a7fa3f2e5                    1
1  002f5656-49ff-0c73-0f02-f85bd7903761                    1
2  0071f0e2-3635-844e-1556-c357c990e0d7                    1
3  0089e4ac-1431-2a5e-dd99-e9c9f0eb83a1                    1
4  008a72d6-8214-b465-aaa7-2119c4e90294                    1

In [170]:
master = master.merge(
    imaging_summary,
    how="left",
    left_on="Id",
    right_on="ENCOUNTER"
)

# Remove duplicate encounter key
master.drop(columns=["ENCOUNTER"], inplace=True)

# Encounters without imaging get 0
master["imaging_study_count"] = (
    master["imaging_study_count"]
    .fillna(0)
    .astype(int)
)

print("Imaging Studies merged successfully!")
print()
print("Master shape:", master.shape)
print()
print("Duplicate Encounter IDs:", master["Id"].duplicated().sum())
print()
print(
    "Missing imaging_study_count:",
    master["imaging_study_count"].isna().sum()
)
print()
print(
    "Imaging study count distribution:"
)
print(master["imaging_study_count"].value_counts().sort_index())

Imaging Studies merged successfully!

Master shape: (61459, 33)

Duplicate Encounter IDs: 0

Missing imaging_study_count: 0

Imaging study count distribution:
imaging_study_count
0    60539
1      920
Name: count, dtype: int64

In [171]:
supplies = pd.read_csv(
    CLEAN_PATH / "supplies_cleaned.csv"
)

print("Supplies dataset loaded successfully!")
print()
print("Shape:")
print(supplies.shape)
print()
print("Columns:")
print(supplies.columns.tolist())
print()
print("First 5 rows:")
display(supplies.head())

Supplies dataset loaded successfully!

Shape:
(1573, 6)

Columns:
['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'QUANTITY']

First 5 rows:

,DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,QUANTITY
0,2021-02-08 00:00:00+00:00,8fa5a097-1970-9370-4193-a7baa3d235b5,b6358095-06f1-cc6a-ac12-3d46550a254a,409534002,Disposable air-purifying respirator (physical ...,2
1,2021-02-08 00:00:00+00:00,8fa5a097-1970-9370-4193-a7baa3d235b5,b6358095-06f1-cc6a-ac12-3d46550a254a,713779008,Nitrile examination/treatment glove non-powde...,24
2,2021-02-08 00:00:00+00:00,8fa5a097-1970-9370-4193-a7baa3d235b5,b6358095-06f1-cc6a-ac12-3d46550a254a,469673003,Isolation gown single-use (physical object),12
3,2021-02-08 00:00:00+00:00,8fa5a097-1970-9370-4193-a7baa3d235b5,b6358095-06f1-cc6a-ac12-3d46550a254a,706724001,Face shield (physical object),2
4,2021-02-08 00:00:00+00:00,8fa5a097-1970-9370-4193-a7baa3d235b5,b6358095-06f1-cc6a-ac12-3d46550a254a,419343004,Alcohol disinfectant (substance),1

In [172]:
supply_summary = (
    supplies
    .groupby("ENCOUNTER")
    .agg(
        supply_count=("CODE", "count"),
        supply_quantity=("QUANTITY", "sum")
    )
    .reset_index()
)

print("Supply summary created!")
print()
print("Shape:")
print(supply_summary.shape)
print()
print("First 10 rows:")
display(supply_summary.head(10))

Supply summary created!

Shape:
(25, 3)

First 10 rows:

                              ENCOUNTER  supply_count  supply_quantity
0  1550cb60-8dab-6aa7-437d-b8d64fb2cd2d            60              490
1  1761683c-9f96-f462-d43e-f152eb64874e            60              490
2  1caf5703-ebea-414d-2a03-7fc85abace61            66              539
3  207760b7-af99-e4cf-86cb-4c8dcb9f29a5            42              343
4  45aa6d98-0e3b-1398-d9a5-804977d8baae            54              441
5  493ca102-f1d9-2619-c83b-41896e59b1e4            72              588
6  4c72268a-c9dc-f278-81c7-f8f7c56ef54f             6               49
7  5e9c1cd6-b404-d6e7-6f65-713e7ea34035            66              539
8  6cc89d88-9540-ef1a-da25-ee875a04e4a1            60              490
9  77c7ccff-dbc5-2ee2-7d48-52f8af2eeb67            78              637

In [173]:
invalid_supply_encounters = set(supply_summary["ENCOUNTER"]) - set(master["Id"])

print("Supply encounters:", supply_summary["ENCOUNTER"].nunique())
print("Master encounters:", master["Id"].nunique())
print("Invalid supply encounters:", len(invalid_supply_encounters))

Supply encounters: 25
Master encounters: 61459
Invalid supply encounters: 0

In [174]:
master = master.merge(
    supply_summary,
    how="left",
    left_on="Id",
    right_on="ENCOUNTER"
)

master.drop(columns=["ENCOUNTER"], inplace=True)

master["supply_count"] = (
    master["supply_count"]
    .fillna(0)
    .astype(int)
)

master["supply_quantity"] = (
    master["supply_quantity"]
    .fillna(0)
    .astype(int)
)

print("Supplies added to master!")
print()
print("Master shape:")
print(master.shape)

Supplies added to master!

Master shape:
(61459, 35)

In [175]:
print("Master rows:", len(master))
print("Unique encounter IDs:", master["Id"].nunique())
print("Duplicate encounter IDs:", master["Id"].duplicated().sum())
print()

print("Missing supply_count:", master["supply_count"].isna().sum())
print("Missing supply_quantity:", master["supply_quantity"].isna().sum())
print()

print("Supply count range:")
print(
    "Min:", master["supply_count"].min(),
    "| Max:", master["supply_count"].max()
)

print()

print("Supply quantity range:")
print(
    "Min:", master["supply_quantity"].min(),
    "| Max:", master["supply_quantity"].max()
)

Master rows: 61459
Unique encounter IDs: 61459
Duplicate encounter IDs: 0

Missing supply_count: 0
Missing supply_quantity: 0

Supply count range:
Min: 0 | Max: 88

Supply quantity range:
Min: 0 | Max: 811

In [176]:
# Load cleaned Providers dataset

providers = pd.read_csv(
    "../data/Cleaned_Datasets/providers_cleaned.csv"
)

print("Providers shape:", providers.shape)
print("\nProviders columns:")
print(providers.columns.tolist())

providers.head()

Providers shape: (5056, 12)

Providers columns:
['Id', 'ORGANIZATION', 'NAME', 'GENDER', 'SPECIALITY', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON', 'UTILIZATION']

,Id,ORGANIZATION,NAME,GENDER,SPECIALITY,ADDRESS,CITY,STATE,ZIP,LAT,LON,UTILIZATION
0,c23e8780-6030-37ec-8d02-8c6e3def10ac,ef58ea08-d883-3957-8300-150554edc8fb,Reginald96 Bruen238,M,GENERAL PRACTICE,60 HOSPITAL ROAD,LEOMINSTER,MA,01453,42.520838,-71.770876,1214
1,3aade15e-5333-3c4e-86c5-aab3511bc8e8,69176529-fd1f-3b3f-abce-a0a3626769eb,Lesley194 Fisher429,M,GENERAL PRACTICE,330 MOUNT AUBURN STREET,CAMBRIDGE,MA,02138,42.375967,-71.118275,2877
2,af6e425b-c7d0-313d-af54-ec0dcab69e3f,5e765f2b-e908-3888-9fc7-df2cb87beb58,Ludivina884 Steuber698,F,GENERAL PRACTICE,211 PARK STREET,ATTLEBORO,MA,02703,41.931653,-71.294503,2365
3,b64820cc-13b4-3185-946b-a208b6f3b43a,f1fbcbfb-fcfa-3bd2-b7f4-df20f1b3c3a4,Esperanza675 Escobedo608,F,GENERAL PRACTICE,ONE GENERAL STREET,LAWRENCE,MA,01842,42.700273,-71.161357,976
4,581cc2bd-9005-3008-8abb-299f40d36ca5,e002090d-4e92-300e-b41e-7d1f21dee4c6,Wilfredo622 Medhurst46,M,GENERAL PRACTICE,1493 CAMBRIDGE STREET,CAMBRIDGE,MA,02138,42.375967,-71.118275,2706

In [177]:
# Validate Provider IDs between Master and Providers dataset

provider_ids_in_master = set(master["PROVIDER"].dropna().unique())
provider_ids_in_providers = set(providers["Id"].dropna().unique())

invalid_provider_ids = provider_ids_in_master - provider_ids_in_providers

print("Unique providers in master:", len(provider_ids_in_master))
print("Unique providers in providers dataset:", len(provider_ids_in_providers))
print("Invalid provider IDs:", len(invalid_provider_ids))

Unique providers in master: 1123
Unique providers in providers dataset: 5056
Invalid provider IDs: 0

In [186]:
# Select provider attributes needed for the analytical dataset

provider_features = providers[
    [
        "Id",
        "ORGANIZATION",
        "GENDER",
        "SPECIALITY",
        "UTILIZATION"
    ]
].copy()

print("Provider feature shape:", provider_features.shape)
print("\nProvider feature columns:")
print(provider_features.columns.tolist())

provider_features.head()

Provider feature shape: (5056, 5)

Provider feature columns:
['Id', 'ORGANIZATION', 'GENDER', 'SPECIALITY', 'UTILIZATION']

,Id,ORGANIZATION,GENDER,SPECIALITY,UTILIZATION
0,c23e8780-6030-37ec-8d02-8c6e3def10ac,ef58ea08-d883-3957-8300-150554edc8fb,M,GENERAL PRACTICE,1214
1,3aade15e-5333-3c4e-86c5-aab3511bc8e8,69176529-fd1f-3b3f-abce-a0a3626769eb,M,GENERAL PRACTICE,2877
2,af6e425b-c7d0-313d-af54-ec0dcab69e3f,5e765f2b-e908-3888-9fc7-df2cb87beb58,F,GENERAL PRACTICE,2365
3,b64820cc-13b4-3185-946b-a208b6f3b43a,f1fbcbfb-fcfa-3bd2-b7f4-df20f1b3c3a4,F,GENERAL PRACTICE,976
4,581cc2bd-9005-3008-8abb-299f40d36ca5,e002090d-4e92-300e-b41e-7d1f21dee4c6,M,GENERAL PRACTICE,2706

In [187]:
# Merge provider attributes into the encounter-level master dataset

master = master.merge(
    provider_features,
    how="left",
    left_on="PROVIDER",
    right_on="Id"
)

# Remove the duplicate provider ID column
master.drop(columns=["Id"], inplace=True)

print("Master shape:", master.shape)
print("Duplicate encounter IDs:", master["Id"].duplicated().sum())

Master shape: (61459, 44)

KeyError: 'Id'

In [188]:
print(master.columns.tolist())

['Id_x', 'START', 'STOP', 'PATIENT', 'ORGANIZATION_x', 'PROVIDER', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION', 'BIRTHDATE', 'GENDER_x', 'RACE', 'ETHNICITY', 'MARITAL', 'AGE_AT_ENCOUNTER', 'condition_count', 'procedure_count', 'procedure_cost', 'medication_count', 'medication_cost', 'immunization_count', 'immunization_cost', 'observation_count', 'allergy_count', 'careplan_count', 'device_count', 'imaging_study_count', 'supply_count', 'supply_quantity', 'Id_y', 'ORGANIZATION_y', 'GENDER_y', 'SPECIALITY_x', 'UTILIZATION_x', 'ORGANIZATION', 'GENDER', 'SPECIALITY_y', 'UTILIZATION_y']

In [189]:
# Check the Provider-related columns created/present in master

provider_check_cols = [
    "PROVIDER",
    "Id_x",
    "Id_y",
    "ORGANIZATION_x",
    "ORGANIZATION_y",
    "ORGANIZATION",
    "GENDER_x",
    "GENDER_y",
    "GENDER",
    "SPECIALITY_x",
    "SPECIALITY_y",
    "UTILIZATION_x",
    "UTILIZATION_y"
]

print(master[provider_check_cols].head())
print("\nMissing values:")
print(master[provider_check_cols].isna().sum())

                               PROVIDER                                  Id_x  \
0  82608ebb-037c-3cef-9d34-3736d69b29e8  748f8357-6cc7-551d-f31a-32fa2cf84126
1  82608ebb-037c-3cef-9d34-3736d69b29e8  5a4735ae-423f-6563-28ab-b3d11b49b2d4
2  82608ebb-037c-3cef-9d34-3736d69b29e8  0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3
3  82608ebb-037c-3cef-9d34-3736d69b29e8  6e93bcf9-45a4-8528-0120-1c1eaa930faf
4  82608ebb-037c-3cef-9d34-3736d69b29e8  8b6787c3-4316-a0cb-899d-4746525c319f

                                   Id_y                        ORGANIZATION_x  \
0  82608ebb-037c-3cef-9d34-3736d69b29e8  f7ae497d-8dc6-3721-9402-43b621a4e7d2
1  82608ebb-037c-3cef-9d34-3736d69b29e8  f7ae497d-8dc6-3721-9402-43b621a4e7d2
2  82608ebb-037c-3cef-9d34-3736d69b29e8  f7ae497d-8dc6-3721-9402-43b621a4e7d2
3  82608ebb-037c-3cef-9d34-3736d69b29e8  f7ae497d-8dc6-3721-9402-43b621a4e7d2
4  82608ebb-037c-3cef-9d34-3736d69b29e8  f7ae497d-8dc6-3721-9402-43b621a4e7d2

                         ORGANIZATION_y                          ORGANIZATION  \
0  f7ae497d-8dc6-3721-9402-43b621a4e7d2  f7ae497d-8dc6-3721-9402-43b621a4e7d2
1  f7ae497d-8dc6-3721-9402-43b621a4e7d2  f7ae497d-8dc6-3721-9402-43b621a4e7d2
2  f7ae497d-8dc6-3721-9402-43b621a4e7d2  f7ae497d-8dc6-3721-9402-43b621a4e7d2
3  f7ae497d-8dc6-3721-9402-43b621a4e7d2  f7ae497d-8dc6-3721-9402-43b621a4e7d2
4  f7ae497d-8dc6-3721-9402-43b621a4e7d2  f7ae497d-8dc6-3721-9402-43b621a4e7d2

  GENDER_x GENDER_y GENDER      SPECIALITY_x      SPECIALITY_y  UTILIZATION_x  \
0        M        M      M  GENERAL PRACTICE  GENERAL PRACTICE             10
1        M        M      M  GENERAL PRACTICE  GENERAL PRACTICE             10
2        M        M      M  GENERAL PRACTICE  GENERAL PRACTICE             10
3        M        M      M  GENERAL PRACTICE  GENERAL PRACTICE             10
4        M        M      M  GENERAL PRACTICE  GENERAL PRACTICE             10

   UTILIZATION_y
0             10
1             10
2             10
3             10
4             10

Missing values:
PROVIDER          0
Id_x              0
Id_y              0
ORGANIZATION_x    0
ORGANIZATION_y    0
ORGANIZATION      0
GENDER_x          0
GENDER_y          0
GENDER            0
SPECIALITY_x      0
SPECIALITY_y      0
UTILIZATION_x     0
UTILIZATION_y     0
dtype: int64

In [190]:
# Duplicate Provider columns same values-ah irukka nu verify pannrom

checks = {
    "ORGANIZATION_x vs ORGANIZATION":
        (master["ORGANIZATION_x"] == master["ORGANIZATION"]).all(),

    "ORGANIZATION_y vs ORGANIZATION":
        (master["ORGANIZATION_y"] == master["ORGANIZATION"]).all(),

    "GENDER_x vs GENDER":
        (master["GENDER_x"] == master["GENDER"]).all(),

    "GENDER_y vs GENDER":
        (master["GENDER_y"] == master["GENDER"]).all(),

    "SPECIALITY_x vs SPECIALITY":
        (master["SPECIALITY_x"] == master["SPECIALITY"]).all(),

    "SPECIALITY_y vs SPECIALITY":
        (master["SPECIALITY_y"] == master["SPECIALITY"]).all(),

    "UTILIZATION_x vs UTILIZATION":
        (master["UTILIZATION_x"] == master["UTILIZATION"]).all(),

    "UTILIZATION_y vs UTILIZATION":
        (master["UTILIZATION_y"] == master["UTILIZATION"]).all()
}

for column_check, result in checks.items():
    print(f"{column_check}: {result}")

KeyError: 'SPECIALITY'

In [191]:
# Current Provider-related columns in master

provider_columns = [
    col for col in master.columns
    if (
        "ORGANIZATION" in col
        or "GENDER" in col
        or "SPECIALITY" in col
        or "UTILIZATION" in col
        or col in ["PROVIDER", "Id_x", "Id_y"]
    )
]

print(provider_columns)

['Id_x', 'ORGANIZATION_x', 'PROVIDER', 'GENDER_x', 'Id_y', 'ORGANIZATION_y', 'GENDER_y', 'SPECIALITY_x', 'UTILIZATION_x', 'ORGANIZATION', 'GENDER', 'SPECIALITY_y', 'UTILIZATION_y']

In [192]:
# Compare duplicate Provider-related columns

print("ORGANIZATION_x == ORGANIZATION_y:",
      (master["ORGANIZATION_x"] == master["ORGANIZATION_y"]).all())

print("ORGANIZATION_y == ORGANIZATION:",
      (master["ORGANIZATION_y"] == master["ORGANIZATION"]).all())

print("GENDER_x == GENDER_y:",
      (master["GENDER_x"] == master["GENDER_y"]).all())

print("GENDER_y == GENDER:",
      (master["GENDER_y"] == master["GENDER"]).all())

print("SPECIALITY_x == SPECIALITY_y:",
      (master["SPECIALITY_x"] == master["SPECIALITY_y"]).all())

print("UTILIZATION_x == UTILIZATION_y:",
      (master["UTILIZATION_x"] == master["UTILIZATION_y"]).all())

ORGANIZATION_x == ORGANIZATION_y: True
ORGANIZATION_y == ORGANIZATION: True
GENDER_x == GENDER_y: False
GENDER_y == GENDER: True
SPECIALITY_x == SPECIALITY_y: True
UTILIZATION_x == UTILIZATION_y: True

In [193]:
# Check where the two Gender columns are different

gender_difference = master[
    master["GENDER_x"] != master["GENDER_y"]
][["PROVIDER", "GENDER_x", "GENDER_y"]]

print("Number of different Gender rows:", len(gender_difference))

print("\nDifferent Gender combinations:")
print(
    gender_difference
    .value_counts(["GENDER_x", "GENDER_y"])
)

print("\nSample differences:")
display(gender_difference.head(10))

Number of different Gender rows: 32044

Different Gender combinations:
GENDER_x  GENDER_y
M         F           16396
F         M           15648
Name: count, dtype: int64

Sample differences:

                                PROVIDER GENDER_x GENDER_y
6   9f529022-166f-3db4-9f92-ff1ba11ee565        M        F
7   9f529022-166f-3db4-9f92-ff1ba11ee565        M        F
13  e2d3a787-83d4-3bd9-a769-753b3285078d        F        M
18  e2d3a787-83d4-3bd9-a769-753b3285078d        F        M
20  e2d3a787-83d4-3bd9-a769-753b3285078d        F        M
21  e2d3a787-83d4-3bd9-a769-753b3285078d        F        M
22  e2d3a787-83d4-3bd9-a769-753b3285078d        F        M
23  e2d3a787-83d4-3bd9-a769-753b3285078d        F        M
27  e2d3a787-83d4-3bd9-a769-753b3285078d        F        M
29  e2d3a787-83d4-3bd9-a769-753b3285078d        F        M

In [194]:
# Confirm the meaning of the two Gender columns

print("Patient Gender distribution:")
print(master["GENDER_x"].value_counts())

print("\nProvider Gender distribution:")
print(master["GENDER_y"].value_counts())

print("\nProvider Gender from Providers dataset:")
print(providers["GENDER"].value_counts())

Patient Gender distribution:
GENDER_x
F    35533
M    25926
Name: count, dtype: int64

Provider Gender distribution:
GENDER_y
F    36281
M    25178
Name: count, dtype: int64

Provider Gender from Providers dataset:
GENDER
F    2609
M    2447
Name: count, dtype: int64

In [195]:
# Clean duplicate columns after Provider integration

master.rename(
    columns={
        "Id_x": "Id",
        "GENDER_x": "PATIENT_GENDER",
        "GENDER_y": "PROVIDER_GENDER",
        "ORGANIZATION": "PROVIDER_ORGANIZATION",
        "SPECIALITY_y": "PROVIDER_SPECIALITY",
        "UTILIZATION_y": "PROVIDER_UTILIZATION"
    },
    inplace=True
)

# Remove duplicate columns created during the merge
master.drop(
    columns=[
        "Id_y",
        "ORGANIZATION_x",
        "ORGANIZATION_y",
        "SPECIALITY_x",
        "UTILIZATION_x"
    ],
    inplace=True
)

print("Master shape:", master.shape)
print("\nProvider-related columns:")
print([
    col for col in master.columns
    if (
        "PROVIDER" in col
        or "PATIENT_GENDER" in col
    )
])

print("\nDuplicate Encounter IDs:", master["Id"].duplicated().sum())

Master shape: (61459, 39)

Provider-related columns:
['PROVIDER', 'PATIENT_GENDER', 'PROVIDER_GENDER', 'PROVIDER_ORGANIZATION', 'PROVIDER_SPECIALITY', 'PROVIDER_UTILIZATION']

Duplicate Encounter IDs: 0

In [196]:
# Load cleaned Organizations dataset

organizations = pd.read_csv(
    "../data/Cleaned_Datasets/organizations_cleaned.csv"
)

print("Organizations shape:", organizations.shape)

print("\nOrganizations columns:")
print(organizations.columns.tolist())

organizations.head()

Organizations shape: (1127, 11)

Organizations columns:
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON', 'PHONE', 'REVENUE', 'UTILIZATION']

,Id,NAME,ADDRESS,CITY,STATE,ZIP,LAT,LON,PHONE,REVENUE,UTILIZATION
0,ef58ea08-d883-3957-8300-150554edc8fb,HEALTHALLIANCE HOSPITALS INC,60 HOSPITAL ROAD,LEOMINSTER,MA,01453,42.520838,-71.770876,9784662000,0.0,1214
1,69176529-fd1f-3b3f-abce-a0a3626769eb,MOUNT AUBURN HOSPITAL,330 MOUNT AUBURN STREET,CAMBRIDGE,MA,02138,42.375967,-71.118275,6174923500,0.0,2877
2,5e765f2b-e908-3888-9fc7-df2cb87beb58,STURDY MEMORIAL HOSPITAL,211 PARK STREET,ATTLEBORO,MA,02703,41.931653,-71.294503,5082225200,0.0,2365
3,f1fbcbfb-fcfa-3bd2-b7f4-df20f1b3c3a4,LAWRENCE GENERAL HOSPITAL,ONE GENERAL STREET,LAWRENCE,MA,01842,42.700273,-71.161357,9786834000,0.0,976
4,e002090d-4e92-300e-b41e-7d1f21dee4c6,CAMBRIDGE HEALTH ALLIANCE,1493 CAMBRIDGE STREET,CAMBRIDGE,MA,02138,42.375967,-71.118275,6176652300,0.0,2706

In [197]:
# Validate Organization IDs between Master and Organizations dataset

organization_ids_in_master = set(
    master["PROVIDER_ORGANIZATION"].dropna().unique()
)

organization_ids_in_organizations = set(
    organizations["Id"].dropna().unique()
)

invalid_organization_ids = (
    organization_ids_in_master - organization_ids_in_organizations
)

print("Unique organizations in master:", len(organization_ids_in_master))
print("Unique organizations in organizations dataset:", len(organization_ids_in_organizations))
print("Invalid organization IDs:", len(invalid_organization_ids))

Unique organizations in master: 1122
Unique organizations in organizations dataset: 1127
Invalid organization IDs: 0

In [198]:
# Select organization attributes needed for the analytical dataset

organization_features = organizations[
    [
        "Id",
        "NAME",
        "CITY",
        "STATE",
        "UTILIZATION"
    ]
].copy()

print("Organization feature shape:", organization_features.shape)

print("\nOrganization feature columns:")
print(organization_features.columns.tolist())

organization_features.head()

Organization feature shape: (1127, 5)

Organization feature columns:
['Id', 'NAME', 'CITY', 'STATE', 'UTILIZATION']

,Id,NAME,CITY,STATE,UTILIZATION
0,ef58ea08-d883-3957-8300-150554edc8fb,HEALTHALLIANCE HOSPITALS INC,LEOMINSTER,MA,1214
1,69176529-fd1f-3b3f-abce-a0a3626769eb,MOUNT AUBURN HOSPITAL,CAMBRIDGE,MA,2877
2,5e765f2b-e908-3888-9fc7-df2cb87beb58,STURDY MEMORIAL HOSPITAL,ATTLEBORO,MA,2365
3,f1fbcbfb-fcfa-3bd2-b7f4-df20f1b3c3a4,LAWRENCE GENERAL HOSPITAL,LAWRENCE,MA,976
4,e002090d-4e92-300e-b41e-7d1f21dee4c6,CAMBRIDGE HEALTH ALLIANCE,CAMBRIDGE,MA,2706

In [199]:
# Merge organization attributes into the encounter-level master dataset

master = master.merge(
    organization_features,
    how="left",
    left_on="PROVIDER_ORGANIZATION",
    right_on="Id",
    suffixes=("", "_ORG")
)

print("Master shape:", master.shape)

print("\nMissing organization names:", master["NAME"].isna().sum())
print("Missing organization cities:", master["CITY"].isna().sum())
print("Missing organization states:", master["STATE"].isna().sum())
print("Missing organization utilization:", master["UTILIZATION"].isna().sum())

Master shape: (61459, 44)

Missing organization names: 0
Missing organization cities: 0
Missing organization states: 0
Missing organization utilization: 0

In [200]:
# Validate Organization integration

print("Unique organizations in master:",
      master["PROVIDER_ORGANIZATION"].nunique())

print("Unique organization names:",
      master["NAME"].nunique())

print("Unique organization states:",
      master["STATE"].nunique())

print("\nOrganization utilization summary:")
print(master["UTILIZATION"].describe())

Unique organizations in master: 1122
Unique organization names: 980
Unique organization states: 1

Organization utilization summary:
count    61459.000000
mean      1147.471941
std       1173.724111
min          2.000000
25%         82.000000
50%        718.000000
75%       2040.000000
max       3954.000000
Name: UTILIZATION, dtype: float64

In [202]:
# Check organization-related columns after the merge

organization_columns = [
    col for col in master.columns
    if (
        "ORGANIZATION" in col
        or col in ["PROVIDER", "Id", "Id_ORG", "NAME", "CITY", "STATE", "UTILIZATION"]
    )
]

print(organization_columns)

['Id', 'PROVIDER', 'PROVIDER_ORGANIZATION', 'Id_ORG', 'NAME', 'CITY', 'STATE', 'UTILIZATION']

In [203]:
# Clean the Organization integration

master.rename(
    columns={
        "NAME": "ORGANIZATION_NAME",
        "CITY": "ORGANIZATION_CITY",
        "STATE": "ORGANIZATION_STATE",
        "UTILIZATION": "ORGANIZATION_UTILIZATION"
    },
    inplace=True
)

# Remove duplicate organization ID created during the merge
master.drop(columns=["Id_ORG"], inplace=True)

print("Master shape:", master.shape)

print("\nOrganization-related columns:")
print([
    col for col in master.columns
    if "ORGANIZATION" in col
])

print("\nDuplicate Encounter IDs:", master["Id"].duplicated().sum())

Master shape: (61459, 43)

Organization-related columns:
['PROVIDER_ORGANIZATION', 'ORGANIZATION_NAME', 'ORGANIZATION_CITY', 'ORGANIZATION_STATE', 'ORGANIZATION_UTILIZATION']

Duplicate Encounter IDs: 0

In [204]:
# Load cleaned Payers dataset

payers = pd.read_csv(
    "../data/Cleaned_Datasets/payers_cleaned.csv"
)

print("Payers shape:", payers.shape)

print("\nPayers columns:")
print(payers.columns.tolist())

payers.head()

Payers shape: (10, 21)

Payers columns:
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE_HEADQUARTERED', 'ZIP', 'PHONE', 'AMOUNT_COVERED', 'AMOUNT_UNCOVERED', 'REVENUE', 'COVERED_ENCOUNTERS', 'UNCOVERED_ENCOUNTERS', 'COVERED_MEDICATIONS', 'UNCOVERED_MEDICATIONS', 'COVERED_PROCEDURES', 'UNCOVERED_PROCEDURES', 'COVERED_IMMUNIZATIONS', 'UNCOVERED_IMMUNIZATIONS', 'UNIQUE_CUSTOMERS', 'QOLS_AVG', 'MEMBER_MONTHS']

,Id,NAME,ADDRESS,CITY,STATE_HEADQUARTERED,ZIP,PHONE,AMOUNT_COVERED,AMOUNT_UNCOVERED,REVENUE,...,UNCOVERED_ENCOUNTERS,COVERED_MEDICATIONS,UNCOVERED_MEDICATIONS,COVERED_PROCEDURES,UNCOVERED_PROCEDURES,COVERED_IMMUNIZATIONS,UNCOVERED_IMMUNIZATIONS,UNIQUE_CUSTOMERS,QOLS_AVG,MEMBER_MONTHS
0,b3221cfc-24fb-339e-823d-bc4136cbc4ed,Dual Eligible,7500 Security Blvd,Baltimore,MD,21244.0,1-877-267-2323,2.786030e+06,358233.14,1439000.0,...,0,1141,0,551,0,280,0,20,0.537055,3060
1,7caa7254-5050-3b5e-9eae-bd5ea30e809c,Medicare,7500 Security Blvd,Baltimore,MD,21244.0,1-800-633-4227,3.619659e+07,2549080.77,7513750.0,...,0,10455,0,6957,0,3057,0,195,0.766254,30888
2,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,Medicaid,7500 Security Blvd,Baltimore,MD,21244.0,1-877-267-2323,1.199131e+08,7530654.21,14145500.0,...,0,4486,0,32913,0,5504,0,416,0.832675,57636
3,d47b3510-2895-3b70-9897-342d681c769d,Humana,500 West Main St,Louisville,KY,40018.0,1-844-330-7799,1.045054e+06,40504392.56,132703700.0,...,2183,0,6008,0,13370,0,7844,946,0.843664,78384
4,6e2f1a2d-27bd-3701-8d08-dae202c58632,Blue Cross Blue Shield,Michigan Plaza,Chicago,IL,60007.0,1-800-262-2583,3.466602e+07,16618646.34,135820800.0,...,0,6095,0,15238,0,7612,0,943,0.850551,75444

In [205]:
# Validate Payer IDs between Master and Payers dataset

payer_ids_in_master = set(
    master["PAYER"].dropna().unique()
)

payer_ids_in_payers = set(
    payers["Id"].dropna().unique()
)

invalid_payer_ids = payer_ids_in_master - payer_ids_in_payers

print("Unique payers in master:", len(payer_ids_in_master))
print("Unique payers in payers dataset:", len(payer_ids_in_payers))
print("Invalid payer IDs:", len(invalid_payer_ids))

Unique payers in master: 10
Unique payers in payers dataset: 10
Invalid payer IDs: 0

In [206]:
# Select payer attributes for analytical integration

payer_features = payers[
    [
        "Id",
        "NAME",
        "AMOUNT_COVERED",
        "AMOUNT_UNCOVERED",
        "QOLS_AVG",
        "MEMBER_MONTHS"
    ]
].copy()

print("Payer feature shape:", payer_features.shape)

print("\nPayer feature columns:")
print(payer_features.columns.tolist())

payer_features.head()

Payer feature shape: (10, 6)

Payer feature columns:
['Id', 'NAME', 'AMOUNT_COVERED', 'AMOUNT_UNCOVERED', 'QOLS_AVG', 'MEMBER_MONTHS']

,Id,NAME,AMOUNT_COVERED,AMOUNT_UNCOVERED,QOLS_AVG,MEMBER_MONTHS
0,b3221cfc-24fb-339e-823d-bc4136cbc4ed,Dual Eligible,2.786030e+06,358233.14,0.537055,3060
1,7caa7254-5050-3b5e-9eae-bd5ea30e809c,Medicare,3.619659e+07,2549080.77,0.766254,30888
2,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,Medicaid,1.199131e+08,7530654.21,0.832675,57636
3,d47b3510-2895-3b70-9897-342d681c769d,Humana,1.045054e+06,40504392.56,0.843664,78384
4,6e2f1a2d-27bd-3701-8d08-dae202c58632,Blue Cross Blue Shield,3.466602e+07,16618646.34,0.850551,75444

In [207]:
# Integrate payer information into the encounter-level master

master = master.merge(
    payer_features,
    how="left",
    left_on="PAYER",
    right_on="Id",
    suffixes=("", "_PAYER")
)

print("Master shape:", master.shape)

print("\nMissing payer names:", master["NAME"].isna().sum())
print("Missing amount covered:", master["AMOUNT_COVERED"].isna().sum())
print("Missing amount uncovered:", master["AMOUNT_UNCOVERED"].isna().sum())
print("Missing QOLS average:", master["QOLS_AVG"].isna().sum())
print("Missing member months:", master["MEMBER_MONTHS"].isna().sum())

Master shape: (61459, 49)

Missing payer names: 0
Missing amount covered: 0
Missing amount uncovered: 0
Missing QOLS average: 0
Missing member months: 0

In [208]:
# Clean the Payer integration

master.rename(
    columns={
        "NAME": "PAYER_NAME",
        "AMOUNT_COVERED": "PAYER_AMOUNT_COVERED",
        "AMOUNT_UNCOVERED": "PAYER_AMOUNT_UNCOVERED",
        "QOLS_AVG": "PAYER_QOLS_AVG",
        "MEMBER_MONTHS": "PAYER_MEMBER_MONTHS"
    },
    inplace=True
)

# Remove the duplicate payer ID created during the merge
master.drop(columns=["Id_PAYER"], inplace=True)

print("Master shape:", master.shape)

print("\nPayer-related columns:")
print([
    col for col in master.columns
    if "PAYER" in col
])

print("\nDuplicate Encounter IDs:", master["Id"].duplicated().sum())

Master shape: (61459, 48)

Payer-related columns:
['PAYER', 'PAYER_COVERAGE', 'PAYER_NAME', 'PAYER_AMOUNT_COVERED', 'PAYER_AMOUNT_UNCOVERED', 'PAYER_QOLS_AVG', 'PAYER_MEMBER_MONTHS']

Duplicate Encounter IDs: 0

In [209]:
# Load cleaned Claims dataset

claims = pd.read_csv(
    "../data/Cleaned_Datasets/claims_cleaned.csv"
)

print("Claims shape:", claims.shape)

print("\nClaims columns:")
print(claims.columns.tolist())

claims.head()

Claims shape: (117889, 31)

Claims columns:
['Id', 'PATIENTID', 'PROVIDERID', 'PRIMARYPATIENTINSURANCEID', 'SECONDARYPATIENTINSURANCEID', 'DEPARTMENTID', 'PATIENTDEPARTMENTID', 'DIAGNOSIS1', 'DIAGNOSIS2', 'DIAGNOSIS3', 'DIAGNOSIS4', 'DIAGNOSIS5', 'DIAGNOSIS6', 'DIAGNOSIS7', 'DIAGNOSIS8', 'REFERRINGPROVIDERID', 'APPOINTMENTID', 'CURRENTILLNESSDATE', 'SERVICEDATE', 'SUPERVISINGPROVIDERID', 'STATUS1', 'STATUS2', 'STATUSP', 'OUTSTANDING1', 'OUTSTANDING2', 'OUTSTANDINGP', 'LASTBILLEDDATE1', 'LASTBILLEDDATE2', 'LASTBILLEDDATEP', 'HEALTHCARECLAIMTYPEID1', 'HEALTHCARECLAIMTYPEID2']

,Id,PATIENTID,PROVIDERID,PRIMARYPATIENTINSURANCEID,SECONDARYPATIENTINSURANCEID,DEPARTMENTID,PATIENTDEPARTMENTID,DIAGNOSIS1,DIAGNOSIS2,DIAGNOSIS3,...,STATUS2,STATUSP,OUTSTANDING1,OUTSTANDING2,OUTSTANDINGP,LASTBILLEDDATE1,LASTBILLEDDATE2,LASTBILLEDDATEP,HEALTHCARECLAIMTYPEID1,HEALTHCARECLAIMTYPEID2
0,e413105d-6f23-34ef-724a-b42adab9df22,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,0,10,10,410620009,NaN,NaN,...,NaN,CLOSED,0.0,NaN,0.0,2019-02-17 05:22:38+00:00,NaN,2019-02-17 05:22:38+00:00,1,0
1,8e430d76-6628-c3ac-8950-2acabeb34f86,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,0,10,10,410620009,NaN,NaN,...,NaN,CLOSED,0.0,NaN,0.0,2019-03-24 05:22:38+00:00,NaN,2019-03-24 05:22:38+00:00,1,0
2,3a69d5f0-26d8-fe66-4a1b-1a7c9ab618c8,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,0,10,10,410620009,NaN,NaN,...,NaN,CLOSED,0.0,NaN,0.0,2019-05-26 05:22:38+00:00,NaN,2019-05-26 05:22:38+00:00,1,0
3,af33009b-e02a-6959-e5cc-5dffc7398cbd,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,0,10,10,410620009,NaN,NaN,...,NaN,CLOSED,0.0,NaN,0.0,2019-07-28 05:22:38+00:00,NaN,2019-07-28 05:22:38+00:00,1,0
4,3153e655-a843-2bf1-72eb-1f06a52e524a,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,0,10,10,410620009,NaN,NaN,...,NaN,CLOSED,0.0,NaN,0.0,2019-10-27 05:22:38+00:00,NaN,2019-10-27 05:22:38+00:00,1,0

In [210]:
# Validate Claims relationships with the analytical master

claim_patient_ids = set(
    claims["PATIENTID"].dropna().unique()
)

master_patient_ids = set(
    master["PATIENT"].dropna().unique()
)

claim_provider_ids = set(
    claims["PROVIDERID"].dropna().unique()
)

master_provider_ids = set(
    master["PROVIDER"].dropna().unique()
)

invalid_claim_patients = claim_patient_ids - master_patient_ids
invalid_claim_providers = claim_provider_ids - master_provider_ids

print("Unique patients in claims:", len(claim_patient_ids))
print("Patients available in master:", len(master_patient_ids))
print("Invalid claim patient IDs:", len(invalid_claim_patients))

print("\nUnique providers in claims:", len(claim_provider_ids))
print("Providers available in master:", len(master_provider_ids))
print("Invalid claim provider IDs:", len(invalid_claim_providers))

Unique patients in claims: 1163
Patients available in master: 1163
Invalid claim patient IDs: 0

Unique providers in claims: 1123
Providers available in master: 1123
Invalid claim provider IDs: 0

In [211]:
# Inspect Claims financial and date-related fields

claim_financial_columns = [
    "OUTSTANDING1",
    "OUTSTANDING2",
    "OUTSTANDINGP"
]

claim_date_columns = [
    "CURRENTILLNESSDATE",
    "SERVICEDATE",
    "LASTBILLEDDATE1",
    "LASTBILLEDDATE2",
    "LASTBILLEDDATEP"
]

print("Financial-related columns:")
for col in claim_financial_columns:
    print(
        f"{col}: "
        f"missing={claims[col].isna().sum()}, "
        f"unique={claims[col].nunique()}, "
        f"min={claims[col].min()}, "
        f"max={claims[col].max()}"
    )

print("\nDate-related columns:")
for col in claim_date_columns:
    print(
        f"{col}: "
        f"missing={claims[col].isna().sum()}, "
        f"unique={claims[col].nunique()}"
    )

Financial-related columns:
OUTSTANDING1: missing=0, unique=1, min=0.0, max=0.0
OUTSTANDING2: missing=103727, unique=1, min=0.0, max=0.0
OUTSTANDINGP: missing=0, unique=1, min=0.0, max=0.0

Date-related columns:
CURRENTILLNESSDATE: missing=0, unique=52914
SERVICEDATE: missing=0, unique=58419
LASTBILLEDDATE1: missing=0, unique=58817
LASTBILLEDDATE2: missing=103727, unique=5692
LASTBILLEDDATEP: missing=0, unique=58817

In [212]:
# Check whether Claims contains usable appointment references

print("Unique appointment IDs in claims:",
      claims["APPOINTMENTID"].nunique())

print("Missing appointment IDs:",
      claims["APPOINTMENTID"].isna().sum())

print("\nSample appointment IDs:")
print(claims["APPOINTMENTID"].dropna().head(10).tolist())

print("\nUnique encounter IDs in master:",
      master["Id"].nunique())

Unique appointment IDs in claims: 61459
Missing appointment IDs: 0

Sample appointment IDs:
['748f8357-6cc7-551d-f31a-32fa2cf84126', '5a4735ae-423f-6563-28ab-b3d11b49b2d4', '0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3', '6e93bcf9-45a4-8528-0120-1c1eaa930faf', '8b6787c3-4316-a0cb-899d-4746525c319f', '8f424287-ee3a-c144-bc1d-3ba926e93fd5', 'fb15e123-fea7-cae8-6d49-ee9d2a85fc84', '01efcc52-15d6-51e9-faa2-bee069fcbe44', '01efcc52-15d6-51e9-faa2-bee069fcbe44', '01efcc52-15d6-51e9-faa2-bee069fcbe44']

Unique encounter IDs in master: 61459

In [213]:
# Verify whether Claims APPOINTMENTID matches Encounter IDs

claim_appointment_ids = set(
    claims["APPOINTMENTID"].dropna().unique()
)

encounter_ids = set(
    master["Id"].dropna().unique()
)

appointments_not_in_encounters = (
    claim_appointment_ids - encounter_ids
)

encounters_not_in_claims = (
    encounter_ids - claim_appointment_ids
)

print("Claims appointment IDs:", len(claim_appointment_ids))
print("Master encounter IDs:", len(encounter_ids))

print("\nAppointment IDs not found in encounters:",
      len(appointments_not_in_encounters))

print("Encounter IDs not found in claims appointments:",
      len(encounters_not_in_claims))

Claims appointment IDs: 61459
Master encounter IDs: 61459

Appointment IDs not found in encounters: 0
Encounter IDs not found in claims appointments: 0

In [214]:
# Inspect claim activity and status by appointment

claim_summary_check = (
    claims
    .groupby("APPOINTMENTID")
    .agg(
        claim_count=("Id", "count"),
        unique_claim_status=("STATUS1", "nunique"),
        closed_claims=("STATUS1", lambda x: (x == "CLOSED").sum()),
        billed_claims=("STATUS1", lambda x: (x == "BILLED").sum())
    )
    .reset_index()
)

print("Claim summary shape:", claim_summary_check.shape)

print("\nClaim count statistics:")
print(claim_summary_check["claim_count"].describe())

print("\nClaim status summary:")
print(
    claims["STATUS1"]
    .value_counts(dropna=False)
)
a
print("\nMaximum claims linked to one appointment:",
      claim_summary_check["claim_count"].max())

Claim summary shape: (61459, 5)

Claim count statistics:
count    61459.000000
mean         1.918173
std          1.421406
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         14.000000
Name: claim_count, dtype: float64

Claim status summary:
STATUS1
CLOSED    117732
BILLED       157
Name: count, dtype: int64

NameError: name 'a' is not defined

In [215]:
# Create encounter-level Claims summary

claim_summary = (
    claims
    .groupby("APPOINTMENTID")
    .agg(
        claim_count=("Id", "count"),
        billed_claim_count=("STATUS1", lambda x: (x == "BILLED").sum()),
        closed_claim_count=("STATUS1", lambda x: (x == "CLOSED").sum())
    )
    .reset_index()
)

print("Claim summary shape:", claim_summary.shape)

print("\nClaim summary columns:")
print(claim_summary.columns.tolist())

print("\nClaim count range:")
print(
    claim_summary["claim_count"].min(),
    "to",
    claim_summary["claim_count"].max()
)

print("\nMissing values:")
print(claim_summary.isna().sum())

claim_summary.head()

Claim summary shape: (61459, 4)

Claim summary columns:
['APPOINTMENTID', 'claim_count', 'billed_claim_count', 'closed_claim_count']

Claim count range:
1 to 14

Missing values:
APPOINTMENTID         0
claim_count           0
billed_claim_count    0
closed_claim_count    0
dtype: int64

,APPOINTMENTID,claim_count,billed_claim_count,closed_claim_count
0,00001605-edaf-eddc-22fe-a53e31355361,4,0,4
1,00028cd4-8eec-a663-514b-36e3822858d4,3,0,3
2,0005f642-bbdc-155f-e9f0-f28e8f042b35,1,0,1
3,0006105b-61df-6f6b-9879-9c547cda949c,4,0,4
4,00067119-65e8-91d6-c8b5-4dcb2e8b55bf,2,0,2

In [216]:
# Validate Claims summary against the analytical master

master_encounter_ids = set(
    master["Id"].dropna().unique()
)

claim_summary_ids = set(
    claim_summary["APPOINTMENTID"].dropna().unique()
)

claims_not_in_master = claim_summary_ids - master_encounter_ids
master_not_in_claims = master_encounter_ids - claim_summary_ids

print("Master encounters:", len(master_encounter_ids))
print("Claim summary appointments:", len(claim_summary_ids))

print("\nClaim appointments not in master:",
      len(claims_not_in_master))

print("Master encounters not in claim summary:",
      len(master_not_in_claims))

Master encounters: 61459
Claim summary appointments: 61459

Claim appointments not in master: 0
Master encounters not in claim summary: 0

In [217]:
# Integrate encounter-level Claims summary into the master

master = master.merge(
    claim_summary,
    how="left",
    left_on="Id",
    right_on="APPOINTMENTID"
)

# Remove the duplicate join key
master.drop(columns=["APPOINTMENTID"], inplace=True)

# Fill any missing counts with 0 and convert to integer
master["claim_count"] = (
    master["claim_count"]
    .fillna(0)
    .astype(int)
)

master["billed_claim_count"] = (
    master["billed_claim_count"]
    .fillna(0)
    .astype(int)
)

master["closed_claim_count"] = (
    master["closed_claim_count"]
    .fillna(0)
    .astype(int)
)

print("Master shape:", master.shape)

print("\nClaims-related columns:")
print([
    col for col in master.columns
    if "claim" in col.lower()
])

print("\nDuplicate Encounter IDs:",
      master["Id"].duplicated().sum())

print("\nMissing Claims features:")
print(
    master[
        ["claim_count", "billed_claim_count", "closed_claim_count"]
    ].isna().sum()
)

Master shape: (61459, 51)

Claims-related columns:
['TOTAL_CLAIM_COST', 'claim_count', 'billed_claim_count', 'closed_claim_count']

Duplicate Encounter IDs: 0

Missing Claims features:
claim_count           0
billed_claim_count    0
closed_claim_count    0
dtype: int64

In [218]:
print("Claim count summary:")
print(master["claim_count"].describe())

print("\nBilled claim count summary:")
print(master["billed_claim_count"].describe())

print("\nClosed claim count summary:")
print(master["closed_claim_count"].describe())

print("\nClaim count frequency:")
print(master["claim_count"].value_counts().sort_index())

Claim count summary:
count    61459.000000
mean         1.918173
std          1.421406
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         14.000000
Name: claim_count, dtype: float64

Billed claim count summary:
count    61459.000000
mean         0.002555
std          0.050478
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: billed_claim_count, dtype: float64

Closed claim count summary:
count    61459.000000
mean         1.915619
std          1.423951
min          0.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         14.000000
Name: closed_claim_count, dtype: float64

Claim count frequency:
claim_count
1     34588
2     12122
3      7031
4      4653
5      1102
6       938
7       596
8       166
9        63
10      126
11        8
12       60
13        5
14        1
Name: count, dtype: int64

In [220]:
# Load cleaned Claims Transactions dataset

claims_transactions = pd.read_csv(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\claims_transactions_cleaned.csv"
)

print("Shape:", claims_transactions.shape)

print("\nColumns:")
print(claims_transactions.columns.tolist())

print("\nFirst 5 rows:")
display(claims_transactions.head())

Shape: (711238, 33)

Columns:
['ID', 'CLAIMID', 'CHARGEID', 'PATIENTID', 'TYPE', 'AMOUNT', 'METHOD', 'FROMDATE', 'TODATE', 'PLACEOFSERVICE', 'PROCEDURECODE', 'MODIFIER1', 'MODIFIER2', 'DIAGNOSISREF1', 'DIAGNOSISREF2', 'DIAGNOSISREF3', 'DIAGNOSISREF4', 'UNITS', 'DEPARTMENTID', 'NOTES', 'UNITAMOUNT', 'TRANSFEROUTID', 'TRANSFERTYPE', 'PAYMENTS', 'ADJUSTMENTS', 'TRANSFERS', 'OUTSTANDING', 'APPOINTMENTID', 'LINENOTE', 'PATIENTINSURANCEID', 'FEESCHEDULEID', 'PROVIDERID', 'SUPERVISINGPROVIDERID']

First 5 rows:

,ID,CLAIMID,CHARGEID,PATIENTID,TYPE,AMOUNT,METHOD,FROMDATE,TODATE,PLACEOFSERVICE,...,PAYMENTS,ADJUSTMENTS,TRANSFERS,OUTSTANDING,APPOINTMENTID,LINENOTE,PATIENTINSURANCEID,FEESCHEDULEID,PROVIDERID,SUPERVISINGPROVIDERID
0,5c58de0b-3ba9-401d-2ce7-a4785ff35c15,e413105d-6f23-34ef-724a-b42adab9df22,0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,CHARGE,129.16,NaN,2019-02-17 05:07:38+00:00,2019-02-17 05:22:38+00:00,f7ae497d-8dc6-3721-9402-43b621a4e7d2,...,NaN,NaN,NaN,NaN,748f8357-6cc7-551d-f31a-32fa2cf84126,NaN,NaN,1,82608ebb-037c-3cef-9d34-3736d69b29e8,82608ebb-037c-3cef-9d34-3736d69b29e8
1,1a647606-c7fa-a050-8802-6c06418ee151,e413105d-6f23-34ef-724a-b42adab9df22,1,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,PAYMENT,NaN,ECHECK,2019-02-17 05:07:38+00:00,2019-02-17 05:22:38+00:00,f7ae497d-8dc6-3721-9402-43b621a4e7d2,...,122.70,NaN,NaN,6.46,748f8357-6cc7-551d-f31a-32fa2cf84126,NaN,NaN,1,82608ebb-037c-3cef-9d34-3736d69b29e8,82608ebb-037c-3cef-9d34-3736d69b29e8
2,f3a474a2-b63b-00e2-21a9-eaf12286b65e,e413105d-6f23-34ef-724a-b42adab9df22,2,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,TRANSFEROUT,NaN,NaN,2019-02-17 05:07:38+00:00,2019-02-17 05:22:38+00:00,f7ae497d-8dc6-3721-9402-43b621a4e7d2,...,NaN,NaN,6.46,6.46,748f8357-6cc7-551d-f31a-32fa2cf84126,NaN,NaN,1,82608ebb-037c-3cef-9d34-3736d69b29e8,82608ebb-037c-3cef-9d34-3736d69b29e8
3,8e455d85-fa90-70b1-34b2-189063ab28e6,e413105d-6f23-34ef-724a-b42adab9df22,3,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,TRANSFERIN,6.46,NaN,2019-02-17 05:07:38+00:00,2019-02-17 05:22:38+00:00,f7ae497d-8dc6-3721-9402-43b621a4e7d2,...,NaN,NaN,6.46,6.46,748f8357-6cc7-551d-f31a-32fa2cf84126,NaN,NaN,1,82608ebb-037c-3cef-9d34-3736d69b29e8,82608ebb-037c-3cef-9d34-3736d69b29e8
4,a3ca968a-a9df-0d36-48bf-d2fd7aca7ff4,e413105d-6f23-34ef-724a-b42adab9df22,4,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,PAYMENT,NaN,CC,2019-02-17 05:07:38+00:00,2019-02-17 05:22:38+00:00,f7ae497d-8dc6-3721-9402-43b621a4e7d2,...,6.46,NaN,NaN,0.00,748f8357-6cc7-551d-f31a-32fa2cf84126,NaN,NaN,1,82608ebb-037c-3cef-9d34-3736d69b29e8,82608ebb-037c-3cef-9d34-3736d69b29e8

In [221]:
print("Transaction Type Counts:")
print(claims_transactions["TYPE"].value_counts(dropna=False))

print("\nTransaction Type vs AMOUNT:")
print(
    claims_transactions.groupby("TYPE")["AMOUNT"]
    .agg(["count", "sum", "mean", "min", "max"])
)

print("\nTransaction Type vs PAYMENTS:")
print(
    claims_transactions.groupby("TYPE")["PAYMENTS"]
    .agg(["count", "sum", "mean", "min", "max"])
)

print("\nTransaction Type vs TRANSFERS:")
print(
    claims_transactions.groupby("TYPE")["TRANSFERS"]
    .agg(["count", "sum", "mean", "min", "max"])
)

Transaction Type Counts:
TYPE
PAYMENT        252335
CHARGE         218721
TRANSFEROUT    120091
TRANSFERIN     120091
Name: count, dtype: int64

Transaction Type vs AMOUNT:
              count           sum        mean   min        max
TYPE
CHARGE       218721  2.069014e+08  945.960263  0.00  623241.97
PAYMENT           0  0.000000e+00         NaN   NaN        NaN
TRANSFERIN   120091  6.471027e+07  538.843624  0.01  623241.97
TRANSFEROUT       0  0.000000e+00         NaN   NaN        NaN

Transaction Type vs PAYMENTS:
              count           sum        mean   min        max
TYPE
CHARGE            0  0.000000e+00         NaN   NaN        NaN
PAYMENT      252335  2.074824e+08  822.249597  0.01  623241.97
TRANSFERIN        0  0.000000e+00         NaN   NaN        NaN
TRANSFEROUT       0  0.000000e+00         NaN   NaN        NaN

Transaction Type vs TRANSFERS:
              count          sum        mean   min        max
TYPE
CHARGE            0         0.00         NaN   NaN        NaN
PAYMENT           0         0.00         NaN   NaN        NaN
TRANSFERIN   120091  64710269.64  538.843624  0.01  623241.97
TRANSFEROUT  120091  64710269.64  538.843624  0.01  623241.97

In [222]:
# Validate Claims Transactions -> Encounters relationship

transaction_appointments = (
    claims_transactions["APPOINTMENTID"]
    .dropna()
    .unique()
)

master_encounters = master["Id"].unique()

print("Unique transaction appointment IDs:",
      len(transaction_appointments))

print("Unique master encounter IDs:",
      len(master_encounters))

print(
    "Transaction appointment IDs not in master:",
    (~claims_transactions["APPOINTMENTID"].isin(master_encounters)).sum()
)

print(
    "Master encounters with no transaction records:",
    (~master["Id"].isin(transaction_appointments)).sum()
)

print(
    "Missing APPOINTMENTID in transactions:",
    claims_transactions["APPOINTMENTID"].isna().sum()
)

Unique transaction appointment IDs: 61459
Unique master encounter IDs: 61459
Transaction appointment IDs not in master: 0
Master encounters with no transaction records: 0
Missing APPOINTMENTID in transactions: 0

In [223]:
transaction_summary = (
    claims_transactions
    .groupby("APPOINTMENTID")
    .agg(
        charge_amount=("AMOUNT", lambda x: x[claims_transactions.loc[x.index, "TYPE"].eq("CHARGE")].sum()),
        payment_amount=("PAYMENTS", "sum"),
        adjustment_amount=("ADJUSTMENTS", "sum"),
        outstanding_amount=("OUTSTANDING", "sum"),
        transaction_count=("ID", "count")
    )
    .reset_index()
)

print("Transaction summary shape:", transaction_summary.shape)

print("\nColumns:")
print(transaction_summary.columns.tolist())

print("\nFirst 5 rows:")
display(transaction_summary.head())

Transaction summary shape: (61459, 6)

Columns:
['APPOINTMENTID', 'charge_amount', 'payment_amount', 'adjustment_amount', 'outstanding_amount', 'transaction_count']

First 5 rows:

,APPOINTMENTID,charge_amount,payment_amount,adjustment_amount,outstanding_amount,transaction_count
0,00001605-edaf-eddc-22fe-a53e31355361,129.22,129.22,0.0,0.00,8
1,00028cd4-8eec-a663-514b-36e3822858d4,550.80,550.80,0.0,990.76,13
2,0005f642-bbdc-155f-e9f0-f28e8f042b35,129.16,129.16,0.0,177.48,5
3,0006105b-61df-6f6b-9879-9c547cda949c,129.21,249.16,0.0,142.65,12
4,00067119-65e8-91d6-c8b5-4dcb2e8b55bf,77.51,137.49,0.0,20.10,12

In [224]:
# Create encounter-level transaction summary

transaction_summary = (
    claims_transactions
    .groupby("APPOINTMENTID")
    .agg(
        transaction_count=("ID", "count"),
        total_amount=("AMOUNT", "sum"),
        total_payments=("PAYMENTS", "sum"),
        total_adjustments=("ADJUSTMENTS", "sum"),
        total_outstanding=("OUTSTANDING", "sum")
    )
    .reset_index()
)

print("Transaction summary shape:", transaction_summary.shape)

print("\nColumns:")
print(transaction_summary.columns.tolist())

print("\nFirst 5 rows:")
display(transaction_summary.head())

Transaction summary shape: (61459, 6)

Columns:
['APPOINTMENTID', 'transaction_count', 'total_amount', 'total_payments', 'total_adjustments', 'total_outstanding']

First 5 rows:

,APPOINTMENTID,transaction_count,total_amount,total_payments,total_adjustments,total_outstanding
0,00001605-edaf-eddc-22fe-a53e31355361,8,129.22,129.22,0.0,0.00
1,00028cd4-8eec-a663-514b-36e3822858d4,13,1021.60,550.80,0.0,990.76
2,0005f642-bbdc-155f-e9f0-f28e8f042b35,5,188.32,129.16,0.0,177.48
3,0006105b-61df-6f6b-9879-9c547cda949c,12,147.04,249.16,0.0,142.65
4,00067119-65e8-91d6-c8b5-4dcb2e8b55bf,12,78.38,137.49,0.0,20.10

In [225]:
print("TEST — cell is running")
print("Claims Transactions rows:", len(claims_transactions))
print("Master rows:", len(master))

TEST — cell is running
Claims Transactions rows: 711238
Master rows: 61459

In [226]:
# Create the final clean encounter-level transaction summary

transaction_summary = (
    claims_transactions
    .groupby("APPOINTMENTID")
    .agg(
        charge_amount=(
            "AMOUNT",
            lambda x: x[
                claims_transactions.loc[x.index, "TYPE"].eq("CHARGE")
            ].sum()
        ),
        payment_amount=("PAYMENTS", "sum"),
        adjustment_amount=("ADJUSTMENTS", "sum"),
        outstanding_amount=("OUTSTANDING", "sum"),
        transaction_count=("ID", "count")
    )
    .reset_index()
)

print("Transaction summary shape:", transaction_summary.shape)

print("\nColumns:")
print(transaction_summary.columns.tolist())

print("\nFirst 5 rows:")
display(transaction_summary.head())

Transaction summary shape: (61459, 6)

Columns:
['APPOINTMENTID', 'charge_amount', 'payment_amount', 'adjustment_amount', 'outstanding_amount', 'transaction_count']

First 5 rows:

,APPOINTMENTID,charge_amount,payment_amount,adjustment_amount,outstanding_amount,transaction_count
0,00001605-edaf-eddc-22fe-a53e31355361,129.22,129.22,0.0,0.00,8
1,00028cd4-8eec-a663-514b-36e3822858d4,550.80,550.80,0.0,990.76,13
2,0005f642-bbdc-155f-e9f0-f28e8f042b35,129.16,129.16,0.0,177.48,5
3,0006105b-61df-6f6b-9879-9c547cda949c,129.21,249.16,0.0,142.65,12
4,00067119-65e8-91d6-c8b5-4dcb2e8b55bf,77.51,137.49,0.0,20.10,12

In [227]:
print("Financial summary:")

print(
    transaction_summary[
        [
            "charge_amount",
            "payment_amount",
            "adjustment_amount",
            "outstanding_amount",
            "transaction_count"
        ]
    ].describe()
)

print("\nMissing values:")
print(
    transaction_summary[
        [
            "charge_amount",
            "payment_amount",
            "adjustment_amount",
            "outstanding_amount"
        ]
    ].isna().sum()
)

print("\nNegative values:")
print(
    (
        transaction_summary[
            [
                "charge_amount",
                "payment_amount",
                "adjustment_amount",
                "outstanding_amount"
            ]
        ] < 0
    ).sum()
)

Financial summary:
       charge_amount  payment_amount  adjustment_amount  outstanding_amount  \
count   61459.000000    61459.000000            61459.0        6.145900e+04
mean     3366.494326     3375.947415                0.0        2.323015e+03
std      8946.690726     8944.957231                0.0        1.166986e+04
min         0.000000        0.000000                0.0        0.000000e+00
25%       129.160000      129.160000                0.0        7.470000e+00
50%       269.680000      295.020000                0.0        1.774800e+02
75%      1365.195000     1381.595000                0.0        1.076360e+03
max    625902.710000   625902.710000                0.0        1.251703e+06

       transaction_count
count       61459.000000
mean           11.572561
std            10.120197
min             1.000000
25%             6.000000
50%             8.000000
75%            14.000000
max           133.000000

Missing values:
charge_amount         0
payment_amount        0
adjustment_amount     0
outstanding_amount    0
dtype: int64

Negative values:
charge_amount         0
payment_amount        0
adjustment_amount     0
outstanding_amount    0
dtype: int64

In [228]:
print("Transaction summary rows:", len(transaction_summary))

print(
    "Duplicate APPOINTMENTID:",
    transaction_summary["APPOINTMENTID"].duplicated().sum()
)

print(
    "APPOINTMENTIDs not in master:",
    (~transaction_summary["APPOINTMENTID"].isin(master["Id"])).sum()
)

print(
    "Master encounters not in transaction summary:",
    (~master["Id"].isin(transaction_summary["APPOINTMENTID"])).sum()
)

Transaction summary rows: 61459
Duplicate APPOINTMENTID: 0
APPOINTMENTIDs not in master: 0
Master encounters not in transaction summary: 0

In [229]:
# Integrate Claims Transactions features into the master dataset

master = master.merge(
    transaction_summary[
        [
            "APPOINTMENTID",
            "charge_amount",
            "payment_amount",
            "outstanding_amount",
            "transaction_count"
        ]
    ],
    how="left",
    left_on="Id",
    right_on="APPOINTMENTID"
)

# Rename transaction features
master.rename(
    columns={
        "charge_amount": "transaction_charge_amount",
        "payment_amount": "transaction_payment_amount",
        "outstanding_amount": "transaction_outstanding_amount",
        "transaction_count": "transaction_count"
    },
    inplace=True
)

# Remove the temporary join key
master.drop(columns=["APPOINTMENTID"], inplace=True)

print("Master shape:", master.shape)

print("\nTransaction-related columns:")
print([
    col for col in master.columns
    if "transaction" in col.lower()
])

print("\nDuplicate Encounter IDs:",
      master["Id"].duplicated().sum())

print("\nMissing transaction features:")
print(
    master[
        [
            "transaction_charge_amount",
            "transaction_payment_amount",
            "transaction_outstanding_amount",
            "transaction_count"
        ]
    ].isna().sum()
)

Master shape: (61459, 55)

Transaction-related columns:
['transaction_charge_amount', 'transaction_payment_amount', 'transaction_outstanding_amount', 'transaction_count']

Duplicate Encounter IDs: 0

Missing transaction features:
transaction_charge_amount         0
transaction_payment_amount        0
transaction_outstanding_amount    0
transaction_count                 0
dtype: int64

In [230]:
import os

cleaned_path = r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets"

cleaned_files = sorted(os.listdir(cleaned_path))

print("Cleaned datasets:")
for file in cleaned_files:
    print(file)

print("\nTotal cleaned files:", len(cleaned_files))

Cleaned datasets:
allergies_cleaned.csv
careplans_cleaned.csv
claims_cleaned.csv
claims_transactions_cleaned.csv
conditions_cleaned.csv
devices_cleaned.csv
encounters_cleaned.csv
imaging_studies_cleaned.csv
immunizations_cleaned.csv
medications_cleaned.csv
observations_cleaned.csv
organizations_cleaned.csv
patients_cleaned.csv
payer_transitions_cleaned.csv
payers_cleaned.csv
procedures_cleaned.csv
providers_cleaned.csv
supplies_cleaned.csv

Total cleaned files: 18

In [231]:
# Load and inspect Payer Transitions

payer_transitions = pd.read_csv(
    r"C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Cleaned_Datasets\payer_transitions_cleaned.csv"
)

print("Shape:", payer_transitions.shape)

print("\nColumns:")
print(payer_transitions.columns.tolist())

print("\nFirst 5 rows:")
display(payer_transitions.head())

Shape: (53101, 8)

Columns:
['PATIENT', 'MEMBERID', 'START_YEAR', 'END_YEAR', 'PAYER', 'SECONDARY_PAYER', 'OWNERSHIP', 'OWNERNAME']

First 5 rows:

,PATIENT,MEMBERID,START_YEAR,END_YEAR,PAYER,SECONDARY_PAYER,OWNERSHIP,OWNERNAME
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,bca22051-b39b-7591-74d4-47e10a94c52e,2019-02-24 05:07:38+00:00,2020-03-01 05:07:38+00:00,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,NaN,Self,Damon455 Langosh790
1,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,bca22051-b39b-7591-74d4-47e10a94c52e,2020-03-01 05:07:38+00:00,2021-03-07 05:07:38+00:00,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,NaN,Self,Damon455 Langosh790
2,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,bca22051-b39b-7591-74d4-47e10a94c52e,2021-03-07 05:07:38+00:00,2022-03-07 05:07:38+00:00,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,NaN,Self,Damon455 Langosh790
3,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,579bba4d-6d19-32f4-e5fe-720eb34328e0,2005-07-11 08:20:52+00:00,2006-07-17 08:20:52+00:00,6e2f1a2d-27bd-3701-8d08-dae202c58632,NaN,Guardian,Adalberto916 Wunsch504
4,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,5656e5a0-b468-6067-f89f-afaf4c49dfc3,2006-07-17 08:20:52+00:00,2007-07-23 08:20:52+00:00,4d71f845-a6a9-3c39-b242-14d25ef86a8d,NaN,Guardian,Adalberto916 Wunsch504

In [232]:
print("Unique patients:", payer_transitions["PATIENT"].nunique())
print("Unique payers:", payer_transitions["PAYER"].nunique())
print("Unique secondary payers:", payer_transitions["SECONDARY_PAYER"].nunique())

print("\nMissing values:")
print(payer_transitions.isna().sum())

print("\nDuplicate complete rows:",
      payer_transitions.duplicated().sum())

print("\nSTART_YEAR after END_YEAR:",
      (
          pd.to_datetime(payer_transitions["START_YEAR"])
          > pd.to_datetime(payer_transitions["END_YEAR"])
      ).sum())

print("\nOwnership distribution:")
print(payer_transitions["OWNERSHIP"].value_counts(dropna=False))

Unique patients: 1163
Unique payers: 10
Unique secondary payers: 6

Missing values:
PATIENT                0
MEMBERID            9546
START_YEAR             0
END_YEAR               0
PAYER                  0
SECONDARY_PAYER    51121
OWNERSHIP           9546
OWNERNAME           9546
dtype: int64

Duplicate complete rows: 0

START_YEAR after END_YEAR: 0

Ownership distribution:
OWNERSHIP
Self        20558
Guardian    15537
NaN          9546
Spouse       7460
Name: count, dtype: int64

In [233]:
payer_transition_summary = (
    payer_transitions
    .groupby("PATIENT")
    .agg(
        payer_transition_count=("PAYER", "count"),
        unique_payer_count=("PAYER", "nunique"),
        unique_secondary_payer_count=("SECONDARY_PAYER", "nunique")
    )
    .reset_index()
)

print("Shape:", payer_transition_summary.shape)

print("\nSummary statistics:")
print(payer_transition_summary.describe())

print("\nFirst 5 rows:")
display(payer_transition_summary.head())

Shape: (1163, 4)

Summary statistics:
       payer_transition_count  unique_payer_count  \
count             1163.000000         1163.000000
mean                45.658641            5.909716
std                 28.218405            2.165192
min                  1.000000            1.000000
25%                 23.000000            5.000000
50%                 45.000000            6.000000
75%                 65.000000            7.000000
max                255.000000            9.000000

       unique_secondary_payer_count
count                   1163.000000
mean                       0.669819
std                        1.678355
min                        0.000000
25%                        0.000000
50%                        0.000000
75%                        0.000000
max                        6.000000

First 5 rows:

,PATIENT,payer_transition_count,unique_payer_count,unique_secondary_payer_count
0,00126cb9-8460-4747-e302-c3609684531e,76,2,0
1,00209bf2-8e4d-06d1-82a4-daad02f25829,81,9,4
2,00ae3b00-9500-efc1-2758-a93d3f77e650,68,9,3
3,00c9ca99-6b9f-add4-8759-f7dfee6ea1a4,55,8,0
4,0142b69f-57f0-9a08-4e2d-65a2b77fdea7,64,6,0

In [234]:
print("Payer transition START range:")
print(payer_transitions["START_YEAR"].min())
print(payer_transitions["START_YEAR"].max())

print("\nPayer transition END range:")
print(payer_transitions["END_YEAR"].min())
print(payer_transitions["END_YEAR"].max())

print("\nEncounter START range:")
print(encounters["START"].min())
print(encounters["START"].max())

Payer transition START range:
1911-07-21 18:47:25+00:00
2021-11-26 14:20:29+00:00

Payer transition END range:
1912-07-26 18:47:25+00:00
2022-11-26 14:20:29+00:00

Encounter START range:
1912-09-26 02:47:25+00:00
2021-11-19 16:50:22+00:00

In [235]:
payer_check = payer_transitions[
    ["PATIENT", "START_YEAR", "END_YEAR", "PAYER"]
].copy()

payer_check["START_YEAR"] = pd.to_datetime(payer_check["START_YEAR"])
payer_check["END_YEAR"] = pd.to_datetime(payer_check["END_YEAR"])

encounter_check = encounters[
    ["Id", "PATIENT", "START"]
].copy()

encounter_check["START"] = pd.to_datetime(encounter_check["START"])

print("Encounters:", len(encounter_check))
print("Payer periods:", len(payer_check))

Encounters: 61459
Payer periods: 53101

In [236]:
payer_check = payer_check.sort_values(
    ["PATIENT", "START_YEAR"]
)

encounter_check = encounter_check.sort_values(
    ["PATIENT", "START"]
)

payer_check.head()

,PATIENT,START_YEAR,END_YEAR,PAYER
30738,00126cb9-8460-4747-e302-c3609684531e,1987-06-06 23:28:56+00:00,1987-08-01 23:28:56+00:00,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a
30739,00126cb9-8460-4747-e302-c3609684531e,1987-08-01 23:28:56+00:00,1987-10-03 23:28:56+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
30740,00126cb9-8460-4747-e302-c3609684531e,1987-10-03 23:28:56+00:00,1987-12-05 23:28:56+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
30741,00126cb9-8460-4747-e302-c3609684531e,1987-12-05 23:28:56+00:00,1988-03-05 23:28:56+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
30742,00126cb9-8460-4747-e302-c3609684531e,1988-03-05 23:28:56+00:00,1988-06-04 23:28:56+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76

In [237]:
encounter_payer_match = encounter_check.merge(
    payer_check,
    on="PATIENT",
    how="left"
)

encounter_payer_match["payer_period_match"] = (
    (encounter_payer_match["START"] >= encounter_payer_match["START_YEAR"]) &
    (encounter_payer_match["START"] <= encounter_payer_match["END_YEAR"])
)

print("Total encounter-payer combinations:",
      len(encounter_payer_match))

print("\nMatched combinations:",
      encounter_payer_match["payer_period_match"].sum())

print("\nEncounters with at least one matching payer period:",
      encounter_payer_match
      .groupby("Id")["payer_period_match"]
      .any()
      .sum())

print("\nEncounters with NO matching payer period:",
      (~encounter_payer_match
       .groupby("Id")["payer_period_match"]
       .any()).sum())

Total encounter-payer combinations: 3937394

Matched combinations: 62258

Encounters with at least one matching payer period: 61338

Encounters with NO matching payer period: 121

In [238]:
match_counts = (
    encounter_payer_match
    .groupby("Id")["payer_period_match"]
    .sum()
)

print("Encounters with 0 matches:", (match_counts == 0).sum())
print("Encounters with 1 match:", (match_counts == 1).sum())
print("Encounters with 2 matches:", (match_counts == 2).sum())
print("Encounters with more than 2 matches:", (match_counts > 2).sum())
print("Maximum matches for one encounter:", match_counts.max())

Encounters with 0 matches: 121
Encounters with 1 match: 60418
Encounters with 2 matches: 920
Encounters with more than 2 matches: 0
Maximum matches for one encounter: 2

In [239]:
double_matches = encounter_payer_match[
    encounter_payer_match["payer_period_match"]
].copy()

double_match_ids = (
    double_matches.groupby("Id")
    .size()
)

double_match_ids = double_match_ids[
    double_match_ids == 2
].index

double_match_examples = double_matches[
    double_matches["Id"].isin(double_match_ids)
].sort_values(["Id", "START_YEAR"])

double_match_examples[
    ["Id", "PATIENT", "START", "START_YEAR", "END_YEAR", "PAYER"]
].head(20)

,Id,PATIENT,START,START_YEAR,END_YEAR,PAYER
59248,00908803-0142-116f-e22e-b43e60724e60,04f25f73-04b2-469c-3806-540417a0d61c,2003-08-04 02:27:51+00:00,2003-04-07 02:27:51+00:00,2003-08-04 02:27:51+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
59249,00908803-0142-116f-e22e-b43e60724e60,04f25f73-04b2-469c-3806-540417a0d61c,2003-08-04 02:27:51+00:00,2003-08-04 02:27:51+00:00,2003-11-03 02:27:51+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
522024,012a4554-5e85-4f4d-3b38-29414b405f5b,297c1550-317d-aac0-b529-042721fed414,2021-11-03 22:02:55+00:00,2021-09-01 22:02:55+00:00,2021-11-03 22:02:55+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
522025,012a4554-5e85-4f4d-3b38-29414b405f5b,297c1550-317d-aac0-b529-042721fed414,2021-11-03 22:02:55+00:00,2021-11-03 22:02:55+00:00,2022-11-03 22:02:55+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
2241748,018b274e-6397-42ba-7e08-d9ed2230f8c4,a1c127d9-d31e-36b1-2a3e-3014be9bfdf0,1972-06-09 20:21:02+00:00,1971-06-04 20:21:02+00:00,1972-06-09 20:21:02+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
2241749,018b274e-6397-42ba-7e08-d9ed2230f8c4,a1c127d9-d31e-36b1-2a3e-3014be9bfdf0,1972-06-09 20:21:02+00:00,1972-06-09 20:21:02+00:00,1973-06-15 20:21:02+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
2782049,0198cccc-f0c9-b874-6e3e-def85dd52659,cb06b854-fa3d-3450-214a-bd8ad35d07d2,2013-07-03 06:15:28+00:00,2012-09-12 06:15:28+00:00,2013-07-03 06:15:28+00:00,d47b3510-2895-3b70-9897-342d681c769d
2782050,0198cccc-f0c9-b874-6e3e-def85dd52659,cb06b854-fa3d-3450-214a-bd8ad35d07d2,2013-07-03 06:15:28+00:00,2013-07-03 06:15:28+00:00,2013-08-07 06:15:28+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
1576684,01a2fb68-cf2d-1bbf-c48f-cceb693557d5,7a929240-2387-1d5c-664b-d643ee18bb39,2018-09-01 19:21:05+00:00,2018-06-02 19:21:05+00:00,2018-09-01 19:21:05+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
1576685,01a2fb68-cf2d-1bbf-c48f-cceb693557d5,7a929240-2387-1d5c-664b-d643ee18bb39,2018-09-01 19:21:05+00:00,2018-09-01 19:21:05+00:00,2019-09-07 19:21:05+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
2871111,02126851-9721-bc39-e59c-e743c5e3c170,ceec80e3-5c50-be88-198c-e98375c8e8a2,2016-02-29 14:27:33+00:00,2015-02-23 14:27:33+00:00,2016-02-29 14:27:33+00:00,6e2f1a2d-27bd-3701-8d08-dae202c58632
2871112,02126851-9721-bc39-e59c-e743c5e3c170,ceec80e3-5c50-be88-198c-e98375c8e8a2,2016-02-29 14:27:33+00:00,2016-02-29 14:27:33+00:00,2017-03-06 14:27:33+00:00,6e2f1a2d-27bd-3701-8d08-dae202c58632
3290086,022f1b57-9789-9215-8d6b-2b1f12949ae3,e23c7a6e-6ef2-3932-1361-b73b4c8a3961,2021-08-02 01:34:00+00:00,2021-05-03 01:34:00+00:00,2021-08-02 01:34:00+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
3290087,022f1b57-9789-9215-8d6b-2b1f12949ae3,e23c7a6e-6ef2-3932-1361-b73b4c8a3961,2021-08-02 01:34:00+00:00,2021-08-02 01:34:00+00:00,2021-09-06 01:34:00+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
3452949,0357c922-6844-e4da-9e39-2796fcde825a,ec3be88f-6d38-5331-b548-18bf9b9f35a3,2012-08-04 07:41:05+00:00,2011-07-30 07:41:05+00:00,2012-08-04 07:41:05+00:00,047f6ec3-6215-35eb-9608-f9dda363a44c
3452950,0357c922-6844-e4da-9e39-2796fcde825a,ec3be88f-6d38-5331-b548-18bf9b9f35a3,2012-08-04 07:41:05+00:00,2012-08-04 07:41:05+00:00,2013-06-01 07:41:05+00:00,d47b3510-2895-3b70-9897-342d681c769d
1049562,03606423-094d-d8f3-b506-5b1d30526bd4,54cc4555-29a2-17ca-1b62-b537b35515a5,2019-12-04 12:56:22+00:00,2019-06-05 12:56:22+00:00,2019-12-04 12:56:22+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
1049563,03606423-094d-d8f3-b506-5b1d30526bd4,54cc4555-29a2-17ca-1b62-b537b35515a5,2019-12-04 12:56:22+00:00,2019-12-04 12:56:22+00:00,2020-12-09 12:56:22+00:00,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76
1499426,0381023d-001e-6c03-46ba-06e7780090d5,74ead5ce-b1a1-88ee-3d88-8c5502531d68,2011-10-22 19:07:42+00:00,2010-10-16 19:07:42+00:00,2011-10-22 19:07:42+00:00,d47b3510-2895-3b70-9897-342d681c769d
1499427,0381023d-001e-6c03-46ba-06e7780090d5,74ead5ce-b1a1-88ee-3d88-8c5502531d68,2011-10-22 19:07:42+00:00,2011-10-22 19:07:42+00:00,2012-10-27 19:07:42+00:00,5059a55e-5d6e-34d1-b6cb-d83d16e57bcf

In [240]:
unmatched_encounters = encounter_payer_match[
    ~encounter_payer_match["payer_period_match"]
].copy()

unmatched_encounter_ids = (
    unmatched_encounters
    .groupby("Id")
    .size()
)

unmatched_ids = unmatched_encounter_ids.index

encounters_no_payer_period = encounter_check[
    encounter_check["Id"].isin(unmatched_ids)
]

print("Unmatched encounters:", len(encounters_no_payer_period))

encounters_no_payer_period.head(20)

Unmatched encounters: 61414

,Id,PATIENT,START
35318,39fad31f-f0e2-061f-2a6b-dec159df271a,00126cb9-8460-4747-e302-c3609684531e,2005-07-23 23:28:56+00:00
35319,482f855e-39e7-9145-7f19-8924573ab8b7,00126cb9-8460-4747-e302-c3609684531e,2005-08-22 23:28:56+00:00
35320,0b1d4e8a-61dd-b713-bada-b6f66eb678b6,00126cb9-8460-4747-e302-c3609684531e,2006-07-29 23:28:56+00:00
35321,86c47926-8246-7203-4157-314c7f5b23ed,00126cb9-8460-4747-e302-c3609684531e,2007-08-04 23:28:56+00:00
35322,dec0f17f-c805-6c2b-d962-fbb0c120bdb0,00126cb9-8460-4747-e302-c3609684531e,2008-08-09 23:28:56+00:00
35323,0f3b0dfa-7484-7ec6-b3b0-96527ca9849b,00126cb9-8460-4747-e302-c3609684531e,2009-08-15 23:28:56+00:00
35324,eeac1cb2-b889-057a-0212-328dfa30393a,00126cb9-8460-4747-e302-c3609684531e,2010-08-21 23:28:56+00:00
35328,37015b3b-bd96-c763-abc1-67b734edc789,00126cb9-8460-4747-e302-c3609684531e,2011-06-11 23:28:56+00:00
35330,37f31c6f-9083-90fb-0ddf-1332d8273081,00126cb9-8460-4747-e302-c3609684531e,2011-08-27 23:28:56+00:00
35331,813c549e-2001-cfd3-617d-f76d89e1b6c9,00126cb9-8460-4747-e302-c3609684531e,2011-11-26 23:28:56+00:00
35332,f384db99-a9f6-a847-44d7-d942de7b60c0,00126cb9-8460-4747-e302-c3609684531e,2011-12-24 23:28:56+00:00
35334,a03fe260-26b8-6330-f8fa-f95d122a8235,00126cb9-8460-4747-e302-c3609684531e,2012-01-07 23:28:56+00:00
35336,06a332c1-316c-2218-d6ac-07ccdd3afac8,00126cb9-8460-4747-e302-c3609684531e,2012-01-14 23:28:56+00:00
35337,6c5f283d-44e3-e024-43c7-b57297d17209,00126cb9-8460-4747-e302-c3609684531e,2012-01-21 23:28:56+00:00
35338,cff550b8-ba02-5ea0-b983-f3d713c9a161,00126cb9-8460-4747-e302-c3609684531e,2012-03-03 23:28:56+00:00
35339,ec2b0813-8729-d19d-39a5-36596c924dca,00126cb9-8460-4747-e302-c3609684531e,2012-04-01 23:28:56+00:00
35342,5ceb599f-1478-306c-bc94-9b259994c9fd,00126cb9-8460-4747-e302-c3609684531e,2012-04-06 14:28:56+00:00
35344,f31a0b6a-98dd-a651-6322-0d1851ae1aa1,00126cb9-8460-4747-e302-c3609684531e,2012-09-01 23:28:56+00:00
35345,0eca4e30-8b15-b21e-308f-68842600b849,00126cb9-8460-4747-e302-c3609684531e,2013-04-01 15:18:29+00:00
35348,da8c36f9-9df4-1214-73d1-2d29bc48cd23,00126cb9-8460-4747-e302-c3609684531e,2013-04-05 16:18:29+00:00

In [241]:
unmatched_ids = match_counts[match_counts == 0].index

encounters_no_payer_period = encounter_check[
    encounter_check["Id"].isin(unmatched_ids)
]

print("Unmatched encounters:", len(encounters_no_payer_period))

encounters_no_payer_period.head(20)

Unmatched encounters: 121

,Id,PATIENT,START
60284,237e6785-0eca-3b39-283a-d15bf2cc9b41,02df500c-4884-89ee-981c-e160dd1f6902,2012-11-06 06:36:35+00:00
42698,922cda1b-9354-e95d-281e-5419c87b6307,0d2673ea-1ad2-be4f-0f45-fcf802d7785f,2017-11-24 06:19:09+00:00
698,a8e3548c-060a-95ec-a607-b166d1b06a7d,122b4063-18dc-f20f-204c-6f2da758717b,2018-09-16 04:46:41+00:00
59033,1d4214a5-6a6a-fc17-d136-52fbe4640358,132baf63-cbc4-cfec-1772-d88d7762fc4e,2019-06-16 17:07:42+00:00
16945,c2c53943-8540-31e2-f334-e56fee37856e,140c88b4-afb8-dca3-92e5-3e688aa19800,2018-05-20 18:51:57+00:00
47288,29b0db13-c9df-31b6-7ffd-a4eefb751d37,144e80cf-0e24-0958-e987-0afc0339b98e,1996-01-12 04:21:05+00:00
49275,9c2696e1-764f-6131-8c62-7793ffe306c0,16374251-beab-44f9-ac53-faece4e66bc2,2017-11-17 12:48:07+00:00
1530,0cd3cb2b-697e-50f0-4a44-4067c16c8c2c,18f70d07-28a0-17f3-2605-bf21cceb194b,2020-02-08 12:59:41+00:00
49184,21f6249d-71ad-2b3e-48d9-04bbb3325ff8,194c23d2-5e47-f9e1-9716-77c19aa167b3,2017-01-02 10:20:58+00:00
34335,9cd37d34-6980-873e-ad84-590cfc579b91,19d74a46-a73e-9493-1eb8-e40b39f89db8,2020-03-27 07:55:36+00:00
52978,eaadab86-084d-79bd-998f-427697476e5b,1a3c4dbc-9cf9-3967-ac48-389057e4f2aa,2014-11-24 01:04:42+00:00
35447,3cc942d3-ccd6-994a-6dcb-3b47727d6c11,1c920b99-e6b8-2445-0f90-0648f2856434,2020-01-13 09:57:03+00:00
19168,8bfba42b-ba0c-a7f5-8fca-a4cc52843a10,1e6c1763-afae-06b8-e9ec-6a3cfee72c45,2012-09-30 14:21:16+00:00
9049,f059c100-125b-1c70-94d9-651d73ea7e5f,1f4b009b-80bf-da5f-a2c1-dad8e71e8927,2014-12-05 18:05:19+00:00
30162,a8e32579-c567-8752-be09-381745ec9841,1f6ca3a4-3383-37f6-45d3-bfe282c43b10,2012-03-05 12:42:16+00:00
18057,edf52c36-5e32-9095-4e74-b0eb11b996ec,22b01ffb-7537-e873-3a7c-0d6961c498d7,2018-10-29 13:47:08+00:00
57898,c0fe4d5f-dbd4-30e3-b7dc-92c4531137b8,2346454f-bd4c-71c5-8f86-5c71d85f5dd2,2012-07-07 06:27:18+00:00
3771,7c992e6c-e92b-5133-7b25-74ad49b91e40,251ec304-b5fb-e3fa-72ed-197b957c3378,2020-05-13 09:29:37+00:00
13558,060f8bbc-3b45-f506-ab04-817c5353a9a2,2798ae24-ef3b-1906-6e41-a31e0fd833a0,1973-07-15 00:04:07+00:00
40969,603115bc-c2b7-8ca3-7543-6bed95045f8a,2e7f9367-ada3-e09c-876d-32b551578630,2013-11-04 23:08:29+00:00

In [242]:
# Get the encounter-level payer for the 121 unmatched encounters
unmatched_with_payer = encounters[
    ["Id", "PATIENT", "START", "PAYER"]
].copy()

unmatched_with_payer = unmatched_with_payer[
    unmatched_with_payer["Id"].isin(unmatched_ids)
]

# Check whether that payer appears anywhere in the patient's
# payer-transition history
patient_payer_history = (
    payer_transitions[
        ["PATIENT", "PAYER"]
    ]
    .drop_duplicates()
)

unmatched_payer_check = unmatched_with_payer.merge(
    patient_payer_history,
    on=["PATIENT", "PAYER"],
    how="left",
    indicator=True
)

print(
    "121 unmatched encounters whose encounter PAYER "
    "appears somewhere in patient's payer history:",
    (unmatched_payer_check["_merge"] == "both").sum()
)

print(
    "121 unmatched encounters whose encounter PAYER "
    "does NOT appear in patient's payer history:",
    (unmatched_payer_check["_merge"] == "left_only").sum()
)

121 unmatched encounters whose encounter PAYER appears somewhere in patient's payer history: 121
121 unmatched encounters whose encounter PAYER does NOT appear in patient's payer history: 0

In [243]:
print("Patients in payer transition summary:", payer_transition_summary["PATIENT"].nunique())
print("Rows in payer transition summary:", len(payer_transition_summary))

print(
    "Patients in encounters:",
    encounters["PATIENT"].nunique()
)

print(
    "Patients in encounters missing from payer summary:",
    len(
        set(encounters["PATIENT"])
        - set(payer_transition_summary["PATIENT"])
    )
)

Patients in payer transition summary: 1163
Rows in payer transition summary: 1163
Patients in encounters: 1163
Patients in encounters missing from payer summary: 0

In [246]:
master = master.merge(
    payer_transition_summary,
    how="left",
    left_on="PATIENT",
    right_on="PATIENT"
)

print("Master shape:", master.shape)
print("Duplicate encounter IDs:", master["Id"].duplicated().sum())

print("\nPayer transition features:")
print(
    master[
        [
            "payer_transition_count",
            "unique_payer_count",
            "unique_secondary_payer_count"
        ]
    ].isna().sum()
)

Master shape: (61459, 64)
Duplicate encounter IDs: 0

Payer transition features:
payer_transition_count          0
unique_payer_count              0
unique_secondary_payer_count    0
dtype: int64

In [247]:
print("========== FINAL MASTER CHECK ==========")

print("Rows:", len(master))
print("Columns:", len(master.columns))

print("\nDuplicate encounter IDs:")
print(master["Id"].duplicated().sum())

print("\nMissing Encounter IDs:")
print(master["Id"].isna().sum())

print("\nMissing Patient IDs:")
print(master["PATIENT"].isna().sum())

print("\nMissing Encounter Start:")
print(master["START"].isna().sum())

print("\nMissing Primary Cost:")
print(master["TOTAL_CLAIM_COST"].isna().sum())

print("\nNegative Primary Cost:")
print((master["TOTAL_CLAIM_COST"] < 0).sum())

========== FINAL MASTER CHECK ==========
Rows: 61459
Columns: 64

Duplicate encounter IDs:
0

Missing Encounter IDs:
0

Missing Patient IDs:
0

Missing Encounter Start:
0

Missing Primary Cost:
0

Negative Primary Cost:
0

In [249]:
print("========== DERIVED FEATURE CHECK ==========")

derived_features = [
    "ENCOUNTER_DURATION_HOURS",
    "observation_count",
    "immunization_count",
    "immunization_cost",
    "allergy_count",
    "careplan_count",
    "device_count",
    "imaging_study_count",
    "supply_count",
    "supply_quantity",
    "condition_count",
    "procedure_count",
    "procedure_cost",
    "medication_count",
    "medication_cost",
    "claim_count",
    "billed_claim_count",
    "closed_claim_count",
    "transaction_charge_amount",
    "transaction_payment_amount",
    "transaction_outstanding_amount",
    "transaction_count",
    "payer_transition_count",
    "unique_payer_count",
    "unique_secondary_payer_count"
]

print("Missing values:")
print(master[derived_features].isna().sum())

print("\nNegative values:")
print((master[derived_features] < 0).sum())

========== DERIVED FEATURE CHECK ==========
Missing values:

KeyError: "['ENCOUNTER_DURATION_HOURS'] not in index"

In [250]:
print(master.columns.tolist())

['Id', 'START', 'STOP', 'PATIENT', 'PROVIDER', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION', 'BIRTHDATE', 'PATIENT_GENDER', 'RACE', 'ETHNICITY', 'MARITAL', 'AGE_AT_ENCOUNTER', 'condition_count', 'procedure_count', 'procedure_cost', 'medication_count', 'medication_cost', 'immunization_count', 'immunization_cost', 'observation_count', 'allergy_count', 'careplan_count', 'device_count', 'imaging_study_count', 'supply_count', 'supply_quantity', 'PROVIDER_GENDER', 'PROVIDER_ORGANIZATION', 'GENDER', 'PROVIDER_SPECIALITY', 'PROVIDER_UTILIZATION', 'ORGANIZATION_NAME', 'ORGANIZATION_CITY', 'ORGANIZATION_STATE', 'ORGANIZATION_UTILIZATION', 'PAYER_NAME', 'PAYER_AMOUNT_COVERED', 'PAYER_AMOUNT_UNCOVERED', 'PAYER_QOLS_AVG', 'PAYER_MEMBER_MONTHS', 'claim_count', 'billed_claim_count', 'closed_claim_count', 'transaction_charge_amount', 'transaction_payment_amount', 'transaction_outstanding_amount', 'transaction_count', 'payer_transition_count_x', 'unique_payer_count_x', 'unique_secondary_payer_count_x', 'payer_transition_count_y', 'unique_payer_count_y', 'unique_secondary_payer_count_y', 'payer_transition_count', 'unique_payer_count', 'unique_secondary_payer_count']

In [251]:
print("========== DERIVED FEATURE CHECK ==========")

derived_features = [
    "condition_count",
    "procedure_count",
    "procedure_cost",
    "medication_count",
    "medication_cost",
    "immunization_count",
    "immunization_cost",
    "observation_count",
    "allergy_count",
    "careplan_count",
    "device_count",
    "imaging_study_count",
    "supply_count",
    "supply_quantity",
    "claim_count",
    "billed_claim_count",
    "closed_claim_count",
    "transaction_charge_amount",
    "transaction_payment_amount",
    "transaction_outstanding_amount",
    "transaction_count",
    "payer_transition_count",
    "unique_payer_count",
    "unique_secondary_payer_count"
]

print("Missing values:")
print(master[derived_features].isna().sum())

print("\nNegative values:")
print((master[derived_features] < 0).sum())

========== DERIVED FEATURE CHECK ==========
Missing values:
condition_count                   0
procedure_count                   0
procedure_cost                    0
medication_count                  0
medication_cost                   0
immunization_count                0
immunization_cost                 0
observation_count                 0
allergy_count                     0
careplan_count                    0
device_count                      0
imaging_study_count               0
supply_count                      0
supply_quantity                   0
claim_count                       0
billed_claim_count                0
closed_claim_count                0
transaction_charge_amount         0
transaction_payment_amount        0
transaction_outstanding_amount    0
transaction_count                 0
payer_transition_count            0
unique_payer_count                0
unique_secondary_payer_count      0
dtype: int64

Negative values:
condition_count                   0
procedure_count                   0
procedure_cost                    0
medication_count                  0
medication_cost                   0
immunization_count                0
immunization_cost                 0
observation_count                 0
allergy_count                     0
careplan_count                    0
device_count                      0
imaging_study_count               0
supply_count                      0
supply_quantity                   0
claim_count                       0
billed_claim_count                0
closed_claim_count                0
transaction_charge_amount         0
transaction_payment_amount        0
transaction_outstanding_amount    0
transaction_count                 0
payer_transition_count            0
unique_payer_count                0
unique_secondary_payer_count      0
dtype: int64

In [252]:
print("========== LOGICAL RELATIONSHIP CHECK ==========")

print(
    "Billed claims > total claims:",
    (master["billed_claim_count"] > master["claim_count"]).sum()
)

print(
    "Closed claims > total claims:",
    (master["closed_claim_count"] > master["claim_count"]).sum()
)

print(
    "Secondary payers > unique payers:",
    (master["unique_secondary_payer_count"] > master["unique_payer_count"]).sum()
)

print(
    "Payment amount > charge amount:",
    (master["transaction_payment_amount"] > master["transaction_charge_amount"]).sum()
)

print(
    "Outstanding amount > charge amount:",
    (master["transaction_outstanding_amount"] > master["transaction_charge_amount"]).sum()
)

========== LOGICAL RELATIONSHIP CHECK ==========
Billed claims > total claims: 0
Closed claims > total claims: 0
Secondary payers > unique payers: 370
Payment amount > charge amount: 13227
Outstanding amount > charge amount: 30346

In [253]:
cost_features = [
    "TOTAL_CLAIM_COST",
    "BASE_ENCOUNTER_COST",
    "PAYER_COVERAGE",
    "procedure_cost",
    "medication_cost",
    "immunization_cost",
    "transaction_charge_amount",
    "transaction_payment_amount",
    "transaction_outstanding_amount"
]

count_features = [
    "condition_count",
    "procedure_count",
    "medication_count",
    "immunization_count",
    "observation_count",
    "allergy_count",
    "careplan_count",
    "device_count",
    "imaging_study_count",
    "supply_count",
    "claim_count",
    "transaction_count"
]

print("========== COST FEATURE SUMMARY ==========")
print(
    master[cost_features]
    .describe()
    .T[
        ["min", "25%", "50%", "75%", "max"]
    ]
)

print("\n========== COUNT FEATURE SUMMARY ==========")
print(
    master[count_features]
    .describe()
    .T[
        ["min", "25%", "50%", "75%", "max"]
    ]
)

========== COST FEATURE SUMMARY ==========
                                  min     25%     50%       75%         max
TOTAL_CLAIM_COST                 0.00  129.16  786.33  1625.890   873646.19
BASE_ENCOUNTER_COST             77.49   77.49  129.16   129.160      129.16
PAYER_COVERAGE                   0.00    0.00    0.00    29.990   227851.81
procedure_cost                   0.00    0.00    0.00  2621.720   625825.22
medication_cost                  0.00    0.00    0.00    14.960  2197449.71
immunization_cost                0.00    0.00    0.00     0.000      702.60
transaction_charge_amount        0.00  129.16  269.68  1365.195   625902.71
transaction_payment_amount       0.00  129.16  295.02  1381.595   625902.71
transaction_outstanding_amount   0.00    7.47  177.48  1076.360  1251702.91

========== COUNT FEATURE SUMMARY ==========
                     min  25%  50%   75%    max
condition_count      0.0  0.0  0.0   1.0   13.0
procedure_count      0.0  0.0  0.0   1.0   27.0
medication_count     0.0  0.0  0.0   1.0   13.0
immunization_count   0.0  0.0  0.0   0.0    5.0
observation_count    0.0  0.0  0.0   9.0  678.0
allergy_count        0.0  0.0  0.0   0.0   12.0
careplan_count       0.0  0.0  0.0   0.0    2.0
device_count         0.0  0.0  0.0   0.0   12.0
imaging_study_count  0.0  0.0  0.0   0.0    1.0
supply_count         0.0  0.0  0.0   0.0   88.0
claim_count          1.0  1.0  1.0   2.0   14.0
transaction_count    1.0  6.0  8.0  14.0  133.0

In [254]:
print("========== FINAL MASTER DATASET ==========")

print("Shape:", master.shape)

print("\n========== COLUMN LIST ==========")
print(master.columns.tolist())

print("\n========== DATA TYPES ==========")
print(master.dtypes)

print("\n========== TOTAL MISSING VALUES ==========")
print(master.isna().sum().sum())

print("\n========== DUPLICATE ENCOUNTER IDs ==========")
print(master["Id"].duplicated().sum())

========== FINAL MASTER DATASET ==========
Shape: (61459, 64)

========== COLUMN LIST ==========
['Id', 'START', 'STOP', 'PATIENT', 'PROVIDER', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION', 'BIRTHDATE', 'PATIENT_GENDER', 'RACE', 'ETHNICITY', 'MARITAL', 'AGE_AT_ENCOUNTER', 'condition_count', 'procedure_count', 'procedure_cost', 'medication_count', 'medication_cost', 'immunization_count', 'immunization_cost', 'observation_count', 'allergy_count', 'careplan_count', 'device_count', 'imaging_study_count', 'supply_count', 'supply_quantity', 'PROVIDER_GENDER', 'PROVIDER_ORGANIZATION', 'GENDER', 'PROVIDER_SPECIALITY', 'PROVIDER_UTILIZATION', 'ORGANIZATION_NAME', 'ORGANIZATION_CITY', 'ORGANIZATION_STATE', 'ORGANIZATION_UTILIZATION', 'PAYER_NAME', 'PAYER_AMOUNT_COVERED', 'PAYER_AMOUNT_UNCOVERED', 'PAYER_QOLS_AVG', 'PAYER_MEMBER_MONTHS', 'claim_count', 'billed_claim_count', 'closed_claim_count', 'transaction_charge_amount', 'transaction_payment_amount', 'transaction_outstanding_amount', 'transaction_count', 'payer_transition_count_x', 'unique_payer_count_x', 'unique_secondary_payer_count_x', 'payer_transition_count_y', 'unique_payer_count_y', 'unique_secondary_payer_count_y', 'payer_transition_count', 'unique_payer_count', 'unique_secondary_payer_count']

========== DATA TYPES ==========
Id                                                str
START                             datetime64[us, UTC]
STOP                                              str
PATIENT                                           str
PROVIDER                                          str
                                         ...
unique_payer_count_y                            int64
unique_secondary_payer_count_y                  int64
payer_transition_count                          int64
unique_payer_count                              int64
unique_secondary_payer_count                    int64
Length: 64, dtype: object

========== TOTAL MISSING VALUES ==========
101617

========== DUPLICATE ENCOUNTER IDs ==========
0

In [255]:
missing_summary = (
    master.isna()
    .sum()
    .reset_index()
)

missing_summary.columns = ["Column", "Missing_Count"]

missing_summary["Missing_Percentage"] = (
    missing_summary["Missing_Count"] / len(master) * 100
)

missing_summary = (
    missing_summary[missing_summary["Missing_Count"] > 0]
    .sort_values("Missing_Count", ascending=False)
)

print("========== MISSING VALUE SUMMARY ==========")
print(missing_summary.to_string(index=False))

========== MISSING VALUE SUMMARY ==========
           Column  Missing_Count  Missing_Percentage
       REASONCODE          45502           74.036349
REASONDESCRIPTION          45502           74.036349
          MARITAL          10613           17.268423

In [262]:
print("========== FINAL MASTER DATASET ==========")

print("Rows:", len(master))
print("Columns:", len(master.columns))

print("Duplicate Encounter IDs:", master["Id"].duplicated().sum())
print("Missing Encounter IDs:", master["Id"].isna().sum())
print("Missing Patient IDs:", master["PATIENT"].isna().sum())
print("Missing Encounter Start:", master["START"].isna().sum())
print("Missing Primary Cost:", master["TOTAL_CLAIM_COST"].isna().sum())
print("Negative Primary Cost:", (master["TOTAL_CLAIM_COST"] < 0).sum())

========== FINAL MASTER DATASET ==========
Rows: 61459
Columns: 64
Duplicate Encounter IDs: 0
Missing Encounter IDs: 0
Missing Patient IDs: 0
Missing Encounter Start: 0
Missing Primary Cost: 0
Negative Primary Cost: 0

In [263]:
print("========== FINAL MASTER COLUMNS ==========")

for i, col in enumerate(master.columns, start=1):
    print(i, "->", col)

========== FINAL MASTER COLUMNS ==========
1 -> Id
2 -> START
3 -> STOP
4 -> PATIENT
5 -> PROVIDER
6 -> PAYER
7 -> ENCOUNTERCLASS
8 -> CODE
9 -> DESCRIPTION
10 -> BASE_ENCOUNTER_COST
11 -> TOTAL_CLAIM_COST
12 -> PAYER_COVERAGE
13 -> REASONCODE
14 -> REASONDESCRIPTION
15 -> BIRTHDATE
16 -> PATIENT_GENDER
17 -> RACE
18 -> ETHNICITY
19 -> MARITAL
20 -> AGE_AT_ENCOUNTER
21 -> condition_count
22 -> procedure_count
23 -> procedure_cost
24 -> medication_count
25 -> medication_cost
26 -> immunization_count
27 -> immunization_cost
28 -> observation_count
29 -> allergy_count
30 -> careplan_count
31 -> device_count
32 -> imaging_study_count
33 -> supply_count
34 -> supply_quantity
35 -> PROVIDER_GENDER
36 -> PROVIDER_ORGANIZATION
37 -> GENDER
38 -> PROVIDER_SPECIALITY
39 -> PROVIDER_UTILIZATION
40 -> ORGANIZATION_NAME
41 -> ORGANIZATION_CITY
42 -> ORGANIZATION_STATE
43 -> ORGANIZATION_UTILIZATION
44 -> PAYER_NAME
45 -> PAYER_AMOUNT_COVERED
46 -> PAYER_AMOUNT_UNCOVERED
47 -> PAYER_QOLS_AVG
48 -> PAYER_MEMBER_MONTHS
49 -> claim_count
50 -> billed_claim_count
51 -> closed_claim_count
52 -> transaction_charge_amount
53 -> transaction_payment_amount
54 -> transaction_outstanding_amount
55 -> transaction_count
56 -> payer_transition_count_x
57 -> unique_payer_count_x
58 -> unique_secondary_payer_count_x
59 -> payer_transition_count_y
60 -> unique_payer_count_y
61 -> unique_secondary_payer_count_y
62 -> payer_transition_count
63 -> unique_payer_count
64 -> unique_secondary_payer_count

In [264]:
duplicate_payer_columns = [
    "payer_transition_count_x",
    "unique_payer_count_x",
    "unique_secondary_payer_count_x",
    "payer_transition_count_y",
    "unique_payer_count_y",
    "unique_secondary_payer_count_y"
]

master.drop(columns=duplicate_payer_columns, inplace=True)

print("Columns after removing duplicate payer-transition features:", len(master.columns))
print(master.columns.tolist())

Columns after removing duplicate payer-transition features: 58
['Id', 'START', 'STOP', 'PATIENT', 'PROVIDER', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION', 'BIRTHDATE', 'PATIENT_GENDER', 'RACE', 'ETHNICITY', 'MARITAL', 'AGE_AT_ENCOUNTER', 'condition_count', 'procedure_count', 'procedure_cost', 'medication_count', 'medication_cost', 'immunization_count', 'immunization_cost', 'observation_count', 'allergy_count', 'careplan_count', 'device_count', 'imaging_study_count', 'supply_count', 'supply_quantity', 'PROVIDER_GENDER', 'PROVIDER_ORGANIZATION', 'GENDER', 'PROVIDER_SPECIALITY', 'PROVIDER_UTILIZATION', 'ORGANIZATION_NAME', 'ORGANIZATION_CITY', 'ORGANIZATION_STATE', 'ORGANIZATION_UTILIZATION', 'PAYER_NAME', 'PAYER_AMOUNT_COVERED', 'PAYER_AMOUNT_UNCOVERED', 'PAYER_QOLS_AVG', 'PAYER_MEMBER_MONTHS', 'claim_count', 'billed_claim_count', 'closed_claim_count', 'transaction_charge_amount', 'transaction_payment_amount', 'transaction_outstanding_amount', 'transaction_count', 'payer_transition_count', 'unique_payer_count', 'unique_secondary_payer_count']

In [265]:
print("========== FINAL ANALYTICAL DATASET VALIDATION ==========")

print("Rows:", len(master))
print("Columns:", len(master.columns))
print("Duplicate Encounter IDs:", master["Id"].duplicated().sum())
print("Missing Encounter IDs:", master["Id"].isna().sum())
print("Missing Patient IDs:", master["PATIENT"].isna().sum())
print("Missing Primary Cost:", master["TOTAL_CLAIM_COST"].isna().sum())
print("Negative Primary Cost:", (master["TOTAL_CLAIM_COST"] < 0).sum())

derived_features = [
    "condition_count",
    "procedure_count",
    "procedure_cost",
    "medication_count",
    "medication_cost",
    "immunization_count",
    "immunization_cost",
    "observation_count",
    "allergy_count",
    "careplan_count",
    "device_count",
    "imaging_study_count",
    "supply_count",
    "supply_quantity",
    "claim_count",
    "billed_claim_count",
    "closed_claim_count",
    "transaction_charge_amount",
    "transaction_payment_amount",
    "transaction_outstanding_amount",
    "transaction_count",
    "payer_transition_count",
    "unique_payer_count",
    "unique_secondary_payer_count"
]

print("\n========== DERIVED FEATURE CHECK ==========")

print(
    "Missing derived values:",
    master[derived_features].isna().sum().sum()
)

print(
    "Negative derived values:",
    (master[derived_features] < 0).sum().sum()
)

========== FINAL ANALYTICAL DATASET VALIDATION ==========
Rows: 61459
Columns: 58
Duplicate Encounter IDs: 0
Missing Encounter IDs: 0
Missing Patient IDs: 0
Missing Primary Cost: 0
Negative Primary Cost: 0

========== DERIVED FEATURE CHECK ==========
Missing derived values: 0
Negative derived values: 0

In [266]:
from pathlib import Path

analytical_path = PROJECT_PATH / "data" / "Analytical_Dataset"

# Create folder if it does not already exist
analytical_path.mkdir(parents=True, exist_ok=True)

# Save final analytical dataset
final_file = analytical_path / "healthcare_analytical_dataset.csv"

master.to_csv(final_file, index=False)

print("========== ANALYTICAL DATASET SAVED ==========")
print("File:", final_file)
print("Rows:", len(master))
print("Columns:", len(master.columns))
print("File exists:", final_file.exists())

========== ANALYTICAL DATASET SAVED ==========
File: C:\Users\vicky\OneDrive\Desktop\PROJECTS\Healthcare_Cost_Optimization_Analytics\data\Analytical_Dataset\healthcare_analytical_dataset.csv
Rows: 61459
Columns: 58
File exists: True